### PR TITLE
[desktop/mac] make destroying ipc more robust with destroyed webcontents

### LINKED ISSUE #4467: [mac] TypeError: object has been destroyed
We've been getting TypeErrors on MacOS for some time now, related to `destroyBridge`. I noticed this when updating. It's likely that this is relating to some part of the ApplicationWindow that's being accessed after the window is already gone.

It's happening in 3.98.14, 3.98.17 and 3.98.20.

Reports:

> unsure of steps leading to this. closed and when I opened get this error. Several times now.

```
Client: darwin
Type: PREMIUM
Tutanota version: 3.98.20
Timestamp (UTC): Fri, 05 Aug 2022 13:12:29 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.98.20 Chrome/102.0.5005.148 Electron/19.0.8 Safari/537.36
TypeError
Error message: Object has been destroyed
Stacktrace:
TypeError: Object has been destroyed
at bf.destroyBridge (desktop/DesktopMain.js:1:828714)
at BrowserWindow. (desktop/DesktopMain.js:1:44176)
```

no text:

```
Client: darwin
Type: PREMIUM
Tutanota version: 3.98.17
Timestamp (UTC): Fri, 05 Aug 2022 10:21:52 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.98.17 Chrome/102.0.5005.148 Electron/19.0.8 Safari/537.36
TypeError
Error message: Object has been destroyed
Stacktrace:
TypeError: Object has been destroyed
at bf.destroyBridge (desktop/DesktopMain.js:1:828714)
at BrowserWindow. (desktop/DesktopMain.js:1:44176)
at process.processTicksAndRejections (../../../../../node:internal/process/task_queues:96:5)
```

> Usual update to the app (macos, desktop app)

```
Client: darwin
Type: PREMIUM
Tutanota version: 3.98.17
Timestamp (UTC): Fri, 05 Aug 2022 13:29:58 GMT
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.98.17 Chrome/102.0.5005.148 Electron/19.0.8 Safari/537.36
TypeError
Error message: Object has been destroyed
Stacktrace:
TypeError: Object has been destroyed
at bf.destroyBridge (desktop/DesktopMain.js:1:828714)
at BrowserWindow. (desktop/DesktopMain.js:1:44176)
at process.processTicksAndRejections (../../../../../node:internal/process/task_queues:96:5)
```

### Regression Test Notes:
* [ ] Native->Web IPC functions still work (Opening a Print dialog with Ctrl+P)
* [ ] Web -> Native IPC functions still work (Open a new window with the drawer menu button, get Logs from about dialog)
* [ ] 2FA login with hardware key still works
* [ ] all of this works with multiple windows open and after closing some windows

### PR DESCRIPTION
**Pull request by ganthern**
sometimes, the window is gone before we get to destroy the bridge.
This gives a TypeError: object has been destroyed.
In other cases, we try to send messages to already destroyed
webContents, giving TypeErrors because webContents.fromId returns
undefined.

To prevent this
  * we add a listener to the destroy event of the webContents
  * don't use ids for referencing the webContents, instead pass the
    content itself around to be able to check isDestroyed()

fix https://github.com/tutao/tutanota/issues/4467

### CODE REVIEW

File: src/desktop/ipc/RemoteBridge.ts [hunk 1]
```diff
@@ -64,6 +64,9 @@ export class RemoteBridge {
 	}
 
 	destroyBridge(window: ApplicationWindow) {
-		primaryIpcHandler.removeHandler(window._browserWindow.webContents.id)
+		if(!window._browserWindow || window._browserWindow.isDestroyed()) return
+		const webContents = window._browserWindow.webContents
+		if(!webContents || webContents.isDestroyed()) return
```
Comment (charlag) [inline src/desktop/ipc/RemoteBridge.ts:69]: so if the window is destroyed then we don't ever remove the handler? Or is it removed from elsewhere? Maybe worth a comment.

Also formatting.

File: src/desktop/ipc/CentralIpcHandler.ts [hunk 2]
```diff
@@ -16,26 +16,43 @@ type RequestHandler = (message: Message<unknown>) => unknown
  * registered once per event name so this must be a singleton per event name!
  */
 export class CentralIpcHandler<IpcConfigType extends IpcConfig<string, string>> {
-	private readonly webContentsIdToRequestHandler = new Map<number, RequestHandler>()
+	// using ref to webContents because webContents tend to get destroyed
+	// and we don't know if ids get reused.
+	private readonly webContentsToRequestHandler = new Map<WebContents, RequestHandler>()
```
Comment (charlag) [inline src/desktop/ipc/CentralIpcHandler.ts:21]: can this be a case for `WeakMap`? `WebContents` should be help by a window anyway, right?

Comment (ganthern) [reply src/desktop/ipc/CentralIpcHandler.ts:21]: I think that's a good ideo, then we can just check if the WC is in the map and don't worry about removing anything.
since the only need to iterate the map is to find destroyed WCs, the fact that you can't iterate a WeakMap shouldn't matter

**Review by charlag — APPROVED** [review]
