### PR TITLE
fix overlap of select plan button with the monthly and yearly buttons

### LINKED ISSUE #5552: Signup UI button misplacement
In the business plan selection if you use specific languages (like German) the monthly/yearly buttons overlap the select button. This is because the text "per user/month - paid yearly Excludes taxes." will become three lines instead of two depending on the UI language.

This bug also applies to the website pricing page.

How to reproduce:
1. Select German as the UI language.
2. Open the signup in the app or the pricing page on the website.
3. Switch to the business plans.
-> The monthly/yearly buttons overlap the select button.
Expected: all margins are fine in any language.

### Personal looks OK

image

### Business does not

image

## Test Notes
* [ ] Overlap doesn't happen during plan select in sign up page
* [ ] Overlap doesn't during plan select on settings page
* [ ] Overlap doesn't happen in the desktop client during plan select
* [ ] Overlap doesn't happen in mobile apps
* [ ] All the select buttons are in the same baseline
* [ ] check greek as well

### PR DESCRIPTION
**Pull request by murilopereirame**
When the current language uses more than two lines of text after the price on select plan page, the select plan button overlaps the monthly and yearly buttons.

Changing the container to flex-column and removing it's fixed height plus adding margin-top auto to the select plan button solves the issue.

fix #5552

### CODE REVIEW

File: src/subscription/BuyOptionBox.ts [hunk 1]
```diff
@@ -85,7 +85,9 @@ export class BuyOptionBox implements Component<BuyOptionBoxAttr> {
 					".buyOptionBox" + (attrs.highlighted ? ".highlighted" : ""),
 					{
 						style: {
-							height: px(attrs.height),
+							display: "flex",
```
Comment (charlag) [inline src/subscription/BuyOptionBox.ts:88]: this could be expressed shorter with `.flex.col`

**Review by charlag — APPROVED** [review]

**Review by ganthern — APPROVED** [review]
very good
