### PR TITLE
Keychain fixes

### LINKED ISSUE #3664: Key invalidation is not handled in mode switching dialog
* Have fingerprints enrolled, enable biometrics only.
* While app is running, remove all fingerprints
* Try to switch to automatic/system password
* an error occurs
* It is also not possible to login afterwards

First error message shows error code -3 for key invalidated, this is expected (though in this case, we should just try again i think)
If you try again unhandled error with code -25293

If you do the same thing but instead you invalidate the keychain by _adding_ a fingerprint, then the following error code is -50

_Originally posted by @johnbotris in https://github.com/tutao/tutanota/issues/3653#issuecomment-966128973_

### PR DESCRIPTION
**Pull request by charlag**
#3664

### CODE REVIEW

File: src/api/worker/facades/FileFacade.js [hunk 1]
```diff
@@ -139,34 +138,29 @@ export class FileFacade {
...
-							              } else if (suspensionTime && isSuspensionResponse(statusCode, suspensionTime)) {
-								              this._suspensionHandler.activateSuspensionIfInactive(Number(suspensionTime))
-								              return this._suspensionHandler.deferRequest(() => this.uploadFileDataNative(fileReference, sessionKey))
-							              } else {
-								              throw handleRestError(statusCode, ` | PUT ${url.toString()} failed to natively upload attachment`, errorId, precondition)
-							              }
-						              })
-					})
-			})
+		const encryptFileInfo = await aesEncryptFile(sessionKey, fileReference.location, random.generateRandomData(16))
```
Comment (johnbotris) [inline src/api/worker/facades/FileFacade.js]: typo in name

**Review by johnbotris — CHANGES_REQUESTED** [review]
besides typo looks good
