### PR TITLE
Fix key error after the first login

### LINKED ISSUE #7330: Error upon longing into an account for the first time on mobile
**Bug in mobile app**

**Describe the bug**
An error appears after you log into a new account on both Android and iOS.

**To Reproduce**
1. Install a fresh copy of the app
2. Log into an account
3. See error

**Expected behavior**
No error appears.

**Additional context**
Android log:
```
Feedback v240.240731.0 - android.security.keystore.KeyPermanentlyInvalidatedException - UNKNOWN - android



 Client: android
 Type: UNKNOWN
 Tutanota version: 240.240731.0
 Timestamp (UTC): Fri, 02 Aug 2024 09:57:24 GMT
 User agent:
Mozilla/5.0 (Linux; Android 13; sdk_gphone_x86_64 Build/TE1A.220922.034; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/103.0.5060.71 Mobile Safari/537.36
android.security.keystore.KeyPermanentlyInvalidatedException
 Error message: Credentials key is missing, cannot decrypt credentials
Stacktrace: 
android.security.keystore.KeyPermanentlyInvalidatedException: Credentials key is missing, cannot decrypt credentials
	at de.tutao.tutanota.credentials.AndroidNativeCredentialsFacade.loadByUserId(AndroidNativeCredentialsFacade.kt:52)
	at de.tutao.tutanota.ipc.NativeCredentialsFacadeReceiveDispatcher.dispatch(NativeCredentialsFacadeReceiveDispatcher.kt:43)
	at de.tutao.tutanota.ipc.AndroidGlobalDispatcher.dispatch(AndroidGlobalDispatcher.kt:41)
	at de.tutao.tutanota.RemoteBridge.invokeMethod(RemoteBridge.kt:154)
	at de.tutao.tutanota.RemoteBridge.handleMessageFromWeb(RemoteBridge.kt:90)
	at de.tutao.tutanota.RemoteBridge$initMessageChannel$1$onMessage$1.invokeSuspend(RemoteBridge.kt:58)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
```

## Test notes
 - [ ] Fix that migration from stored credentials without `passphraseKey` still works
 - [ ] Try to log in after a fresh install. See that the error does not occur anymore.

### PR DESCRIPTION
**Pull request by charlag**
We have added a migration to add `encryptedPassphraseKey` and we've been erroneously calling `getDecryptedCredentialsByUserId()` before any credentials have been stored.

Now we first make sure that the credentials are there and then we try to fetch and decrypt them.

fix #7330

### CODE REVIEW

File: src/common/api/main/PageContextLoginListener.ts [hunk 1]
```diff
@@ -36,10 +36,16 @@ export class PageContextLoginListener implements LoginListener {
 		// Update the credentials after the full login.
 		// It is needed because we added encryptedPassphraseKey to credentials which is only
 		// available after the full login which happens async.
-		const storedCredentials = await this.credentialsProvider.getDecryptedCredentialsByUserId(credentials.userId)
-		if (storedCredentials != null) {
-			const updatedCredentials = credentialsToUnencrypted(credentials, storedCredentials.databaseKey)
-			await this.credentialsProvider.store(updatedCredentials)
+
+		// First try to fetch credentials info and only then try to get decrypted credentials as it is not valid to
+		// call `getDecryptedCredentialsByUserId()` without storing any credentials first.
```
Comment (wec43) [inline src/common/api/main/PageContextLoginListener.ts:41]: Just a question: can we just check the key exists? Because I think the key is not tied directly to `CredentialsInfo`?

**Comment by charlag** [comment]
rebased

File: src/common/api/main/PageContextLoginListener.ts (hunk 1 above)
Comment (charlag) [reply src/common/api/main/PageContextLoginListener.ts:41]: we can either get all of them and search or we can get one of them, that's kind of our options?

**Review by wec43 — APPROVED** [review]
