### PR TITLE
Fix attempt to download all attachments when offline

### LINKED ISSUE #4937: When downloading multiple attachments without an Internet connection, all attachments are tried one after the other
While offline and hitting "Save all" on an email, all attachments are downloaded after each other but will fail after 20 seconds. It's also a dev bug because since the newly introduced progress indication the whole UI will be blocked. For 3 attachments, the client can't be used anymore for at least 1 minute.

**To Reproduce**
1. Log in to some account that has emails with multiple attachments
2. turn of internet
3. click on "Save all"
4. every 20 second a notification for unsuccessful download shows up
5. with the new progress indication, the whole UI is blocked for the whole time

**Expected behavior**
The user should have an option to abort the downloading process or no attempt should be made to download the files if there is no internet connection (client is offline)

## Test Notes
* [x] retest #4811 before
* [x] test on Firefox, Chrome, Safari, Desktop and mobile
* [x] open a mail with multiple attachments
* [x] turn of internet connection
* [x] click on Save all
* [x] it will try to download the attachments for about 20 seconds and then reports that it was not possible
* [x] downloading a single attachments basically shows the same behavior
* [x] activate internet again with throttling (F12 -> Network)
* [x] hit "Save all" and wait until to loading bar is visible but the process is not finished -> then quickly turn off internet
* [x] the download should fail and an error message should be displayed
* [x] make sure that a few files were downloaded nevertheless (about the amount indicated by the progress bar)
* [x] since file chooser was also slightly refactored:
  * [x] make sure it is possible to select and open/ import multiple files from:
    * [x] Calendar importer
    * [x] Contact importer
    * [x] Contact form importer - secure connect (bedpremium has a contact formular)
    * [x] attaching files to an email
    * [x] adding inline images to an email

### Regressions
* [x] downloading single and multiple attachments with internet connection works fine
* [x] when adding a whitelabel logo, you can only select one file
* [x] when importing calendar events, you can select multiple files

### PR DESCRIPTION
**Pull request by nokhub**
fix #4937

### CODE REVIEW

File: src/file/FileControllerBrowser.ts [hunk 1]
```diff
@@ -28,15 +29,29 @@ export class FileControllerBrowser implements FileController {
...
-				const downloadedFile = await this.downloadAndDecrypt(file)
-				downloadedFiles.push(downloadedFile)
-			} catch (e) {
-				await handleDownloadErrors(e, (msg) => Dialog.message(() => lang.get(msg) + " " + file.name))
-			}
+		try {
+			const progress = stream(0)
+			await showProgressDialog(
+				"pleaseWait_msg",
+				new Promise<void>(async (resolve) => {
```
Comment (ganthern) [inline src/file/FileControllerBrowser.ts]: is the "new Promise" call necessary here?

File: src/file/FileControllerNative.ts [hunk 2]
```diff
@@ -24,30 +25,62 @@ export class FileControllerNative implements FileController {
 	 * Temporary files are deleted afterwards in apps.
 	 */
 	async download(file: TutanotaFile) {
-		await guiDownload(this.doDownload(file))
+		await guiDownload(
+			isAndroidApp() || isDesktop()
+				? this.doDownload(
+						new Array(file),
```
Comment (ganthern) [inline src/file/FileControllerNative.ts]: we can just do [file], `new Array()` has this weird overload where it's creating an array of length n if n is a number and the only parameter

File: src/file/FileControllerNative.ts [hunk 3]
```diff
@@ -67,44 +100,65 @@ export class FileControllerNative implements FileController {
...
-						}
-					}),
+			await guiDownload(
+				this.doDownload(
+					tutanotaFiles,
+					(file) => this.downloadAndDecryptInNative(file),
+					(files) =>
+						promiseMap(files, async (file) => {
+							try {
+								await this.fileApp.open(file)
```
Comment (ganthern) [inline src/file/FileControllerNative.ts:106]: are we actually opening each file after download?

File: src/file/FileControllerNative.ts [hunk 4]
```diff
@@ -67,44 +100,65 @@ export class FileControllerNative implements FileController {
...
+					tutanotaFiles,
+					(file) => this.downloadAndDecryptInNative(file),
+					async (files) => {
+						const dataFiles = (await promiseMap(files, (f) => this.fileApp.readDataFile(f.location))).filter(Boolean)
+						const zipFileInTemp = await this.fileApp.writeDataFile(
+							await zipDataFiles(dataFiles as Array<DataFile>, `${sortableTimestamp()}-attachments.zip`),
+						)
+						return this.fileApp.putFileIntoDownloadsFolder(zipFileInTemp.location)
+					},
+					async () => {}, // no cleanup needed
```
Comment (ganthern) [inline src/file/FileControllerNative.ts]: maybe we should still do a manual cleanup since we have the chance

File: src/file/FileController.ts [hunk 5]
```diff
@@ -228,3 +230,44 @@ export async function downloadAndDecryptDataFile(file: TutanotaFile, fileFacade:
...
+
+type DownloadArgs<T> = {
+	tutanotaFiles: TutanotaFile[]
+	downloadAction: (file: TutanotaFile) => Promise<T>
+	processDownloadedFiles: (downloadedFiles: T[]) => Promise<unknown>
+	cleanUp: (downloadedFiles: T[]) => Promise<unknown>
+	progress?: stream<number>
+}
+
+export async function doDownload<T>(args: DownloadArgs<T>) {
```
Comment (ganthern) [inline src/file/FileController.ts:242]: I feel like this could be a place where we could use something like the template method pattern to make the callsites more readable. we only have so many combinations of these args.

File: src/file/FileControllerNative.ts (hunk 3 above)
Comment (nokhub) [reply src/file/FileControllerNative.ts:106]: apparently there is no such thing like a direct download in iOS. When clicking on an attachment it will open and then offer the option to download. That's why the "Save all" option is not available on iOS. I was also confused why this code exists but decided not to mess with it. Should I rather remove it? As far as I can tell this case can never happen

File: src/file/FileControllerNative.ts (hunk 2 above)
Comment (nokhub) [reply src/file/FileControllerNative.ts]: already resolved in the latest commit :+1:

**Review by ganthern — APPROVED** [review]
