### PR TITLE
fix altered instances not being excluded on import

### LINKED ISSUE #5708: Importing events with rescheduled occurrences keeps original occurrence
At least from Google Calendar.

1. On Google Calendar, create a weekly repeating event and reschedule one occurrence for the next day.
2. Export that calendar and import it to Tutanota.
3. See the repeating event, including the occurrence that was supposed to be rescheduled. One occurrence is also shown on the next day, i.e., the occurrence is duplicated.

**Expected behavior**
Occurrence is rescheduled and not duplicated.

**Screenshots**
Original in Google Calendar:
image

Imported to Tutanota:
image

**Files**
Here is the ICS file, for convenience:
```
BEGIN:VCALENDAR
PRODID:-//Google Inc//Google Calendar 70.9054//EN
VERSION:2.0
CALSCALE:GREGORIAN
METHOD:PUBLISH
X-WR-CALNAME:Another export test
X-WR-TIMEZONE:Europe/Berlin
BEGIN:VEVENT
DTSTART;VALUE=DATE:20230802
DTEND;VALUE=DATE:20230803
RRULE:FREQ=WEEKLY;BYDAY=WE
DTSTAMP:20230801T093501Z
UID:4k0c5e7dv6if6k81ercq7bt372@google.com
CREATED:20230801T093020Z
LAST-MODIFIED:20230801T093455Z
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:Ghoulgle event
TRANSP:TRANSPARENT
END:VEVENT
BEGIN:VEVENT
DTSTART;VALUE=DATE:20230810
DTEND;VALUE=DATE:20230811
DTSTAMP:20230801T093501Z
UID:4k0c5e7dv6if6k81ercq7bt372@google.com
RECURRENCE-ID;VALUE=DATE:20230809
CREATED:20230801T093020Z
LAST-MODIFIED:20230801T093455Z
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:Ghoulgle event
TRANSP:TRANSPARENT
END:VEVENT
END:VCALENDAR
```

### PR DESCRIPTION
**Pull request by ganthern**
we're now grouping events by uid before checking if they
should be created or not.
the first event of a group without a recurrenceId
is the designated progenitor (the rest is dropped
as duplicate). if it has a repeat rule and we
encounter altered instances in that group,
their recurrenceIds are added as excluded instances
on the progenitor.

this does not handle updating existing progenitors
when new altered instances are imported or adding
existing altered instances on newly imported
progenitors

fix #5708
fix ed27db58b2735268d70a6119ed1deeb27e8a8919

### CODE REVIEW

File: src/calendar/export/CalendarImporterDialog.ts [hunk 1]
```diff
@@ -9,97 +9,145 @@ import { lang } from "../../misc/LanguageViewModel"
...
+			} else {
+				if (progenitor?.event.repeatRule != null) {
+					insertIntoSortedArray(
+						createDateWrapper({ date: event.recurrenceId }),
+						progenitor.event.repeatRule.excludedDates,
+						(left, right) => left.date.getTime() - right.date.getTime(),
+						() => true,
+					)
+				}
+				alteredInstances.push({ event, alarms })
```
Comment (charlag) [inline src/calendar/export/CalendarImporterDialog.ts:140]: should we still create it if there's no progenitor? we probably should but we should make sure it doesn't invalidate some invariant somewhere

**Review by charlag — APPROVED** [review]

File: src/calendar/export/CalendarImporterDialog.ts (hunk 1 above)
Comment (ganthern) [reply src/calendar/export/CalendarImporterDialog.ts:140]: yes, it's valid to have no knowledge of the progenitor since we are allowed to send invitations to only an altered instance of a series.
