### PR TITLE
Calendarupdate notfound 4964

### LINKED ISSUE #4964: Uncaught NotFoundError on CalendarEventUpdate DELETE
About ~2 reports per day:

```
Client: android
Type: PREMIUM
Tutanota version: 3.106.5
Timestamp (UTC): Tue, 10 Jan 2023 16:47:31 GMT
User agent:
Mozilla/5.0 (Linux; Android 9; SM-G955F Build/PPR1.180610.011; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36
NotFoundError
Error message: 404: | DELETE /rest/tutanota/calendareventupdate/MnPp0sF--k-2/NLML9HI--3-9
Stacktrace:
NotFoundError: 404: | DELETE /rest/tutanota/calendareventupdate/MnPp0sF--k-2/NLML9HI--3-9
at cP (https://assets.tutanota.com/common-min-ad5cd377.js:1:7575)
at l.onload (https://assets.tutanota.com/worker.js:12:100956)
```

This one happened after clicking the notification, cancelling the biometric prompt on a login screen with two saved credentials and bringing the app back to foreground after a few hours to complete the login:

```
Clicked on a calendar Event push notification. Left the app when I was asked to login and returned a couple hours later to the app. Error was shown after logging in...

Client: android
Type: PREMIUM
Tutanota version: 3.106.5
Timestamp (UTC): Mon, 09 Jan 2023 21:12:46 GMT
User agent:
Mozilla/5.0 (Linux; Android 13; SM-A528B Build/TP1A.220624.014; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/108.0.5359.128 Mobile Safari/537.36
NotFoundError
Error message: 404: | DELETE /rest/tutanota/calendareventupdate/ME_w8kp----2/NL6Kf6L--3-9
Stacktrace:
NotFoundError: 404: | DELETE /rest/tutanota/calendareventupdate/ME_w8kp----2/NL6Kf6L--3-9
at cP (https://assets.tutanota.com/common-min-ad5cd377.js:1:7575)
at l.onload (https://assets.tutanota.com/worker.js:12:100956)
```

and ios:

```
Client: ios
Type: PREMIUM
Tutanota version: 3.106.4
Timestamp (UTC): Thu, 05 Jan 2023 20:52:51 GMT
User agent:
Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148
NotFoundError
Error message: 404: | DELETE /rest/tutanota/calendareventupdate/MTpGaoV--g-2/NL1CTJA--3-9
Stacktrace:
o@asset://app/common-min-b40ebf9b.js:1:12207
Fe@asset://app/common-min-b40ebf9b.js:1:28486
cP@asset://app/common-min-b40ebf9b.js:1:7581
@asset://app/worker.js:12:100957
```

### Test Notes
test this on ios, android and linux

* [ ] syncing all calendar events after login still works (new credentials, login, go offline after sync, look at calendar)
* [ ] syncing them after offline login and going online still works
* [ ] alarms are scheduled after logging in
* [ ] calendar updates are still applied for other clients (create calendar, delete calendar, create event, move event, delete event, add alarm)
* [ ] accepting, cancelling and updating events from ICS files still works (for events where an internal recipient is invited, but doesn't have the calendar shared)

### LINKED ISSUE #5142: Event participation of a tutanota user will not be updated if the event wasn't created with an all-lowercase mail address
* create a contact with a mixed-case mail address of an internal user
* invite that user to an event
* accept/decline that invitation with that user (reply will be sent with all-lowercase sender)
* see that the update is ignored because CalendarModel only considers attendees with the same case as on the event as invited.

We'll have to ignore case for users that we know are ours, because for those the case is unimportant.  

we probably should fixup the attendees when sending invitiations and additionally make the attendee check in the CalendarModel (when the reply is handled) aware of this distinction.

#5125

### PR DESCRIPTION
**Pull request by ganthern**
fix #4964
fix #5142

### CODE REVIEW

File: src/calendar/model/CalendarModel.ts [hunk 1]
```diff
@@ -149,232 +90,231 @@ export class CalendarModelImpl implements CalendarModel {
...
+	/** Load map from group/groupRoot ID to the calendar info */
+	async loadCalendarInfos(progressMonitor: IProgressMonitor): Promise<Map<Id, CalendarInfo>> {
+		const user = this.logins.getUserController().user
 
 		const calendarMemberships = user.memberships.filter((m) => m.groupType === GroupType.Calendar)
 		const notFoundMemberships: GroupMembership[] = []
-		return promiseMap(calendarMemberships, (membership) =>
-			Promise.all([
-				this._entityClient.load(CalendarGroupRootTypeRef, membership.group).then((it) => {
-					progressMonitor.workDone(1)
```
Comment (charlag) [inline src/calendar/model/CalendarModel.ts:171]: what happened to this `workDone()`?

File: src/api/common/utils/CommonCalendarUtils.ts [hunk 2]
```diff
@@ -90,10 +90,27 @@ export function getEventElementMinId(timestamp: number): string {
...
 /**
  * get the first attendee from the list of attendees/guests that corresponds to one of the given recipient addresses, if there is one
  */
 export function findAttendeeInAddresses<T extends { address: EncryptedMailAddress }>(attendees: ReadonlyArray<T>, addresses: ReadonlyArray<string>): T | null {
-	const lowerCaseAddresses = addresses.map((r) => r.toLowerCase())
-	return attendees.find((a) => lowerCaseAddresses.includes(a.address.address.toLowerCase())) ?? null
+	// the filters are necessary because of #5147
+	// we may get passed addresses and attendees that could not be decrypted and don't have addresses.
+	const lowerCaseAddresses = addresses.filter(Boolean).map(cleanMailAddress)
+	return attendees.filter((a) => a.address.address != null).find((a) => lowerCaseAddresses.includes(cleanMailAddress(a.address.address))) ?? null
```
Comment (charlag) [inline src/api/common/utils/CommonCalendarUtils.ts:107]: does `filter()` make sense here or can we just do `find()` straight away.

File: src/mail/editor/SendMailModel.ts [hunk 3]
```diff
@@ -420,7 +421,7 @@ export class SendMailModel {
 		const recipientsFilter = (recipientList: Array<PartialRecipient>) =>
 			deduplicate(
 				recipientList.filter((r) => isMailAddress(r.address, false)),
-				(a, b) => a.address === b.address,
+				(a, b) => cleanMailAddress(a.address) === cleanMailAddress(b.address),
```
Comment (charlag) [inline src/mail/editor/SendMailModel.ts:424]: this is maybe too much in N^2, should we make a Set?

File: src/mail/editor/SendMailModel.ts [hunk 4]
```diff
@@ -557,7 +558,7 @@ export class SendMailModel {
 	 */
 	removeRecipient(recipient: Recipient, type: RecipientField, notify: boolean = true): boolean {
 		const recipients = this.recipients.get(type) ?? []
-		const didRemove = findAndRemove(recipients, (r) => r.address === recipient.address)
+		const didRemove = findAndRemove(recipients, (r) => cleanMailAddress(r.address) === cleanMailAddress(recipient.address))
```
Comment (charlag) [inline src/mail/editor/SendMailModel.ts:561]: maybe we could at least pull `cleanMailAddress(recipient.address)` out?

**Review by charlag — APPROVED** [review]

**Comment by charlag** [comment]
any test notes we can for #4964 ?

File: src/calendar/model/CalendarModel.ts (hunk 1 above)
Comment (ganthern) [reply src/calendar/model/CalendarModel.ts:171]: all three of them were merged and moved to line 126 (along with the one in the catch block). we're loading three instances in parallel and it's not too useful to make the progress that granular.

Comment (ganthern) [reply src/calendar/model/CalendarModel.ts:171]: but i just noticed that line 126 should probably be inside the catch block

File: src/api/common/utils/CommonCalendarUtils.ts (hunk 2 above)
Comment (ganthern) [reply src/api/common/utils/CommonCalendarUtils.ts:107]: true

File: src/mail/editor/SendMailModel.ts (hunk 3 above)
Comment (ganthern) [reply src/mail/editor/SendMailModel.ts:424]: set might be difficult because we need a custom compare, but we could map the mail addresses before going into the n² part.

File: src/mail/editor/SendMailModel.ts (hunk 4 above)
Comment (ganthern) [reply src/mail/editor/SendMailModel.ts:561]: yes

**Comment by ganthern** [comment]
> any test notes we can for #4964 ?

added some

**Review by charlag — APPROVED** [review]
