### PR TITLE
fix multiple emails are selected when using long press

### LINKED ISSUE #5696: multiple emails are selected when using long press
**Describe the bug**
When you select an email in the mobile app by using a long press, two emails are marked as selected.

**To Reproduce**
1. Have multiple emails in the mobile app
2. Open any email
3. Go back
4. Long press on a different email
5. See error

**versions**
 - iOS, Android
 - Tutanota v3.115.2

## Test notes
* [ ] Multi select still working
* [ ] In single column layout and not in multi select mode, when long press an email/contact, 
        it enters in multi select with only the pressed email/contact
* [ ] In multi column layout and not in multi select mode, if an email/contact is open and start 
        multi select with another email/contact holding CTRL, both emails are selected
* [ ] Multi select with SHIFT still working as expected
* [ ] Selecting multiple emails/contacts holding CTRL still working as expected

### PR DESCRIPTION
**Pull request by murilopereirame**
When the user is on mobile or more specific on a viewport that uses the single column layout and visualises an email, when back to mail list and long press to select another different email, the first one keeps selected.

This commit changes the behavior of the emails lists and contacts lists, discarding the previous selected email if in single column layout. On bigger viewports that uses two or more columns, the behavior stays the same.

fix #5696

### CODE REVIEW

File: src/misc/ListModel.ts [hunk 1]
```diff
@@ -328,8 +328,17 @@ export class ListModel<ElementType extends ListElement> {
 	}
 
 	/** An element was added to the selection. If multiselect was not on, add previous single selection and newly added selected item to the selection. */
-	onSingleInclusiveSelection(item: ElementType): void {
+	onSingleInclusiveSelection(item: ElementType, clearSelectionOnMultiSelectStart?: boolean): void {
+		// If isn't in MultiSelect, we discard all previous items
```
Comment (wrdhub) [inline src/misc/ListModel.ts:332]: Everything looks good, so sorry to nit-pick on the comment. "If isn't in MultiSelect" isn't quite grammatically correct, I would phrase it as "If it isn't in MultiSelect" or "If not in MultiSelect"

File: src/misc/ListModel.ts [hunk 2]
```diff
@@ -328,8 +328,17 @@ export class ListModel<ElementType extends ListElement> {
...
+		// and start a new set of selected items in MultiSelect mode
+		// we do it only if the user is on singleColumnMode, otherwise
+		// we want to keep the original behavior
```
Comment (wrdhub) [inline src/misc/ListModel.ts:335]: Also, I feel like "original behavior" can be confusing in the future (what "original behavior" was gets lost to time). Would describing the behaviors here make a too-long comment? Or maybe just say, "We do it only if the user is in singleColumnMode, because there are different expected behaviors there."?

File: src/misc/ListModel.ts (hunk 1 above)
Comment (murilopereirame) [reply src/misc/ListModel.ts:332]: Thanks for the insight

File: src/misc/ListModel.ts (hunk 2 above)
Comment (murilopereirame) [reply src/misc/ListModel.ts:335]: I agree, in the future, maybe not so distant, it will be confusing for those who will maintain it

**Comment by murilopereirame** [comment]
@wrdhub I updated the comment and amend the commit

**Review by ganthern — APPROVED** [review]
