### PR TITLE
Apply only the labels that have actually been added or removed

### LINKED ISSUE #10166: Cannot unassign label from mail when: mailbox labels count > MAX_NBR_OF_MAILS_SYNC_OPERATION
**Steps to reproduce:**
- Have 51 or more labels.
- Assign the label that is at the bottom of the label list to a mail (labels are ordered alphabetically).
- Try to unassign the label from the mail and see that it doesn't work.

**Additional informations:**
Currently the workaround is to:
- Rename the label so it's ordered in the top 50.
- Unassign the label.
- Revert the name change.

## Test notes
- [ ] Issue is no longer reproducible.
- [ ] Applying labels to multiple email with some labels being partially applied works as expected.

### PR DESCRIPTION
**Pull request by wrdhub**
Close #10166

### CODE REVIEW

File: src/mail-app/mail/view/LabelsPopup.ts [hunk 1]
```diff
@@ -69,49 +67,47 @@ export class LabelsPopup implements ModalComponent {
...
-						}),
+									},
+									m(".text-ellipsis", label.name),
+								),
+							],
+						)
+					}),
 				),
-				this.isMaxLabelsReached && m(".small.center.pb-8", lang.get("maximumLabelsPerMailReached_msg")),
+				this.viewModel.isLabelLimitReached() && m(".small.center.pb-8", lang.get("maximumLabelsPerMailReached_msg")),
```
Comment (charlag) [inline src/mail-app/mail/view/LabelsPopup.ts]: aside: I'm surprised it works to render `false` into mithril but I guess it works

File: src/mail-app/mail/view/LabelsPopupViewModel.ts [hunk 2]
```diff
@@ -0,0 +1,88 @@
...
+	) {
+		for (const label of initialLabelState) {
+			this.labelStateTracker.push({ label: label.label, state: label.state, startingState: label.state })
+		}
+		// We sort right now
+		this.labelStateTracker.sort((labelA, labelB) => labelA.label.name.localeCompare(labelB.label.name))
+		this.updateLabelLimitReached()
+	}
+
+	getLabelState(): Array<{ label: MailSet; state: LabelState; startingState: LabelState }> {
```
Comment (charlag) [inline src/mail-app/mail/view/LabelsPopupViewModel.ts:22]: you could make it `readonly` (both the array and the object inside) but it's not very important in this case

File: src/mail-app/mail/view/LabelsPopupViewModel.ts [hunk 3]
```diff
@@ -0,0 +1,88 @@
...
+	isLabelLimitReached(): boolean {
+		return this.labelLimitReached
+	}
+
+	toggleLabel(label: MailSet): void {
+		this.toggleLabelById(getElementId(label))
+	}
+
+	toggleLabelById(labelId: Id): void {
+		const labelIndex = this.labelStateTracker.findIndex((item) => getElementId(item.label) === labelId)
```
Comment (charlag) [inline src/mail-app/mail/view/LabelsPopupViewModel.ts]: I was a bit confused why you've been looking for the index. You can just `find` it and mutate it directly. You would only need an index if the object was immutable

File: src/mail-app/mail/view/LabelsPopupViewModel.ts [hunk 4]
```diff
@@ -0,0 +1,88 @@
...
+		switch (this.labelStateTracker[labelIndex].state) {
+			case LabelState.AppliedToSome:
+				this.labelStateTracker[labelIndex].state = this.labelLimitReached ? LabelState.NotApplied : LabelState.Applied
+				break
+			case LabelState.NotApplied:
+				this.labelStateTracker[labelIndex].state = LabelState.Applied
```
Comment (charlag) [inline src/mail-app/mail/view/LabelsPopupViewModel.ts]: it is correct that we would toggle it to an applied even though the limit is reached?

File: src/mail-app/mail/view/LabelsPopupViewModel.ts [hunk 5]
```diff
@@ -0,0 +1,88 @@
...
+				break
+			case LabelState.Applied:
+				this.labelStateTracker[labelIndex].state = LabelState.NotApplied
+				break
+		}
+
+		this.updateLabelLimitReached()
+	}
+
+	getLabelStateChange(): Record<"addedLabels" | "removedLabels", MailSet[]> {
```
Comment (charlag) [inline src/mail-app/mail/view/LabelsPopupViewModel.ts:56]: this can be private? ah, it's visible for test

File: test/tests/mail/view/LabelsPopupViewModelTest.ts [hunk 6]
```diff
@@ -0,0 +1,291 @@
+import o from "@tutao/otest"
+import { MailSet, MailSetTypeRef } from "../../../../src/common/api/entities/tutanota/TypeRefs"
+import { createTestEntity } from "../../TestUtils"
+import { MailSetKind } from "../../../../src/common/api/common/TutanotaConstants"
+import { LabelsPopupViewModel } from "../../../../src/mail-app/mail/view/LabelsPopupViewModel"
+import { LabelState } from "../../../../src/mail-app/mail/model/MailModel"
+
+o.spec("LabelsPopupViewModelTest", () => {
```
Comment (charlag) [inline test/tests/mail/view/LabelsPopupViewModelTest.ts:8]: I am trying to make people write spec name without "Test"

File: test/tests/mail/view/LabelsPopupViewModelTest.ts [hunk 7]
```diff
@@ -0,0 +1,291 @@
...
+			name: "6",
+		}),
+	]
+
+	let mailLabelMap: Map<Id, ReadonlyArray<MailSet>>
+	let initialLabelStates: { label: MailSet; state: LabelState }[]
+	let viewModel: LabelsPopupViewModel
+
+	const checkStateChangeOutput = (expectedAdded: MailSet[], expectedRemoved: MailSet[], expectedMaxReached: boolean) => {
+		const { addedLabels, removedLabels } = viewModel.getLabelStateChange()
```
Comment (charlag) [inline test/tests/mail/view/LabelsPopupViewModelTest.ts:48]: aside: I would probably not test the internal workings of it and would just look at the observable state (what's the label state? is limit reached?). but it's also fine like this

File: test/tests/mail/view/LabelsPopupViewModelTest.ts [hunk 8]
```diff
@@ -0,0 +1,291 @@
...
+
+		o(addedLabels.length).equals(expectedAdded.length)
```
Comment (charlag) [inline test/tests/mail/view/LabelsPopupViewModelTest.ts]: why not `deepEquals`? because of the order?

File: src/mail-app/mail/view/LabelsPopupViewModel.ts (hunk 4 above)
Comment (wrdhub) [reply src/mail-app/mail/view/LabelsPopupViewModel.ts]: Yeah, it never checked at this point if the limit had been reached, relying on the UI to prevent a user from adding. I will add a check here.

File: src/mail-app/mail/view/LabelsPopupViewModel.ts (hunk 5 above)
Comment (wrdhub) [reply src/mail-app/mail/view/LabelsPopupViewModel.ts:56]: It is also accessed by labels popup to pass on which labels to apply

File: test/tests/mail/view/LabelsPopupViewModelTest.ts (hunk 6 above)
Comment (wrdhub) [reply test/tests/mail/view/LabelsPopupViewModelTest.ts:8]: why?

File: test/tests/mail/view/LabelsPopupViewModelTest.ts (hunk 7 above)
Comment (wrdhub) [reply test/tests/mail/view/LabelsPopupViewModelTest.ts:48]: I guess I see what you are saying here. But the whole motivation behind wanting tests and rewriting this whole thing was to double check what is getting passed to the server as added and removed is correct, so that is why we are checking what we are checking.

File: test/tests/mail/view/LabelsPopupViewModelTest.ts (hunk 6 above)
Comment (charlag) [reply test/tests/mail/view/LabelsPopupViewModelTest.ts:8]: just picked one option for consistency
