### PR TITLE
[desktop] try to find perfect match before fallback textId in Spellch…

### LINKED ISSUE #3659: Language options for spellchecking displaying incorrect name
For Portuguese, all three options `pt`, `pt-BR` and `pt-PT` show the name "Portuguese, Brazil". Maybe it should be just "Portuguese", like English is just that.

language_selection

### PR DESCRIPTION
**Pull request by ganthern**
…eckLanguageDialog.js

SpellcheckLanguageDialog.js looked for the first language in the
LanguageViewModel that fullfills any of these:
* its langCode-locale has perfect match with dictionaries langCode-locale
* it only has a langCode that matches the dictionaries' langCode perfectly
* the language code with its locale removed matches the dictionaries' langCode

the language pt-br runs into the third case and gets returned for the pt-pt dict,
even though later in the languages list there would be a perfect match with pt-pt.

this commit adds another missing language text id (Portuguese) and changes
the textId selection so it tries to find perfect matches before considering
any fallbacks.

fix #3659

### CODE REVIEW

File: src/gui/dialogs/SpellcheckLanguageDialog.js [hunk 1]
```diff
@@ -48,18 +48,18 @@ async function getItems(): Promise<Array<SelectorItem<string>>> {
...
-					// find the name for a language given a locale with a perfect match
-					(locale && language.code === `${langCode}_${locale.toLowerCase()}`)
-					// fine the name for a language without a locale, with a perfect match
-					|| language.code === langCode
-					// the code given by electron doesn't always have a locale when we do,
-					// e.g. for Persian we have "fa_ir" in LanguageViewModel, but electron only gives us "fa"
-					|| language.code.slice(0, 2) === langCode), language => language.textId)
-				|| getMissingLanguageLabel(langCode)
-
+			console.log(textId, langCode, locale)
```
Comment (johnbotris) [inline src/gui/dialogs/SpellcheckLanguageDialog.js:62]: leftover console.log

File: src/gui/dialogs/SpellcheckLanguageDialog.js [hunk 2]
```diff
@@ -48,18 +48,18 @@ async function getItems(): Promise<Array<SelectorItem<string>>> {
...
+			// first, find the name for a language given a locale with a perfect match
+			const l = languages.find(language => (locale && language.code === `${langCode}_${locale.toLowerCase()}`))
+				// find the name for a language without a locale, with a perfect match
+				|| languages.find(language => language.code === langCode)
+				// try to get a missing one before splitting
+				|| getMissingLanguage(langCode)
+				// the code given by electron doesn't always have a locale when we do,
+				// e.g. for Persian we have "fa_ir" in LanguageViewModel, but electron only gives us "fa"
+				|| languages.find(language => language.code.slice(0, 2) === langCode)
+			const textId = mapNullable(l, language => language.textId)
```
Comment (johnbotris) [inline src/gui/dialogs/SpellcheckLanguageDialog.js:60]: `mapNullable` has been made redundant by optional chaining, we should use that instead: `textId = l?.textId`. Also `l` should be named `language`

**Review by johnbotris — CHANGES_REQUESTED** [review]
looks good besides the nitpicks

**Review by johnbotris — APPROVED** [review]
