### PR TITLE
Show a dialog with failed emails while exporting

### LINKED ISSUE #6131: Mail exporter does not handle errors
> Tried to batch export, it showed "please wait" for ~~20 min, then error occured.

```
Client: linux
Tutanota version: 3.118.12
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.118.12 Chrome/116.0.5845.190 Electron/26.2.2 Safari/537.36
NotFoundError
Error message: 404: NisWj7I----9 | GET /rest/tutanota/mailbody/MXkKriT----2
Stacktrace:
NotFoundError: 404: NisWj7I----9 | GET /rest/tutanota/mailbody/MXkKriT----2
at df (asset://app/common-min-e1360136.js:1:10423)
at p.onload (asset://app/worker.js:12:23115)
```

Mail exporter should probably skip those email, optionally showing how many emails were exporter out of selected ones.

## Test Notes
- [ ] Exporting emails in batch works
- [ ] Exporting single emails works
- [ ] When you have any kind of error while exporting emails, the already downloaded emails are included in the zip file and you receive a message indicating which emails failed to export

### PR DESCRIPTION
**Pull request by murilopereirame**
When exporting emails there's no indicator of which emails failed to export.

This commit adds a Dialog informing the user which emails failed to export and export the emails that had success while downloading, so users doesn't lose all export progress. The dialog shows the sender and the subject of the email, allowing the user identify and retry the failed email.

fix #6131

## Merge notes
Needs translation update

### CODE REVIEW

**Comment by wrdhub** [comment]
I have some questions about how this interacts when going offline

File: src/mail/export/Exporter.ts [hunk 1]
```diff
@@ -67,7 +67,7 @@ export async function exportMails(
 	fileController: FileController,
 	operationId?: OperationId,
 	signal?: AbortSignal,
-): Promise<void> {
+): Promise<Mail[] | undefined> {
```
Comment (ganthern) [inline src/mail/export/Exporter.ts:70]: I think it would be fine to always return an array (empty if everything goes well). That way we don't miss void-returning branches if we refactor this.

but the doc-comment needs updating

File: src/mail/view/MailViewerToolbar.ts [hunk 2]
```diff
@@ -152,9 +155,13 @@ export class MailViewerActions implements Component<MailViewerToolbarAttrs> {
 								"{current}": Math.round((operation.progress() / 100) * attrs.mails.length).toFixed(0),
 								"{total}": attrs.mails.length,
 							}),
-						exportMails(attrs.mails, locator.mailFacade, locator.entityClient, locator.fileController, operation.id, ac.signal).finally(
-							operation.done,
-						),
+						exportMails(attrs.mails, locator.mailFacade, locator.entityClient, locator.fileController, operation.id, ac.signal)
+							.then((result) => {
+								if (result && result.length > 0) {
+									this.renderExportFailedEmailsDialog(result)
```
Comment (ganthern) [inline src/mail/view/MailViewerToolbar.ts:161]: convention-wise I would call this showExportFailedEmailsDialog since it's not part of the normal UI hierarchy in this component.

it also doesn't need to be a method as far as I can see

File: src/mail/view/MailViewerToolbar.ts [hunk 3]
```diff
@@ -164,6 +171,37 @@ export class MailViewerActions implements Component<MailViewerToolbarAttrs> {
...
+			actionButtonAttrs: null,
+		}))
+
+		const dialog = Dialog.createActionDialog({
+			title: lang.get("failedToExport_title"),
+			child: () =>
+				m("", [
+					m(".pt-m", lang.get("failedToExport_msg")),
+					m(ExpandableTable, {
+						title: () => lang.get("failedToExport_label", { "{0}": mailList.length }),
```
Comment (ganthern) [inline src/mail/view/MailViewerToolbar.ts:186]: This is purely subjective but I think just having the title be empty would look better because of the disparate fonts. ExpandableTable also has some weird padding that makes the "show" button just sit there randomly.
Ideally, the show button would be modified to say "show {count} failures" with proper alignment/spacing

File: src/mail/view/MailViewerToolbar.ts [hunk 4]
```diff
@@ -152,9 +156,9 @@ export class MailViewerActions implements Component<MailViewerToolbarAttrs> {
 								"{current}": Math.round((operation.progress() / 100) * attrs.mails.length).toFixed(0),
 								"{total}": attrs.mails.length,
 							}),
-						exportMails(attrs.mails, locator.mailFacade, locator.entityClient, locator.fileController, operation.id, ac.signal).finally(
-							operation.done,
-						),
+						exportMails(attrs.mails, locator.mailFacade, locator.entityClient, locator.fileController, operation.id, ac.signal)
+							.then(this.handleExportEmailsResult)
```
Comment (charlag) [inline src/mail/view/MailViewerToolbar.ts:160]: do not pass methods by reference, they lose `this` reference and it leads to *fun* errors

File: src/mail/export/Exporter.ts (hunk 1 above)
Comment (charlag) [reply src/mail/export/Exporter.ts]: This is really confusing semantically, both options, you need to read the jsdoc to figure out that it only returns failed mails, I would expect those are successful ones. How about

```ts
export async function exportMails(
  // args here...
): Promise<{exported: number, failed: number}> {
```

File: src/mail/export/Exporter.ts [hunk 5]
```diff
@@ -67,7 +67,7 @@ export async function exportMails(
 	fileController: FileController,
 	operationId?: OperationId,
 	signal?: AbortSignal,
-): Promise<Mail[]> {
+): Promise<{ failures: Mail[] }> {
```
Comment (charlag) [inline src/mail/export/Exporter.ts:70]: sorry for nitpick but `failures` sounds like those would be errors, I would maybe say `failed`?

**Comment by charlag** [comment]
Did you submit the translation keys already?

**Comment by murilopereirame** [comment]
> Did you submit the translation keys already?

Yes, staging project
