### PR TITLE
Fix invalid value attachments

### LINKED ISSUE #7355: ApiCallException$InternalSdkException: errorMessage=Invalid value not found: TypeRef(tutanota, File) attachments
1. Receive an email with attachment
2. See empty notification on Android

### PR DESCRIPTION
**Pull request by charlag**
Close #7355

### CODE REVIEW

File: tuta-sdk/rust/sdk/src/json_serializer.rs [hunk 1]
```diff
@@ -117,11 +134,14 @@ impl JsonSerializer {
...
-                    mapped.insert(association_name, ElementValue::IdGeneratedId(GeneratedId(id)));
+                    mapped.insert(
+                        association_name,
+                        ElementValue::IdGeneratedId(GeneratedId(id)),
+                    );
                 }
                 (
                     AssociationType::ListElementAssociation,
-                    Cardinality::One,
+                    Cardinality::One | Cardinality::ZeroOrOne,
```
Comment (wec43) [inline tuta-sdk/rust/sdk/src/json_serializer.rs:144]: For `ListElementAssociation`, `ZeroOrOne` is not `Option`?

Comment (charlag) [reply tuta-sdk/rust/sdk/src/json_serializer.rs:144]: what do you mean? We already handle all `ZeroOrOne` + `Null` cases together?

Comment (wec43) [reply tuta-sdk/rust/sdk/src/json_serializer.rs:144]: Ah ok I got confused. There are too many conditions.
