### PR TITLE
[desktop] Show message when needing to update manually if on macOS

### LINKED ISSUE #10185: [desktop] Mac client update fails when the client is ran from a read-only volume
**Steps to reproduce:**
- Run an old client directly from a downloaded `.dmg` without moving it to the Applications directory
- Attempt to update the client
- See that the update fails
- Check the logs and see the following error `"[ElectronUpdater]","ERROR:","Error: Error: Cannot update while running on a read-only volume. The application is on a read-only volume. Please move the application and try again. If you're on macOS Sierra or later, you'll need to move the application out of the Downloads directory. See https://github.com/Squirrel/Squirrel.Mac/issues/182 for more information."`

**AC:**
When the client is ran outside of the Applications directory, and there's an update, Have a dialog show with a message along the lines of "Something is preventing the update, please download and update manually." with a link to the download page.

**Implementation hint:**
Electron provides a method [`app.isInApplicationsFolder()`](https://www.electronjs.org/docs/latest/api/app#appisinapplicationsfolder-macos) that we can use to check if the client is in the Applications directory.

## Test notes

- [ ] Verify that running the app from outside of the applications folder displays a message urging the user to manually update when trying to update from within the app.

### PR DESCRIPTION
**Pull request by paw-hub**
This happens if the app is not in the Applications folder.

Closes #10185

### CODE REVIEW

File: src/common/desktop/ElectronUpdater.ts [hunk 1]
```diff
@@ -282,12 +283,21 @@ export class ElectronUpdater {
 	}
 
 	installUpdate() {
+		// We cannot reliably update on macOS if the app is not in the applications folder (e.g. might be in a DMG)
+		if (isAppleDevice() && !this.app.isInApplicationsFolder()) {
```
Comment (wrdhub) [inline src/common/desktop/ElectronUpdater.ts]: Could this trigger on mobile?

Comment (paw-hub) [reply src/common/desktop/ElectronUpdater.ts]: No. We don't use Electron on mobile.

Comment (paw-hub) [reply src/common/desktop/ElectronUpdater.ts]: That said this is probably still wrong, as I think we want to anyway check `process.platform` directly for desktop code, instead.
