### PR TITLE
[desktop] update electron deps, fix #1282

### LINKED ISSUE #1282: macOS:  Application crashes on exit with error dialog
This does not happen if you just open the app and then closing it immediately. You have to work a while with the desktop client and then quit the application. Here is an example output of the error information:

Process:               Tutanota Desktop [734]
Path:                  /Applications/Tutanota Desktop.app/Contents/MacOS/Tutanota Desktop
Identifier:            de.tutao.tutanota
Version:               3.50.10 (3.50.10.361)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Tutanota Desktop [734]
User ID:               501

Date/Time:             2019-05-07 10:35:58.875 +0200
OS Version:            Mac OS X 10.14.4 (18E226)
Report Version:        12

Time Awake Since Boot: 6500 seconds
Time Since Wake:       6300 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       EXC_I386_GPFLT
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [734]

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   com.github.Electron.framework 0x0000000106c4e4df 0x104eab000 + 31077599
1   com.github.Electron.framework 0x0000000106c4b00e 0x104eab000 + 31064078
2   com.github.Electron.framework 0x0000000106c4e5ef 0x104eab000 + 31077871
3   com.github.Electron.framework 0x0000000106c4c8f0 0x104eab000 + 31070448
4   com.github.Electron.framework 0x0000000106c4404a 0x104eab000 + 31035466
5   com.github.Electron.framework 0x0000000106b9ee0e 0x104eab000 + 30359054
6   com.github.Electron.framework 0x0000000106b19558 0x104eab000 + 29812056
7   com.github.Electron.framework 0x0000000104ead5df AtomMain + 95
8   de.tutao.tutanota             0x0000000104ea4f10 0x104ea4000 + 3856
9   libdyld.dylib                 0x00007fff660cd3d5 start + 1

### PR DESCRIPTION
**Pull request by ganthern**

### CODE REVIEW

File: buildSrc/electron-package-json-template.js [hunk 1]
```diff
@@ -7,6 +7,7 @@ const pj = require('../package.json')
  */
 
 module.exports = function (nameSuffix, version, targetUrl, iconPath, sign, notarize) {
+	//sign = false
```
Comment (charlag) [inline buildSrc/electron-package-json-template.js]: This
