### PR TITLE
Fix minor UI bugs - Missing delete button, calendar indicator shrinking and ext overflowing

### LINKED ISSUE #9563: Long text overflows EventDetailsView and becomes scrollable
**Mobile:**

### LINKED ISSUE #9626: iPad Air Landscape - Missing delete event button on agenda view
**Bug in mobile app**

**To Reproduce**
1. Go to agenda view
2. Open an event
3. Check that the delete button does not show up on the top right

### LINKED ISSUE #9627: Calendar indicator shrinks when calendar title is too big
In the event editor, if the user has a calendar with a long title the calendar color indicator will shrink to accommodate the long title.

## Test notes

**Create a calendar with a long title like: _Test calendar very long and unnecessary title because who knows maybe someone wants to give a calendar a very descriptive name_**

1. Open the event editor, either by editing an event or creating a new one
- [x] When the long titled calendar is selected the Select component should show a single line of text
- [x] The calendar color indicator, circle on the left, is shown as usual
- [x] Clicking on the select component should open a dropdown menu with the calendars options
  - [x] The long titled calendar is shown fully
  - [x] The calendar color indicator, circle on the left, is shown as usual

### PR DESCRIPTION
**Pull request by andrehgdias**
Closes #9563 
Closes #9626 
Closes #9627

### CODE REVIEW

File: src/calendar-app/calendar/gui/eventeditor-view/CalendarEventEditView.ts [hunk 1]
```diff
@@ -345,7 +345,14 @@ export class CalendarEventEditView implements Component<CalendarEventEditViewAtt
 						marginInline: px(size.vpad_xsm / 2),
 					},
 				}),
-				m("span", { style: { color: isSelected ? theme.content_button_selected : undefined } }, option.name),
+				m(
+					"span",
+					{
+						class: `${isDisplay ? "text-ellipsis" : ""}`,
```
Comment (murilopereirame) [inline src/calendar-app/calendar/gui/eventeditor-view/CalendarEventEditView.ts:351]: Why not ```isDisplay ? "text-ellipsis" : ""``` ?

**Review by murilopereirame — APPROVED** [review]
