### PR TITLE
Wait for extendMailIndex to finish before searching again

### LINKED ISSUE #8693: Extending search does not show new mails in mail list
**Steps to reproduce**
- In search view, extend the search range (by a month for example).
- Scroll to the bottom of the mail list.
- See that mails from the newly extended period do not appear on the list.

**Note that:**
- This does not happen all the time (sometimes mails do show in the list).
- Mails also appear when refreshing the search query, so mails are in fact fetched and indexed when the range is extended, just not rendered.

**Findings:**
- This bug might have started after the date picker was introduced.
- Date Picker instantly update the date in ``updateSearchUrl()`` before completing the indexing.
- This results in calling updateUI before the indexing completed and not updating UI after indexing.

**Time taken: 9h**

# Test notes
- [ ] Delete bedpremium@tutanota.com's credentials (if logged in) and re-login
- [ ] Wait for the initial one month index to build
- [ ] Search for "a"
- [ ] Change the start date to another date in the current index range (e.g. one day later). Click outside of the date picker dialog to start the search.
    - [ ] Verify that the search results refresh near-instantaneously.
- [ ] Change the start date to the previous year, 2024. Click outside of  the date picker dialog to start the search.
    - [ ] Verify a dialog appears asking to extend the mail index, and agree.
    - [ ] Initially, nothing happens (the URL does not change, and the results don't change).
    - [ ] Once the mail index is finished getting the previous year, the search results refresh with the new results, with the oldest results dating back to 2024.

### PR DESCRIPTION
**Pull request by paw-hub**
Closes #8693

### CODE REVIEW

File: src/mail-app/search/view/SearchViewModel.ts [hunk 1]
```diff
@@ -524,10 +524,20 @@ export class SearchViewModel {
...
-				this.indexerFacade.extendMailIndex(startDate.getTime()).then(() => {
-					this.updateSearchUrl()
-					this.updateUi()
+
+				const listModel = this._listModel
+				const endDate = this._endDate
+
+				this.indexerFacade.extendMailIndex(startDate.getTime()).then(async () => {
+					// don't do anything further if the search parameters were changed
+					if (this._startDate !== startDate || this._endDate !== endDate || this._listModel !== listModel || !this.freeToAskAboutExtendingIndex) {
```
Comment (charlag) [inline src/mail-app/search/view/SearchViewModel.ts:533]: is it enough to compare the times only? we usually use `isSameSearchRestriction()`

**Review by charlag — APPROVED** [review]
Great job! I think there might be some corner cases still but I thought it would not work with current search code at all.

File: src/mail-app/search/view/SearchViewModel.ts [hunk 2]
```diff
@@ -524,10 +524,17 @@ export class SearchViewModel {
...
 			if (confirmed) {
 				this._startDate = startDate
-				this.indexerFacade.extendMailIndex(startDate.getTime()).then(() => {
-					this.updateSearchUrl()
-					this.updateUi()
+
+				const searchRestriction = this.getRestriction()
+				this.indexerFacade.extendMailIndex(startDate.getTime()).then(async () => {
+					// don't do anything further if the search parameters were changed and thus createRestriction was called again
+					if (searchRestriction !== this.getRestriction()) {
```
Comment (charlag) [inline src/mail-app/search/view/SearchViewModel.ts:531]: this is a referential comparison but this is intentional? memoization is done on the whole URL but the restriction is only computed from part of it so it might sometimes be not referentially equal

File: src/mail-app/search/view/SearchViewModel.ts [hunk 3]
```diff
@@ -524,10 +524,17 @@ export class SearchViewModel {
 			this.freeToAskAboutExtendingIndex = true
 			if (confirmed) {
 				this._startDate = startDate
-				this.indexerFacade.extendMailIndex(startDate.getTime()).then(() => {
-					this.updateSearchUrl()
-					this.updateUi()
+
+				const searchRestriction = this.getRestriction()
+				this.indexerFacade.extendMailIndex(startDate.getTime()).then(async () => {
+					// don't do anything further if the search parameters were changed
```
Comment (hrb-hub) [inline src/mail-app/search/view/SearchViewModel.ts:530]: I think there's a typo in the comment?
// don't do anything further if the search parameters were **not** changed

Comment (hrb-hub) [reply src/mail-app/search/view/SearchViewModel.ts:530]: My bad the condition was incorrect then :sweat_smile:

**Review by hrb-hub — APPROVED** [review]

**Review by charlag — APPROVED** [review]
