### PR TITLE
Show header title as contactList name on mobile

### LINKED ISSUE #9487: Wrong header title for contact list on mobile
In 2 and 3 column layout the header says "contacts" even if the contact list is open which is misleading.

It should probably say contact list name, like mail folders do.

### Test Notes
- [x] Login and navigate to contacts. `Contacts` is showing as header title in 2 and 3 column layout.
- [x] Select one of the contactList, selected contactList name is showing as header title in 2 and 3 column layout

### PR DESCRIPTION
**Pull request by BijinDev**
In 2column and 3column layout header title were shown as Contacts even if the contactList is open.
Fixed by showing the selected contactList name as the header title.

Close #9487

### CODE REVIEW

File: src/mail-app/contacts/view/ContactView.ts [hunk 1]
```diff
@@ -347,9 +347,10 @@ export class ContactView extends BaseTopLevelView implements TopLevelView<Contac
 		)
 	}
 
-	private getHeaderLabel(): TranslationKey {
+	private getHeaderLabel() {
```
Comment (charlag) [inline src/mail-app/contacts/view/ContactView.ts]: please add a return type to it (I think it should either be `MaybeTranslation` or `Translation`)
