### PR TITLE
[desktop] properly handle findInPage rejections

### LINKED ISSUE #3362: Search in page error on quick keyboard input
When searching on a page with  <kbd>Ctrl</kbd>+<kbd>f</kbd> in the desktop client, an error is triggered when typing tooooo fast.

**To Reproduce**

**Note:** I can only reproduce on the production system, not locally

1. Open the desktop client
2. Hit <kbd>Ctrl</kbd>+<kbd>f</kbd> to get to the *Search in Page* overlay
3. Hit loads of buttons quickly, does not work when typing slowly (10 fast fingers anyone?)
```
TypeError
Error message: Cannot read property 'activeMatchOrdinal' of undefined
Stacktrace:
TypeError: Cannot read property 'activeMatchOrdinal' of undefined
at file:///tmp/.mount_tutanosAe8r9/resources/app.asar/native-main-9b277870.js:1:11513
at l (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/polyfill.js:1:81787)
at H._settlePromiseFromHandler (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/polyfill.js:1:54790)
at H._settlePromise (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/polyfill.js:1:55590)
at H._settlePromise0 (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/polyfill.js:1:56289)
at H._settlePromises (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/polyfill.js:1:57641)
at H._fulfill (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/polyfill.js:1:56659)
at Object.main486 (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/polyfill.js:1:44919)
at b._handleMessage (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/common-a3994593.js:1:6110)
at f.handleMessageObjectFromNative (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/native-common-0f760396.js:1:1461)
at Function.<anonymous> (file:///tmp/.mount_tutanosAe8r9/resources/app.asar/native-common-0f760396.js:1:599)
```

**Expected behavior**
No error shown, other behavior is as intended/expected.

**Context**
Looks like it is triggered by a `r == undefined` here:
https://github.com/tutao/tutanota/blob/18d3181a3421fc7ca116cc8423546f8f7c6709d6/src/gui/SearchInPageOverlay.js#L106

### PR DESCRIPTION
**Pull request by ganthern**
* handle CancelledError as an expected error
* log other rejections
* return null in any rejection case and for no results instead of mock result object
* 
close #3362

### CODE REVIEW

File: src/desktop/ApplicationWindow.js [hunk 1]
```diff
@@ -363,13 +364,13 @@ export class ApplicationWindow {
...
-	findInPage([searchTerm, options]: [string, {forward: boolean, matchCase: boolean}]): Promise<FindInPageResult> {
+	findInPage([searchTerm, options]: [string, {forward: boolean, matchCase: boolean}]): Promise<?FindInPageResult> {
 		this._findingInPage = true
 		if (searchTerm !== '') {
 			this._lastSearchRequest = [searchTerm, options]
 			this._browserWindow.webContents.findInPage(searchTerm, options)
 			return new Promise((resolve, reject) => {
-				this._lastSearchPromiseReject("outdated request")
+				this._lastSearchPromiseReject(new CancelledError("search request was superseded"))
 				this._lastSearchPromiseReject = reject
```
Comment (jowlo) [inline src/desktop/ApplicationWindow.js:374]: is this correct setting `_lastSearchPromiseReject` twice here?

Comment (ganthern) [reply src/desktop/ApplicationWindow.js:374]: _lstSearchPromiseReject is a function
the first line calls the last value with an error (rejecting the last search request if it is still ongoing, doing nothing if  the request is done because the function is replaced with noOp on request completion)

the second line replaces the function with the new request's reject callback.

**Review by jowlo — APPROVED** [review]
