### PR TITLE
Fix technical sender in info banner overflowing

### LINKED ISSUE #3910: Text overflow in mail authentication InfoBanner
Text overflow is not set correctly for the InfoBanner box on small screen sizes. See screenshot:
Screenshot_20220217_001856

# Test notes
- [ ] Resize the client's window to be small
- [ ] View an email with a notice that its contents cannot be verified but also shows a technical sender with a long address in a banner. Alternatively, use Developer Tools to make the displayed technical sender a long sequence of characters that cannot be broken up easily (e.g. a long sequence of repeated characters such as `aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa@email.com`).
- [ ] Verify that it is correctly wrapped to the end of the banner and that it does not overflow off the edge.

### PR DESCRIPTION
**Pull request by paw-hub**
InfoBanner's styling should be able to handle long words. For example, you may receive an email with a long technical sender containing words or sequences of characters that cannot be broken up nicely, and we do not want to have this overflow.

image

Fixes #3910

### CODE REVIEW

File: src/gui/base/InfoBanner.ts [hunk 1]
```diff
@@ -41,10 +41,11 @@ export class InfoBanner implements Component<InfoBannerAttrs> {
...
 			[
-				m(".flex", [
-					m(".mt-s.mr-s", this.renderIcon(icon, type ?? null)),
-					m(".flex-grow", [
-						m(".mr.pt-s", [m(".small", lang.getMaybeLazy(message))]),
+				m(".mt-s.mr-s", {style: {position: "absolute"}}, this.renderIcon(icon, type ?? null)), // absolute position makes the icon fixed to the top left corner of the banner
+				m("",
+					{style: {margin: "0 0 0 25px"}}, // allow room for the icon
+					[
+						m(".mr.pt-s", [m(".small", {style: {"word-wrap": "break-word"}}, lang.getMaybeLazy(message))]),
```
Comment (ganthern) [inline src/gui/base/InfoBanner.ts:48]: instead of the explicit style prop, try to use the css classes we already defined in the main-styles.ts, like:

https://github.com/tutao/tutanota/blob/f8f26b2cc2c2d05bc3aed4d8893e9ee1eb406b18/src/gui/main-styles.ts#L628-L630

**Review by ganthern — CHANGES_REQUESTED** [review]

File: src/gui/base/InfoBanner.ts (hunk 1 above)
Comment (paw-hub) [reply src/gui/base/InfoBanner.ts]: Should be good now!

File: src/gui/base/InfoBanner.ts [hunk 2]
```diff
@@ -41,10 +41,11 @@ export class InfoBanner implements Component<InfoBannerAttrs> {
 				},
 			},
 			[
-				m(".flex", [
-					m(".mt-s.mr-s", this.renderIcon(icon, type ?? null)),
-					m(".flex-grow", [
-						m(".mr.pt-s", [m(".small", lang.getMaybeLazy(message))]),
+				m(".mt-s.mr-s.abs", this.renderIcon(icon, type ?? null)), // absolute position makes the icon fixed to the top left corner of the banner
+				m("",
+					{style: {margin: "0 0 0 25px"}}, // allow room for the icon
```
Comment (ganthern) [inline src/gui/base/InfoBanner.ts:46]: if the size of icons changes, this will break. we can use the `size` object to relate this margin to the icon's size with `margin-left: px(size.icon_size_large + 1)`

**Review by ganthern — CHANGES_REQUESTED** [review]

File: src/gui/base/InfoBanner.ts (hunk 2 above)
Comment (paw-hub) [reply src/gui/base/InfoBanner.ts]: Fixed!

**Review by ganthern — APPROVED** [review]
