### PR TITLE
LoginForm should have email automatically focused if not on mobile

### LINKED ISSUE #2810: Focus username input when switching to login form from credentials selector
When you select "Different account" while viewing saved credentials in loginview, the username field isn't automatically focused, despite this being where you want to end up most of the time.

# Test notes
- [ ] With no credentials saved, open the client to view the login form.
    - [ ] (Desktop/Web) Verify that the email address text field has focus.
    - [ ] (Mobile - can use developer tools) Verify that no textbox is focused.
- [ ] Log in, saving credentials, and then sign out.
- [ ] With saved credentials on the login page, go to More -> Different account.
    - [ ] (Desktop/Web) Verify that the email address text field has focus.
    - [ ] (Mobile - can use developer tools) Verify that no textbox is focused.

## Regression test
- [ ] Create a new email and add a recipient.
    - [ ] Verify that suggestions are shown as you type the recipient.
    - [ ] Verify that the recipient is added successfully once finished.

### PR DESCRIPTION
**Pull request by paw-hub**
On a non-mobile device, we should automatically focus on email address so that the email can immediately be typed once on the login page.

Fixes #2810

### CODE REVIEW

File: src/gui/base/TextField.ts [hunk 1]
```diff
@@ -200,10 +200,9 @@ export class TextField implements ClassComponent<TextFieldAttrs> {
 						"aria-label": lang.getMaybeLazy(a.label),
 						oncreate: vnode => {
 							this.domInput = vnode.dom as HTMLInputElement
-							vnode.attrs.onDomInputCreated?.(this.domInput)
+							a.onDomInputCreated?.(this.domInput)
```
Comment (johnbotris) [inline src/gui/base/TextField.ts:203]: was this a bug?

**Review by johnbotris — APPROVED** [review]
