### PR TITLE
Fix duplicate shortcuts, Fix shortcuts not being removed

### LINKED ISSUE #3008: Shortcuts are listed multiple times in help
After hitting <kbd>F1</kbd> to see the shortcut help, some key (combinations) are listed multiple times. They should only appear once.

Screenshot from 2021-05-03 10-41-03

### PR DESCRIPTION
**Pull request by Pa7Hub**
fixes #3008

Function used for removing shortcuts would not remove some shortcuts due to invalid index.

### CODE REVIEW

File: src/mail/view/MailView.js [hunk 1]
```diff
@@ -243,7 +243,7 @@ export class MailView implements CurrentView {
 				},
 				help: "scrollToBottom_action"
 			},
-		].concat(listSelectionKeyboardShortcuts(() => this.mailList.list)).concat([
+		// ].concat(listSelectionKeyboardShortcuts(() => this.mailList.list)).concat([
```
Comment (johnbotris) [inline src/mail/view/MailView.js:246]: left in commented out code

File: src/misc/KeyManager.js [hunk 2]
```diff
@@ -148,7 +148,7 @@ class KeyManager {
 				       return
 			       }
 			       let shortcuts = ((this._modalShortcuts.length
-				       > 1) ? this._modalShortcuts : this._shortcuts).concat(this._desktopShortcuts) // we do not want to show a dialog with the shortcuts of the help dialog
+				       > 1) ? this._modalShortcuts : this._shortcuts.map(s => s.shortcut)).concat(this._desktopShortcuts) // we do not want to show a dialog with the shortcuts of the help dialog
```
Comment (johnbotris) [inline src/misc/KeyManager.js:151]: Could we un-bork the formatting here? you didnt do it i know but since it's being touched anyway...

File: src/misc/KeyManager.js [hunk 3]
```diff
@@ -172,17 +172,22 @@ class KeyManager {
...
 		Keys.META.code = (client.browser === BrowserType.FIREFOX ? 224 : 91)
-		addAll(this._shortcuts, shortcuts)
 		for (let s of shortcuts) {
 			let id = this._createKeyIdentifier(s.key.code, s.ctrl, s.alt, s.shift, s.meta)
+			this._shortcuts.push({id: id, shortcut: s})
 			this._keyToShortcut[id] = s
 		}
 	}
 
 	unregisterShortcuts(shortcuts: Shortcut[]) {
```
Comment (johnbotris) [inline src/misc/KeyManager.js:182]: (not sure where to put this comment) Do `registerModalShortcuts`/`registerDesktopShortcuts`/`unregisterModalShortcuts` still work after this change?

Comment (johnbotris) [reply src/misc/KeyManager.js:182]: I guess they should, maybe just make sure

**Review by johnbotris — CHANGES_REQUESTED** [review]

File: src/misc/KeyManager.js [hunk 4]
```diff
@@ -172,17 +173,22 @@ class KeyManager {
...
-		removeAll(this._shortcuts, shortcuts)
 		for (let s of shortcuts) {
 			let id = this._createKeyIdentifier(s.key.code, s.ctrl, s.alt, s.shift, s.meta)
+			this._shortcuts.forEach(s => {
```
Comment (johnbotris) [inline src/misc/KeyManager.js:186]: we should use `ArrayUtils.findAllAndRemove` here

**Review by johnbotris — CHANGES_REQUESTED** [review]

File: src/misc/KeyManager.js [hunk 5]
```diff
@@ -183,12 +183,7 @@ class KeyManager {
 	unregisterShortcuts(shortcuts: Shortcut[]) {
 		for (let s of shortcuts) {
 			let id = this._createKeyIdentifier(s.key.code, s.ctrl, s.alt, s.shift, s.meta)
-			this._shortcuts.forEach(s => {
-				if (s.id === id) {
-					let i = this._shortcuts.indexOf(s)
-					this._shortcuts.splice(i, 1)
-				}
-			})
+			findAllAndRemove(this._shortcuts, (s) => s.id === id)
```
Comment (johnbotris) [inline src/misc/KeyManager.js:186]: After looking at this again I think we have a chance to improve the key manager while we're changing it anyway - It seems like we are redundantly tracking shortcuts in both an array (`_shortcuts`) and a map (`_keyToShortcut`) for no reason (and same for modal shortcuts). It would be good to clean this up a bit, and I don't think it would be too extensive of a change

Comment (jowlo) [reply src/misc/KeyManager.js:186]: Yes, i had noticed this as well. We need to make sure that we reset to the correct shortcuts when we close a modal though.
