### PR TITLE
Fix all-day events spanning two days when created at the end of the day

### LINKED ISSUE #7723: All day events created near the end of a day default to two days
When creating an all day event near the end of a day, where the default end of the event will be on a new day, the event will be all day for both days. Changing the event to be an all day event for a single day does not work, the "To" always falls back to the second day.

e.g. an event created for the 23rd of February at 23:45 to 24th of February 00:15 results in a 2 day all day event, and with the "All day" toggle selected the to day cannot be set to the 23rd.

### PR DESCRIPTION
**Pull request by andrehgdias**
Fixed the issue by allowing users to change the end date back to the same date as the initial date.
Closes #7723

### CODE REVIEW

File: src/common/api/common/utils/CommonCalendarUtils.ts [hunk 1]
```diff
@@ -180,3 +180,30 @@ export enum CalendarViewType {
...
+ * Checks if dateA occurs before dateB based on the specified comparison type.
+ *
+ * @param {Date} dateA - The first date to compare.
+ * @param {Date} dateB - The second date to compare.
+ * @param {string} comparisonType - The type of comparison to perform.
+ *                              "full" = compare date and time,
+ *                              "dayMonthYear" = compare only day, month, and year.
+ * @returns {boolean} - Returns true if dateA is before dateB according to the comparison type, false otherwise.
+ */
+export function isBefore(dateA: Date, dateB: Date, comparisonType: "full" | "dayMonthYear"): boolean {
```
Comment (murilopereirame) [inline src/common/api/common/utils/CommonCalendarUtils.ts:194]: I'd suggest date and dateTime as comparison types

File: src/common/api/common/utils/CommonCalendarUtils.ts [hunk 2]
```diff
@@ -180,3 +180,30 @@ export enum CalendarViewType {
...
+	switch (comparisonType) {
+		case "full":
+			return dateA.getTime() < dateB.getTime()
+		case "dayMonthYear": {
+			const [day1, month1, year1] = [dateA.getDate(), dateA.getMonth(), dateA.getFullYear()]
```
Comment (murilopereirame) [inline src/common/api/common/utils/CommonCalendarUtils.ts:199]: Wouldn't it be easier and faster to set both dates to midnight and return? ```dateA.getTime() < dateB.getTime()``` ?

**Review by murilopereirame — APPROVED** [review]
