### PR TITLE
Fix updating deleted event show error

### LINKED ISSUE #3388: Updating deleted event shows error
### Steps to reproduce
1. Open calendar of same account in two browser windows
2. Create event
3. Open edit dialog in first window
4. Delete event in second window
5. Save changes to event in first window
6. See error

```
Feedback v3.86.0 - NotFoundError - PREMIUM - Browser
Client: Browser
Type: PREMIUM
Tutanota version: 3.86.0
Timestamp (UTC): Mon, 16 Aug 2021 07:01:55 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36
NotFoundError
Error message: 404: MhCl2QY----0 | PUT /rest/tutanota/calendarevent/MgzaHuZ--B-0/MTYyODAzODc1MzkyMA
Stacktrace:
NotFoundError: 404: MhCl2QY----0 | PUT /rest/tutanota/calendarevent/MgzaHuZ--B-0/MTYyODAzODc1MzkyMA
at ai (https://test.tutanota.com/common-min-0b4a1380.js:1:2210)
at XMLHttpRequest.p.onload (https://test.tutanota.com/worker.js:1:101575)
```

## Test Notes
- [ ] Do the same steps to reproduce, but when try to save the event, you see a dialog informing that the event no longer exists
- [ ] Editing existing events still working

### PR DESCRIPTION
**Pull request by murilopereirame**
When the user tries to update an event that was deleted, they receive just an error.

Now, the app handles the NotFoundError and shows a message to the user informing that the event doesn't exist anymore.

fix #3388

### CODE REVIEW

File: src/translations/en.ts [hunk 1]
```diff
@@ -1598,6 +1598,7 @@ export default {
 		"yourCalendars_label": "Your calendars",
 		"yourFolders_action": "YOUR FOLDERS",
 		"yourMessage_label": "Your message",
-		"you_label": "You"
+		"you_label": "You",
+		"eventNoLongerExists_msg": "The requested event no longer exists"
```
Comment (ganthern) [inline src/translations/en.ts:1602]: I'd rather say "the edited event no longer exists and couldn't be updated" to be very explicit

**Review by ganthern — APPROVED** [review]

**Comment by rezbyte** [comment]
Hey, just testing this on the test build. I am getting the 'The requested event no longer exists' error message whenever I edit an event now.
