### PR TITLE
Fix mails disappear from search view when moved

### LINKED ISSUE #1732: Mails disappear from search view when moved
**Describe the bug**
Mails disappear from search view when moved even though the selected "Email folder" is "All"

**To Reproduce**
1. Search some emails in all folders.
2. Select one from the results and move to a different folder.

**Expected behavior**
The email stays in the search results, with a different location.

**Actual behavior**
Email disappears from search results.

## Test Notes
* [ ] Searching for emails/contacts still working
* [ ] When an email is updated by another client, the search receive and applies the update
* [ ] Editing an email from the search works
* [ ] When an email is moved to a folder included on the search it's shown or updated
* [ ] When an email is moved to a folder excluded from the search, it's removed

### PR DESCRIPTION
**Pull request by murilopereirame**
When the user search for emails and another client do some update that
affects the current results, the affected emails where gone from the
list and the search needs to be done again.

This happens due the fact that the **MOVE** operation consists on the
combination of the DELETE and CREATE operations. So, when the client
receives the DELETE action, the email is removed from the list but not 
re-added when the CREATE action is received.

This commit handles the MOVE operation by checking if it really is a
MOVE operation (the updates contain a CREATE and DELETE for same id) and
then handle to update the current states to match the new listId.

fix #1732

### CODE REVIEW

File: src/misc/ListModel.ts [hunk 1]
```diff
@@ -231,16 +231,19 @@ export class ListModel<ElementType extends ListElement> {
 		// We cannot use binary search here because the sort order of items can change based on the entity update and we need to find the position of the
 		// old entity by id in order to remove it.
 
+		// Since every element id is unique and there's no scenario where the same item appears twice but in different lists, we can safely sort just
```
Comment (charlag) [inline src/misc/ListModel.ts:234]: Element IDs don't have to be unique, they are not all `GeneratedId`s but that *was* the assumption here in the ListModel that the given IDs don't repeat until the calendar search. Will it work with that?

Comment (murilopereirame) [reply src/misc/ListModel.ts:234]: > Element IDs don't have to be unique, they are not all `GeneratedId`s but that _was_ the assumption here in the ListModel that the given IDs don't repeat until the calendar search. Will it work with that?

No, it will not work. Thanks for remembering about this case.
When we generate the further events, they have the same ID as their progenitor

Comment (murilopereirame) [reply src/misc/ListModel.ts:234]: It should work, generated events already have the same ID as their progenitor, so do the comparison by the elementIdpart or by the full element will lead to the same behavior.

**Review by charlag — APPROVED** [review]
