### PR TITLE
Fix pressing enter bypassing the `confirmFreeSubscription` dialog

### LINKED ISSUE #5169: Pressing enter on free signup bypasses the checkboxes
During free signup when the message ("I don't own any other free account..." -> Screenshot) shows up,
you can bypass clicking the checkboxes by just pressing enter

**To Reproduce**
1. click on signup
2. select free subscription
3. popup shows up
4. press enter
5. the next signup page opens

image

### PR DESCRIPTION
**Pull request by rezbyte**
Stops users from bypassing the business & age check boxes when signing up for a free account.

Closes #5169.

### CODE REVIEW

File: src/subscription/UpgradeSubscriptionPage.ts [hunk 1]
```diff
@@ -207,7 +207,7 @@ function confirmFreeSubscription(): Promise<boolean> {
 			dialog.close()
 			setTimeout(() => resolve(confirmed), DefaultAnimationTime)
 		}
-
+		const isFormValid = stream.lift((_oneAccountValue, _privateUseValue) => _oneAccountValue && _privateUseValue, oneAccountValue, privateUseValue)
```
Comment (charlag) [inline src/subscription/UpgradeSubscriptionPage.ts:210]: I think I would just make a method instead of a new stream, we don't need to listen to it

Comment (rezbyte) [reply src/subscription/UpgradeSubscriptionPage.ts]: Fair point, changed.

**Review by wrdhub — APPROVED** [review]
