### PR TITLE
fix wrong operator binding when deciding on date to use for new event

### LINKED ISSUE #5124: Wrong pre-selected date and time when creating calendar event
How to reproduce:
1. Log in into your Tutanota account.
2. Click on a time slot during the day in the week view (but not on the first day of the week).
-> The event editor is opened and the pre-selected day is the first day of the week and the time is 00:00 - 00:30
Expected: The pre-selected date and time is what you had clicked on.
When doing the same thing again without logging in again, the day will match your selection but the time will still be 00:00 - 00:30.

This bug might lead to creating events at the wrong day and time unnoticed.

Reproduced in v3.109.1 in the desktop client on Ubuntu.

### PR DESCRIPTION
**Pull request by ganthern**
fix #5124

### CODE REVIEW

File: src/calendar/view/CalendarView.ts [hunk 1]
```diff
@@ -376,7 +378,7 @@ export class CalendarView extends BaseTopLevelView implements TopLevelView<Calen
 		}
 
 		Promise.all([calendarInfos, locator.mailModel.getUserMailboxDetails()]).then(([calendars, mailboxDetails]) =>
-			showCalendarEventDialog(dateToUse, calendars, mailboxDetails),
+			showCalendarEventDialog(assertNotNull(date, "date for new event was null"), calendars, mailboxDetails),
```
Comment (charlag) [inline src/calendar/view/CalendarView.ts:381]: we can really do without assert here, maybe make a new variable?

Comment (ganthern) [reply src/calendar/view/CalendarView.ts:381]: tried that, TS was not happy (check the compare button next to the force push)

**Review by charlag — APPROVED** [review]
