### PR TITLE
fix DesktopSseClient and DesktopIntegrator tests

### LINKED ISSUE #3065: Failing desktop test
Desktop tests were broken by the babel async to generator plugin

### PR DESCRIPTION
**Pull request by johnbotris**
fix #3065

### CODE REVIEW

File: src/desktop/DesktopMain.js [hunk 1]
```diff
@@ -26,7 +26,7 @@ import {ElectronNotificationFactory} from "./NotificatonFactory"
 import {KeytarSecretStorage} from "./sse/SecretStorage"
```
Comment (charlag) [inline src/desktop/DesktopMain.js:26]: I think it's much better than before. It still has init(), startupInstance() and main(). We still handle argv in two places outside of handleArgv() and `wasAutolaunched` is inside components? If think if you touch this we should fix at least some of these

**Review by charlag — APPROVED** [review]
