### PR TITLE
give ViewSlider the ability to handle browser history events

### LINKED ISSUE #4731: In single-column mode settings subitems lists, using the browser back button on a details screen leads to an empty list
In single column mode:
1. go to one of the settings : My Templates, User management, Groups, Whitelabel accounts, Contact forms, Knowledgebase - My Templates (all settings that have a list of items are affected)
2. view one of the items' details page in the settings
3. use the system back button or browser back button (maybe twice)
4. get an empty list where the list of groups/whitelabel accounts/contact forms should be

Affects v3.104.2 Firefox on Linux, Chrome on Android and Safari on iOS
Also happens on 3.103.3

### Notes
* this works fine in the android app with the system back button, the WebMobileFacade contains all the logic to do this correctly.
* the ViewSlider doesn't register history listeners on the windowFacade so it can't react to the browser back button

## Test Notes
test on firefox, chrome and safari (user management is enough). All of this is about single-column mode.

* [ ] the bug doesn't reproduce anymore
* [ ] when the drawer menu (mail view shows folders here) is open in the settings, hitting the back button closes it
* [ ] if it is not open, we go back in history (potentially to the login page if that's the last entry in history)

### Regressions
* [ ] on an android with a hardware/dedicated software back button we can still use that button to go from user details view to user list
* [ ] on androids with pure gesture navigation we can still navigate between details, list and drawer as usual
* [ ] the back button in the browser behaves as expected in multi-column mode.
* [ ] search for some email and select it
* [ ] the browser back button leads back to the list of search results
* [ ] click a calendar event to open the preview popup and use the browser back button to close it again
* [ ] edit a calendar event and use the browser back button to close it again
* [ ] test the interaction with stacked modals and the view slider -> just check for sensible behavior with the browser back button

### PR DESCRIPTION
**Pull request by ganthern**
if the view slider has a previous (further left) column that's not a foreground column it can focus, it will do so and signal the window facade that the back button event has been handled.

otherwise, if the focused column is a foreground column, it will focus the next column to the right and signal the handled event. this has the effect of closing the drawer menu in our application.

fix #4731

Co-authored-by: nok <nok@tutao.de>

### CODE REVIEW

File: src/gui/nav/ViewSlider.ts [hunk 1]
```diff
@@ -48,17 +46,32 @@ export class ViewSlider implements Component<ViewSliderAttrs> {
 	private _busy: Promise<unknown>
 	private _parentName: string
 	private _isModalBackgroundVisible: boolean
+	private resizeListener: windowSizeListener = () => this._updateVisibleBackgroundColumns()
+	private handleHistoryEvent = () => {
```
Comment (charlag) [inline src/gui/nav/ViewSlider.ts:50]: would be great to unify it with `handleBackPress()` but I guess it isn't possible at the moment at least

File: src/gui/nav/ViewSlider.ts [hunk 2]
```diff
@@ -48,17 +46,32 @@ export class ViewSlider implements Component<ViewSliderAttrs> {
 	private _busy: Promise<unknown>
 	private _parentName: string
 	private _isModalBackgroundVisible: boolean
+	private resizeListener: windowSizeListener = () => this._updateVisibleBackgroundColumns()
```
Comment (charlag) [inline src/gui/nav/ViewSlider.ts:49]: can make them `readonly` right?

File: src/misc/WindowFacade.ts [hunk 3]
```diff
@@ -188,6 +188,14 @@ export class WindowFacade {
 		}
 	}
 
+	removeHistoryEventListener(listener: (e: Event) => boolean): void {
+		const index = this._historyStateEventListeners.indexOf(listener)
```
Comment (charlag) [inline src/misc/WindowFacade.ts:192]: we have `remove()` at home

File: src/gui/nav/ViewSlider.ts [hunk 4]
```diff
@@ -48,17 +46,32 @@ export class ViewSlider implements Component<ViewSliderAttrs> {
...
+	private handleHistoryEvent = () => {
+		const prev = this.getPreviousColumn()
+		if (prev != null && prev.columnType !== ColumnType.Foreground) {
+			this.focusPreviousColumn()
```
Comment (charlag) [inline src/gui/nav/ViewSlider.ts:53]: when we return `false`, `WindowFacade` will try to revert the history change but that should be okay because the item in the list has the same URL, right? In my (limited) testing it works except it fires `updateUrl()` twice.

out of scope but we probably should discuss changing how routing works for single-column layout so that if we have `mailListId/mailId` it shows you the viewer and if you are in the list it should be just `mailLlistId`.

**Review by charlag — APPROVED** [review]

**Comment by charlag** [comment]
also I think we should expand test notes for regressions to test cases in search/calendar

File: src/gui/nav/ViewSlider.ts (hunk 4 above)
Comment (nokhub) [reply src/gui/nav/ViewSlider.ts:53]: false means we handled it and the window facade should try to revert the change, yes

**Review by charlag — APPROVED** [review]
