### PR TITLE
Only process updates for calendar group in CalendarViewModel, fix #4977

### LINKED ISSUE #4977: Shared calendar group names are changed if user name is changed
How to reproduce:
1. User 1 shares one or multiple calendars with user 2
2. User 2 changes their user name
-> The shared calendars names at user 1 change to the new name of user 2 and they all have the default color

After logging out and in again this is resolved.

### PR DESCRIPTION
**Pull request by sarashub**
close #4977

### CODE REVIEW

File: src/calendar/view/CalendarViewModel.ts [hunk 1]
```diff
@@ -444,13 +443,15 @@ export class CalendarViewModel implements EventDragHandlerCallbacks {
 					}
 				} else if (isUpdateForTypeRef(GroupInfoTypeRef, update)) {
 					this._calendarInfos.getAsync().then((calendarInfos) => {
-						const calendarInfo = calendarInfos.get(eventOwnerGroupId) // ensure that it is a GroupInfo update for a calendar group.
+						const calendarInfo = calendarInfos.get(eventOwnerGroupId)
```
Comment (charlag) [inline src/calendar/view/CalendarViewModel.ts:446]: would it make more sense to only reload if `calendarInfo.groupInfo._id` is the same as updated id? Then we don't need to check group types and such

**Review by ganthern — APPROVED** [review]
