### PR TITLE
Fix being able to open Labels dropdown even if there are no labels

### LINKED ISSUE #8141: It is possible to open Labels dropdown even when there are no labels
It is possible to open it even when there are no labels

_Originally posted by @charlag in https://github.com/tutao/tutanota/issues/8007#issuecomment-2541432021_

**Estimated : .25h**
**Time Taken: .25h**

**Test Notes**
- [ ] Not able to perform apply labels from shortcut (by L button) without opening an email.
- [ ] Able to see Labels dropdown (shortcut by L button) if atleast one label present

### PR DESCRIPTION
**Pull request by BijinDev**
The issue is being able to open labels dropdown even if there are no labels.
Resolved by only showing dropdown if there are any labels found.

close #8141

### CODE REVIEW

File: src/mail-app/mail/view/MailView.ts [hunk 1]
```diff
@@ -585,13 +585,14 @@ export class MailView extends BaseTopLevelView implements TopLevelView<MailViewA
 	 *Shortcut Method to show Labels dropdown only when atleast one mail is selected.
 	 */
 	private labels() {
-		const mailList = this.mailViewModel.listModel
-		if (mailList == null) {
+		const mailList = assertNotNull(this.mailViewModel.listModel)
```
Comment (charlag) [inline src/mail-app/mail/view/MailView.ts:588]: we should not unwrap it I think, we might not have a list model if the connection is too slow. Before it was checking for it and we should keep it this way.

**Review by charlag — CHANGES_REQUESTED** [review]

**Review by charlag — APPROVED** [review]
