### PR TITLE
Always get result of inbox rule match to use after spam classification

### LINKED ISSUE #10598: Inbox rule priority not respected when "Never send it to spam" is unchecked
**Steps to reproduce:**
- Create inbox rule **A** with **"Never send it to spam"** unchecked
- Create inbox rule **B** with **"Never send it to spam"** checked
- Make sure rule **A** is on top
- Receive an email that matches both inbox rules **A** and **B**
- See that inbox rule **B** is applied even though **A** should take priority

**Expected behavior:**
Inbox rule priority is respected regardless of whether **"Never send it to spam"** is checked or not.

**Additional information:**
This happens because we process rules excluded from spam filter first (we should probably rethink this), see: https://github.com/tutao/tutanota/blob/9bd1e459a5e60ab7be4648bd985031e548f483e4/src/mail-app/mail/model/ProcessInboxHandler.ts#L94-L116

**Implementation hint:**
To solve this, we could apply all inbox rules **before** spam classification and include the **"Never send it to spam"** value of the matching rule in the result we get from applying rules. We then only do spam classification if no inbox rule matches, or if the matching rule does not exclude spam classification.

**Estimated: 2h**

### PR DESCRIPTION
**Pull request by wrdhub**
Fixes #10598

### CODE REVIEW

File: src/mail-app/mail/model/ProcessInboxHandler.ts [hunk 1]
```diff
@@ -91,25 +91,23 @@ export class ProcessInboxHandler {
...
 
 		// We process rules which are excluded from spam list first and if none apply then we run spam prediction.
-		const result = await this.inboxRuleHandler()?.findAndApplyRulesExcludedFromSpamFilter(mailboxDetail, mail, sourceFolder)
-		if (result) {
-			const { targetFolder, processInboxDatum } = result
-			finalProcessInboxDatum = processInboxDatum
-			moveToFolder = targetFolder
-		} else {
+		const matchingInboxRule = await this.inboxRuleHandler()?.findMatchingInboxRule(mailboxDetail, mail, sourceFolder)
+		if (!matchingInboxRule || (matchingInboxRule && !matchingInboxRule.excludeFromSpamFilter)) {
```
Comment (hrb-hub) [inline src/mail-app/mail/model/ProcessInboxHandler.ts]: This might be easier to understand if the condition was flipped. We then can just check `matchingInboxRule?.excludeFromSpamFilter`

**Comment by hrb-hub** [comment]
Apart from failing tests needing fixed, the rest looks good! good job!

**Review by hrb-hub — APPROVED** [review]
