### PR TITLE
fix trying to log the stack of an undefined error

### LINKED ISSUE #4932: Uncaught TypeError: Cannot read properties of undefined (reading 'stack')
```
Client: Browser
Type: PREMIUM
Tutanota version: 3.106.5
Timestamp (UTC): Thu, 05 Jan 2023 12:47:44 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/108.0.0.0 Safari/537.36
TypeError
Error message: Cannot read properties of undefined (reading 'stack')
Stacktrace:
TypeError: Cannot read properties of undefined (reading 'stack')
at yt (https://mail.tutanota.com/app.js:1:80846)
at https://mail.tutanota.com/app.js:1:119112
```

### PR DESCRIPTION
**Pull request by ganthern**
close #4932

### CODE REVIEW

File: src/misc/ErrorHandler.ts [hunk 1]
```diff
@@ -40,7 +40,11 @@ function produceThrottledFunction<R>(ms: number, fn: () => Promise<R>): () => Pr
  * */
 const importErrorHandler = produceThrottledFunction(200, () => import("./ErrorHandlerImpl.js"))
 
-export async function handleUncaughtError(e: Error) {
+export async function handleUncaughtError(e?: Error) {
+	if (e == null) {
```
Comment (charlag) [inline src/misc/ErrorHandler.ts:44]: if we get here and the error is not there for some reason I think we should create a new error and act on it, we can at least get some stack trace, this should not happen normally

Comment (ganthern) [reply src/misc/ErrorHandler.ts:44]: isn't the uncaught error handler invoked from the top level after the original stack has been completely unwound?

Comment (charlag) [reply src/misc/ErrorHandler.ts:44]: It can be:
 - `window` `error` event
 - `window` `unhandledrejection` event
 - the one from worker
 - the one from `NavButton`
 - the one from `ServiceWorkerClient`

we could at least guess which one it is that is misbehaving

Comment (ganthern) [reply src/misc/ErrorHandler.ts:44]: in the report where I can check it it's the unhandledRejection event with an undefined reason. It's also happening exclusively on safari.

Comment (charlag) [reply src/misc/ErrorHandler.ts:44]: ah, okay then, should we at least print something? not nice if we completely eat up the errors

Comment (ganthern) [reply src/misc/ErrorHandler.ts:44]: yes, I can see that.

**Review by charlag — APPROVED** [review]
