### PR TITLE
Fix agenda view scrolling on different layouts

### LINKED ISSUE #6402: Agenda scroll works on three columns layout but not on one/two columns layout
The scroll works on three columns layout but not on one/two columns layout.
Also, not working on mobile devices.

See https://github.com/tutao/tutanota/issues/6326#issuecomment-1899967655

## How to Reproduce
With the latest test release on mobile devices or on one/two columns layout:
- [ ] Open Agenda view
- [ ] Add events until they became off screen
- [ ] Try to scroll

## Test notes
- [ ] On a mobile device, do the following:
    - [ ] In the Agenda view, try scrolling on a day that has too many items to display at once. Verify it works.
    - [ ] Verify swiping left to right works as expected in the following views:
        - [ ] Agenda
        - [ ] Day
        - [ ] Week
        - [ ] Month
- [ ] On a desktop computer in the Agenda view, verify that vertical scrolling works in the following layouts:
    - [ ] One-column
    - [ ] Two-column
    - [ ] Three-column
- [ ] On a desktop computer in the Day view on an empty day, try resizing the window vertically. Verify no scrollbar flickers in and out of existence, and that there is no horizontal scrollbar.

### PR DESCRIPTION
**Pull request by paw-hub**
Fix that vertical scrolling does not work on 1/2 column layouts, and that there is no horizontal scrolling bar, either.

Also remove a styling workaround to fix an issue with scrollbars, as this also fixes the vertical scrollbar randomly appearing.

Fixes #6402 and #6326

### CODE REVIEW

**Review by ganthern — APPROVED** [review]

File: src/gui/base/PageView.ts [hunk 1]
```diff
@@ -55,7 +47,7 @@ export class PageView implements Component<Attrs> {
 						attrs.previousPage.nodes,
 					),
 					m(
-						".fill-absolute",
+						".fill-absolute.overflow-y-scroll",
```
Comment (charlag) [inline src/gui/base/PageView.ts:50]: i don't think PageView itself should scroll, maybe stuff inside of it.
