### PR TITLE
Handle birthday parse exceptions

### LINKED ISSUE #2708: Contact view not usable after opening contact with invalid birthday
Import the attached contact and then observe what happens to the contact viewer and folder section. Contact is not displayed and cannot be deleted.
contact-view

[contact-invlaid-birthday.txt](https://github.com/tutao/tutanota/files/5972362/contact-invlaid-birthday.txt)

### PR DESCRIPTION
**Pull request by jowlo**
Incorrect birthdays are now silently not imported. Surprisingly, not
handling the exception broke the whole UI.

The vcard importer probably needs a rewrite as real parser.

fix #2708

### CODE REVIEW

File: src/contacts/view/ContactViewer.js [hunk 1]
```diff
@@ -257,11 +257,15 @@ export class ContactViewer {
 	}
 
 	_formatBirthday(): string {
+		let bday = ""
 		if (this._hasBirthday()) {
-			return formatBirthdayWithMonthName(isoDateToBirthday(neverNull(this.contact.birthdayIso)))
-		} else {
-			return ""
+			try {
+				bday = formatBirthdayWithMonthName(isoDateToBirthday(neverNull(this.contact.birthdayIso)))
```
Comment (charlag) [inline src/contacts/view/ContactViewer.js:263]: This is invoked on every render which is already bad enough but if we try/catch/console.log it's going to heat entire district.
Maybe if we are here we should put it into some `memoized` thingy.

Comment (jowlo) [reply src/contacts/view/ContactViewer.js]: yes, that's true. thanks for the pointer to the `memoized` stuff

File: src/contacts/view/ContactViewer.js [hunk 2]
```diff
@@ -129,7 +129,9 @@ export class ContactViewer {
 									insertBetween([
 										this.contact.company ? m("span.company", this.contact.company) : null,
 										this.contact.role ? m("span.title", this.contact.role) : null,
-										this._hasBirthday() ? m("span.birthday", this._formatBirthday()) : null
+										this._hasBirthday() && this.contact.birthdayIso
+											? m("span.birthday", memoized(this._formatBirthday)(neverNull(this.contact.birthdayIso)))
```
Comment (charlag) [inline src/contacts/view/ContactViewer.js:133]: That's not exatly how memoized works. You need to keep the result of `memoized` in a field so that it caches the return value internally. Right now you create a new memoized function each time and call it so there's no difference.

Also, passing `this._formatBirthday` like this will lose `this` so I would just make it freestanding below to avoid confusion.

Comment (jowlo) [reply src/contacts/view/ContactViewer.js:133]: Actually i looked at the code just realized that memoized only has a single "cache" entry. So yes, that does not make any sense in multiple ways...

Comment (charlag) [reply src/contacts/view/ContactViewer.js:133]: Ah , yes, it's also an array, isn't it? hmm

Comment (jowlo) [reply src/contacts/view/ContactViewer.js:133]: The parameter `birthdayIso`? Thats actually a string...

Comment (charlag) [reply src/contacts/view/ContactViewer.js:133]: no, wait, I thought insertBetween operates on multiple dates or something but it doesn't, why would `memoized` work? you should only have 0 or 1 birthday here?

Comment (jowlo) [reply src/contacts/view/ContactViewer.js]: Well, i guess technically it would work, but then again we dont update this contact view when the contact changes anyway (which was what i was going for). So we can just save the formatted string upon component creation.

Comment (charlag) [reply src/contacts/view/ContactViewer.js]: Wait, but we do update the view? We create the new one? Yeah, then it's easiest to just save it, otherwise I woul do memoize.

Comment (jowlo) [reply src/contacts/view/ContactViewer.js]: Yes, if there is an entity update we create a new viewer. But actually, i just saw that `this.contactAppellation` is saved on the Viewer so it doesn't make too much sense not to also save the Birthday.

**Review by charlag — APPROVED** [review]
