### PR TITLE
[desktop/win] fix joinFiles not closing the output stream

### LINKED ISSUE #4946: Uncaught Error: EPERM Operation not permitted when trying to directly open attachments (as opposed to download, then open)
Seems to happen at least since 3.103.3 on windows only:

```
Client: win32
Type: PREMIUM
Tutanota version: 3.106.4
Timestamp (UTC): Fri, 06 Jan 2023 12:06:33 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.106.4 Chrome/108.0.5359.62 Electron/22.0.0 Safari/537.36
Error
Error message: EPERM: operation not permitted, open 'C:\Users\noo\AppData\Local\Temp\tutanota\nkX3ZzdgucS7lQyX8LnRtQ\download\QUOTE - CM_FR_20230111_71956 .pdf'
Stacktrace:
Error: EPERM: operation not permitted, open 'C:\Users\noo\AppData\Local\Temp\tutanota\nkX3ZzdgucS7lQyX8LnRtQ\download\QUOTE - CM_FR_20230111_71956 .pdf'
```

```
Client: win32
Type: PREMIUM
Tutanota version: 3.103.3
Timestamp (UTC): Mon, 07 Nov 2022 14:32:35 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.103.3 Chrome/102.0.5005.167 Electron/19.1.3 Safari/537.36
Error
Error message: EPERM: operation not permitted, open 'C:\Users\noo\AppData\Local\Temp\tutanota\HOxRpF7Wor9FNvnmzpT7qw\download\Emran Aloul.pdf'
Stacktrace:
Error: EPERM: operation not permitted, open 'C:\Users\noo\AppData\Local\Temp\tutanota\HOxRpF7Wor9FNvnmzpT7qw\download\Emran Aloul.pdf'
```
```

Client: win32
Type: PREMIUM
Tutanota version: 3.104.5
Timestamp (UTC): Fri, 02 Dec 2022 14:30:53 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.104.5 Chrome/102.0.5005.167 Electron/19.1.5 Safari/537.36
Error
Error message: EPERM: operation not permitted, open 'C:\Users\user\AppData\Local\Temp\tutanota\WBPSqyrxJoUWG_MOa1iX5Q\download\【最新版_久保編集】★fin_資料3_諸外国指標・政策概要比較一覧(1117時点） - コピー.xlsx'
Stacktrace:
Error: EPERM: operation not permitted, open 'C:\Users\user\AppData\Local\Temp\tutanota\WBPSqyrxJoUWG_MOa1iX5Q\download\【最新版_久保編集】★fin_資料3_諸外国指標・政策概要比較一覧(1117時点） - コピー.xlsx'

```

> Attachments will not open after multiple tries and refresh.

> I receive a message "an error has occurred" every time I open my Tutanota account.

> Every time I log on it says "error". I am also unable to download attachments. 

> For the last week or so I have been unable to open attachments from known sources that previously were opening without a problem. When I try to download, they do not appear in my download file. The error code says they can't be accessed because they're already open in another file or something similar. Help, I need these files!

### Observation:
* Looking at all the file names, there doesn't seem to be a pattern like spaces or other special characters that cause this. It's also not constrained to one file type.
* the fact that some users report an error after each app start is odd; is there another file like a log that we're accessing on startup that may have the same problem? -> this may be happening during tmp cleanup

### Further Info:
One user got back to us, they're experiencing this since about ~26th of december. They're receiving this message when using the "open" option on attachments:
> "There was an error opening this document. This file is already open or in use by another application."

### Test Notes
see reproduction in comment. try it on win, linux, mac. If #2113 happens, that's not a dev-bug

### PR DESCRIPTION
**Pull request by ganthern**
on windows, we need to call close() to release the file handle and be able to open the joined file with other apps (or re-download the file)

fix #4946

### CODE REVIEW

File: src/desktop/net/DesktopDownloadManager.ts [hunk 1]
```diff
@@ -266,10 +266,7 @@ export class DesktopDownloadManager {
 				readStream.pipe(outStream, { end: false })
 			})
 		}
-		// Wait for the write stream to finish
-		await new Promise((resolve) => {
-			outStream.end(resolve)
-		})
+		await closeFileStream(outStream)
```
Comment (charlag) [inline src/desktop/net/DesktopDownloadManager.ts:269]: death to node streams

**Review by charlag — APPROVED** [review]
