### PR TITLE
Fixes External Calendars synchronization

### LINKED ISSUE #8446: External calendar is added multiple times
**Describe the bug**
When I add a new external calendar subscription I might click on subscribe multiple times as the UI does not update after the first click.

**To Reproduce**
1. Add Calendar / from URL
2. Paste ics link
3. Click on subscribe
4. Click on subscribe
5. Click on subscribe
6. The subscription will be added multiple times

**Expected behavior**
The UI needs to change after I click on subscribe for the first time. The calendar should only get created once.

### LINKED ISSUE #8447: External calendar might get synchronized multiple times in parallel
**Describe the bug**
If I try to synchronize an external calendar multiple times an actual sync is triggered multiple times in parallel. This leads to errors (e.g. BadRequest) due to race conditions.

**To Reproduce**
1. Add an external calendar
2. Click on sync
3. Click on sync
4. Click on sync

**Expected behavior**
Only one sync should be run at a time and while it is running it should not be possible to schedule another sync.

### PR DESCRIPTION
**Pull request by murilopereirame**
Adds a flag when subscribing to external calendars that locks the interface and prevents users from subscribing to the same calendar multiple times.

It also adds a queue to calendar sync and synchronizes it, preventing the same calendar from being synced in parallel.

Fixes #8446
Fixes #8447

### CODE REVIEW

File: src/calendar-app/calendar/view/CalendarView.ts [hunk 1]
```diff
@@ -757,13 +762,15 @@ export class CalendarView extends BaseTopLevelView implements TopLevelView<Calen
...
 				await Dialog.message("invalidICal_error", e.message)
+				this.viewModel.isProcessingExternalCalendar = false
 				return
 			}
 
 			const calendarGroup = await calendarModel.createCalendar(getExternalCalendarName(iCalStr), properties.color, [], properties.sourceUrl)
 			const calendarGroupRoot = await locator.entityClient.load(CalendarGroupRootTypeRef, calendarGroup._id)
 			deviceConfig.updateLastSync(calendarGroup._id)
 			await handleCalendarImport(calendarGroupRoot, events, CalendarType.URL)
+			this.viewModel.isProcessingExternalCalendar = false
```
Comment (andrehgdias) [inline src/calendar-app/calendar/view/CalendarView.ts:773]: Can we fire this as a callback after dialog.close()?

File: src/calendar-app/calendar/view/CalendarViewModel.ts [hunk 2]
```diff
@@ -113,6 +113,7 @@ export class CalendarViewModel implements EventDragHandlerCallbacks {
 	private _isNewPaidPlan: boolean = false
 	private localCalendars: Map<Id, CalendarInfo> = new Map<Id, CalendarInfo>()
 	private _calendarColors: GroupColors = new Map()
+	isProcessingExternalCalendar: boolean = false
```
Comment (andrehgdias) [inline src/calendar-app/calendar/view/CalendarViewModel.ts:116]: Maybe this flag could be renamed to something that indicates it's the creation of a external calendar

Comment (andrehgdias) [reply src/calendar-app/calendar/view/CalendarViewModel.ts:116]: Also, can we use it to disable the button on the ui?

File: src/calendar-app/calendar/view/CalendarView.ts (hunk 1 above)
Comment (murilopereirame) [reply src/calendar-app/calendar/view/CalendarView.ts]: Unfortunately, no. This is already the okAction of the Dialog

File: src/calendar-app/calendar/view/CalendarViewModel.ts (hunk 2 above)
Comment (murilopereirame) [reply src/calendar-app/calendar/view/CalendarViewModel.ts]: > Maybe this flag could be renamed to something that indicates it's the creation of a external calendar

Renamed!



> Also, can we use it to disable the button on the ui?

No :(

**Review by andrehgdias — APPROVED** [review]
