### PR TITLE
Fixes app crashes during alarm scheduling

### LINKED ISSUE #8728: iOS App crashes after granting Notifications permission
When the user is asked for granting notifications permissions and grants it, the app crashes with the following stacktrace:

```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Incident Identifier: B356ACBF-F880-4EDB-ABD5-C147C048D2C0
CrashReporter Key:   c865ace46a921c7bb1ded81f1908f1f963c55524
Hardware Model:      iPhone13,1
Process:             Tuta Calendar [989]
Path:                /private/var/containers/Bundle/Application/65BAFF11-C779-411E-B538-C46090AF81BA/Tuta Calendar.app/Tuta Calendar
Identifier:          de.tutao.calendar
Version:             271.250227.0 (271.250227.0)
AppStoreTools:       16C7009
AppVariant:          1:iPhone13,1:18
Code Type:           ARM-64 (Native)
Role:                Foreground
Parent Process:      launchd [1]
Coalition:           de.tutao.calendar [1086]

Date/Time:           2025-03-12 22:26:17.4673 +0100
Launch Time:         2025-03-12 22:25:34.4085 +0100
OS Version:          iPhone OS 18.3.2 (22D82)
Release Type:        User
Baseband Version:    5.20.03
Report Version:      104

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x0000000103602a20
Termination Reason: SIGNAL 5 Trace/BPT trap: 5
Terminating Process: exc handler [989]

Triggered by Thread:  1

Thread 0 name:   Dispatch queue: com.apple.main-thread
Thread 0:
0   libsystem_kernel.dylib               0x1e0f04788 mach_msg2_trap + 8
1   libsystem_kernel.dylib               0x1e0f07e98 mach_msg2_internal + 80
2   libsystem_kernel.dylib               0x1e0f07db0 mach_msg_overwrite + 424
3   libsystem_kernel.dylib               0x1e0f07bfc mach_msg + 24
4   CoreFoundation                       0x18f81f804 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                       0x18f81eeb0 __CFRunLoopRun + 1212
6   CoreFoundation                       0x18f871284 CFRunLoopRunSpecific + 588
7   GraphicsServices                     0x1dcae14c0 GSEventRunModal + 164
8   UIKitCore                            0x1923ba674 -[UIApplication _run] + 816
9   UIKitCore                            0x191fe0e88 UIApplicationMain + 340
10  Tuta Calendar                        0x1024ea47c 0x1024e4000 + 25724
11  dyld                                 0x1b5acdde8 start + 2724

Thread 1 Crashed:
0   TutanotaSharedFramework              0x103602a20 0x103554000 + 715296
1   libswiftCore.dylib                   0x18de9c13c LazyFilterSequence.Iterator.next() + 412
2   libswiftCore.dylib                   0x18df2128c LazyMapSequence.Iterator.next() + 448
3   libswiftCore.dylib                   0x18de9c13c LazyFilterSequence.Iterator.next() + 412
4   libswiftCore.dylib                   0x18ddb2434 Array.append<A>(contentsOf:) + 1556
5   libswiftCore.dylib                   0x18df5fc88 static RangeReplaceableCollection.+= infix<A>(_:_:) + 220
6   TutanotaSharedFramework              0x103600038 0x103554000 + 704568
7   TutanotaSharedFramework              0x103601fa4 0x103554000 + 712612
8   TutanotaSharedFramework              0x1035fc068 0x103554000 + 688232
9   TutanotaSharedFramework              0x1035fb930 0x103554000 + 686384
10  Tuta Calendar                        0x10250adb8 0x1024e4000 + 159160
11  TutanotaSharedFramework              0x10364a7b5 0x103554000 + 1009589
12  TutanotaSharedFramework              0x10362c795 0x103554000 + 886677
13  Tuta Calendar                        0x1025169fd 0x1024e4000 + 207357
14  Tuta Calendar                        0x102514e75 0x1024e4000 + 200309
15  Tuta Calendar                        0x1024eb4d9 0x1024e4000 + 29913
16  Tuta Calendar                        0x10251d18d 0x1024e4000 + 233869
17  Tuta Calendar                        0x1024ee291 0x1024e4000 + 41617
18  libswift_Concurrency.dylib           0x19b103e39 completeTaskWithClosure(swift::AsyncContext*, swift::SwiftError*) + 1

Thread 2:
0   libsystem_pthread.dylib              0x21a53e46c start_wqthread + 0

Thread 3 name:  com.apple.uikit.eventfetch-thread
Thread 3:
0   libsystem_kernel.dylib               0x1e0f04788 mach_msg2_trap + 8
1   libsystem_kernel.dylib               0x1e0f07e98 mach_msg2_internal + 80
2   libsystem_kernel.dylib               0x1e0f07db0 mach_msg_overwrite + 424
3   libsystem_kernel.dylib               0x1e0f07bfc mach_msg + 24
4   CoreFoundation                       0x18f81f804 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                       0x18f81eeb0 __CFRunLoopRun + 1212
6   CoreFoundation                       0x18f871284 CFRunLoopRunSpecific + 588
7   Foundation                           0x18e3d70e8 -[NSRunLoop(NSRunLoop) runMode:beforeDate:] + 212
8   Foundation                           0x18e533bb0 -[NSRunLoop(NSRunLoop) runUntilDate:] + 64
9   UIKitCore                            0x19244da78 -[UIEventFetcher threadMain] + 420
10  Foundation                           0x18e4c2f30 __NSThread__start__ + 724
11  libsystem_pthread.dylib              0x21a53e7d0 _pthread_start + 136
12  libsystem_pthread.dylib              0x21a53e480 thread_start + 8

Thread 4 name:  JavaScriptCore libpas scavenger
Thread 4:
0   libsystem_kernel.dylib               0x1e0f0a090 __psynch_cvwait + 8
1   libsystem_pthread.dylib              0x21a540f98 _pthread_cond_wait + 1204
2   JavaScriptCore                       0x1a6524620 scavenger_thread_main + 1328
3   libsystem_pthread.dylib              0x21a53e7d0 _pthread_start + 136
4   libsystem_pthread.dylib              0x21a53e480 thread_start + 8

Thread 5 name:  caulk::deferred_logger
Thread 5:
0   libsystem_kernel.dylib               0x1e0f04704 semaphore_wait_trap + 8
1   caulk                                0x21d5ab680 caulk::semaphore::timed_wait(double) + 220
2   caulk                                0x21d5ab4a4 caulk::concurrent::details::worker_thread::run() + 36
3   caulk                                0x21d5bf188 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
4   libsystem_pthread.dylib              0x21a53e7d0 _pthread_start + 136
5   libsystem_pthread.dylib              0x21a53e480 thread_start + 8

Thread 6 name:  caulk.messenger.shared:high
Thread 6:
0   libsystem_kernel.dylib               0x1e0f04704 semaphore_wait_trap + 8
1   caulk                                0x21d5ab680 caulk::semaphore::timed_wait(double) + 220
2   caulk                                0x21d5ab4a4 caulk::concurrent::details::worker_thread::run() + 36
3   caulk                                0x21d5bf188 void* caulk::thread_proxy<std::__1::tuple<caulk::thread::attributes, void (caulk::concurrent::details::worker_thread::*)(), std::__1::tuple<caulk::concurrent::details::worker_thread*>>>(void*) + 96
4   libsystem_pthread.dylib              0x21a53e7d0 _pthread_start + 136
5   libsystem_pthread.dylib              0x21a53e480 thread_start + 8

Thread 7:
0   libsystem_pthread.dylib              0x21a53e46c start_wqthread + 0

Thread 8:
0   libsystem_pthread.dylib              0x21a53e46c start_wqthread + 0

Thread 9 name:  com.apple.NSURLConnectionLoader
Thread 9:
0   libsystem_kernel.dylib               0x1e0f04788 mach_msg2_trap + 8
1   libsystem_kernel.dylib               0x1e0f07e98 mach_msg2_internal + 80
2   libsystem_kernel.dylib               0x1e0f07db0 mach_msg_overwrite + 424
3   libsystem_kernel.dylib               0x1e0f07bfc mach_msg + 24
4   CoreFoundation                       0x18f81f804 __CFRunLoopServiceMachPort + 160
5   CoreFoundation                       0x18f81eeb0 __CFRunLoopRun + 1212
6   CoreFoundation                       0x18f871284 CFRunLoopRunSpecific + 588
7   CFNetwork                            0x190d8fc4c +[__CFN_CoreSchedulingSetRunnable _run:] + 416
8   Foundation                           0x18e4c2f30 __NSThread__start__ + 724
9   libsystem_pthread.dylib              0x21a53e7d0 _pthread_start + 136
10  libsystem_pthread.dylib              0x21a53e480 thread_start + 8

Thread 10:
0   libsystem_pthread.dylib              0x21a53e46c start_wqthread + 0

Thread 11:
0   libsystem_kernel.dylib               0x1e0f04704 semaphore_wait_trap + 8
1   libdispatch.dylib                    0x19756b544 _dispatch_sema4_wait + 28
2   libdispatch.dylib                    0x19756bbf8 _dispatch_semaphore_wait_slow + 132
3   UIKitCore                            0x1924d5964 0x191fcc000 + 5282148
4   UIKitCore                            0x1922c559c 0x191fcc000 + 3118492
5   Foundation                           0x18e4c2f30 __NSThread__start__ + 724
6   libsystem_pthread.dylib              0x21a53e7d0 _pthread_start + 136
7   libsystem_pthread.dylib              0x21a53e480 thread_start + 8

Thread 12:
0   libsystem_pthread.dylib              0x21a53e46c start_wqthread + 0

Thread 13:
0   libsystem_pthread.dylib              0x21a53e46c start_wqthread + 0

Thread 14:
0   libsystem_pthread.dylib              0x21a53e46c start_wqthread + 0

Thread 15 name:  JSC Heap Collector Thread
Thread 15:
0   libsystem_kernel.dylib               0x1e0f0a090 __psynch_cvwait + 8
1   libsystem_pthread.dylib              0x21a540f98 _pthread_cond_wait + 1204
2   JavaScriptCore                       0x1a654a4e8 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2180
3   JavaScriptCore                       0x1a654865c WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 460
4   JavaScriptCore                       0x1a6704b48 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352
5   JavaScriptCore                       0x1a67049dc WTF::wtfThreadEntryPoint(void*) + 16
6   libsystem_pthread.dylib              0x21a53e7d0 _pthread_start + 136
7   libsystem_pthread.dylib              0x21a53e480 thread_start + 8

Thread 16 name:  Heap Helper Thread
Thread 16:
0   libsystem_kernel.dylib               0x1e0f0a090 __psynch_cvwait + 8
1   libsystem_pthread.dylib              0x21a540f98 _pthread_cond_wait + 1204
2   JavaScriptCore                       0x1a654a4e8 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2180
3   JavaScriptCore                       0x1a654865c WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 460
4   JavaScriptCore                       0x1a6704b48 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352
5   JavaScriptCore                       0x1a67049dc WTF::wtfThreadEntryPoint(void*) + 16
6   libsystem_pthread.dylib              0x21a53e7d0 _pthread_start + 136
7   libsystem_pthread.dylib              0x21a53e480 thread_start + 8

Thread 17 name:  Heap Helper Thread
Thread 17:
0   libsystem_kernel.dylib               0x1e0f0a090 __psynch_cvwait + 8
1   libsystem_pthread.dylib              0x21a540f98 _pthread_cond_wait + 1204
2   JavaScriptCore                       0x1a654a4e8 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2180
3   JavaScriptCore                       0x1a654865c WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 460
4   JavaScriptCore                       0x1a6704b48 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352
5   JavaScriptCore                       0x1a67049dc WTF::wtfThreadEntryPoint(void*) + 16
6   libsystem_pthread.dylib              0x21a53e7d0 _pthread_start + 136
7   libsystem_pthread.dylib              0x21a53e480 thread_start + 8

Thread 18 name:  Heap Helper Thread
Thread 18:
0   libsystem_kernel.dylib               0x1e0f0a090 __psynch_cvwait + 8
1   libsystem_pthread.dylib              0x21a540f98 _pthread_cond_wait + 1204
2   JavaScriptCore                       0x1a654a4e8 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2180
3   JavaScriptCore                       0x1a654865c WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 460
4   JavaScriptCore                       0x1a6704b48 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352
5   JavaScriptCore                       0x1a67049dc WTF::wtfThreadEntryPoint(void*) + 16
6   libsystem_pthread.dylib              0x21a53e7d0 _pthread_start + 136
7   libsystem_pthread.dylib              0x21a53e480 thread_start + 8

Thread 19 name:  Heap Helper Thread
Thread 19:
0   libsystem_kernel.dylib               0x1e0f0a090 __psynch_cvwait + 8
1   libsystem_pthread.dylib              0x21a540f98 _pthread_cond_wait + 1204
2   JavaScriptCore                       0x1a654a4e8 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2180
3   JavaScriptCore                       0x1a654865c WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 460
4   JavaScriptCore                       0x1a6704b48 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352
5   JavaScriptCore                       0x1a67049dc WTF::wtfThreadEntryPoint(void*) + 16
6   libsystem_pthread.dylib              0x21a53e7d0 _pthread_start + 136
7   libsystem_pthread.dylib              0x21a53e480 thread_start + 8

Thread 20 name:  Heap Helper Thread
Thread 20:
0   libsystem_kernel.dylib               0x1e0f0a090 __psynch_cvwait + 8
1   libsystem_pthread.dylib              0x21a540f98 _pthread_cond_wait + 1204
2   JavaScriptCore                       0x1a654a4e8 WTF::ParkingLot::parkConditionallyImpl(void const*, WTF::ScopedLambda<bool ()> const&, WTF::ScopedLambda<void ()> const&, WTF::TimeWithDynamicClockType const&) + 2180
3   JavaScriptCore                       0x1a654865c WTF::Detail::CallableWrapper<WTF::AutomaticThread::start(WTF::AbstractLocker const&)::$_0, void>::call() + 460
4   JavaScriptCore                       0x1a6704b48 WTF::Thread::entryPoint(WTF::Thread::NewThreadContext*) + 352
5   JavaScriptCore                       0x1a67049dc WTF::wtfThreadEntryPoint(void*) + 16
6   libsystem_pthread.dylib              0x21a53e7d0 _pthread_start + 136
7   libsystem_pthread.dylib              0x21a53e480 thread_start + 8


Thread 1 crashed with ARM Thread State (64-bit):
    x0: 0x000000016da2d4e0   x1: 0x000000016da2d510   x2: 0x00000001f96c1238   x3: 0x0000000000000000
    x4: 0x0000000000000000   x5: 0x0000000131604c01   x6: 0x0000000000000000   x7: 0x0000000000000000
    x8: 0xc1c5b4e988000000   x9: 0x7ff0000000000000  x10: 0x0000000a00000003  x11: 0x0000000c00000003
   x12: 0x0000000000000010  x13: 0x0000000000000051  x14: 0x0000000027d4eb2d  x15: 0x0000000000000001
   x16: 0x000000018e3c58f8  x17: 0x00000001f7e64c70  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016da2d4e0  x21: 0x000000016da2daa8  x22: 0x000000016da2da10  x23: 0x00000001f96c1238
   x24: 0x00000001f967c6c8  x25: 0x0000000103621348  x26: 0x0000000103ec0098  x27: 0x000000016da2d510
   x28: 0x000000016da2d660   fp: 0x000000016da2d640   lr: 0x000000010360224c
    sp: 0x000000016da2d4d0   pc: 0x0000000103602a20 cpsr: 0x80001000
   far: 0x0000000000000000  esr: 0xf2000001 (Breakpoint) brk 1

Binary Images:
       0x1024e4000 -        0x102567fff Tuta Calendar arm64  <67265a7ec3563e7c881df3f65decba10> /private/var/containers/Bundle/Application/65BAFF11-C779-411E-B538-C46090AF81BA/Tuta Calendar.app/Tuta Calendar
       0x103554000 -        0x103e3ffff TutanotaSharedFramework arm64  <68b8b508c85c3d8fb33f16cc3214a71d> /private/var/containers/Bundle/Application/65BAFF11-C779-411E-B538-C46090AF81BA/Tuta Calendar.app/Frameworks/TutanotaSharedFramework.framework/TutanotaSharedFramework
       0x1027ac000 -        0x1027b7fff libobjc-trampolines.dylib arm64e  <4aba9420e4d03c989d62c653b259eab4> /private/preboot/Cryptexes/OS/usr/lib/libobjc-trampolines.dylib
       0x1e0f03000 -        0x1e0f3cfe3 libsystem_kernel.dylib arm64e  <881fe934759c3089b98660344cb843e3> /usr/lib/system/libsystem_kernel.dylib
       0x18f7a9000 -        0x18fcecfff CoreFoundation arm64e  <0013a8b125243534b5ba681aaf18c798> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
       0x1dcae0000 -        0x1dcae8fff GraphicsServices arm64e  <3eca7962867b3029adc8bbe100f85ba5> /System/Library/PrivateFrameworks/GraphicsServices.framework/GraphicsServices
       0x191fcc000 -        0x193ee4fff UIKitCore arm64e  <8cc54497f7ec3903ae5aa274047c0cf1> /System/Library/PrivateFrameworks/UIKitCore.framework/UIKitCore
       0x1b5a9e000 -        0x1b5b21137 dyld arm64e  <a770ff8c8fb93e0385fe7f26db36812b> /usr/lib/dyld
               0x0 - 0xffffffffffffffff ??? unknown-arch  <00000000000000000000000000000000> ???
       0x1975ad000 -        0x19762cffb libsystem_c.dylib arm64e  <400d888f854833fc802ff29678681197> /usr/lib/system/libsystem_c.dylib
       0x18dd95000 -        0x18e336fff libswiftCore.dylib arm64e  <6c67e84efe3536858bc3232d31044d06> /usr/lib/swift/libswiftCore.dylib
       0x19b09a000 -        0x19b11cfff libswift_Concurrency.dylib arm64e  <b4ca132580cd3d06937c00c53ad9f2aa> /usr/lib/swift/libswift_Concurrency.dylib
       0x18e3ad000 -        0x18f0ddfff Foundation arm64e  <e2f95328659e3c0197f752b5b3bb7aa5> /System/Library/Frameworks/Foundation.framework/Foundation
       0x21a53d000 -        0x21a549ff3 libsystem_pthread.dylib arm64e  <6f6e49251fb43a0b99d26bd8b7b1a148> /usr/lib/system/libsystem_pthread.dylib
       0x1a6428000 -        0x1a7c5ef3f JavaScriptCore arm64e  <2952bfa6959939dbbca250e97ad38818> /System/Library/Frameworks/JavaScriptCore.framework/JavaScriptCore
       0x21d5a6000 -        0x21d5cdfff caulk arm64e  <2d9c1ba230b332c097748cf6ae8db267> /System/Library/PrivateFrameworks/caulk.framework/caulk
       0x190c9e000 -        0x191062fff CFNetwork arm64e  <e610c6a8da363e07910f2d4a62320985> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
       0x197567000 -        0x1975acfff libdispatch.dylib arm64e  <c05e486d81f2367e9ce1e14573c4c268> /usr/lib/system/libdispatch.dylib

EOF
```
It might be related to an invalid Advanced Repeat Rule, more specifically, a invalid SETPOS rule.

### PR DESCRIPTION
**Pull request by murilopereirame**
Imported events might contain invalid SETPOS rules that can crash the app.

fixes #8728

### CODE REVIEW

File: app-android/tutashared/src/main/java/de/tutao/tutashared/alarms/AlarmModel.kt [hunk 1]
```diff
@@ -82,15 +83,22 @@ object AlarmModel {
 
 			// This map + filter prevent an infinity loop trap by removing invalid rules like POS 320 for freq. weekly
 			// and ensures that 0 <= abs(SETPOS) < eventCount
+			var areAllSetPosValid = true
 			val parsedSetPos = setPosRules.map {
-				if (it.interval.toInt() < 0) {
-					expandedEvents.count() - abs(it.interval.toInt())
-				} else {
-					it.interval.toInt() - 1
+				try {
```
Comment (charlag) [inline app-android/tutashared/src/main/java/de/tutao/tutashared/alarms/AlarmModel.kt:88]: similar to the other case and we could do it with nullable again but we could do it even simpler and just put try/catch around the whole `map()` and return, like

```kotlin
val parsedSetPos = try {
  setPosRules.map {
    // ...
  }.filter {
    // ...
  }
} catch (e: NumberFormatException) {
    Log.w()
    break
}

you should also tell what happened in the log message, it's not clear from the context what is failed

File: app-ios/TutanotaSharedFramework/Alarms/RepeatRule.swift [hunk 2]
```diff
@@ -22,6 +22,7 @@ extension RepeatRule {
 			let type = try ByRuleType(value: decryptedType)
 
 			let interval: String = try decrypt(base64: $0.interval, key: sessionKey)
+			if Int(string: interval) == nil { throw TUTErrorFactory.createError("Invalid bySetPos rule with interval \(interval)") }
```
Comment (charlag) [inline app-ios/TutanotaSharedFramework/Alarms/RepeatRule.swift:25]: I thought you would also right away change the type of AdvanceRule interval to by a number, is there are reason not to do it?

https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/

Comment (murilopereirame) [reply app-ios/TutanotaSharedFramework/Alarms/RepeatRule.swift]: Actually, we missed the rule type check (already fixed). 

BySetPos that are not integers are not supported, and we decided not to take a value because it might confuse users if they get an alarm when they shouldn't.
