### PR TITLE
Fix error handler import delay

### LINKED ISSUE #3868: Error handling is broken
https://github.com/tutao/tutanota/blob/62504ff7da159fd48bc9bbb8aef79e17477b0183/src/misc/ErrorHandler.ts#L18

should be `Date.now() - previousTry`.

This made error handler get stuck after the first error so the error notification would never be shown.

## Test notes
 - [ ] Regression testing: paste this in devTools and see that error handling notification is shown:
 ```js
window.dispatchEvent(new ErrorEvent("error", {error: new Error("oops")})); window.dispatchEvent(new ErrorEvent("error", {error: new Error("oops")}));
```

### PR DESCRIPTION
**Pull request by charlag**
fix #3868

### CODE REVIEW

File: src/misc/ErrorHandler.ts [hunk 1]
```diff
@@ -11,11 +11,24 @@ assertMainOrNodeBoot()
...
+		// ms: 10
+		// a: previousTry
+		// b: Date.now()
+		// c: previousTry + ms
+		// If the last call was at 1001 and we are now calling fn again at 1003 then we want to wait until 1011 which would be (a + ms) - b.
+
+		if (previousTry !== 0 &&  sincePreviousTry < ms) {
+			const waitShouldEndAt = previousTry + ms
+			const timeUntilWaitEnd = waitShouldEndAt - Date.now()
+			console.log("delaying error handler import by", timeUntilWaitEnd)
```
Comment (johnbotris) [inline src/misc/ErrorHandler.ts:30]: leftover log stmt

**Review by johnbotris — COMMENTED** [review]
seems good, just gotta remove the log

File: src/misc/ErrorHandler.ts (hunk 1 above)
Comment (charlag) [reply src/misc/ErrorHandler.ts:30]: I actually thought to leave it but I guess it doesn't matter
