### PR TITLE
Fix folder name tooltip on mail viewer header overflowing the screen

### LINKED ISSUE #6162: Email folder name popup does not fit on screen
## Issue
When looking at at email, if you hover over the folder icon by the time it will show the name of the folder that the email is in. If the folder name is long enough, it can overflow and the name can be hidden.

Screenshot from 2023-11-15 11-07-02

The popup should be moved over enough that the full name is visible. I have only seen this in desktop, but mobile apps should be checked too. 

## Notes
I think the issue is similar to the previously fixed file attachment popup issue (#5919), so the solution may be similar.

## Test Notes
- [ ] The far left of the icon tooltip is at the bottom left of the icon if it would overflow and is fully visible
- [ ] The far left of the icon tooltip is at the perfect bottom of the icon if it wouldn't overflow and is fully visible

### PR DESCRIPTION
**Pull request by rezbyte**
Stops tooltips from overflowing if they exceed the bounds of the viewport by shifting them left.

Closes #6162.

### CODE REVIEW

File: src/gui/base/Icon.ts [hunk 1]
```diff
@@ -40,10 +47,30 @@ export class Icon implements Component<IconAttrs> {
...
+							if (this.root && tooltip) this.moveElementIfOffscreen(this.root, tooltip)
+						},
+					},
+					vnode.attrs.hoverText,
+				),
 		) // icon is typed, so we may not embed untrusted data
 	}
 
+	private moveElementIfOffscreen(root: HTMLElement, tooltip: HTMLElement): void {
+		const tooltipRect = tooltip.getBoundingClientRect()
```
Comment (charlag) [inline src/gui/base/Icon.ts:65]: I am a bit concerned about performance. This would be executed every time we put an icon on the screen and `getBoundingClientRect` can cause layout thrashing.
Can we only do it when necessary, like on hover?

Comment (rezbyte) [reply src/gui/base/Icon.ts:68]: Good idea, I've pushed the change now.

File: src/gui/base/Icon.ts [hunk 2]
```diff
@@ -27,6 +28,13 @@ import("./icons/Icons.js").then((IconsModule) => {
 })
 
 export class Icon implements Component<IconAttrs> {
+	private root?: HTMLElement
```
Comment (charlag) [inline src/gui/base/Icon.ts:31]: a nitpick but we rather do `root: HTMLElement | null = null`

**Review by charlag — APPROVED** [review]

File: src/gui/base/Icon.ts (hunk 2 above)
Comment (charlag) [reply src/gui/base/Icon.ts:31]: there are probably valid cases where we want optional fields (like in component attributes) so it's a bit hard
