### PR TITLE
Ask for permission instead of throwing error when importing contacts

### LINKED ISSUE #6797: Importing contacts without permission to access contacts results in error
**To Reproduce**
1. Click "Import" in the onboarding wizard or in Settings > Contacts.
2. Click "Don't allow" when asked for permission (this doesn't happen if permission has already been denied)
3. Error 

**Expected behavior**
Fail gracefully
With notifications, if they are denied there is a popup that says "Grant notification permissions" that takes you directly to the settings page; it should probably do this too (though it should not pop up right after the initial denial, only the next time "Import" is selected). 

**Smartphone (please complete the following information):**
happens on both iOS and android

## Test Notes
test on android and iOS
- [ ] Try to import contacts, deny permission, no error
- [ ] Try to import contacts, give permission, import works
- [ ] Try to import contacts when permission is already given, import works
- [ ] importing works when done from:
   - [ ] the welcome dialog
   - [ ] settings > contacts
   - [ ] contacts > more button by "All contacts" > Import contacts 
- [ ] Clicking "ok" to our dialog brings up the permission in settings
- [ ] Clicking "cancel" to our dialog closes the dialog and does nothing else
- [ ] Regression test the notification privilege in the welcome dialog, that it works as expected

### PR DESCRIPTION
**Pull request by wrdhub**
Ask for permission instead of throwing error when importing contacts

fix #6797

### CODE REVIEW

File: src/contacts/ContactImporter.ts [hunk 1]
```diff
@@ -69,6 +71,16 @@ export class ContactImporter {
 		)
 	}
 
+	// will check for permission and ask for it if it is not granted
+	async importContactsFromDeviceSafely() {
```
Comment (charlag) [inline src/contacts/ContactImporter.ts:75]: we probably don't need to keep `importContactsFromDevice()` public.

Then this function can be named `importContactsFromDevice()` and the other one can be renamed, will make the interface a bit less clunky.

File: src/contacts/ContactImporter.ts [hunk 2]
```diff
@@ -29,6 +29,8 @@ import { ImportNativeContactBooksDialog } from "./view/ImportNativeContactBooksD
 import { StructuredContact } from "../native/common/generatedipc/StructuredContact.js"
 import { isoDateToBirthday } from "../api/common/utils/BirthdayUtils.js"
 import { ContactBook } from "../native/common/generatedipc/ContactBook.js"
+import { requestPermission } from "../gui/dialogs/SetupWizard.js"
```
Comment (charlag) [inline src/contacts/ContactImporter.ts:32]: I am unhappy that `requestPermission()` is grabbing random things from the locator and I wouldn't use it as-is. At least we should move it out of `SetupWizard` and even better would be refactor it into something injectable.
