### PR TITLE
Log errors in calendar facade

### LINKED ISSUE #5111: Errors during calendar event creation have bad error messages
We completely discard the error information: it is neither printed nor included in the error object:

https://github.com/tutao/tutanota/blob/e01157d1d90819a66f9538e57f64029f09b42288/src/api/worker/facades/CalendarFacade.ts#L182

https://github.com/tutao/tutanota/blob/e01157d1d90819a66f9538e57f64029f09b42288/src/api/worker/facades/CalendarFacade.ts#L135

related to https://github.com/tutao/tutanota/issues/4959

## Test notes
It is a bit tricky to trigger setupMultiple error with calendar but with outdated cache many things are possible! One case is when we try to import the events but our UID check uses local state and we might try to create an event with same UID and the server will tell it's not okay.

 * prepare an .ics file, even one event is enough
 * prepare a platform with offline storage (like desktop)
 * import the .ics file into the calendar
 * use devtools to go offline on desktop (this just turns off websocket, all the other requests will still work)
 * import the same .ics file into the calendar
 * you should see that the `PreconditionFailedError` that happened is printed to the console
 * The dialog should show that importing the event failed

### PR DESCRIPTION
**Pull request by wrdhub**
close #5111

### CODE REVIEW

File: src/api/worker/facades/CalendarFacade.ts [hunk 1]
```diff
@@ -179,6 +180,7 @@ export class CalendarFacade {
 				//In this case the user will not be informed about the number of failed events. We considered this is okay because it is not actionable anyways.
 				throw new ConnectionError("Connection lost while saving events")
 			} else {
+				console.log("Could not save events. Number of failed imports: ", failed)
```
Comment (ganthern) [inline src/api/worker/facades/CalendarFacade.ts:183]: I feel we should log a bit more info here, we have a list of all the errors that occurred during `setupMultiple` in the `errors` variable

**Review by charlag — APPROVED** [review]

**Comment by charlag** [comment]
We need few test notes how we can reproduce it?
