### PR TITLE
A way to get the spell check to work

### LINKED ISSUE #10487: [desktop] Spellchecker doesn't work on first launch until spellcheck language is changed
**Steps to reproduce:**
- Make sure the client is closed
- Start the client
- Open the email editor and write some text containing typos
- See that the spellchecker doesn't work
- Change the spellcheck language to a different language
- See that the spellchecker now works

**Expected behaviour:**
The spellchecker should work from the start without having to set the language each initial launch

**Additional informations:**
The spellcheck language is set in `WindowManager#_setSpellcheckLang` and the dictionaries are downloaded on `session-created` here: https://github.com/tutao/tutanota/blob/c28751b8ec6f70df5e45900f0ec86243aaceb886/src/common/desktop/DesktopMain.ts#L447

### PR DESCRIPTION
**Pull request by wrdhub**

### CODE REVIEW

File: src/common/desktop/DesktopMain.ts [hunk 1]
```diff
@@ -260,6 +254,18 @@ async function createComponents(): Promise<Components> {
 	})
 	const webDialogController = new WebDialogController()
 
+	electron.app.on("session-created", async (session) => {
+		const updateUrl = await conf.getConst(BuildConfigKey.updateUrl)
+		// FIXME bring back
```
Comment (hrb-hub) [inline src/common/desktop/DesktopMain.ts]: Forgotten FIXME 😅

**Comment by hrb-hub** [comment]
Great job getting the workaround to work! We should probably add comments explaining why we do it though, maybe even link to the electron issue‥?

File: src/common/desktop/DesktopMain.ts [hunk 2]
```diff
@@ -460,12 +466,21 @@ async function main(components: Components) {
...
+function manageDownloadsForSession(session: Session, dictUrl: string, conf: DesktopConfig) {
 	log.debug(TAG, "getting dictionaries from:", dictUrl)
 	session.setSpellCheckerDictionaryDownloadURL(dictUrl)
 	session
 		.removeAllListeners("spellcheck-dictionary-download-failure")
-		.on("spellcheck-dictionary-initialized", (_ev, lcode) => log.debug(TAG, "spellcheck-dictionary-initialized", lcode))
+		.on("spellcheck-dictionary-initialized", (_ev, lcode) => {
+			// This is part of a workaround due to an electron issue with spellcheck
+			// The spellcheck language is set to a different language at startup, and then here it is switched to the correct language
+			conf.getVar(DesktopConfigKey.spellcheck).then((l) => {
```
Comment (hrb-hub) [inline src/common/desktop/DesktopMain.ts:477]: I just realized we might missing the `process.platform !== "darwin"` check here, or is it not needed here?

We should also probably remember to test this on Mac and Windows when the time  comes 😬

Comment (hrb-hub) [reply src/common/desktop/DesktopMain.ts:477]: The comments look good though, thank you

Comment (wrdhub) [reply src/common/desktop/DesktopMain.ts:477]: It's not needed there because we only initialize if the spell check language was set, which only happens if the previous platform check confirms it isn't darwin.
