### PR TITLE
fixes multiple files in calendar event

### LINKED ISSUE #3383: Multiple events in calendar invite
**Bug in calendar**

When creating and event and adding invalid (eg mistyped) guests with Tutanota addresses, trying to send the invite, removing the invalid addresses and successfully sending afterwards, the event invitation has multiple `.ics` files as attachments, one for each sending attempt.

**To Reproduce**
1. Create new event in calendar
2. Add a guest with an invalid internal address, eg `d08b7489b47f40afae5aff99@tutanota.com`
3. Add another guest with a _valid_ internal address
4. Hit "Send"
5. See error about the invalid address and dismiss this error
6. Remove invalid address from step 2
7. Hit "Send" again
8. See invite mail in "Sent" folder or recipients inbox
9. Invite mail contains *two* `.ics` files, one from the first attempt and one from the second one

**Expected behavior**
There should only be a single attached `.ics` file that contains only the valid recipients as it was displayed when hitting send the last time.

**Screenshots**
Screenshot from 2021-08-13 15-11-56

**Context**
We probably create the attachment file before sending the invite and never remove it from the mail draft when fails sending. Thus we add the file again on the next attempt to send.

### PR DESCRIPTION
**Pull request by vaf-hub**
fixes #3383

### CODE REVIEW

File: src/calendar/date/CalendarUpdateDistributor.js [hunk 1]
```diff
@@ -145,7 +145,17 @@ export class CalendarMailDistributor implements CalendarUpdateDistributor {
 		sendMailModel.setBody(body)
 		this._sendStart()
 		await sendMailModel.send(method)
-		                    .finally(() => this._sendEnd())
+		                   .catch((e) => {
+			                   // we remove the attachment from the model to prevent adding more than one calendar file
+			                   // in case the user changes the event and tries to send again a new attachment is created
+			                   sendMailModel.getAttachments().find(file => {
+			                   	if (file && file.name === inviteFile.name){
+			                   		sendMailModel.removeAttachment(file)
```
Comment (johnbotris) [inline src/calendar/date/CalendarUpdateDistributor.js:153]: This shouldn't happen inside the call to `find`, move it outside

**Review by johnbotris — CHANGES_REQUESTED** [review]

File: src/calendar/date/CalendarUpdateDistributor.js (hunk 1 above)
Comment (vaf-hub) [reply src/calendar/date/CalendarUpdateDistributor.js]: Yes that's true. I changed it.

**Review by johnbotris — APPROVED** [review]
