### PR TITLE
Fix membership removal errors when logging in

### LINKED ISSUE #9143: 403 NotAuthorizedError when Logging after being removed from a shared mailbox
When logging in after being removed from a shared mailbox, the user sees: 
- a `NotAuthorizedError` on Desktop.
- a `MembershipRemovedError` on Web.

**Steps to reproduce:**
- Using client A, add a user to a shared mailbox.
- Using client B, login and wait for the client to sync.
- Logout from client B.
- Using client A, remove the user from the shared mailbox.
- Using client B, login again and see error.

Perform these steps with client B being Desktop, then Web. See that two different errors are thrown:
_On Desktop:_
```
Feedback v287.250616.0 - NotAuthorizedError - PAID - linux
Client: linux
Type: PAID
Tutanota version: 287.250616.0
Timestamp (UTC): Mon, 16 Jun 2025 16:19:34 GMT
Time zone: Europe/Berlin
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop-test/287.250616.0 Chrome/134.0.6998.205 Electron/35.5.0 Safari/537.36
NotAuthorizedError
Error message: 403: OStXU4A----4 | GET /rest/tutanota/mailfolder/OStG9NH--3-4
Stacktrace:
NotAuthorizedError: 403: OStXU4A----4 | GET /rest/tutanota/mailfolder/OStG9NH--3-4
at La (asset://app/common-min-C4N3d9Tk.js:1:38667)
at suspensionHandler.isSuspended.h.onload (asset://app/mail-worker.js:18:56441)
```

_On Web:_
```
Feedback v287.250616.0 - MembershipRemovedError - PAID - Browser
Client: Browser
Type: PAID
Tutanota version: 287.250616.0
Timestamp (UTC): Mon, 16 Jun 2025 16:08:06 GMT
Time zone: Europe/Berlin
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0
MembershipRemovedError
Error message: user has been removed from contact or mail group
Stacktrace:
MembershipRemovedError. user has been removed from contact or mail group
```

### PR DESCRIPTION
**Pull request by paw-hub**
Closes #9143

### CODE REVIEW

File: src/mail-app/mail/model/MailModel.ts [hunk 1]
```diff
@@ -114,29 +114,49 @@ export class MailModel {
...
+				try {
+					mailSets = await this.loadMailSetsForListId(foldersRef.folders)
+				} catch (e) {
+					if (e instanceof NotAuthorizedError || e instanceof NotFoundError) {
+						console.warn("Got", e.name, "when trying to load a mailbox", detail.mailbox._id, "(cached user likely outdated)")
+					} else {
+						throw e
+					}
+
+					lastCaughtRestError = e
```
Comment (charlag) [inline src/mail-app/mail/model/MailModel.ts]: can we move these two lines into the first branch of the condition? i got mighty confused and was thinking that `lastCaughtRestError` declaration is incorrect. If we have just two branches and nothing after it's easier to follow

**Review by charlag — COMMENTED** [review]
why do we end up loading mail sets for the group that we don't have anymore? If the user is cached then mail sets should also be cached, right? I think your fix is good (and also good job with that little refactoring) but I am not sure I understand how we get there

**Review by wrdhub — APPROVED** [review]

**Comment by paw-hub** [comment]
> why do we end up loading mail sets for the group that we don't have anymore? If the user is cached then mail sets should also be cached, right? I think your fix is good (and also good job with that little refactoring) but I am not sure I understand how we get there

I've just added a comment as to why this happens.

Basically, LoginFacade forces a cache update of the User upon login, and thus the cache for those groups gets wiped before we receive the entity event for that user, thus MailboxModel's list of mailbox details is temporarily outdated.
