### PR TITLE
Fixes whitelabel themes being merged with default ones

### LINKED ISSUE #7090: Whitelabel colors are not available on native clients
When I log in to an account which has a whitelabeled domain on either desktop or mobile I should be able to choose my custom colors under Settings > Appearance. 

## Test Notes
- [ ] Whitelabel still working on web
- [ ] Whitelabel works on mobile
- [ ] Whitelabel works on desktop
- [ ] The custom theme is displayed during onboarding
- [ ] The custom theme is displayed inside settings

### PR DESCRIPTION
**Pull request by murilopereirame**
This commit adds the whitelabel domain as the themeId for the whitelabel theme in case it doesn't have an Id.

Co-authored-by: and <and@tutao.de>

Fixes #7090

### CODE REVIEW

File: src/login/PostLoginActions.ts [hunk 1]
```diff
@@ -209,6 +210,11 @@ export class PostLoginActions implements PostLoginAction {
 			// jsonTheme is stored on WhitelabelConfig as an empty json string ("{}", or whatever JSON.stringify({}) gives you)
 			// so we can't just check `!whitelabelConfig.jsonTheme`
 			if (Object.keys(customizations).length > 0) {
+				// Custom theme is missing themeId, so we update it with the whitelabel domain
+				if (!customizations.themeId) {
```
Comment (charlag) [inline src/login/PostLoginActions.ts:214]: I think we can safely override it

**Review by charlag — APPROVED** [review]

**Review by wrdhub — APPROVED** [review]
