### PR TITLE
SystemModel v134 Fix PayPal redirect for calendar app

### LINKED ISSUE #8611: Redirected to Mail app after changing payment info on calendar app
**Bug in mobile app**
I get redirected to the Mail app after I update paypal payment info on calendar app.

**To Reproduce**
1. Open calendar app
2. Change Paypal payment details and confirm
3. Mail app is opened

**Expected behavior**
The calendar should come to foreground after updating the payment information.

### PR DESCRIPTION
**Pull request by wrdhub**
Fix #8611

### CODE REVIEW

File: src/common/subscription/SubscriptionUtils.ts [hunk 1]
```diff
@@ -144,13 +145,23 @@ export function getPreconditionFailedPaymentMsg(data: string | null): Translatio
 	}
 }
 
+/*
+ * Identifies from which app the user subscribed from
+ */
+export enum SubscriptionApp {
```
Comment (charlag) [inline src/common/subscription/SubscriptionUtils.ts:159]: should probably move it to `TutanotaConstants`
