### PR TITLE
keyboard shortcuts overlapping with other language keyboards 

### LINKED ISSUE #5179: Unexpected closing when typing Cmd + A (anywhere)
I noticed that Tutanota desktop Mac app closes itself when I type Cmd + A. I noticed this a few days ago while trying to select text while creating a folder. I procrastinated reporting the issue, but tonight I had the same problem just typing the command in the application to select all emails. So, I do report the issue now.

**How to reproduce it?:** Just open the desktop application, type "cmd" + "A". The application closes itself or crashes. 

**What is supposed to be done:** Select all messages in a mail pane or select all text.

**Potential cause:** An incorrect mapping of keyboard shortcuts that links "Cmd + A" to what "Cmd + Q" is supposed to do.

**Solution:** Check the keyboard shortcuts, if it's not that, then it's an insidious bug somewhere else.

### PR DESCRIPTION
**Pull request by BijinDev**
Close #5179

### CODE REVIEW

File: packages/tutanota-utils/lib/Utils.ts [hunk 1]
```diff
@@ -692,3 +693,7 @@ export function isSessionStorageAvailable(): boolean {
 		return false
 	}
 }
+
+export function isLatinChar(char: string): boolean {
```
Comment (charlag) [inline packages/tutanota-utils/lib/Utils.ts]: 0x7f is the top of the ASCII table so I guess the name should be `isAsciiChar`

File: src/common/desktop/electron-localshortcut/KeyboardEventsAreEqual.ts [hunk 2]
```diff
@@ -23,9 +27,11 @@ export default function areEqual(ev1: any, ev2: any): boolean {
 		}
 	}
 
-	if ((_lower(ev1.key) === _lower(ev2.key) && ev1.key !== undefined) || (ev1.code === ev2.code && ev1.code !== undefined)) {
+	if (keyIsLatin && _lower(ev1.key) === _lower(ev2.key) && ev1.key !== undefined) {
 		// Events are equals
 		return true
+	} else if (!keyIsLatin && _lower(ev1.code) === _lower(ev2.code) && ev1.code !== undefined) {
```
Comment (charlag) [inline src/common/desktop/electron-localshortcut/KeyboardEventsAreEqual.ts]: I'm not sure why we need `_lower` on the code

Comment (BijinDev) [reply src/common/desktop/electron-localshortcut/KeyboardEventsAreEqual.ts]: Yes, we don't need to lower the code
