### PR TITLE
fix repeat rule being editable in situations where it should not

### LINKED ISSUE #5728: Allowed to change repeat rule for a shared event with a guest
1. User A shares calendar (as R/W or as sharing) with user B
2. User A creates a repeating event and adds a guest to it
3. User B opens the event and tries to edit it. The repeat rule editing is enabled while it shouldn't be

## Test Notes 
* [ ] test the bug above
* [ ] otherwise, user B can not edit anything about the event but the alarms.

### PR DESCRIPTION
**Pull request by ganthern**
fix #5728

### CODE REVIEW

File: src/calendar/date/eventeditor/CalendarEventModel.ts [hunk 1]
```diff
@@ -366,7 +366,7 @@ export class CalendarEventModel {
 	 * returns true if such operations can be attempted.
 	 * */
 	canEditSeries(): boolean {
-		return this.operation !== CalendarOperation.EditThis
+		return this.operation !== CalendarOperation.EditThis && (this.eventType === EventType.OWN || this.eventType === EventType.SHARED_RW)
```
Comment (charlag) [inline src/calendar/date/eventeditor/CalendarEventModel.ts:369]: it would be locked if it's not ours right?

**Review by charlag — APPROVED** [review]
