### PR TITLE
fix changing payment method with no existing postings

### LINKED ISSUE #2895: Cannot change payment method
Customers which have no account posting cannot change the payment methods. We should handle the case when there are no posting, e.g. customers with first year for free promotion.

https://github.com/tutao/tutanota/blob/0243aa882ce0446ad29a346cd86b75dc331045aa/src/subscription/PaymentViewer.js#L99

### PR DESCRIPTION
**Pull request by vaf-hub**
fixes #2895

### CODE REVIEW

File: src/subscription/PaymentViewer.js [hunk 1]
```diff
@@ -96,8 +96,9 @@ export class PaymentViewer implements UpdatableSettingsViewer {
 			label: "paymentMethod_label",
 			click: createNotAvailableForFreeClickHandler(true, () => {
 					if (this._accountingInfo) {
-						let lastPosting = neverNull(this._postings[0])
-						let nextPayment = Number(lastPosting.balance) * -1
+						let nextPayment = this._postings.length
+							? Number(this._postings[0].balance) * -1
```
Comment (charlag) [inline src/subscription/PaymentViewer.js:100]: maybe `filterInt()` instead?

Comment (vaf-hub) [reply src/subscription/PaymentViewer.js:100]: I am not sure why we would need `filterInt()`? I think it is safe to assume that `balance` is a NumberString.

Comment (charlag) [reply src/subscription/PaymentViewer.js:100]: Probably, yeah. Leave it then.

**Review by charlag — APPROVED** [review]
