### PR TITLE
catch all errors during file download, close #2055

### LINKED ISSUE #2055: Unknown error when opening pdf attachment
This was reported by a user today that an unexpected error was shown when opening an pdf attachment in the desktop client. I don't think this happens very often but we should catch the error and show an error dialog that something went wrong. Something like "Failed to open attachment". Best would be to identify why this error occured but i am not sure if it is because of the filename or a decryption problem.

```
Client: win32
Type: PREMIUM
Tutanota version: 3.72.0
Timestamp (UTC): Wed, 13 May 2020 21:11:18 GMT
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.72.0 Chrome/80.0.3987.158 Electron/8.2.0 Safari/537.36
Error
Error message: UNKNOWN: unknown error, open 'C:\Users\<username>\AppData\Local\Temp\tuta\foo bar $605.14.pdf'
Stacktrace:
Error: UNKNOWN: unknown error, open 'C:\Users\<user>\AppData\Local\Temp\tuta\foo bar $605.14.pdf'
```

### PR DESCRIPTION
**Pull request by ganthern**
this will prevent the report dialog from showing up if opening or
downloading an attachment fails and logs the error to the console.

-------------------------
#2055 was an unknown error (which is exactly what the report function is there for), but this I/O can fail for pretty much any reason we can't anticipate. Showing a graceful dialog and asking users to send logs if they get annoyed enough to contact support seems to be an acceptable way of handling this that's somewhere between getting error reports for every OS hiccup and not getting any reports at all.

FileOpenErrors are associated with a pretty specific error message ('cant open on _this device_') which may be misleading in these cases, hence this pr adds a new generic message.
On the other hand, only Android throws FileOpenErrors because it actually doesn't have the capability, the other clients throw them for pretty much any failure.

### CODE REVIEW

File: src/mail/MailEditor.js [hunk 1]
```diff
@@ -713,15 +713,21 @@ export class MailEditor {
 					label: "download_action",
 					type: ButtonType.Secondary,
 					click: () => {
+						let promise = Promise.resolve()
```
Comment (charlag) [inline src/mail/MailEditor.js:716]: don't need to assign here and I wouldn't to catch errors. Flow can prove that we assign it in all branches.

File: src/translations/en.js [hunk 2]
```diff
@@ -1108,6 +1108,7 @@ module.exports = {
 		"yourCalendars_label": "Your calendars",
 		"yourFolders_action": "YOUR FOLDERS",
 		"yourMessage_label": "Your message",
-		"createUserFailed_msg": "Could not create the user. Please contact support."
+		"createUserFailed_msg": "Could not create the user. Please contact support.",
+		"errorDuringFileOpen_msg": "Failed to open Attachment."
```
Comment (charlag) [inline src/translations/en.js:1112]: "Attachment" can be lowercase and we need new key in `TranslationKeyType`
