### PR TITLE
Fix move/undoMove mails in different folders/mailboxes

### LINKED ISSUE #9539: Moving mails that are in different mailboxes using folder dropdown in SearchView throws an error

### LINKED ISSUE #9572: In conversation list mode, undo move/trash moves all moved conversation mails to the current folder
**Steps to reproduce:**
- Set `Settings > Email > Email list grouping` to "Group by conversation".
- Open a conversation that has mails in different folders.
- Trash or move the conversation, then undo the move.
- See that undo action moves conversation mails to the current folder rather than back to their original folders.

## Test notes
- [ ] Set `Settings > Email > Email list grouping` to `Group by conversation`
- [ ] With a folder selected (folder view)
- [x] Move a conversation that has its mails in different folders, see that all the mails except those in _Sent_ folder are moved. Undo the move and see that the mails are back in their original folders
- [x] Trash a conversation that has its mails in different folders, see that all the mails including those in _Sent_ folder are moved. Undo the move and see that the mails are back in their original folders
- [x] Undo still works as expected when conversation list grouping is disabled

### LINKED ISSUE #9589: Error thrown when trying to undo move mails from label view
```
Feedback v304.250901.0 - BadRequestError - PAID - Browser
Client: Browser
Type: PAID
Tutanota version: 304.250901.0
Timestamp (UTC): Fri, 05 Sep 2025 13:25:36 GMT
Time zone: Europe/Berlin
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0
BadRequestError
Error message: 400: OZP2RkO----4 | POST /rest/tutanota/movemailservice
Stacktrace:
BadRequestError. 400: OZP2RkO----4 | POST /rest/tutanota/movemailservice
```

**Steps to reproduce:**
- Switch to label view.
- Move one or multiple mails.
- Undo the move.
- See Error.

### LINKED ISSUE #9685: Bad request error when marking as spam using move to spam toolbar action if mails are in different mailboxes
**Steps to reproduce:**
- Have access to at least one shared mailbox and the personal mailbox, both with mail in it that can turn up in the same search query
- Search for the mails
- Select all mails that were found
- Move selected mails to spam using the toolbar action

Image

- See error

### In Mailview for mails in own personal mailbox
- [x] The move to Spam action works and can be undone using the undo snackbar

- [x] When `Settings > Email > Report spam` is set to `Always ask`
    - [x] Report confirmation dialog is shown after action only when moving from a folder that isn't subfolder of spam.
    - [x] When mails are in a subfolder of spam, mails are moved to spam but not reported (the undo snackbar only mentions move but not report, and there are no requests made to the `reportmailservice`)
    - [x] When `No` is chosen, mails are moved to spam but not reported (the undo snackbar only mentions move but not report, and there are no requests made to the `reportmailservice`)
    - [x] When `Yes` is chosen, mails are moved to spam and reported (the undo snackbar mentions move and report, and there's a request made to the `reportmailservice` after the undo snackbar disappears)
    - [x] Works when a folder is selected but also when a label is selected
    - [x] Works when conversation grouping is enabled
    - [x] Works when conversation grouping is disabled

- [x] When `Settings > Email > Report spam` is set to `Never report`
    - [x] Report confirmation dialog is never shown.
    - [x] Mails are moved to spam but not reported (the undo snackbar only mentions move but not report, and there are no requests made to the `reportmailservice`)
    - [x] Works when a folder is selected but also when a label is selected
    - [x] Works when conversation grouping is enabled
    - [x] Works when conversation grouping is disabled

- [x] When `Settings > Email > Report spam` is set to `Always report`
    - [x] Report confirmation dialog is never shown.
    - [x] When mails are in a subfolder of spam, mails are moved to spam but not reported (the undo snackbar only mentions move but not report, and there are no requests made to the `reportmailservice`)
    - [x] When mails are not in a subfolder of spam, mails are moved to spam and reported (the undo snackbar mentions move and report, and there's a request made to the `reportmailservice` after the undo snackbar disappears)
    - [x] Works when a folder is selected but also when a label is selected
    - [x] Works when conversation grouping is enabled
    - [x] Works when conversation grouping is disabled

### In Mailview for mails in shared mailbox
- [x] The move to Spam action can be undone using the undo snackbar

- [x] When `Settings > Email > Report spam` is set to `Always ask`
    - [x] Report confirmation dialog is shown after action only when moving from a folder that isn't subfolder of spam.
    - [x] When mails are in a subfolder of spam, mails are moved to spam but not reported (the undo snackbar only mentions move but not report, and there are no requests made to the `reportmailservice`)
    - [x] When `No` is chosen, mails are moved to spam but not reported (the undo snackbar only mentions move but not report, and there are no requests made to the `reportmailservice`)
    - [x] When `Yes` is chosen, mails are moved to spam and reported (the undo snackbar mentions move and report, and there's a request made to the `reportmailservice` after the undo snackbar disappears)
    - [x] Works when a folder is selected but also when a label is selected
    - [x] Works when conversation grouping is enabled
    - [x] Works when conversation grouping is disabled

- [x] When `Settings > Email > Report spam` is set to `Never report`
    - [x] Report confirmation dialog is never shown.
    - [x] Mails are moved to spam but not reported (the undo snackbar only mentions move but not report, and there are no requests made to the `reportmailservice`)
    - [x] Works when a folder is selected but also when a label is selected
    - [x] Works when conversation grouping is enabled
    - [x] Works when conversation grouping is disabled

- [x] When `Settings > Email > Report spam` is set to `Always report`
    - [x] Report confirmation dialog is never shown.
    - [x] When mails are in a subfolder of spam, mails are moved to spam but not reported (the undo snackbar only mentions move but not report, and there are no requests made to the `reportmailservice`)
    - [x] When mails are not in a subfolder of spam, mails are moved to spam and reported (the undo snackbar mentions move and report, and there's a request made to the `reportmailservice` after the undo snackbar disappears)
    - [x] Works when a folder is selected but also when a label is selected
    - [x] Works when conversation grouping is enabled
    - [x] Works when conversation grouping is disabled

### In SearchView
- [ ] The move to Spam action works and can be undone using the undo snackbar
  - [x] For mails in own mailbox
  - [x] For mails in shared mailbox
  - [x] For mails where some of are in own personal mailbox and others are in the shared mailbox

- [x] When `Settings > Email > Report spam` is set to `Always ask`
    - [x] Report confirmation dialog is shown after action only when there's at least one mail being moved from a folder that isn't subfolder of spam.
    - [x] When mails are in a subfolder of spam, mails are moved to spam but not reported (the undo snackbar only mentions move but not report, and there are no requests made to the `reportmailservice`)
    - [x] When `No` is chosen, mails are moved to spam but not reported (the undo snackbar only mentions move but not report, and there are no requests made to the `reportmailservice`)
    - [x] When `Yes` is chosen, mails are moved to spam and reported (the undo snackbar mentions move and report, and there's a request made to the `reportmailservice` after the undo snackbar disappears)

- [x] When `Settings > Email > Report spam` is set to `Never report`
    - [x] Report confirmation dialog is never shown.
    - [x] Mails are moved to spam but not reported (the undo snackbar only mentions move but not report, and there are no requests made to the `reportmailservice`)

- [x] When `Settings > Email > Report spam` is set to `Always report`
    - [x] Report confirmation dialog is never shown.
    - [x] When mails are in a subfolder of spam, mails are moved to spam but not reported (the undo snackbar only mentions move but not report, and there are no requests made to the `reportmailservice`)
    - [x] When mails are not in a subfolder of spam, mails are moved to spam and reported (the undo snackbar mentions move and report, and there's a request made to the `reportmailservice` after the undo snackbar disappears)

**Note: When conversation grouping is enabled, move to Spam action only moves the primary email (unlike the regular move to spam), this is an existing bug that will be addressed later. See: #9687**

### PR DESCRIPTION
**Pull request by BijinDev**
Close #9539
Close #9572
Close #9589
Close #9685

**Tutadb: !786**

### CODE REVIEW

File: src/common/api/entities/monitor/TypeModels.js [hunk 1]
```diff
@@ -226,7 +226,7 @@ export const typeModels = {
 				"type": "ELEMENT_ASSOCIATION",
 				"cardinality": "ZeroOrOne",
 				"refTypeId": 31,
-				"dependency": null
+				"dependency": "sys"
```
Comment (charlag) [inline src/common/api/entities/monitor/TypeModels.js:229]: I'm surprised that this changed but maybe it's a side effect of something?

File: src/common/api/worker/facades/lazy/MailFacade.ts [hunk 2]
```diff
@@ -376,27 +377,29 @@ export class MailFacade {
 	/**
 	 * Move mails from {@param targetFolder} except those that are in {@param excludeMailSet}.
 	 */
-	async moveMails(mails: readonly IdTuple[], targetFolder: IdTuple, excludeMailSet: IdTuple | null): Promise<void> {
+	async moveMails(mails: readonly IdTuple[], targetFolder: IdTuple, excludeMailSet: IdTuple | null): Promise<MovedMails[]> {
```
Comment (charlag) [inline src/common/api/worker/facades/lazy/MailFacade.ts:387]: I think we should add a `@return` comment to this function and probably few other ones so it's more clear what it actually returns

File: src/mail-app/mail/view/MailGuiUtils.ts [hunk 3]
```diff
@@ -169,10 +169,9 @@ async function showUndoMoveMailSnackbar(undoModel: UndoModel, onUndoMove: () =>
 export async function moveMails(params: MoveMailsParams): Promise<boolean> {
 	const { mailModel, mailIds, targetFolder, moveMode } = params
 	try {
-		const mails = await mailModel.loadAllMails(mailIds)
-		await mailModel.moveMails(getIds(mails), targetFolder, moveMode)
+		const folderMails = await mailModel.moveMails(mailIds, targetFolder, moveMode)
```
Comment (charlag) [inline src/mail-app/mail/view/MailGuiUtils.ts]: I would also rename `folderMails` into something that's hinting at what it is, like `mailOrigin`

File: src/mail-app/mail/view/MailGuiUtils.ts [hunk 4]
```diff
@@ -241,76 +240,55 @@ async function runPostSimpleMoveActions(
 	}
 }
 
-async function runPostMoveActions({ mailModel, targetFolder, isReportable = true, mailboxModel, moveMode, undoModel }: MoveMailsParams, mails: Mail[]) {
-	const mailsByFolder = mailsAndFolderByFolderId(mails)
+async function runPostMoveActions({ mailModel, targetFolder, mailboxModel, moveMode, undoModel }: MoveMailsParams, mailsByFolder: MovedMails[]) {
```
Comment (charlag) [inline src/mail-app/mail/view/MailGuiUtils.ts]: also would name `mailsByFolder` differently

File: src/mail-app/mail/view/MailGuiUtils.ts [hunk 5]
```diff
@@ -241,76 +240,55 @@ async function runPostSimpleMoveActions(
...
 		? `${lang.getTranslation("undoMoveMail_msg", { "{folder}": getFolderName(targetFolder) }).text} ${lang.getTranslation("undoMailReport_msg").text}`
 		: lang.getTranslation("undoMoveMail_msg", { "{folder}": getFolderName(targetFolder) }).text
 
 	const onUndoMove = async () => {
-		for (const { folder, mails: folderMails } of mailsByFolder.values()) {
-			const areMailsNotMoved = excludedFolder != null && folder.folderType === excludedFolder
-			if (areMailsNotMoved || isSameId(folder._id, targetFolder._id)) {
+		for (const { folderBeforeMove, mailIds } of mailsByFolder) {
+			const mailFolder = await mailModel.getMailSetById(elementIdPart(folderBeforeMove))
+			const areMailsNotMoved = excludedFolder != null && mailFolder?.folderType === excludedFolder
```
Comment (charlag) [inline src/mail-app/mail/view/MailGuiUtils.ts]: would they get returned if the folder was excluded?

File: src/mail-app/mail/view/MailGuiUtils.ts [hunk 6]
```diff
@@ -241,76 +240,55 @@ async function runPostSimpleMoveActions(
...
+				MoveMode.Mails,
+			)
 		}
 	}
 
 	const undoResult = await showUndoMoveMailSnackbar(undoModel, onUndoMove, undoMoveText)
 
 	if (shouldReportMails && undoResult !== MoveMailSnackbarResult.Undo) {
-		await mailModel.reportMails(MailReportType.SPAM, async () => mails)
+		const reportableMails = await mailModel.loadAllMails(reportableMailIds)
```
Comment (charlag) [inline src/mail-app/mail/view/MailGuiUtils.ts]: why do we `await` here directly and not in the last argument to `reportMails()`?

File: src/mail-app/mail/view/MailGuiUtils.ts [hunk 7]
```diff
@@ -549,55 +561,94 @@ export async function showMoveMailsDropdown(
...
-	const folders = await getMoveTargetFolderSystems(mailModel, mails)
+
+	const moveTargets = await getMoveTargetFolderSystems(mailModel, mails)
 	const currentFolders = deduplicate(mails.map((mail) => mailModel.getMailFolderForMail(mail)))
 
-	await showMailFolderDropdown(
-		origin,
-		folders,
-		(f) => {
+	let onFolderClick: (f: FolderInfo | SystemFolderType) => void
```
Comment (charlag) [inline src/mail-app/mail/view/MailGuiUtils.ts]: it is a bit of a lie here because in actuality it is

```ts
let onFolderClick: ((f: FolderInfo) => void) | ((f: SystemFolderType) => void)
```

so it's not a function that supports *both* it's a function that supports one of them. Ideally TypeScript would catch this but variance is kind of broken.

Right now it's not a bug because you check in both places but it's basically unsafe as far as types are concerned.

To avoid committing a type crime you would need to bind `moveTargets` and `onClick` into a single argument, something like:

```ts
moveData: {targets: MoveTargets.SimpleMove, onClick: (folder: SystemFolderType) => unknown} | {targets: MoveTargets.RegularMove, onClick: (folder: FolderInfo) => unknown}
```

**Comment by charlag** [comment]
"Get mailsByFolder from moveMailService" should probably be changed. What are we trying to achieve? We are fixing a specific issue. that should be in the comment.

"Fix move/undoMove mails in different folders/mailboxes" can be merged with later commit (the one I mentioned above)

File: src/mail-app/mail/view/MailGuiUtils.ts (hunk 7 above)
Comment (charlag) [reply src/mail-app/mail/view/MailGuiUtils.ts]: or it can be two separate functions

File: src/mail-app/search/view/SearchView.ts [hunk 8]
```diff
@@ -824,9 +824,18 @@ export class SearchView extends BaseTopLevelView implements TopLevelView<SearchV
 		return () => editDraft(conversationViewModel.primaryViewModel())
 	}
 
+	private isMovingMailsAllowed() {
```
Comment (charlag) [inline src/mail-app/search/view/SearchView.ts]: we do this until we implement the fix, right?

File: src/mail-app/mail/view/MailGuiUtils.ts [hunk 9]
```diff
@@ -206,6 +196,53 @@ export async function moveMails(params: MoveMailsParams): Promise<boolean> {
 	}
 }
 
+function mailsAndFolderByFolderId(mails: readonly Mail[]): Map<string, { folder: MailFolder; mails: Mail[] }> {
```
Comment (charlag) [inline src/mail-app/mail/view/MailGuiUtils.ts]: I'm not sure if this commit "Allow simple move mail to be undone" is still relevant

**Review by charlag — APPROVED** [review]
