### PR TITLE
[Android] Fix login failure when biometrics are disabled on device

### LINKED ISSUE #9064: Disabling biometrics (system-wide) makes android app unusable
After disabling biometrics (removing all fingerprints) on my phone I can no longer do anything in the Tuta Android App. Trying to log in by pressing on my account fails with "Could not unlock credentials: You haven't set up Face Unlock".
It's also impossible to remove the account because pressing on delete does nothing.

Reinstalling the app will likely fix this since it should flush settings/accounts but I wanted to open an issue first.

**To Reproduce**
1. Have biometrics enabled and a fingerprint saved on your phone
2. Have the Tuta app set to be unlockable using biometrics
3. Disable biometrics system-wide
4. Open app and try logging in/removing the account

**Expected behavior**
The app should ask me to log in using my password (and 2FA) if biometrics aren't available. I should also be able to remove the account.

**Screenshots**

Image

Image

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy Z Flip 6
 - OS: Android 15 / One UI 7.0
 - App Version: v287.250527.0

### PR DESCRIPTION
**Pull request by BijinDev**
If the user disables biometrics on their phone but the app’s 
`appLockMethod` is still set to biometrics, login attempts result in a 
`CredentialAuthenticationException`. This happens because the app still
 tries to use biometrics, which are no longer available.

Fixed by detecting `BiometricAuthenticationError`which clear stored 
credentials and setting `appLockMethod` to `None` to allow fallback
 authentication.

Close #9064

### CODE REVIEW

File: src/common/login/LoginViewModel.ts [hunk 1]
```diff
@@ -357,6 +357,16 @@ export class LoginViewModel implements ILoginViewModel {
 				await this.updateCachedCredentials()
 				this.state = LoginState.NotAuthenticated
 				this.helpText = "credentialsKeyInvalidated_msg"
+			} else if (e instanceof CredentialAuthenticationError && e.message.includes("No fingerprints enrolled")) {
```
Comment (charlag) [inline src/common/login/LoginViewModel.ts]: I don't think depending on the message is a good idea, I bet it's also localized.

here's the place where it's thrown:

https://github.com/tutao/tutanota/blob/b61d6c2abde47389b2c8a39338b41548f08146b1/app-android/tutashared/src/main/java/de/tutao/tutashared/credentials/AuthenticationPrompt.kt#L64

It has an error code which is more stable.

You have a choice of 1. adding code as a `data` field on the error or 2. introducing another error

File: src/common/login/AppLock.ts [hunk 2]
```diff
@@ -27,4 +30,14 @@ export class MobileAppLock implements AppLock {
 		}
 		return this.mobileSystemFacade.enforceAppLock(await this.mobileSystemFacade.getAppLockMethod())
 	}
+
+	/**
+	 * If the selected AppLockMethod is not present in supportedAppLockMethods allow fallback to `None`, otherwise
+	 * it will keep on restricting user from loggingIn
+	 */
+	async setAppLockMethod() {
```
Comment (charlag) [inline src/common/login/AppLock.ts]: at this point we have cleared the credentials, I think this method should be called `resetAppLockMethod()` and it should unconditionally set to `None`

File: src/common/login/LoginViewModel.ts (hunk 1 above)
Comment (BijinDev) [reply src/common/login/LoginViewModel.ts]: Introduced another error `AppLockAuthenticationError` for applock authentication exceptions

File: app-android/tutashared/src/main/java/de/tutao/tutashared/credentials/AuthenticationPrompt.kt [hunk 3]
```diff
@@ -48,21 +50,23 @@ class AuthenticationPrompt constructor() {
...
-	@Throws(CredentialAuthenticationException::class)
+	@Throws(CredentialAuthenticationException::class, AppLockAuthenticationException::class)
 	private fun showPrompt(
 		activity: FragmentActivity,
 		promptInfo: PromptInfo,
 		cryptoObject: BiometricPrompt.CryptoObject?,
 	) {
 		sem.acquireUninterruptibly()
 		var error: String? = null
+		var errorCode: Int? = null
```
Comment (charlag) [inline app-android/tutashared/src/main/java/de/tutao/tutashared/credentials/AuthenticationPrompt.kt]: It looks good now! I just have a little nitpick.

We should only ever have either both error message and error code or neither. Having one but not another would be an error and we should make it unrepresentable.

I would suggest that we replace these two variables with one of type `Exception` and we construct the error directly in the `onAuthenticationError()` and then just throw it in the end if it's there.

Alternatively we could make a tuple like:

```kt
var error: Pair<Int, String>? = null
```

**Review by charlag — APPROVED** [review]
awesome!
