### PR TITLE
Fix show partially selected labels in conversation

### LINKED ISSUE #8696: When there is a label on one of the emails the label dropdown on the conversation should show it as partially applied and currently it does not
> When there is a label on one of the emails the label dropdown on the conversation should show it as partially applied and currently it does not 

 _Originally posted by @charlag in [#8459](https://github.com/tutao/tutanota/issues/8459#issuecomment-2710546931)_

### PR DESCRIPTION
**Pull request by BijinDev**
close #8696

### CODE REVIEW

File: src/mail-app/mail/view/MailView.ts [hunk 1]
```diff
@@ -715,7 +715,14 @@ export class MailView extends BaseTopLevelView implements TopLevelView<MailViewA
 					if (mailList == null) {
 						return
 					}
-					showLabelsPopup(mailModel, mailList.getSelectedAsArray(), (mails: Mail[]) => this.mailViewModel.getActionableMails(mails), dom, opts)
+					// conversationViewModel is not there if we are in multiselect or if nothing is selected
+					if (this.conversationViewModel != null) {
+						// when viewing a conversation we need to get the label state for all the mails in that conversation
+						const conversationMails = this.conversationViewModel.conversationItems().map((mailItem) => mailItem.viewModel.mail)
+						showLabelsPopup(mailModel, conversationMails, (mails: Mail[]) => Promise.resolve(mails.map((mail) => mail._id)), dom, opts)
```
Comment (charlag) [inline src/mail-app/mail/view/MailView.ts:722]: I would do `async` instead of `Promise.resolve()`

**Review by charlag — APPROVED** [review]
Good job!
