### PR TITLE
Remove winreg, use WindowsRegistryFacade

### LINKED ISSUE #9398: Windows: ADD command exited with code 1: ERROR: Invalid syntax. Type "REG ADD /?" for usage.
```
Error message:
ADD command exited with code 1: ERROR: Invalid syntax. Type "REG ADD /?" for usage.
Stacktrace:
g: ADD command exited with code 1:

ERROR: Invalid syntax.
Type "REG ADD /?" for usage.
    at D (file:///C:/Users/[redacted]/AppData/Local/Programs/Tuta%20Mail/tutanota-desktop/resources/app.asar/desktop/winreg-CRVgKtPa.js:1:6452)
    at ChildProcess.<anonymous> (file:///C:/Users/me/AppData/Local/Programs/Tuta%20Mail/tutanota-desktop/resources/app.asar/desktop/winreg-CRVgKtPa.js:1:10844)
    at ChildProcess.emit (node:events:518:28)
    at maybeClose (node:internal/child_process:1101:16)
    at ChildProcess._handle.onexit (node:internal/child_process:304:5)
App version:
299.250725.1
Client type:
Windows
Additional info:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/299.250725.1 Chrome/138.0.7204.100 Electron/37.2.3 Safari/537.36
```

**Estimated: 8h**
**Time taken: 10h**

## Test notes
- [x] Enabling/disabling auto startup on Windows works
- [x] The Linux and macOS apps still open

### PR DESCRIPTION
**Pull request by paw-hub**
We use the REG command to manipulate/query the Windows registry.

Also adds CommandExecutor so that we have a nice, unit-testable way to execute commands.

Closes #9398

### CODE REVIEW

File: src/common/desktop/DesktopUtils.ts [hunk 1]
```diff
@@ -272,3 +271,9 @@ export function isRectContainedInRect(closestRect: Rectangle, lastBounds: Rectan
 function findMailToUrlInArgv(argv: string[]): string | null {
 	return argv.find((arg) => arg.startsWith("mailto")) ?? null
 }
+
+// Prevent statically importing this as we do not want to load the module during tests
+const sendDummyKeystroke = new LazyLoaded(async () => {
```
Comment (charlag) [inline src/common/desktop/DesktopUtils.ts]: I don't know if `LazyLoaded` is necessary, we can just re-import it virtually for free but it also does not hurt.

File: src/common/desktop/integration/WindowsRegistryFacade.ts [hunk 2]
```diff
@@ -0,0 +1,192 @@
...
+		private readonly registryHive: RegistryHive,
+		private readonly path: string,
+	) {}
+
+	/**
+	 * Get all values in the registry key
+	 * @return a map of all values, or null if nothing
+	 */
+	enumerate(): Promise<Map<string, WindowsRegistryValueType> | null> {
+		this.promise = this.promise.then(async () => {
```
Comment (charlag) [inline src/common/desktop/integration/WindowsRegistryFacade.ts]: the issue with chaining promises like this is that if one operation ever fails you can't proceed anymore. We should change it to `finally` or something like that

File: src/common/desktop/integration/WindowsRegistryFacade.ts [hunk 3]
```diff
@@ -0,0 +1,192 @@
...
+
+export type WindowsRegistryValueType = string | number
+
+/**
+ * High level interface for interacting with a given registry key
+ *
+ * Should be instantiated with WindowsRegistryFacade
+ */
+export class WindowsRegistryKey {
+	private promise: Promise<any> = Promise.resolve()
```
Comment (charlag) [inline src/common/desktop/integration/WindowsRegistryFacade.ts]: is there a reason to have `any` or could `unknown` also work?

File: src/common/desktop/integration/WindowsRegistryFacade.ts [hunk 4]
```diff
@@ -0,0 +1,192 @@
...
+			const fullPath = `${this.registryHive}${this.path}`
+			let type
+			if (typeof value === "number") {
+				type = RegistryValueType.DWORD
+			} else {
+				type = RegistryValueType.String
+			}
+			const result = await this.childProcess.run({
+				executable: "reg",
+				args: ["ADD", fullPath, "/v", name, "/t", type, "/d", String(value), "/f"],
```
Comment (charlag) [inline src/common/desktop/integration/WindowsRegistryFacade.ts]: I remember the other library had issues with spaces, do we need to quote/escape something or is it already okay because we don't spawn a shell?
https://github.com/fresc81/node-winreg/commit/6131f717a4a7b3e0f02d61e010b4becd59fa0203

File: test/tests/desktop/integration/DesktopIntegratorTest.ts [hunk 5]
```diff
@@ -547,91 +532,75 @@ o.spec("DesktopIntegrator Test", () => {
 	})
 
 	o.spec("Windows", function () {
+		let windowsRegistryFacade: WindowsRegistryFacade
+		let autorunMock: WindowsRegistryKey
+
 		o.beforeEach(function () {
 			n.setPlatform("win32")
+			windowsRegistryFacade = object()
```
Comment (charlag) [inline test/tests/desktop/integration/DesktopIntegratorTest.ts:540]: I would love to change `n.setPlatform()` to something similar to `withOverridenEnv()` but maybe not now

File: src/common/desktop/CommandExecutorFacade.ts [hunk 6]
```diff
@@ -0,0 +1,212 @@
...
+	 * An error code of zero typically indicates success. A non-zero error means that there was an error, but
+	 * the process still ran successfully.
+	 */
+	readonly exitCode: number
+}
+
+/**
+ * Interface for executing commands.
+ */
+export class CommandExecutorFacade {
```
Comment (charlag) [inline src/common/desktop/CommandExecutorFacade.ts]: I would propose to just call it `CommandExecutor`? I know we (ab)use "facade" a lot but I think it would be simpler to distinguish with some IPC-exposed interface

File: src/common/desktop/CommandExecutorFacade.ts [hunk 7]
```diff
@@ -0,0 +1,212 @@
...
+	constructor(private readonly childProcess: ChildProcessExports) {}
+
+	/**
+	 * Run the given command.
+	 * @param params params to execute
+	 * @return output from the command
+	 * @throws Error if the command failed to execute
+	 */
+	run(params: ProcessParams): Promise<CommandOutput> {
```
Comment (charlag) [inline src/common/desktop/CommandExecutorFacade.ts]: we can overload it to return the correct output. something like

```ts
run(params: ProcessParams & {stdoutEncoding: ProcessIOEncoding.Utf8}): Promise<CommandOutput<ProcessIOEncoding.Utf8>>
run(params: ProcessParams & {stdoutEncoding: ProcessIOEncoding.Binary}): Promise<CommandOutput<ProcessIOEncoding.Binary>>
run(params: ProcessParams & {stdoutEncoding: ProcessIOEncoding.Ignore}): Promise<CommandOutput<ProcessIOEncoding.Ignore>>
```

but maybe it's even better to do it with generic?

```ts
run<
  STDOUT extends ProcessIOEncoding,
  STDERR extends ProcessIOEncoding
>(
    params: ProcessParams<STDOUT, STDERR>
): Promise<CommandOuput<BufferFor<STDOUT>, BufferFor<STDERR>>
```

idk, what do you think?

File: src/common/desktop/CommandExecutorFacade.ts (hunk 6 above)
Comment (paw-hub) [reply src/common/desktop/CommandExecutorFacade.ts]: Probably better, yes.

File: src/common/desktop/integration/WindowsRegistryFacade.ts (hunk 4 above)
Comment (paw-hub) [reply src/common/desktop/integration/WindowsRegistryFacade.ts]: I'll definitely investigate this later, but I am fairly confident we should be fine.

File: src/common/desktop/DesktopUtils.ts (hunk 1 above)
Comment (paw-hub) [reply src/common/desktop/DesktopUtils.ts]: Meh, if re-importing is free, we might as well. It looks better anyway.

File: src/common/desktop/integration/WindowsRegistryFacade.ts (hunk 3 above)
Comment (paw-hub) [reply src/common/desktop/integration/WindowsRegistryFacade.ts]: Nah, `unknown` is more correct here. I'll fix that.

File: src/common/desktop/integration/WindowsRegistryFacade.ts (hunk 2 above)
Comment (paw-hub) [reply src/common/desktop/integration/WindowsRegistryFacade.ts]: The promise is gone. It is now a lie.

File: src/common/desktop/CommandExecutorFacade.ts (hunk 7 above)
Comment (paw-hub) [reply src/common/desktop/CommandExecutorFacade.ts]: I decided to go with the generic approach.

It's a little funky, but it should nicely default to string output for stdout and stderr and only override them when specified.

File: src/common/desktop/integration/WindowsRegistryFacade.ts (hunk 4 above)
Comment (paw-hub) [reply src/common/desktop/integration/WindowsRegistryFacade.ts]: I wrote a simple program that prints the arguments on separate lines, and having spaces in the arguments did not break anything.

Comment (charlag) [reply src/common/desktop/integration/WindowsRegistryFacade.ts]: I think it's not a problem with general `spawn`, their issue was specifically with REG.EXE

**Comment by hrb-hub** [comment]
Really cool!!

File: src/common/desktop/integration/WindowsRegistryFacade.ts (hunk 4 above)
Comment (paw-hub) [reply src/common/desktop/integration/WindowsRegistryFacade.ts]: I gave this a quick test: If I include quotes in the data argument, REG.EXE will include the quotes verbatim in the actual data.

image

Comment (paw-hub) [reply src/common/desktop/integration/WindowsRegistryFacade.ts]: Passing spaces for the other parameters has the same effect: adding quotes will literally insert quotes.

I don't think reg.exe is at fault here, besides the fact it allows such nonsense.

image
image
image
