### PR TITLE
Fix dragging all-day events

### LINKED ISSUE #6513: dancing and multiplying all-day events on mobile layout
**Describe the bug**
When editing (or deleting) events on the PC while Tuta is in mobile layout, the events change to the date the mouse is hovering over and show generally odd behavior.

**To Reproduce**
1. Change to mobile layout
2. Go to Calendar
3. Create an All-Day event in week-view
4. Edit/Delete the event while hovering the mouse over a different date 
5. The event has moved to that date

5.1 When closing the event editor, the hovered date is still saved for the event
5.2 When changing the date to a non-hovered one and saving, the event is duplicated (on the hovered and edited date)
5.3 When deleting the event, it will still show on the hovered date but disappear after a delay and some scrolling

Note: The duplicated events show in the calendar on different clients but with inconsistent dates

**Screenshots**
This occurred when editing and saving to a different date than the event hovered (now non-editable):
Desktop client mobile layout:
image

Web Client:
image

When exiting and re-entering the mailbox on the client, the actual state is shown (Web Client)

**Additional context**
Tuta Version 3.121.4

Enjoy! :)

## Test notes
- [ ] Try to drag an all-day event in the mobile view. Verify that this issue no longer occurs (the event should no longer be draggable).
- [ ] Try to drag an event outside of the calendar view. Verify the drag is cancelled.
- [ ] Verify that dragging normal events works.

### PR DESCRIPTION
**Pull request by paw-hub**
Moving the cursor outside of the calendar view cancels the drag event.

Also do not allow dragging all-day events in the mobile view, as this does not work properly with the mobile header.

Fixes #6513

### CODE REVIEW

**Review by wrdhub — APPROVED** [review]

File: src/calendar/view/CalendarView.ts [hunk 1]
```diff
@@ -240,6 +240,7 @@ export class CalendarView extends BaseTopLevelView implements TopLevelView<Calen
 									},
 									selectedDate: this.viewModel.selectedDate(),
 									onDateSelected: (date, viewType) => {
+										this.viewModel.selectedDate(date)
```
Comment (charlag) [inline src/calendar/view/CalendarView.ts:243]: why do we need this one as well as URL? wouldn't setting the URL trigger it already?

Comment (paw-hub) [reply src/calendar/view/CalendarView.ts:243]: Sorry, that was not intended to be in the commit. I made a change here when I was testing and forgot to remove it.

That being said, we do this pattern for day as well. Maybe we should re-evaluate this?

https://github.com/tutao/tutanota/blob/227b7e440965de46a0cc0f766555b001cbde1442/src/calendar/view/CalendarView.ts#L214-L215

Comment (charlag) [reply src/calendar/view/CalendarView.ts:243]: hm yeah we should check if we need it at all or not

Comment (paw-hub) [reply src/calendar/view/CalendarView.ts:243]: Seems to not be needed.
