### PR TITLE
Fix async waiting on u2f key

### LINKED ISSUE #3390: U2F register/login
**Bug in web app**

**Describe the bug**
I am not able to register a new U2F token to my account. TOTP works fine.

In Chromium the key is not recognized with a generic error:
```
u2fApi.getApiVersion 
        js_api_version: 1.1
u2fSupport true
2Logger.js:89 U2f error undefined {}
```
On Firefox we immediately show an error that the key is not recognized when saving. Firefox asks for the key, but nothing happens. 
Screenshot from 2021-08-13 16-25-07

**Expected result**

Key can be registered.

### PR DESCRIPTION
**Pull request by jowlo**
fix #3390

### CODE REVIEW

File: src/misc/U2fClient.js [hunk 1]
```diff
@@ -79,7 +79,7 @@ export class U2fClient {
 			], [], resolve, TIMEOUT)
 		})
 		const response = this._handleRawResponse(rawResponse)
```
Comment (charlag) [inline src/misc/U2fClient.js:81]: This seems wrong.
`response` is not a Promise, (check `_handleRawResponse` and maybe improve type of it if you have time?)
`rawResponse` *is* a promise because we create it on the previous line.

Comment (charlag) [reply src/misc/U2fClient.js:81]: rawResponse seems to be of type


```js
u2f.Error|u2f.RegisterResponse
```

with

```js
/**
 * Data object for a registration response.
 * @typedef {{
 *   version: string,
 *   keyHandle: string,
 *   transports: Transports,
 *   appId: string
 * }}
 */
u2f.RegisterResponse;
```

```js
/**
 * An error object for responses
 * @typedef {{
 *   errorCode: u2f.ErrorCodes,
 *   errorMessage: ?string
 * }}
 */
u2f.Error;
```

with

```js
/**
 * Response status codes
 * @const
 * @enum {number}
 */
u2f.ErrorCodes = {
	'OK': 0,
	'OTHER_ERROR': 1,
	'BAD_REQUEST': 2,
	'CONFIGURATION_UNSUPPORTED': 3,
	'DEVICE_INELIGIBLE': 4,
	'TIMEOUT': 5
};
```

Comment (jowlo) [reply src/misc/U2fClient.js:81]: Yes, you are right, it seems wrong. I am a bit puzzled that it did work though... I'm on it!

Comment (jowlo) [reply src/misc/U2fClient.js]: I guess we could also start typing the `u2f-api.js` wrapper, but i am not sure that is helpful at all..

File: src/misc/U2fClient.js [hunk 2]
```diff
@@ -89,16 +90,18 @@ export class U2fClient {
 		})
 	}
 
-	_handleRawResponse(rawResponse: Object): Object {
-		console.log("U2f error", rawResponse.errorCode, JSON.stringify(rawResponse))
+	_handleRawResponse(rawResponse: {clientData: Base64Url, registrationData: Base64Url} | {errorCode: number}): Object {
```
Comment (johnbotris) [inline src/misc/U2fClient.js:93]: pls type the return

**Review by jowlo — COMMENTED** [review]
i approve
