### PR TITLE
Fix assertNotNull failed getting server time after partial login success

### LINKED ISSUE #10176: AssertNotNull failed : You can't get server time if no rest requests were made
Introduced in #10138

This can occur when no rest requests have yet been made and we try to check if the offline DB is out of sync after a failed partial login due to an `InvalidModelError`.

**Stacktrace:**
```
Error: AssertNotNull failed : You can't get server time if no rest requests were made
    at k (asset://app/common-min-Cf7wogqm.js:1:3250)
    at Hc.getServerTimestampMs (asset://app/mail-worker.js:18:90559)
    at xc.getServerTimestampMs (asset://app/mail-worker.js:18:78093)
    at xc.timeSinceLastSyncMs (asset://app/mail-worker.js:18:78000)
    at async xc.isOutOfSync (asset://app/mail-worker.js:18:77610)
    at async Oc.checkOutOfSync (asset://app/mail-worker.js:18:73616)
    at async Mc.checkOutOfSyncCache (asset://app/mail-worker.js:18:48102)
```

**Additional information:**
Only users previously impacted by #10137 are impacted by this. So the workaround is the same as #10137 (clearing credentials and logging in again)

## Pre release tasks
- [x] Rename `outOfSync_label` to `dataExpired_label` in PoEditor

## Test notes
- [ ] `InvalidModelError` is handled correctly
  - [x] Have a client with saved credentials
  - [x] Go offline and stay offline until further notice
  - [x] Check that offline login works
  - [x] Close the client
  - [x] Open `server_type_models.json` stored in the local config and change the type or cardinality of one of the mailbox's `values` (mailbox type is `tutanota/125`) to cause an `InvalidModelError` to be thrown
  - [x] Start the client and login
  - [x] See that the "Data out of sync" dialog is shown
  - [x] Close the dialog and check that cache is purged and that you're logged out
  - [x] Go back online and login again successfully
  - [x] Go offline again and stay offline until further notice
  - [x] Check that offline login works
  - [x] Close the client
  - [x] Open `server_type_models.json` and change the type or cardinality of one of the mail's `values` (mail type is `tutanota/97`) to cause an `InvalidModelError` to be thrown
  - [x] Start the client and login
  - [x] See that the "Data out of sync" dialog is shown when loading the mail list
  - [x] Close the dialog and check that cache is purged and that you're logged out
  - [x] Go back online and login again successfully
- [x] When an exception that is not an `InvalidModelError` is thrown during partial login, the client is logged out properly, and login retry is possible
- [x] When an `OutOfSyncError` is thrown the "Data expired" dialog is shown instead of the "Data out of sync" dialog

### PR DESCRIPTION
**Pull request by hrb-hub**
Trying to get the server time after partial login success could fail, if no rest requests were made or if the client is offline.

We avoid getting server time by avoiding the out of sync cache check and just treat the cache as out of sync whenever an InvalidModelError is thrown, which could actually happen at any point if the mapped entity is not in sync with the current server model.

Close #10176

Co-authored-by: ivk <ivk@tutao.de>

### CODE REVIEW

File: src/common/api/main/LoginController.ts [hunk 1]
```diff
@@ -191,16 +190,23 @@ export class LoginController {
 				)
 			} catch (e) {
 				console.log("Error finishing login", e)
+				let errToRethrow = e
+
 				if (e instanceof InvalidModelError) {
 					// It's possible for the model to be invalid when logging in with a new model and a very old cache
-					await this.loginFacade.checkOutOfSyncCache()
+					await this.loginFacade.checkOutOfSyncCache().catch(
```
Comment (charlag) [inline src/common/api/main/LoginController.ts]: why do we check for out of sync in the first place? If we have invalid model there's nothing we can do anyway but clear the cache, right?

File: src/common/api/main/LoginController.ts [hunk 2]
```diff
@@ -191,16 +190,23 @@ export class LoginController {
...
+						// ConnectionError might be thrown when getting the server time that's needed to check sync state
+						ofClass(ConnectionError, async (connectionErr) => {
```
Comment (charlag) [inline src/common/api/main/LoginController.ts]: what is the point of this catch? You are awaiting this so there are two situations:
 - it is `ConnectionError`. You will catch it and rethrow it later
 - It is not `ConnectionError`. It will just get rethrown and you won't log out and will get stuck in invalid state (I guess that's how it was before but still weird)

File: src/common/api/worker/rest/RestClient.ts [hunk 3]
```diff
@@ -308,6 +310,28 @@ export class RestClient {
 		return Date.now() + timeOffset
 	}
 
+	/**
+	 * Wait for the server time offset to be set after a rest request is made before returning the server time.
+	 * will throw a ConnectionError if the server time offset isn't set after some time
+	 */
+	async getServerTimestampMsAsync(): Promise<number> {
+		await this.waitForServerTimeOffset()
```
Comment (charlag) [inline src/common/api/worker/rest/RestClient.ts]: iff we want to do this I would `Promise.race` with `delay()`. Like I said earlier I don't see a point in checking out of sync if we the model is wrong anyway.

File: src/common/api/main/LoginController.ts (hunk 1 above)
Comment (hrb-hub) [reply src/common/api/main/LoginController.ts]: The reasoning here was that an `InvalidModelError` with an outdated cache is fine and expected to happen, so we handle it by clearing cache. But an `InvalidModelError` with a non-outdated cache should not occur unless we did something wrong, and therefore we throw.

File: src/common/api/main/LoginController.ts (hunk 2 above)
Comment (hrb-hub) [reply src/common/api/main/LoginController.ts]: It was done this way because `this.loginFacade.checkOutOfSyncCache()` might throw an `OutOfSyncError` which we do not want to catch, because if we logout before rethrowing it, we won't be able to clear cache from the error handler, unless I'm missing something‥

We probably should make sure to logout on any exception that isn't an `OutOfSyncError` though, my bad 😅
