### PR TITLE
fix loginForm is not prefilled with address

### LINKED ISSUE #5810: Email address is not put into the login field after signup
How to reproduce:
1. Sign up for a new account.
-> When switching to the login form after signup the email address field is empty.
Expected: The email address selected at signup is put into the field.

This bug exists since 3.118.1. Locally the bug could not be reproduced with 3.118.1. The URL is the same in both cases (/login?noAutoLogin=true&loginWith=<email address>". Additional observation: In the error case the "saved credentials" button is visible in the login form. In the other case it is not.

## Test Notes:
* [ ] try the following in Firefox, Chrome, Safari, Linux Desktop, Windows Desktop, Max, Desktop, Apps
* [ ] without stored accounts
  * [ ] if you previously stored accounts make sure to reload the page after deleting all of them
  * [ ] create a new account and make sure that the email address is put into the login field
* [ ] with stored accounts
  * [ ] switch to the loginForm with "Different account"
  * [ ] create a new account and make sure that the email address is put into the login field
  * [ ] delete all accounts which should automatically redirect you to the loginForm
  * [ ] create a new account and make sure that the email address is put into the login field

### PR DESCRIPTION
**Pull request by nokhub**
When the loginForm promise is resolved, the url
arg loginWith is read and stored in the mailAddress Stream. The loginForm promise is only resolved
in the oncreate function of the loginForm.
Since the oncreate function is not called again
when switching from saved accounts to create a new account, the promise won't be resolved again.

Moving the promise.resolve() to the onupdate
function solves the issue.

fix #5810

### CODE REVIEW

File: src/login/LoginView.ts [hunk 1]
```diff
@@ -216,7 +216,7 @@ export class LoginView extends BaseTopLevelView implements TopLevelView<LoginVie
 		return m(
 			".flex.col.pb",
 			{
-				oncreate: (vnode) => {
```
Comment (charlag) [inline src/login/LoginView.ts:219]: it is not allowed to resolve the same promise twice. We need to recreate `this.loginForm` in `onDestroy()` of it I think.

Comment (nokhub) [reply src/login/LoginView.ts:219]: I agree that this approach is cleaner. I will ammend the changes since it is only a small change anyway

**Review by charlag — APPROVED** [review]
