### PR TITLE
directly throw any offline errors from setupMultiple

### LINKED ISSUE #5137: Updating calendar event does not properly handle network errors
`CalendarFacade#updateCalendarEvent()` calls `_saveMultipleAlarms()` but doesn't unwrap `SetupMultipleError` to convert it to `ConnectionError`.

```
Updating a calendar appointment (to add a reminder)


Client: win32
Tutanota version: 3.108.12
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.108.12 Chrome/108.0.5359.179 Electron/22.0.3 Safari/537.36
SetupMultipleError
Error message: Setup multiple entities failed
Number of errors: 1
First error: ConnectionError: 0: | POST /rest/sys/useralarminfo/LjHEozM--R-1
Stacktrace:
SetupMultipleError: Setup multiple entities failed
Number of errors: 1
First error: ConnectionError: 0: | POST /rest/sys/useralarminfo/LjHEozM--R-1
at Ka.setupMultiple (asset://app/worker.js:1:28888)
at async kl._saveMultipleAlarms (asset://app/worker.js:12:132367)
at async kl.updateCalendarEvent (asset://app/worker.js:12:128872)
```

To fix it we should do a similar thing to what `_saveCalendarEvents` does and convert it to `ConnectionError` if appropriate.

## Test Notes
* [ ] saving calendar events with multiple alarms still works
* [ ] updating calendar events with multiple alarms still works
* [ ] if the connection drops while saving/updating, an offline notification is shown, but no uncaught error is thrown.

### PR DESCRIPTION
**Pull request by ganthern**
fix #5137

### CODE REVIEW

File: src/api/worker/facades/lazy/CalendarFacade.ts [hunk 1]
```diff
@@ -384,26 +379,29 @@ export class CalendarFacade {
...
-						this.entityClient.load<CalendarEventUidIndex>(CalendarEventUidIndexTypeRef, [groupRoot.index.list, uint8arrayToCustomId(hashUid(uid))]),
-				)
-				.catch(ofClass(NotFoundError, () => null))
-				.catch(ofClass(NotAuthorizedError, () => null))
-		}).then((indexEntry) => {
-			if (indexEntry) {
-				return this.entityClient.load<CalendarEvent>(CalendarEventTypeRef, indexEntry.calendarEvent).catch(ofClass(NotFoundError, () => null))
-			} else {
-				return null
+		for (const membership of calendarMemberships) {
```
Comment (charlag) [inline src/api/worker/facades/lazy/CalendarFacade.ts:384]: this will conflict with rescheduling, we also rewrote this function

File: src/api/worker/facades/lazy/CalendarFacade.ts [hunk 2]
```diff
@@ -456,7 +454,8 @@ export class CalendarFacade {
 		const allAlarms = flat(
 			userAlarmInfosAndNotificationsPerEvent.map(({ userAlarmInfoAndNotification }) => userAlarmInfoAndNotification.map(({ alarm }) => alarm)),
 		)
-		const alarmIds = await this.entityClient.setupMultipleEntities(userAlarmInfoListId, allAlarms)
+
+		const alarmIds: Array<string> = await this.entityClient.setupMultipleEntities(userAlarmInfoListId, allAlarms)
```
Comment (charlag) [inline src/api/worker/facades/lazy/CalendarFacade.ts:458]: `Id[]`

**Review by charlag — COMMENTED** [review]
I do not understand the fix and how it connects to the commit message, is it about removing the branch where we check for offline errors?

(even though I wrote an original issue I don't remember the details now)

**Comment by ganthern** [comment]
The fix is about not packaging Connection errors at all into a SetupMultiple error and then not catching setupMultiple at all.

this will cause any failures that are not connection errors to still be reported as currently and connection errors be handled by the global offline error handler.

File: src/api/worker/facades/lazy/CalendarFacade.ts (hunk 2 above)
Comment (ganthern) [reply src/api/worker/facades/lazy/CalendarFacade.ts:458]: `Array<Id>`, fite me

File: src/api/worker/facades/lazy/CalendarFacade.ts (hunk 1 above)
Comment (ganthern) [reply src/api/worker/facades/lazy/CalendarFacade.ts:384]: I guess we can just integrate the fix into the rescheduling PR then, it's not a lot.

**Review by charlag — APPROVED** [review]
I saw the important part now!

File: src/api/worker/facades/lazy/CalendarFacade.ts (hunk 2 above)
Comment (charlag) [reply src/api/worker/facades/lazy/CalendarFacade.ts:458]: I thought they wanted to deprecate this syntax but I'm not sure anymore
