### PR TITLE
Don't close the mail editor if tab is not closed (fix #2423)

### LINKED ISSUE #2423: Weird behaviour of the Mail Editor
Two unexpected behaviors:

Chrome: 
Mail Editor automatically closes when Tab closing is denied:
1. Open the Mail Editor (reply or new E-Mail)
2. try to close the tab you're currently on
3. It will now ask for you to confirm the closing action, press cancel
4. The Mail Editor will now just close without further confirmation 

Firefox: 
Mail Editor close-popup opens when Tab closing is denied:
1. see above
2. see above
3. see above
4. The Mail Editor won't close but the small Dialog at the top left will open. 

Expected behavior for both: Do not change Mail Editor at all when canceling tab-closure

### PR DESCRIPTION
**Pull request by SnowyMouse**
Fixes #2423 by changing the listener to do nothing but still trigger if the tab is closed when on browser, allowing the user the option to not close the tab if they are unsure without closing the editor regardless of their choice.

### CODE REVIEW

File: src/mail/MailEditorN.js [hunk 1]
```diff
@@ -449,7 +449,10 @@ function createMailEditorDialog(model: SendMailModel, blockExternalContent: bool
 		middle: () => conversationTypeString(model.getConversationType()),
 		create: () => {
 			windowCloseUnsubscribe = windowFacade.addWindowCloseListener(() => {
-				closeButtonAttrs.click(newMouseEvent(), domCloseButton)
+				// Simulate a button click only if we're on not on browser, since on a browser, we can't override it closing, only ask if the user is sure they want to close
+				if (!isBrowser()) {
+					closeButtonAttrs.click(newMouseEvent(), domCloseButton)
```
Comment (charlag) [inline src/mail/MailEditorN.js:454]: I don't know if we need to do anything outside of browser, there are no tabs outside of browser anyway

Comment (SnowyMouse) [reply src/mail/MailEditorN.js:454]: It looks like the event fires when you click the close button on the desktop client's window, too.

Currently, if you close the window on the desktop client, it will show a little drop down next to the Close button as if you clicked that, giving you the option to save a draft. Or, if you didn't type anything, it simply closes the mail editor.

Comment (charlag) [reply src/mail/MailEditorN.js:454]: Didn't remember about desktop, maybe it's worth mentioning it

**Comment by SnowyMouse** [comment]
I've added some comments. I also decided to use separate listener functions for browser and desktop as I felt that would make it more clear. I don't think anything else needs the listener, anyway.
