### PR TITLE
Fix permission for notifications being asked too early

### LINKED ISSUE #6771: Notification permission pop up is shown together with onboarding wizard
After installing the app and adding the account for the first time the app immediately asks me to enable push notification.

**To reproduce**
* Remove TutaMai app and install it again.
* Add an account
* Error -> See request to enable push notification

**Expected**
I expect that the request for system permission appears after clicking "enable notification" from the onboarding dialog.

## Test Notes
- [ ] When login in for the first time after install, no dialog asking for permission is presented
  - [ ] There's a page in the wizard asking for notifications permission
  - [ ] When clicking to authorize, a system prompt appears to allow notifications
- [ ] If the wizard is dismissed without giving permissions, the user will be prompted by system dialog during the next login
### Extended test:
  - Do a fresh install
  - Close the wizard without allowing notifications
  - Close the app and open again
  - Deny notifications after login
  - Close the app and allow notification on settings
  - Open the app again
  - [ ] Try to receive a notification and receive it with success

### PR DESCRIPTION
**Pull request by murilopereirame**
Co-authored-by: ivk <ivk@tutao.de>

fix #6771

### CODE REVIEW

File: src/login/PostLoginActions.ts [hunk 1]
```diff
@@ -128,7 +129,16 @@ export class PostLoginActions implements PostLoginAction {
...
-			locator.pushService.register()
+			if ((isApp() && deviceConfig.getIsSetupComplete()) || isDesktop()) {
+				// Do not try to register for notifications while the setup dialog
+				// is being shown because we might not have a permission yet and
+				// we don't want to ask for it while dialog is shown, we will ask in
+				// the dialog anyway.
+				// After dialog is finished or dismissed the setup is "complete".
+				locator.pushService.register()
+			} else {
+				console.log("Skipping registering for notifications while setup dialog is shown")
```
Comment (wrdhub) [inline src/login/PostLoginActions.ts:140]: I don't think this log is necessary

**Review by wrdhub — APPROVED** [review]
