### PR TITLE
Change the column order of the subscription selector. Fix #1902

### LINKED ISSUE #1902: Column order in signup and upgrade dialog wrong for small screen sizes
If the screen width is less than 1230px, the free column will be displayed on the right instead of the left side. The columns should only be displayed in that order on mobiles (where only one colum is displayed), not on desktops with smaller screens.

### PR DESCRIPTION
**Pull request by antomor**
Change the column order of the sign-up and upgrade dialog only when one-column layout is shown (e.g. mobile).

### CODE REVIEW

**Comment by charlag** [comment]
Hi,
thanks for the PR!

I would propose to do something else than checking column widths. These column values have nothing to do with columns in this dialog, it's about big UI columns like the folder list, mail list and mail viewer.

Columns in this dialog has fixed width of 230px plus 10px margin on each side and also dialog itself has paddings and margin. I think we should subtract all of that from the window width and check if all the boxes fit or not. That would be reliable.

Instead of subtracting dialog values (and thus coupling this subscription selector to the dialog) we can get the dom from Vnode on second render and see if columns fit there or not.

Currently it's not clear why we use completely different columns to figure out if these boxes fit or not.

File: src/subscription/SubscriptionSelector.js [hunk 1]
```diff
@@ -39,10 +40,10 @@ class _SubscriptionSelector {
 				m(BuyOptionBox, this._createProUpgradeBoxAttr(vnode.attrs))
 			]
 		} else {
-			// Shows different order of BuyBoxes if screen with is smaller than 560 px.
-			// Changes order of BuyBoxes to Premium Pro Free, needed for mobile view
-			const minWidthTwoColumns = size.first_col_min_width + size.second_col_min_width + 20;
-			if (window.innerWidth < minWidthTwoColumns ) {
+			// Add BuyOptionBox margin twice to the boxWidth received
+			const columnWidth = vnode.attrs.boxWidth + 20;
```
Comment (antomor) [inline src/subscription/SubscriptionSelector.js:44]: I think that we should reference a common variable where the `BuyOptionBox`margin is defined.
I have tried to use a static variable within the `BuyOptionBox` class, but I get a flow error, and exporting directly a variable from the file where `BuyOptionBox` is defined doesn't seem to be a common practice in the repo. What would you suggest?

**Comment by antomor** [comment]
Hi @charlag , thank you for your suggestion. I totally agree with you, but at a first glance it was not clear to me the reasoning applied. Anyway, I am not familiar neither with Mithril nor with Flow, so any further hint is appreciated.

File: src/subscription/SubscriptionSelector.js (hunk 1 above)
Comment (charlag) [reply src/subscription/SubscriptionSelector.js:44]: You can use static variables like here
https://github.com/tutao/tutanota/blob/c9b63f9c159127268bab24853000e37456058460/src/gui/base/Dialog.js#L58

but the best would probably be just
```js
export const BOX_MARGIN = 10
```

**Comment by charlag** [comment]
Thanks for looking into this, to be fair it's quite messy and undocumented part of the codebase so good job finding your way around!

File: src/subscription/SubscriptionSelector.js (hunk 1 above)
Comment (antomor) [reply src/subscription/SubscriptionSelector.js]: At first I have tried exactly the solution suggested by you, but from [BuyOptionsBox](https://github.com/tutao/tutanota/blob/c9b63f9c159127268bab24853000e37456058460/src/subscription/BuyOptionBox.js#L111), the class itself is not exported, but it exports the type `Class<MComponent<BuyOptionBoxAttr>>`, and it would haven't had that static variable (from here the flow error).
Anyway, I opted for the second solution, thanks :-)

Comment (charlag) [reply src/subscription/SubscriptionSelector.js]: Ah, I get it now, it's an artifact, I just didn't get to change all those places yet where it re-exports class constant instead of doing `export class A implements MComponent<Attrs>`. It's fine with exporting standalone constant for now.

File: src/subscription/BuyOptionBox.js [hunk 2]
```diff
@@ -46,7 +48,7 @@ class _BuyOptionBox {
 
 		return m("", {
 			style: {
-				margin: "10px",
+				margin: `${BOX_MARGIN}px`,
```
Comment (charlag) [inline src/subscription/BuyOptionBox.js:51]: we have a `px` function for that, would be nicer to use it

**Comment by antomor** [comment]
Hi @charlag, no problem at all. I have just applied your suggestion. Feel free to pointing out other problems, if any :-)

**Comment by charlag** [comment]
Hey, I removed `onupdate()` handler since we don't need it anymore, squashed and rebased it. Thanks a lot for the changes!
