### PR TITLE
[ios] show message box if shared attachment size exceeds limit

### LINKED ISSUE #4833: There is no error message when the shared attachment size exceeds the 25Mb limit
**Bug in mobile app**

**Describe the bug**
When a user shares items exceeding 25Mb in size with tutanota, the app will open but no mail editor will be created because we check the limit before opening it. There is no indication of the reason why the operation failed.

**Expected behavior**
Either the Share extension or the App should show a helpful error message as to why the operation failed.

## Test Notes
* [ ] when attaching files exceeding 25MB, the app opens and shows an error dialog. No editor is created.
* [ ] when attaching files summing to under 25MB, the mail editor is created normally.

### Regression Tests
* [ ] mailto handling on desktop still works
* [ ] "Send As -> E-Mail" context menu action still works on windows

### PR DESCRIPTION
**Pull request by ganthern**
we're already getting a UserError with the correct message, just need to show it.
rethrowing the error to make the native side clean up.

close #4833

### CODE REVIEW

File: src/native/main/WebCommonNativeFacade.ts [hunk 1]
```diff
@@ -25,35 +27,43 @@ export class WebCommonNativeFacade implements CommonNativeFacade {
...
+			}
 
-		editor.show()
+			editor.show()
+		} catch (e) {
+			if (e instanceof UserError) {
+				// noinspection ES6MissingAwait
+				Dialog.message(() => e.message)
+			}
+			throw e
```
Comment (charlag) [inline src/native/main/WebCommonNativeFacade.ts:65]: do you still re-throw `UserError` then?

Comment (ganthern) [reply src/native/main/WebCommonNativeFacade.ts:65]: yes, I'm not returning from the catch. I still want the native side to see that we're done with the shared data
