### PR TITLE
Fix birthday event expanding to next day

### LINKED ISSUE #9503: Birthday events extend to multiple days
In certain cases birthday events are being displayed as all day events from 02:00 until 03:00 next day.
This seems to be related to timezone issues.

**Steps to reproduce**
1. Create a contact with birthday on 29/09/1985
2. Go to Calendar
3. See that the birthday is rendered from 29/09 until 30/09

### PR DESCRIPTION
**Pull request by andrehgdias**
This commit introduces a new helper function to create start and end dates from ISO strings, applying a timezone if provided. This fixes the problem where on positive timezones, specifically on the date 29.09.1985 the calculated end date was wrong and the event expanded for two days.

Closes #9503

### CODE REVIEW

File: src/common/calendar/date/CalendarEventsRepository.ts [hunk 1]
```diff
@@ -355,17 +356,7 @@ export class CalendarEventsRepository {
...
-		// Set the year because we can have birthdays without year
-		if (contact.birthdayIso?.startsWith("--")) {
-			fullDateIso = contact.birthdayIso.replace("-", "1970")
-		}
-
-		// Set up start and end date base on UTC.
-		// Also increments a copy of startDate by one day and set it as endDate
-		const startDate = new Date(fullDateIso!) // Uses fullDateIso as UTC value, therefore it creates a new Date applying the local timezone on top of fullDateIso
-		const endDate = incrementDate(new Date(startDate), 1)
+		const { startDate, endDate } = getAllDayDatesUTCFromIso(contact.birthdayIso!, this.zone)
```
Comment (bedhub) [inline src/common/calendar/date/CalendarEventsRepository.ts:364]: Are we are actually sure that we have a birthdayIso field? What happens in that case?
