### PR TITLE
fix self not being displayed on calendar editor attendee list

### LINKED ISSUE #5714: Guests cannot see themselves on the attendees list if they didn't create the event
To reproduce:
- Create an event with two other guests
- Accept the invitation as one guest
- Look at the event in the calendar

Expected result:
You see every attendee, just like what the organizer sees

Actual result:
You see every attendee who is not you

Organizer view:
image

Attendee view (bedpremium@tutanota.com):
image

### PR DESCRIPTION
**Pull request by ganthern**
fix #5714

### CODE REVIEW

File: src/calendar/view/eventeditor/AttendeeListEditor.ts [hunk 1]
```diff
@@ -136,6 +133,11 @@ export class AttendeeListEditor implements Component<AttendeeListEditorAttrs> {
 			attendeeRenderers.push(() => renderGuest(guest, attrs))
 		}
 
+		const ownGuest = whoModel.ownGuest
```
Comment (charlag) [inline src/calendar/view/eventeditor/AttendeeListEditor.ts:136]: I think this chunk needs a comment on it. Is own guest not in the list of guests? why is this needed?

**Review by charlag — APPROVED** [review]

File: src/calendar/view/eventeditor/AttendeeListEditor.ts (hunk 1 above)
Comment (ganthern) [reply src/calendar/view/eventeditor/AttendeeListEditor.ts:136]: whoModel.guests actually specifies that on the getter, but I added another comment.
