### PR TITLE
9595 store calendar colors remotely

### LINKED ISSUE #9595: Store Birthday calendar color remotely
## AC

- The birthday calendar colour should be stored remotely
- Clients can retrieve this colour and synchronize across devices
- The widget can also use this colour
- The calendar colour should be stored in the Contact Group
- No more fake groups are used

## Test notes
**Functionality** 
- [x] Check calendar color syncs between clients and devices
- [x] Check widget correctly fetches the calendar color
  - [x] [Android] Configuration page
  - [x] [Android / iOS] Event rendering
- [x] Check if upgrade from previous version doesn't break rendering (we changed constants)
- [x] Edit dialog now works fine #9676
  - [x] Input for calendar name should be read-only 

**Regression tests**
- [x] Check older clients can still see the birthday events with the old colors
- [x] Calendars still correctly rendered on the sidebar:
  - [x] Each calendar is displayed in their correct classification (Your, Shared, Subscription)
  - [x] In the event popup/details, correct calendar information is displayed
- [x] Editing each calendar still works as expected:
  - [x] Normal
  - [x] Shared
  - [x] Subscription

### PR DESCRIPTION
**Pull request by andrehgdias**
Closes #9595

### CODE REVIEW

File: src/calendar-app/calendar/gui/eventpopup/CalendarEventPreviewViewModel.ts [hunk 1]
```diff
@@ -369,8 +378,8 @@ export class CalendarEventPreviewViewModel {
 	}
 
 	// Returns null if there is no ownerGroup, which might be the case if an event invitation is being viewed
-	getCalendarRenderInfo(): CalendarRenderInfo | null {
-		if (!this.calendarEvent._ownerGroup) return null
-		return this.calendarModel.getCalendarRenderInfo(this.calendarEvent._ownerGroup)
+	getCalendarInfoBase(): CalendarInfoBase | undefined {
+		if (!this.calendarEvent._ownerGroup) return undefined
+		return this.calendar.getLoaded()
```
Comment (murilopereirame) [inline src/calendar-app/calendar/gui/eventpopup/CalendarEventPreviewViewModel.ts]: Calling ```this.calendar.getLoaded()``` can throw an error in case the calendar isn't loaded yet.
Prefer calling ```this.calendar.getSync()``` or check if the calendar is loaded using ```this.calendar.isLoaded()```

File: src/calendar-app/calendar/gui/eventpopup/EventPreviewView.ts [hunk 2]
```diff
@@ -268,11 +268,11 @@ export class EventPreviewView implements Component<EventPreviewViewAttrs> {
 						borderRadius: "50%",
 						width: px(size.hpad_large),
 						height: px(size.hpad_large),
-						backgroundColor: calendarColor,
+						backgroundColor: `#${calendarColor}`,
 					},
 				}),
 			),
-			m(".flex.col", [calendarName, m("small.text-fade", lang.get(calendarRenderType!))]),
+			m(".flex.col", [calendarName, m("small.text-fade", lang.get(calendarType!))]),
```
Comment (murilopereirame) [inline src/calendar-app/calendar/gui/eventpopup/EventPreviewView.ts]: Do we need the ```!``` on ```calendarType```?

File: src/calendar-app/calendar/search/view/CalendarSearchViewModel.ts [hunk 3]
```diff
@@ -93,20 +87,20 @@ export class CalendarSearchViewModel {
...
+				if (isBirthdayCalendarInfo(calendarInfo)) {
+					return calendarInfo.id === this._selectedCalendar
 				}
-
-				// It isn't a string, so it can be only a Calendar Info
-				const calendarValue = calendar.info
-				return isSameId([calendarValue.groupRoot.longEvents, calendarValue.groupRoot.shortEvents], this._selectedCalendar)
-			})?.info ?? null
-		)
+				if (isCalendarInfo(calendarInfo)) {
```
Comment (murilopereirame) [inline src/calendar-app/calendar/search/view/CalendarSearchViewModel.ts:98]: Do we need this if? We already know that isn't a birthday calendar

File: src/calendar-app/calendar/view/CalendarViewModel.ts [hunk 4]
```diff
@@ -227,46 +231,12 @@ export class CalendarViewModel implements EventDragHandlerCallbacks {
...
-					group: { _id: calendarID },
-					shared: false,
-					userIsOwner: true,
-				}),
-			)
-
-			if (!this.isNewPaidPlan && !this.hiddenCalendars.has(calendarID)) {
-				this._hiddenCalendars.add(calendarID)
-			}
+	get calendarColors() {
```
Comment (murilopereirame) [inline src/calendar-app/calendar/view/CalendarViewModel.ts:245]: It might be worth to put it in a memoized function, otherwise you have to rebuild the map every render cycle

**Review by murilopereirame — CHANGES_REQUESTED** [review]

File: src/calendar-app/calendar/gui/eventpopup/CalendarEventPreviewViewModel.ts (hunk 1 above)
Comment (andrehgdias) [reply src/calendar-app/calendar/gui/eventpopup/CalendarEventPreviewViewModel.ts]: missed this one

File: src/calendar-app/calendar/search/view/CalendarSearchViewModel.ts (hunk 3 above)
Comment (andrehgdias) [reply src/calendar-app/calendar/search/view/CalendarSearchViewModel.ts:98]: Not really, this was used for type guarding only...
