### PR TITLE
Change date parsing to not remove empty date parts, fix #3782

### LINKED ISSUE #3782: Web client test failures in FormatterTest (parseBirthdayGermanLocale, parseBirthdayUsLocale)
**Failures in web client tests**

**Describe the bug**

The test `parseBirthdayGermanLocale` (as well as `parseBirthdayUsLocale`) in FormatterTest fails because `DateParser.parseBirthday` does not properly return null for the input "a.4.12" ("a/4/12"). 

**To Reproduce**

Run the tests with `npm run testclient` and open the browser tests in Chromium.

**Expected behavior**
The tests cases should both pass and `DateParser.parseBirthday` should return null for both inputs.

**Additional context**
Stumbled upon these failures investigating another client bug, so they may have been there for a while. Resulted in the date "a/4/12" being valid, and the server returns it as "4/12".

### PR DESCRIPTION
**Pull request by nowhub**
`DateParser._cleanUpAndSplit` removes any characters
that cannot be dealt with, such as the char 'a'.
This results in an empty date part if a date of the form
"a/4/12", for example, is entered by a user.
`_cleanUpAndSplit` would then remove the part containing only 'a'
(zero-length) and the date would be interpreted as
month/day or day/month, depending on locale, which
resulted in unexpected dates being saved.

Instead, we cut off dates that have more than three
parts and do not remove zero-length parts, which
fixes the test failure mentioned in the issue.

### CODE REVIEW

File: src/misc/DateParser.ts [hunk 1]
```diff
@@ -179,6 +179,6 @@ export function _cleanupAndSplit(dateString: string): number[] {
 	dateString = dateString.replace(/[^ 0-9.\/-]/g, "")
 	return dateString
 		.split(/[.\/-]/g)
-		.filter(part => part.trim().length > 0)
+		.filter((part, index) => index < 3)
```
Comment (charlag) [inline src/misc/DateParser.ts:182]:
```suggestion
		.slice(0, 3)
```

also comment on why we do it here would be great

**Review by charlag — APPROVED** [review]
