### PR TITLE
Fix checkbox being misplaced when paired with a long label

### LINKED ISSUE #6309: Checkbox misplaced when paired with a long label
**Describe the bug**
The checkboxes in the sign up are misplaced when their labels are too long for the dialog. This happens to the English version of the terms & conditions checkbox in the sign up model & the German version of confirmation dialog. 

**To Reproduce**
1. Go to the 2nd stage of the sign up modal
2. See the the checkbox is misaligned

**Expected behavior**
The checkbox stays to the left of the label.

**Screenshots**
Wire 2023-12-15 at 4_15 PM
Wire 2023-12-15 at 4_15 PM-2

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version 120

**Additional context**
Brought to my attention from @kibhub via @charlag.

## Test Notes
- [ ] Check button can still be disabled
- [ ] Terms and conditions checkbox when purchasing or redeeming gift cards is styled correctly
- [ ] When a checkbox has a single word label bigger than its container, it word wraps by character
- [ ] When a checkbox has a multiple word label bigger than its container, it word wraps by word
- [ ] Checkbox still reads correctly on TalkBack (the Android screen reader) & VoiceOver (the iOS screen reader)
- [ ] External content SVG still displays correctly

### PR DESCRIPTION
**Pull request by rezbyte**
Closes #6309.

### CODE REVIEW

File: src/gui/base/Checkbox.ts [hunk 1]
```diff
@@ -25,9 +26,26 @@ export class Checkbox implements Component<CheckboxAttrs> {
 	view(vnode: Vnode<CheckboxAttrs>): Children {
 		const a = vnode.attrs
 		const helpLabel = a.helpLabel ? m("small.block.content-fg", lang.getMaybeLazy(a.helpLabel)) : []
+		const rawIcon: BootIcons = a.checked ? BootIcons.CheckboxSelected : BootIcons.Checkbox
+		const icon = BootIconsSvg[rawIcon]
```
Comment (ganthern) [inline src/gui/base/Checkbox.ts]: can we do this once instead of on every redraw?

File: src/gui/base/Checkbox.ts [hunk 2]
```diff
@@ -41,7 +42,7 @@ export class Checkbox implements Component<CheckboxAttrs> {
 				},
 			},
 			m(
-				"label.break-all",
+				`label${Checkbox.getBreakClass(a.label())}`,
```
Comment (ganthern) [inline src/gui/base/Checkbox.ts:45]: i'd much rather have this in the class property of the attrs as well instead of the selector

File: src/gui/base/Checkbox.ts [hunk 3]
```diff
@@ -82,7 +75,7 @@ export class Checkbox implements Component<CheckboxAttrs> {
 							cursor: a.disabled ? "default" : "pointer",
 							font: "inherit",
 							"background-color": theme.content_accent,
-							"mask-image": `url("data:image/svg+xml,${icon}")`,
+							"mask-image": `url("${Checkbox.getIcon(a.checked)}")`,
```
Comment (ganthern) [inline src/gui/base/Checkbox.ts:66]: can we do this once for each state instead of on every redraw?

File: src/gui/base/Checkbox.ts (hunk 2 above)
Comment (rezbyte) [reply src/gui/base/Checkbox.ts:45]: Any particular reason why? I can't find any info on the differences between using the `class` property & dynamically updating the tag. There isn't anything in the guidelines about this either. The `class` property already contains a dynamic class so the resulting code will be messy.

File: src/gui/base/Checkbox.ts (hunk 3 above)
Comment (rezbyte) [reply src/gui/base/Checkbox.ts:66]: Good idea, I'll put a commit through.

File: src/gui/base/Checkbox.ts (hunk 2 above)
Comment (ganthern) [reply src/gui/base/Checkbox.ts:47]: We've had security problems with building dynamic mithril selectors. That's really only a problem when using the attributes feature with user input, but making the selector that's capable of producing arbitrary html itself static makes it way easier to confirm at a glance that it's impossible to be causing problems. The class attribute is just used as-is without fancy parsing.

I also realize that I'm more careful than the guidelines propose and that we have tons of old code where the selector is still built on demand, so I'm ready to be told that this stance is overly cautious :D

**Review by ganthern — APPROVED** [review]

File: src/gui/base/Checkbox.ts (hunk 2 above)
Comment (rezbyte) [reply src/gui/base/Checkbox.ts:47]: Fair enough. I don't think that's unreasonably cautious given it's the same effort to put dynamic classes in the `class` property as putting it in the mithril selector. In that case, I would propose adding this to the coding guidelines. Using the `class` property instead would be a better habit to get into for the security reasons you just described.
