### PR TITLE
Fix outlook event invite description with links

### LINKED ISSUE #7814: URL removed from calendar description after being invited and editing (Outlook invite)
**Describe the bug**
User receives invitation from Outlook and the URL (Microsoft Teams call) disappears when they edit it. As a workaround, they have had to create another event for e.g. reminders.

**To Reproduce**
1. Send a calendar invitation from Outlook to a Tuta account
2. Accept it (notice the URL) 
3. Edit the event and note the description 
4, Save the event and notice the URL is gone (since it was stripped from the description)

**Expected behavior**
It's expected that the URL doesn't disappear so that users are able to open the Teams call easily.

**Additional context**
- The URLs are stripped from the description when the event editor opens, just closing the editor without saving does not affect anything. 
- Reportedly the issue was only reproduceable on Outlook.

### PR DESCRIPTION
**Pull request by andrehgdias**
Fixed Outlook event invite descriptions to preserve links after sanitization by applying the prepareCalendarDescription function
Closes #7814

### CODE REVIEW

File: src/common/api/common/utils/CommonCalendarUtils.ts [hunk 1]
```diff
@@ -180,3 +180,32 @@ export enum CalendarViewType {
...
+ *
+ * They look like this:
+ * ```
+ * text<https://example.com>
+ * ```
+ *
+ * @param description Description to clean up
+ * @param sanitizer Optional sanitizer to apply after preparing the description
+ */
+export function prepareCalendarDescription(description: string, sanitizer?: (s: string) => string): string {
```
Comment (charlag) [inline src/common/api/common/utils/CommonCalendarUtils.ts:199]: please *do not* modify HTML after sanitizing. This is a big no-no. 

To quote our coding guidelines:

>Sanitization
>
>Never modify sanitized HTML as text.
>
>Repeat after me
>
>**Never. modify. sanitized. HTML. as. text.**
>
>XSS is insidious but mXSS is even more so. mXSS is when browsers parse HTML in "creative" ways in order to make valid HTML out of invalid one so the absolutely safe but invalid HTML can get mutated by the browser (hence "m") and this can lead to security issues.
>
>Anything that isn't absolutely static should be sanitized first and not modified afterwards, if you do modify the text after sanitized all bets are off and you need to re-sanitize. Operating on the DOM is generally safer than on the text but also must be done with extreme care.
>
>m.trust should be used in very few places and very carefully.

we do have linkifyjs which we used for the same purpose but we stopped because it was breaking HTML. The guidelines above are written because we did have issues like this and more than once.

Comment (charlag) [reply src/common/api/common/utils/CommonCalendarUtils.ts:199]: My bad, I see that you do sanitize but why only sometimes? Shouldn't it always be sanitized afterwards?

Comment (andrehgdias) [reply src/common/api/common/utils/CommonCalendarUtils.ts:199]: It is not a requirement for this function specifically, you might want to do some other operation to the text before sanitizing.
I would prefer to return the text and later explicitly sanitize at the function caller, but I kept the same behavior as this function had.

Comment (andrehgdias) [reply src/common/api/common/utils/CommonCalendarUtils.ts]: Decided to make it mandatory as you mentioned :+1:
