### PR TITLE
Remove buggy workaround for old Chrome versions

### LINKED ISSUE #414: Wrong day formatting in Chrome for some dates
new Intl.DateTimeFormat("en-GB", {day: 'numeric', month: 'numeric', year: 'numeric'}).format(new Date(1919, 3, 15))
Result is "14/04/1919" although it should be "15/04/1919"
This only happens for some past years and never for the current one.

### LINKED ISSUE #3684: Leap Year Birthdays Default to 3/1/???? and not 2/29/????
**Describe the bug**
When creating a birthday for a contact on 2/29/???? the date is stored as 3/1/???? upon saving in the contact editor menu. 

**To Reproduce**
1. Go to 'Contacts"
2. Select a contact and add 2/29/???? as their birthday
3. Click on "Save

**Expected behavior**
The birthday should be stored as the leap day, rather than being moved forward.

### PR DESCRIPTION
**Pull request by nowhub**
The workaround was done to fix #414, but it failed to consider leap
years. As a result, birthdays of contacts on Feb. 29 were displayed
as Mar. 1.

The aforementioned bug does not appear to be present in recent
Chrome versions.

 fix #3684

### CODE REVIEW

File: src/contacts/model/ContactUtils.ts [hunk 1]
```diff
@@ -28,33 +28,12 @@ export function getContactListName(contact: Contact): string {
...
 export function formatBirthdayNumeric(birthday: Birthday): string {
 	if (birthday.year) {
-		//in chromimum Intl.DateTimeFormat is buggy for some dates with years the format subtracts a day from the date
-		//example date is 15.8.1911 ->format returns 14.8.1911
-		//this issue does not happen with recent years so the formatting is done with the current year then this year is changed with the original of the birthday
-		let refYear = new Date()
-		let bdayString = formatDate(new Date(refYear.getFullYear(), Number(neverNull(birthday).month) - 1, Number(neverNull(birthday).day)))
-		bdayString = bdayString.replace(/\d{4}/g, String(neverNull(birthday).year))
-		return bdayString
+		return formatDate(new Date(Number(neverNull(birthday).year), Number(neverNull(birthday).month) - 1, Number(neverNull(birthday).day)))
```
Comment (charlag) [inline src/contacts/model/ContactUtils.ts:31]: I know you didn't add it but this `neverNull` is not needed anywhere in this function

File: test/client/contact/ContactUtilsTest.ts [hunk 2]
```diff
@@ -5,149 +5,180 @@ import {createContactMailAddress} from "../../../src/api/entities/tutanota/Conta
...
+		bday.month = "7"
+		bday.year = null
+		o(formatBirthdayNumeric(bday)).equals("7/9")
+		bday = createBirthday()
+		bday.day = "12"
+		bday.month = "10"
+		bday.year = "2009"
+	})
+
+	o("formatBirthdayNumeric", () => {
```
Comment (charlag) [inline test/client/contact/ContactUtilsTest.ts:155]: We generally write case definition using `function()` instead of arrow function because ospec is using it for some state tracking (yeah...) so if you could replace this one and other in this file?

**Review by charlag — APPROVED** [review]
