### PR TITLE
[android] Fix crash when downloading cmap on invoice

### LINKED ISSUE #7160: Unknown extension .cmap
**Bug in mobile app**

**Describe the bug**
When opening a PDF invoice on android (and probably also iOS), the app crashes as the ".cmap" extension is unknown. 
".cmap" files are used to allow special font rendering inside the PDF invoices.

**To Reproduce**
1. Go to 'payment'
2. Click on 'show'
3. Click on 'download'
4. See that app crashes

**Expected behavior**
Downloading a PDF invoice is successful.

**Smartphone (please complete the following information):**
 - OS: Android 14
 - Version 234.20240627.0

**Additional context**
```
type: crash
osVersion: google/cheetah/cheetah:14/AP2A.240605.024/2024062700:user/release-keys
package: de.tutao.tutanota:396356
process: de.tutao.tutanota
processUptime: 14054 + 371 ms
installer: com.android.packageinstaller

java.lang.IllegalStateException: Unknown extension cmap for url https://assets.tutanota.com/pdf/identity_h.cmap
at de.tutao.tutanota.MainActivity.getMimeTypeForUrl(Unknown Source:142)
at de.tutao.tutanota.MainActivity.access$getMimeTypeForUrl(Unknown Source:0)
at de.tutao.tutanota.MainActivity$onCreate$2.shouldInterceptRequest(Unknown Source:216)
at WV.r5.a(chromium-TrichromeWebView6432.apk-stable-647812433:83)
at org.chromium.android_webview.AwContentsBackgroundThreadClient.shouldInterceptRequestFromNative(chromium-TrichromeWebView6432.apk-stable-647812433:15)
```

### LINKED ISSUE #7235: downloading an invoice crashes mobile app
**Bug in mobile app**

**Describe the bug**
When downloading an invoice, the app shuts down

**To Reproduce**
1. Go to Settings > Payment > Invoices & payments
2. Try to download an invoice
3. App crashes

## Test notes

- [ ] On Android, download an invoice and verify that the application does not crash. Check the device's files, and you should find the invoice present there.

### PR DESCRIPTION
**Pull request by paw-hub**
It seems we did not specify the mime type for .cmap extensions, thus downloading invoices can result in an uncaught exception.

Fixes #7235
Fixes #7160

### CODE REVIEW

File: app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt [hunk 1]
```diff
@@ -378,6 +378,7 @@ class MainActivity : FragmentActivity() {
 			"ttf" -> "font/ttf"
 			"wasm" -> "application/wasm"
 			"icc" -> "application/vnd.iccprofile"
+			"cmap" -> "application/octet-stream" // used for invoices; no good mime type for cmap, so just use octet-stream
```
Comment (charlag) [inline app-android/app/src/main/java/de/tutao/tutanota/MainActivity.kt:381]: I guess that's fine, they could also be text/plain

**Review by charlag — APPROVED** [review]
