### PR TITLE
Fix dynamic import in recovery code news

### LINKED ISSUE #4768: "Display recovery code" in news item stuck in spinner
To reproduce:

- [ ] signup a new account and login
- [ ] opt in to usage data, immediately click "display recovery code" on the recovery code news item, enter password
- [ ] observe:
Screenshot_Recovery_Code

### PR DESCRIPTION
**Pull request by nowhub**
Authored by ivk@tutao.de

fix #4768

### CODE REVIEW

File: src/misc/news/items/RecoveryCodeNews.ts [hunk 1]
```diff
@@ -61,14 +64,12 @@ export class RecoveryCodeNews implements NewsListItem {
 
 	render(newsId: NewsId): Children {
 		const recoveryCode = this.recoveryCode
+		// toggle the load if it's not started yet
+		this.recoverCodeField.getAsync()
+
+		const RecoverCodeField = this.recoverCodeField.getSync()
```
Comment (nokhub) [inline src/misc/news/items/RecoveryCodeNews.ts:70]: maybe add a comment here explaining when getSync actually returns a value that is not null.
i.e. after the dynamic import is finished and the render function is triggered again by the redraw.
but I don't have a strong opinion on this

**Review by nokhub — APPROVED** [review]
seems all good
