### PR TITLE
Change shared mailbox sender name 

### LINKED ISSUE #4845: It's not possible to change the sender name on shared mailboxes
currently, it'll use the name of the mail box and then hold on to it forever because it gets copied to the MailAddressProperties.

need to add an edit button to the mail address.

## Test Notes
create a premium account with a global admin, and two non-admin users; all three with different names.
General Note: test that the new sender name can be used in the mail editor each time it's changed.
 
* [ ] create a shared mail group with a name different from any of the user names
* [ ] add one of the non-admin users to the group.
* [ ] the mail group's sender name is initially set to the chosen mail group name
* [ ] the global admin can change the sender name if they're **not** a member of the mail group
* [ ] the global admin can change the sender name if they're a member of the mail group

now create a local admin group and add the other non-admin user to it.

* [ ] the local admin can't change the sender name of the mail group.
* [ ] it's possible to set the shared mail group to be administrated by the admin group and afterwards:
* [ ] the local admin user can change the mail groups sender name if they're **not** a member of the mail group
* [ ] the local admin user can change the mail groups sender name if they're a member of the mail group
* [ ] the global admin can still change the mail groups sender name if they're **not** a member of the mail group
* [ ] the global admin can still change the mail groups sender name if they're a member of the mail group

### Regression Tests
* [ ] all settings for local admin groups can be changed and are applied
  * name
  * members
  * administrated by
  * active/inactive
  * administrated groups
* [ ] all settings for shared mailboxes are changed and applied
  * name
  * members
  * administrated by
  * active/inactive
* [ ] retest #516

### PR DESCRIPTION
**Pull request by ganthern**
close #4845

### CODE REVIEW

File: packages/tutanota-utils/lib/ArrayUtils.ts [hunk 1]
```diff
@@ -204,7 +204,10 @@ export function lastThrow<T>(array: ReadonlyArray<T>): T {
 	return neverNull(last(array))
 }
 
-export function firstThrow<T>(array: ReadonlyArray<T>): T {
+/**
+ * get first item or throw if there is none
+ */
+export function getFirstOrThrow<T>(array: ReadonlyArray<T>): T {
```
Comment (charlag) [inline packages/tutanota-utils/lib/ArrayUtils.ts:210]: yess

File: src/settings/groups/GroupDetailsModel.ts [hunk 2]
```diff
@@ -164,6 +186,19 @@ export class GroupDetailsModel {
...
+	async changeGroupSenderName(newName: string): Promise<void> {
+		if (this.senderName.isLoaded() && this.senderName.getLoaded() === newName) return
+		const mailGroupId = await this.groupInfo.group
+		await locator.mailAddressFacade.setSenderName(mailGroupId, this.getGroupMailAddress(), newName)
+
+		// we may not be a member of the group and therefore won't necessarily receive updates
+		// for updated mailbox properties.
+		this.senderName.reset()
+		// noinspection ES6MissingAwait
+		this.senderName.getAsync()
```
Comment (charlag) [inline src/settings/groups/GroupDetailsModel.ts:198]: but if we *are* a member it will be still cached in the entity rest cache at this point, right?

File: src/settings/groups/GroupDetailsModel.ts [hunk 3]
```diff
@@ -291,7 +328,7 @@ export class GroupDetailsModel {
 
 			if (isUpdateForTypeRef(GroupInfoTypeRef, update) && operation === OperationType.UPDATE) {
 				const updatedUserGroupInfo = await this.entityClient.load(GroupInfoTypeRef, this.groupInfo._id)
-				if (isSameId(this.groupInfo._id, [neverNull(instanceListId), instanceId])) {
+				if (isSameId(this.groupInfo._id, [assertNotNull(instanceListId, "got groupInfo update without instanceListId"), instanceId])) {
```
Comment (charlag) [inline src/settings/groups/GroupDetailsModel.ts:331]: do we really need these messages? This can only happen if something goes Really Wrong

File: packages/tutanota-utils/lib/ArrayUtils.ts (hunk 1 above)
Comment (charlag) [reply packages/tutanota-utils/lib/ArrayUtils.ts:210]: but I think you already used it in the first commit with this name? :thinking:

File: src/settings/groups/GroupDetailsModel.ts [hunk 4]
```diff
@@ -0,0 +1,318 @@
...
+import {showProgressDialog} from "../../gui/dialogs/ProgressDialog.js"
+import {showBuyDialog} from "../../subscription/BuyDialog.js"
+import {locator} from "../../api/main/MainLocator.js"
+import {BadRequestError, NotAuthorizedError, PreconditionFailedError} from "../../api/common/error/RestError.js"
+import {compareGroupInfos, getGroupInfoDisplayName} from "../../api/common/utils/GroupUtils.js"
+import {EntityUpdateData, isUpdateForTypeRef} from "../../api/main/EventController.js"
+
+export class GroupDetailsModel {
+	groupInfo: GroupInfo
+	private readonly group: LazyLoaded<Group>
```
Comment (charlag) [inline src/settings/groups/GroupDetailsModel.ts:30]: I am not even sure we need to use `LazyLoaded` here still but we can keep it for now

File: src/settings/groups/GroupDetailsModel.ts [hunk 5]
```diff
@@ -0,0 +1,318 @@
...
+
+	getGroupMailAddress(): string {
+		return this.groupInfo.mailAddress ?? ""
+	}
+
+	/**
+	 * remove the group of the given groupInfo from this group
+	 */
+	removeGroupMember(userGroupInfo: GroupInfo): void {
+		showProgressDialog(
```
Comment (charlag) [inline src/settings/groups/GroupDetailsModel.ts:147]: showing dialogs from the model is generally eh

Comment (charlag) [reply src/settings/groups/GroupDetailsModel.ts:147]: also do we need to redraw afterwards

File: src/settings/groups/GroupDetailsModel.ts [hunk 6]
```diff
@@ -0,0 +1,318 @@
...
+			? BookingItemFeatureType.LocalAdminGroup
+			: BookingItemFeatureType.SharedMailGroup
+
+		const confirmed = await showBuyDialog({featureType: bookingItemType, count: deactivate ? -1 : 1, freeAmount: 0, reactivate: !deactivate})
+		if (confirmed) {
+			const group = await this.group.getAsync()
+			try {
+				return await locator.groupManagementFacade.deactivateGroup(group, !deactivate)
+			} catch (e) {
+				if (!(e instanceof PreconditionFailedError)) throw e
```
Comment (charlag) [inline src/settings/groups/GroupDetailsModel.ts:170]: same goes for these dialogs

File: src/settings/groups/GroupDetailsModel.ts [hunk 7]
```diff
@@ -0,0 +1,318 @@
...
+					return Dialog.message("emailAddressInUse_msg")
+				} else {
+					return Dialog.message("stillReferencedFromContactForm_msg")
+				}
+			}
+		}
+	}
+
+	changeGroupName(newName: string): Promise<void> {
+		const newGroupInfo: GroupInfo = Object.assign({}, this.groupInfo)
```
Comment (charlag) [inline src/settings/groups/GroupDetailsModel.ts:183]: I'd rather use `createGroupInfo()`

File: src/settings/groups/GroupDetailsModel.ts [hunk 8]
```diff
@@ -0,0 +1,318 @@
...
+	async onActivationStatusSelected(deactivate: boolean): Promise<void> {
+		const members = await this.members.getAsync()
+		if (deactivate && members.length > 0) {
+			return Dialog.message("groupNotEmpty_msg")
+		} else {
+			return showProgressDialog("pleaseWait_msg", this.showGroupBuyDialog(deactivate))
+		}
+	}
+
+	createAdministratedByInfo(): {options: SelectorItemList<Id | null>, currentVal: Id | null} | null {
```
Comment (charlag) [inline src/settings/groups/GroupDetailsModel.ts:223]: attrs don't beong here

File: src/settings/groups/GroupDetailsModel.ts [hunk 9]
```diff
@@ -0,0 +1,318 @@
...
+		return {
+			options: adminGroupIdToName,
+			currentVal: this.groupInfo.localAdmin
+		}
+	}
+
+	onAdministratedBySelected(id: Id | null): void {
+		if (this.groupInfo.groupType === GroupType.LocalAdmin) {
+			// noinspection JSIgnoredPromiseFromCall
+			Dialog.message("updateAdminshipLocalAdminGroupError_msg")
```
Comment (charlag) [inline src/settings/groups/GroupDetailsModel.ts:250]: dialog

File: src/settings/groups/GroupDetailsModel.ts [hunk 10]
```diff
@@ -0,0 +1,318 @@
...
+		} else {
+			// noinspection JSIgnoredPromiseFromCall
+			showProgressDialog(
```
Comment (charlag) [inline src/settings/groups/GroupDetailsModel.ts:253]: dialog

File: src/settings/groups/GroupDetailsView.ts [hunk 11]
```diff
@@ -0,0 +1,276 @@
...
+	 * @private
+	 */
+	private renderHeader(): Children {
+		return m(".h4.mt-l", getGroupTypeDisplayName(this.model.getGroupType()))
+	}
+
+	renderView(): Children {
+		return m("#user-viewer.fill-absolute.scroll.plr-l", [
+			this.renderHeader(),
+			...this.renderCommonInfo(),
```
Comment (charlag) [inline src/settings/groups/GroupDetailsView.ts:42]: you don't really need to spread it I think? I'd just make it return `Children` like usual and would dump it there and let Mithril flatten it. The only reason not to would be if we had keys.

File: src/settings/groups/GroupDetailsView.ts [hunk 12]
```diff
@@ -0,0 +1,276 @@
...
+			this.renderMembersTable(),
+		]
+	}
+
+	private renderCreatedTextField(): Children {
+		return m(TextField, {label: "created_label", value: formatDateWithMonth(this.model.getCreationDate()), disabled: true})
+	}
+
+	private renderAdministratedByDropdown(): Children {
+		if (!logins.getUserController().isGlobalAdmin()) return null
```
Comment (charlag) [inline src/settings/groups/GroupDetailsView.ts:72]: should prolly check via model

File: src/settings/groups/GroupDetailsView.ts [hunk 13]
```diff
@@ -0,0 +1,276 @@
...
+		const administratedByInfo = this.model.createAdministratedByInfo()
+		if (!administratedByInfo) return null
+		const {options, currentVal} = administratedByInfo
+		return m(DropDownSelector, {
+			label: "administratedBy_label",
+			items: options,
+			selectedValue: currentVal,
+			selectionChangedHandler: id => this.model.onAdministratedBySelected(id),
+		} as DropDownSelectorAttrs<Id | null>)
```
Comment (charlag) [inline src/settings/groups/GroupDetailsView.ts:81]: casting is not nice, would be good to use `satisfies` but we need to update ts for that

File: src/settings/groups/GroupDetailsView.ts [hunk 14]
```diff
@@ -0,0 +1,276 @@
...
+					value: false,
+				},
+				{
+					name: lang.get("deactivated_label"),
+					value: true,
+				},
+			],
+			selectedValue: this.model.isGroupActive(),
+			selectionChangedHandler: deactivate => this.model.onActivationStatusSelected(deactivate),
+		} as DropDownSelectorAttrs<boolean>)
```
Comment (charlag) [inline src/settings/groups/GroupDetailsView.ts:137]: casting

File: src/settings/groups/GroupDetailsView.ts [hunk 15]
```diff
@@ -0,0 +1,276 @@
...
+			m(".h5.mt-l.mb-s", lang.get("groupMembers_label")),
+			m(Table, membersTableAttrs)
+		]
+	}
+
+	private renderAdministratedGroupsTable(): Children {
+		let lines: TableLineAttrs[] = this.model.getAdministratedGroups().map(groupInfo => {
+			let removeButtonAttrs: IconButtonAttrs | null = null
+
+			if (logins.getUserController().isGlobalAdmin()) {
```
Comment (charlag) [inline src/settings/groups/GroupDetailsView.ts:250]: via model

**Review by charlag — COMMENTED** [review]
It seems to work, nice! Also a bunch of good refactorings. Normally if it would be a pure feature I wouldn't mention some things but if we are already there…

File: src/settings/groups/GroupDetailsModel.ts (hunk 2 above)
Comment (charlag) [reply src/settings/groups/GroupDetailsModel.ts:198]: I couldn't make it break but I am not sure why

File: src/settings/groups/GroupDetailsModel.ts (hunk 5 above)
Comment (ganthern) [reply src/settings/groups/GroupDetailsModel.ts]: redraw seems to not be necessary

**Review by charlag — APPROVED** [review]
