### PR TITLE
[desktop] Fix making excessive handshakes

### LINKED ISSUE #6053: Excessive handshakes in desktop client
v3.118.12

We see many cases of  users hitting "Bad Handshake Ratio" limits, especially while indexing. It seems like it could be related to using `fetch()` builtin from Node. Local testing shows that we indeed do a lot of handshakes and it seems like keepalive time is very short.

### PR DESCRIPTION
**Pull request by charlag**
fix #6053

see tutadb!527

### CODE REVIEW

File: src/desktop/net/ProtocolProxy.ts [hunk 1]
```diff
@@ -5,26 +5,46 @@ import { Session } from "electron"
...
+
+type GlobalFetch = typeof global.fetch
 
 const TAG = "[ProtocolProxy]"
 
 export const ASSET_PROTOCOL = "asset"
-const PROXIED_REQUEST_READ_TIMEOUT = 20000
+
+/** How long the socket should stay open without any data sent over it. See IDLE_TIMEOUT_MS in tutadb. */
+const SOCKET_IDLE_TIMEOUT_MS = 5 * 60 * 10_000 + 1000
```
Comment (murilopereirame) [inline src/desktop/net/ProtocolProxy.ts:17]: It's bigger than the server's IDLE_TIMEOUT, is it correct?

Comment (charlag) [reply src/desktop/net/ProtocolProxy.ts:17]: Server idle timeout might also change but yes generally we want to let the server drive this one

**Review by ganthern — APPROVED** [review]
