### PR TITLE
fix display of large event names in preview

### LINKED ISSUE #2899: long description & location overflow event popup horizontally
**Bug in web app**

**To Reproduce**
1. create an event in calendar view with very long name and/or location
2. click on it and see overflow

**Expected behavior**

**Screenshots**
overflow-calendar-chrome-win

**Environment:**
seems to be happening in all browsers & platforms

### LINKED ISSUE #2949: Create overlay for buble text field suggestions
Right now the suggestions list from the bubble text field in mail editor changes the content size of the mail editor. This leads to not very nice movement of the content when typing in the mail address. We should make a real overlay for the suggestion list and also refactor the bubble text field input to the new component style.

### PR DESCRIPTION
**Pull request by johnbotris**
We now will show up to two lines of text for the title, and any more will be scrollable.

Also, disable horizontal scrolling for the description field and use `word-wrap: break-word` instead. 

Screenshot from 2021-05-17 14-17-35

fix #2899

### CODE REVIEW

File: src/gui/main-styles.js [hunk 1]
```diff
@@ -271,6 +271,7 @@ styles.registerStyle('main', () => {
 		'.text-ellipsis': {overflow: 'hidden', 'text-overflow': 'ellipsis', 'min-width': 0, 'white-space': 'nowrap'},
 		'.min-width-0': {'min-width': 0},
 		'.text-break': {overflow: 'hidden', 'word-break': 'break-word'},
+		'.text-wrap': {overflow: 'hidden', 'word-wrap': 'break-word'},
```
Comment (charlag) [inline src/gui/main-styles.js:274]: Same as class above

**Review by charlag — APPROVED** [review]
Need to test on Safari/iOS properly

File: src/gui/main-styles.js (hunk 1 above)
Comment (charlag) [reply src/gui/main-styles.js:274]: omg I'm blind
