### PR TITLE
fix too large attachments in mailto link

### LINKED ISSUE #3376: newMailtoUrlMailEditor doesn't check the attachment size
**Bug in desktop app**

**Describe the bug**
passing a mailto url with attachments exceeding 25MB in size will cause an uncaught UserError.

**To Reproduce**
1. call the desktop client (current master) with a command line argument like mailto:?attach=/path/to/large/file.zip
2. see error after clicking "attach files"

**Expected behavior**
the "tooBigAttachment_msg" should be shown.

### PR DESCRIPTION
**Pull request by vaf-hub**
fixes #3376

### CODE REVIEW

File: src/mail/editor/MailEditor.js [hunk 1]
```diff
@@ -655,20 +662,34 @@ export async function newMailtoUrlMailEditor(mailtoUrl: string, confidential: bo
...
+			() => dataFiles.map((df, i) => m(".text-break.selectable.mt-xs", {
 				title: attach[i]
-			}, df.name)).filter(Boolean)
+			}, df.name))
 		)
 
-		dataFiles = keepAttachments
-			? dataFiles.filter(Boolean)
-			: []
+		const acceptedDataFiles = []
```
Comment (johnbotris) [inline src/mail/editor/MailEditor.js:676]: we should put this in a function instead of copy pasting. Also, imo we should just not attach anything if the total size is too large, maybe we should do this in `SendMailModel` as well. I think it makes more sense for the user to choose which files to discard rather than arbitrarily discarding them ourselves

**Review by johnbotris — CHANGES_REQUESTED** [review]

File: src/mail/editor/MailEditor.js (hunk 1 above)
Comment (vaf-hub) [reply src/mail/editor/MailEditor.js]: I put the code in a function and use it in all three places (also in `ContactFormRequestDialog`). I am not sure I want to change the behavior of how files are attached or discarded in this bug fix. I suggest you open a new issue tagged as improvement in case you want to further discuss such a change.

**Review by johnbotris — COMMENTED** [review]
Looks good, except: I feel like if there total size of attachements is too large we should just not attach anything and let the user decide. I know it was already done this way but to me it feels arbitrary and unnecessary?

**Comment by vaf-hub** [comment]
I agree, that it's arbitrary. I am not sure if it is better not to attach anything than attaching all files that are small enough. Ideally, we would let the user decide which files to attach. As I mentioned, though, I think we should open a new issue for that.
I see two options. One idea I have is the following: Allow attach all files but somehow indicate in the MailEditor how large an attachment is and that the overall attachment size is too large. (Saving or sending should open an error dialog and force the user to remove attachments or have all attachments removed automatically).

**Comment by johnbotris** [comment]
Ok then, this looks good to go

**Review by johnbotris — APPROVED** [review]
