### PR TITLE
Save restriction states of different search types

### LINKED ISSUE #6627: Repeatedly Switching Between Search Types Results in Incorrect Views Being Displayed
**Describe the bug**

**To Reproduce**
1. Search Mails or Contacts
2. Switch to another type
3. Switch back to first type
4. 3rd column switches to correct type, but 1st and second will not (for example if going Contacts -> Mail, the date and others filters are not there)

**Expected behavior**
The correct search type will be shown.

## Test Notes
Test on desktop and mobile
- [ ] Switching between Mail, Contact, and Calendar search types will show the appropriate filters in the first column, and results (including the no results icon) 
- [ ] When switching between Mail, Contact, and Calendar search types filter setting are preserved

### PR DESCRIPTION
**Pull request by wrdhub**
close #6627

### CODE REVIEW

File: src/search/view/SearchView.ts [hunk 1]
```diff
@@ -151,7 +151,10 @@ export class SearchView extends BaseTopLevelView implements TopLevelView<SearchV
 										m(NavButton, {
 											label: "emails_label",
 											icon: () => BootIcons.Mail,
-											href: () => "/search/mail",
+											href: "#",
+											click: async () => {
```
Comment (charlag) [inline src/search/view/SearchView.ts:155]: nitpick: I am usually against making `click` or any event handlers async because it confuses people with what it does or does not.

Since you are calling an async function anyway I'd propose to just drop those async/await qualifiers

File: src/search/view/SearchView.ts [hunk 2]
```diff
@@ -232,6 +243,27 @@ export class SearchView extends BaseTopLevelView implements TopLevelView<SearchV
 		this.viewSlider = new ViewSlider([this.folderColumn, this.resultListColumn, this.resultDetailsColumn])
 	}
 
+	private async routeToType(type: string): Promise<void> {
```
Comment (charlag) [inline src/search/view/SearchView.ts:246]: `type` can be more specific

File: src/search/view/SearchView.ts [hunk 3]
```diff
@@ -232,6 +243,27 @@ export class SearchView extends BaseTopLevelView implements TopLevelView<SearchV
...
+		let latestRestriction = null
+		// contacts do not have restrictions at this time
+		if (type === "mail") {
```
Comment (charlag) [inline src/search/view/SearchView.ts:249]: if `type` is a more narrow type you could  `switch` on all 3 cases here to make sure we don't forget to add more in the future

File: src/search/view/SearchView.ts [hunk 4]
```diff
@@ -232,6 +243,27 @@ export class SearchView extends BaseTopLevelView implements TopLevelView<SearchV
...
+			latestRestriction = this.searchViewModel.latestMailRestriction
+		} else if (type === "calendar") {
+			latestRestriction = this.searchViewModel.latestCalendarRestriction
+		}
+		const searchRouter = await locator.scopedSearchRouter()
```
Comment (charlag) [inline src/search/view/SearchView.ts:254]: it looks like you don't need the router anymore

File: src/search/view/SearchView.ts [hunk 5]
```diff
@@ -232,6 +243,27 @@ export class SearchView extends BaseTopLevelView implements TopLevelView<SearchV
...
+		if (this.searchViewModel.currentQuery) {
```
Comment (charlag) [inline src/search/view/SearchView.ts:255]: I think this logic should be in the viewModel. To have more than one `if` is already a lot for the poor, busy view. There are other signs too e.g. that you need to expose latest restriction and router. Instead I'd create a method like `switchToSearchType()` or something like that. We might still need to call viewSlider here though

File: src/search/model/SearchUtils.ts [hunk 6]
```diff
@@ -26,17 +26,23 @@ assertMainOrNode()
 
 const FIXED_FREE_SEARCH_DAYS = 28
 
+export const enum SearchCategoryTypes {
```
Comment (charlag) [inline src/search/model/SearchUtils.ts:29]: we should probably put on our coding guidelines how we name enums (like single vs plural)

**Review by charlag — APPROVED** [review]
