### PR TITLE
Fix toolbar actions for sticky mail 

### LINKED ISSUE #8775: Cannot trash or move mails opened from notification using the actions bar
Trashing or moving a mail (using the actions bar) that was opened from a notification that was received while the app was closed does nothing.
This happens on both mobile and desktop.

**Steps to reproduce:**
- Make sure the app is closed.
- Receive an email.
- Open the newly received email from notification.
- Using the actions bar, see that trashing the mail does nothing. And that move action does not open the move targets dropdown.

After a bit of investigation, it appears this happens because `listModel.getSelectedAsArray` returns an empty array at this point (https://github.com/tutao/tutanota/blob/3dbb592c5b289ebf7ac1e7f7cedd07da090ae64a/src/mail-app/mail/view/MailViewModel.ts#L349). This results in `actionableMails` being an empty array (https://github.com/tutao/tutanota/blob/3dbb592c5b289ebf7ac1e7f7cedd07da090ae64a/src/mail-app/mail/view/MailView.ts#L1029)

**Time spent: 4h**

**Test Notes**
- [ ] With the app closed, receive a mail notification.
- [ ] Open the newly received mail using the notification.
- [ ] Using the actions toolbar
  - [ ] Able to mark as Read/Unread
  - [ ] Able to export.
  - [ ] Able to move to different folder
  - [ ] Able to trash.
  - [ ] Assign labels.
- [ ] Works with conversation view enabled.
- [ ] Works with conversation view disabled (single mail view mode).

### PR DESCRIPTION
**Pull request by BijinDev**
When opening a mail from a notification, some of the toolbar actions are either noOp or not available. This is because we open the mail as a sticky mail independently of the list state, resulting in selected mails and subsequently actionable mails being an empty array. Therefore, actions will either be hidden or do nothing.

Fixed by using conversation mails (primary mail when conversation view is disabled) as actionable mails.

Close #8775

### CODE REVIEW

File: src/mail-app/mail/view/ConversationViewModel.ts [hunk 1]
```diff
@@ -302,7 +302,14 @@ export class ConversationViewModel {
 		return isOfTypeOrSubfolderOf(folders, mailFolder, MailSetKind.TRASH)
 	}
 
-	conversationItems(): ReadonlyArray<ConversationItem> {
+	readonly conversationMails: () => readonly Mail[] = memoizedWithHiddenArgument(
```
Comment (charlag) [inline src/mail-app/mail/view/ConversationViewModel.ts:305]: I'm not sure if it's a good idea to memoize like this, mail instance on `viewModel` might get updated, in this ViewModel we only react to `ConversationEntry` updates and the rest is inside the `MailViewerViewModel`. If we memoize base on items we will memoize outdated mails

File: src/mail-app/mail/view/MailView.ts [hunk 2]
```diff
@@ -500,12 +500,14 @@ export class MailView extends BaseTopLevelView implements TopLevelView<MailViewA
 	}
 
 	private getSetUnreadStateAction(): ((unread: boolean) => void) | null {
-		const mails = this.mailViewModel.listModel?.getSelectedAsArray() ?? []
-		if (isEmpty(mails) || (mails.length === 1 && isDraft(getFirstOrThrow(mails)))) {
+		const conversationMails = this.conversationViewModel?.conversationMails()
```
Comment (charlag) [inline src/mail-app/mail/view/MailView.ts:503]: it gets pretty complicated, is there any way we can shove it into ViewModel? same goes for other changes in this file
