### PR TITLE
Fix not seeing some calendar event updates in calendar

### LINKED ISSUE #6365: Long events in the next month aren't displayed
**Describe the bug**
When the user have an long event that have some part in the next month, sometime it isn't displayed correctly, showing only the current month part.

**To Reproduce**
1. As the OWNER of a calendar, shares it with a GUEST;
2. As the GUEST accept the calendar sharing invite;
3. As the OWNER add an all day event from 25.12.2023 to 05.01.2024;
4. As the GUEST see that the calendar render just the December part of the event.

**Expected behavior**
The event is rendered correctly in both months

**Screenshots**

 - Version 3.118.27/3.119.3

## Test notes
 - [ ] Try to reproduce the issue
 - [ ] Try adding/removing events from another client and see that the changes are reflected on the current client

### PR DESCRIPTION
**Pull request by charlag**
fix #6365

### CODE REVIEW

File: src/calendar/view/CalendarViewModel.ts [hunk 1]
```diff
@@ -59,15 +59,16 @@ export class CalendarViewModel implements EventDragHandlerCallbacks {
 	 */
 	private previewedEvent: { event: CalendarEvent; model: CalendarEventPreviewViewModel | null } | null = null
 
-	_hiddenCalendars: Set<Id>
-	// Events that have been dropped but still need to be rendered as temporary while waiting for entity updates.
+	private _hiddenCalendars: Set<Id>
+	/** Events that have been dropped but still need to be rendered as temporary while waiting for entity updates. */
+	// visible for tests
```
Comment (rezbyte) [inline src/calendar/view/CalendarViewModel.ts:64]: It is bad practice to test using private member variables. Tests should only care about whether the code returns what is expected of it based on the codes specification. Private member variables are solely an implementation detail.

For example, assert on `temporaryEvents()` instead of `_draggedEvent.eventClone` & `_transientEvents`.
Use:
```ts
o(viewModel.temporaryEvents).deepEquals([])
```
Instead of:
```ts
o(viewModel._draggedEvent?.eventClone).equals(undefined)
o(viewModel._transientEvents).deepEquals([])
```

Comment (charlag) [reply src/calendar/view/CalendarViewModel.ts:64]: I am mostly with you on this but I have not introduced it nor gonna change it in this PR,  I just  wanted to document it

**Review by rezbyte — APPROVED** [review]
Works like a charm! :+1:  I do like the cleanups too. Perhaps, also consider cleaning up the tests for `CalendarViewModel` as we discussed?

File: src/calendar/view/CalendarViewModel.ts (hunk 1 above)
Comment (charlag) [reply src/calendar/view/CalendarViewModel.ts:64]: I had another look at it and I confirm once again that in many cases it's not a simple mechanical change and to test it without resorting to grabbing private fields would either need a separate component or some other kind of refactoring that's out of scope. In general I would also say that it's testing the wrong thing if it's checking internal state of multiple fields (who cares about it on the outside?). If you insist on changing this I would suggest making a technical task and scheduling it.

Comment (rezbyte) [reply src/calendar/view/CalendarViewModel.ts:64]: Thanks for taking a look into it. In that case, we can leave it for now. I agree with you completely about asserting on internal state. We could create a technical task to review whether our tests are appropriate for the level they are on.
