### PR TITLE
Fix deactivating desktop integration

### LINKED ISSUE #2896: Can't disable desktop intergration
trying to disable desktop integration causes an error, at least in linux:

Screenshot from 2021-04-01 09-07-11

activating it seems to work fine

### PR DESCRIPTION
**Pull request by johnbotris**
fix #2896

### CODE REVIEW

**Review by charlag — APPROVED** [review]

File: test/client/desktop/integration/DesktopIntegratorTest.js [hunk 1]
```diff
@@ -276,9 +276,9 @@ o.spec("DesktopIntegrator Test", () => {
 			const integrator = new DesktopIntegrator(electronMock, fsExtraMock, cpMock, () => Promise.resolve({default: winregMock}))
 
 			await integrator.disableAutoLaunch()
-			o(fsExtraMock.unlink.callCount).equals(1)
-			o(fsExtraMock.unlink.args.length).equals(1)
-			o(fsExtraMock.unlink.args[0]).equals('/app/path/file/.config/autostart/appName.desktop')
+			o(fsExtraMock.promises.unlink.callCount).equals(1)
```
Comment (charlag) [inline test/client/desktop/integration/DesktopIntegratorTest.js:279]: If it's fs.promises why our unlink still has cb?

Comment (charlag) [reply test/client/desktop/integration/DesktopIntegratorTest.js:279]: It doesn't return promise if there is a callback

**Review by charlag — APPROVED** [review]
