### PR TITLE
Fix the login table being unreadable on small screens

### LINKED ISSUE #1497: Settings > Login page is not usable in small screen
I have a 14 inch laptop with 1280x720@1.5 resolution. This is the screenshot of the Settings > Login page:

image

In settings pages, the right half part is totally empty, while the left side is crowded. Here is no way to manually change column width. The names of session devices are unreadable.

## Test Notes
- [ ] The active sessions table remains readable when viewed 
  - [ ] with a small window
  - [ ] on mobile
  - [ ] with a medium window (iPad)
  - [ ] with a large window (desktop)
 - [ ] When clicking or tapping on a row in the table, an information dialog appears

### PR DESCRIPTION
**Pull request by rezbyte**
This PR makes the Active Sessions table use the cells style instead of multiple headers to improve readability on smaller screens.
Screenshot from 2023-12-19 14-08-01

Closes #1497.

### CODE REVIEW

**Comment by charlag** [comment]
I am not sure if that's the right approach, I think I would check in with @bedhub .
I think it is hard to discover that it's scrollable, you might miss that there's a "close" button.

I would propose to re-structure it into multiline solution but again, check in with @bedhub

**Comment by rezbyte** [comment]
I had a chat with @bedhub today & we have decided to use the cell styling of the table as used in the rejected senders table instead of scrolling. We should also look at using this style for the rest of the tables in the future.

**Review by ganthern — APPROVED** [review]

File: src/settings/login/LoginSettingsViewer.ts [hunk 1]
```diff
@@ -218,19 +219,24 @@ export class LoginSettingsViewer implements UpdatableSettingsViewer {
...
 					return {
-						cells: [
-							thisSession ? lang.get("thisClient_label") : session.clientIdentifier,
-							formatDateTimeFromYesterdayOn(session.lastAccessTime),
-							session.loginIpAddress ? session.loginIpAddress : "",
+						cells: () => [
+							{
+								main: thisSession ? lang.get("thisClient_label") : session.clientIdentifier,
+								info: [
+									`${lang.get("lastAccess_label")}: ${formatDateTimeFromYesterdayOn(session.lastAccessTime)}`,
```
Comment (ganthern) [inline src/settings/login/LoginSettingsViewer.ts:235]: we should make this a key with a parameter

Comment (rezbyte) [reply src/settings/login/LoginSettingsViewer.ts:235]: Here's a screenshot in Hebrew (an RTL language):
Screenshot from 2023-12-20 08-38-25(1)
It renders fine. If you like I can still change it to a key with a parameter if you can provide an example of this.

Comment (charlag) [reply src/settings/login/LoginSettingsViewer.ts:235]: I would also chime in that it should be a proper translation key

Comment (ganthern) [reply src/settings/login/LoginSettingsViewer.ts:235]: > It renders fine. If you like I can still change it to a key with a parameter if you can provide an example of this.

`createActionStatus_msg` is one that has two parameters. It's used like this:

https://github.com/tutao/tutanota/blob/2939aa9f4356f0dc9f523ee5ce19d09e08ab979b/src/settings/ImportUsersViewer.ts#L141-L149

In this case, it would probably be something like 
"Last Access: {time}" and the translators can then do whatever, knowing that the `{time}` part will be replaced with a formatted datetime string.

Comment (rezbyte) [reply src/settings/login/LoginSettingsViewer.ts:235]: Thanks, I'll replace with a key now.

**Comment by charlag** [comment]
Did you add the translation key to Phrase staging project?

**Comment by rezbyte** [comment]
> Did you add the translation key to Phrase staging project?

Not yet. I can't find anything on how to access nor use Phrase. Nothing in the docs, not even a web search shows anything useful.

**Comment by rezbyte** [comment]
I have added the key to the staging project now.

**Review by charlag — APPROVED** [review]
