### PR TITLE
Fix cannot set offline range more than 20 years from settings

### LINKED ISSUE #10673: Cannot set offline range date more than 20 years from settings
**Steps to reproduce:**
- Navigate to `Settings > Email > Local data storage`
- Attempt to set the date beyond 20 years in the past
- See that it isn't possible with the message `Invalid Date`
- Navigate to Search View ,set the search start date beyond 20 years in the past, and wait for indexing to finish
- Navigate back to `Settings > Email > Local data storage` and see new date is reflected there

**App Version: 340.260326.1**

### PR DESCRIPTION
**Pull request by BijinDev**
Fixed by setting the maximum extending range to Epoch instead of 20 years in both `mail settings` view and in `search list filter` view

Close #10673

Co-authored-by: hrb-hub <hrb-hub@users.noreply.github.com>

### CODE REVIEW

File: src/common/offline/OfflineStorageSettingsModel.ts [hunk 1]
```diff
@@ -53,8 +53,8 @@ export class OfflineStorageSettingsModel {
 		// The choice of 7500 days (a bit over 20 years) is a bit arbitrary.
```
Comment (wrdhub) [inline src/common/offline/OfflineStorageSettingsModel.ts]: This comment is now obsolete, please update it

**Review by wrdhub — CHANGES_REQUESTED** [review]

File: src/calendar-app/calendar/gui/pickers/DatePickerDialog.ts [hunk 2]
```diff
@@ -60,7 +60,8 @@ export function showDateRangeSelectionDialog({
 								date: startDate ?? undefined,
 								onDateSelected: (date) => {
 									warning = null
-									startDate = date
+									//the maximum user can extend range is till Epoch
+									startDate = date.getTime() < FULL_INDEXED_TIMESTAMP ? new Date(FULL_INDEXED_TIMESTAMP) : date
```
Comment (hrb-hub) [inline src/calendar-app/calendar/gui/pickers/DatePickerDialog.ts]: I'm probably missing something, but I'm not sure we want to generally restrict the date picker, and if we do want to restrict the date picker to not go beyond Epoch, we should probably just use `0` instead of `FULL_INDEXED_TIMESTAMP` since I don't think indexing is relevant to the general date picker.

File: src/common/offline/OfflineStorageSettingsModel.ts [hunk 3]
```diff
@@ -50,11 +50,9 @@ export class OfflineStorageSettingsModel {
 	}
 
 	isValidDate(newDate: Date): boolean {
-		// The choice of 7500 days (a bit over 20 years) is a bit arbitrary.
-		// The theoretical maximum is the number of days between Epoch and May 15th 2109, exceeding that will
-		// lead to an overflow in our 42 bit timestamp in the id.
-		const now = new Date().getTime()
-		return newDate.getTime() < now && now - newDate.getTime() < 7500 * DAY_IN_MILLIS
+		//set the maximum user can extend range is till Epoch
```
Comment (hrb-hub) [inline src/common/offline/OfflineStorageSettingsModel.ts]: While the first part of the comment is obsolete, I think we should still keep the second part as it explains why the range is as it is, though the wording might need changing a bit, something like:
`For a date to be valid, it must be between Epoch and May 15th 2109, exceeding that will lead to an overflow in our 42 bit timestamp in the id.`

File: src/mail-app/search/view/SearchViewModel.ts [hunk 4]
```diff
@@ -504,9 +504,11 @@ export class SearchViewModel {
 					if (offlineRange > newState.currentMailIndexTimestamp || isIndexingDoneOrCancelled) {
 						this.offlineStorageSettings.setTimeRange(
 							new Date(
-								newState.currentMailIndexTimestamp === FULL_INDEXED_TIMESTAMP
-									? newState.aimedMailIndexTimestamp
-									: newState.currentMailIndexTimestamp,
+								newState.currentMailIndexTimestamp !== FULL_INDEXED_TIMESTAMP
```
Comment (hrb-hub) [inline src/mail-app/search/view/SearchViewModel.ts:500]: I think this maybe needs a comment 😅

File: src/calendar-app/calendar/gui/pickers/DatePickerDialog.ts (hunk 2 above)
Comment (BijinDev) [reply src/calendar-app/calendar/gui/pickers/DatePickerDialog.ts]: otherwise it is possible to set the `from date` beyond Epoch in search filter

Comment (BijinDev) [reply src/calendar-app/calendar/gui/pickers/DatePickerDialog.ts]: `FULL_INDEXED_TIMESTAMP` is changed to `GENERATED_ID_MIN_TIMESTAMP` which is 0

Comment (hrb-hub) [reply src/calendar-app/calendar/gui/pickers/DatePickerDialog.ts]: `FULL_INDEXED_TIMESTAMP` is only for mail indexing, or do we also want to restrict calendar search?

**Review by hrb-hub — APPROVED** [review]

**Review by wrdhub — APPROVED** [review]
