### PR TITLE
[android] fix opening notifications when app is not already running

### LINKED ISSUE #3724: Opening mail from notification not working
Seems like opening a mail from a notification has broken

_Originally posted by @johnbotris in https://github.com/tutao/tutanota/issues/3610#issuecomment-989012396_

### PR DESCRIPTION
**Pull request by johnbotris**
fixes #3724

### CODE REVIEW

File: src/native/main/NativeInterfaceMain.js [hunk 1]
```diff
@@ -57,14 +57,14 @@ class DesktopTransport implements Transport<NativeRequestType, JsRequestType> {
...
 export class NativeInterfaceMain implements NativeInterface {
 
-	_queueDeferred: DeferredObject<Queue<NativeRequestType, JsRequestType>> = defer();
-	+_queue: Promise<Queue<NativeRequestType, JsRequestType>>
-	_appUpdateListener: ?() => void
+	+_queueDeferred: DeferredObject<Queue<NativeRequestType, JsRequestType>> = defer();
 
-	constructor() {
-		this._queue = this._queueDeferred.promise
+	get _queue(): Promise<Queue<NativeRequestType, JsRequestType>> {
```
Comment (charlag) [inline src/native/main/NativeInterfaceMain.js:62]: We use it like once, do we need it?

File: src/app.js [hunk 2]
```diff
@@ -267,6 +268,10 @@ import("./translations/en").then((en) => lang.init(en.default)).then(async () =>
 	// see https://github.com/MithrilJS/mithril.js/issues/2659
 	m.route.prefix = neverNull(state.prefix).replace(/(?:%[a-f89][a-f0-9])+/gim, decodeURIComponent)
 
+	if (isApp() || isDesktop()) {
```
Comment (charlag) [inline src/app.js:271]: I would prefer if we:
 - described here why it should be here
 - described in the commit why it wasn't working

File: src/native/main/NativeInterfaceMain.js (hunk 1 above)
Comment (johnbotris) [reply src/native/main/NativeInterfaceMain.js:62]: maybe, maybe not

**Review by charlag — APPROVED** [review]
