### PR TITLE
8844 delete dialog when nothing selected

### LINKED ISSUE #8844: Permanent delete confirmation dialog appears even when nothing is selected
**Steps to reproduce**
- Navigate to either a mail folder that allows permanent delete (Trash or Spam), or contacts.
- Using a keyboard and with nothing selected, press the `Del` key.
- See that the permanent delete confirmation dialogue appears.

**Expected behavior**
When nothing is selected, pressing the delete key does nothing.

## Test Notes
- [ ] Login to "bedpremium@tutanota.de". Search "Tuta" in email
    - [ ] Press 'Del' key without selecting or opening emails. 
    - [ ] No dialogues appear with "You have selected emails from the trash folder, they will be permanently deleted."
    - [ ] Select an email and press 'Del' key. 
    - [ ] Mail got deleted if it not in trash, if it is in trash confirmation dialogue will appear.
- [ ] Search "Bed" in contacts
    - [ ] Press 'Del' key without selecting contact. 
    - [ ] No dialogues appear with " Are you sure you want to delete the selected contact(s)?"
    - [ ] Select a contact and press 'Del' key. 
    - [ ] confirmation dialogue will appear.

### PR DESCRIPTION
**Pull request by BijinDev**
close #8844

### CODE REVIEW

File: src/mail-app/contacts/view/ContactView.ts [hunk 1]
```diff
@@ -821,8 +821,12 @@ export class ContactView extends BaseTopLevelView implements TopLevelView<Contac
 		}
 	}
 
-	private deleteSelectedContacts(): Promise<void> {
-		return deleteContacts(this.getSelectedContacts(), () => this.contactViewModel.listModel.selectNone())
+	private deleteSelectedContacts() {
+		const selectedContacts = this.getSelectedContacts()
+		if (isNotEmpty(selectedContacts)) {
+			return deleteContacts(this.getSelectedContacts(), () => this.contactViewModel.listModel.selectNone())
```
Comment (hrb-hub) [inline src/mail-app/contacts/view/ContactView.ts:827]: Nit: Can also use `selectedContacts` instead of `this.getSelectedContacts` here :)
