### PR TITLE
Fix keyboard navigation inside dialogs stuck at disabled elements

### LINKED ISSUE #7834: Keyboard navigation inside dialogs stuck at disabled elements
### Test notes
- [ ] Navigation using TAB key works as expected inside dialogs with disabled elements
    - [ ] Disabled elements are skipped

### PR DESCRIPTION
**Pull request by andrehgdias**
Closes #7834

### CODE REVIEW

File: src/common/misc/KeyManager.ts [hunk 1]
```diff
@@ -79,10 +79,19 @@ export interface Shortcut {
 	help: TranslationKey
 }
 
+function isFocusable(e: HTMLElement) {
```
Comment (charlag) [inline src/common/misc/KeyManager.ts:82]: adopted from https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/
