### PR TITLE
remove old Component type, separate f1 help gui from keymanager

### LINKED ISSUE #3225: 1-3 keys for switching between calendar views do not work
They are listed in the code but they are not in F1 help and do not work.

### PR DESCRIPTION
**Pull request by ganthern**
makes sure that lifecycle methods on mithril component classes don't return promises to make issues like #3225 less likely
 
lifecycle methods passed to m on plain objects are not checked yet

### CODE REVIEW

**Comment by vitoreiji** [comment]
A simpler fix would be the same fix as for #3249, which is not loading the customer at all to register shortcuts. But this PR does include some nice code improvements which would be a shame not to incorporate.

I'm not sure if we want to keep the batch queueing though, since we don't need it if not loading the customer and I can't think of a case where we will need it.

@bedhub and I also tested it, and it turns out that if we introduce a delay just before unregistering shortcuts, then the bug is back, so this is not fixed by the queueing itself, but rather it was fixed most likely by coincidence. If the async operation needed for the shortcuts took a bit longer, the bug would still manifest itself.

It would be great to apply the other improvements, though.

**Comment by ganthern** [comment]
> it was fixed most likely by coincidence.

yeah, I can see that - the problem is not prevented by allowing shortcut promises if you can await them before passing them to the keymanager.

File: src/gui/dialogs/ShortcutDialog.js [hunk 1]
```diff
@@ -0,0 +1,67 @@
...
+import {lang} from "../../misc/LanguageViewModel"
+import m from "mithril"
+import stream from "mithril/stream/stream.js"
+import {Dialog} from "../base/Dialog"
+import {Keys} from "../../api/common/TutanotaConstants"
+import {TextFieldN} from "../base/TextFieldN"
+import type {Shortcut} from "../../misc/KeyManager"
+import {ButtonType} from "../base/ButtonN"
+
+let isOpen = false
```
Comment (johnbotris) [inline src/gui/dialogs/ShortcutDialog.js:12]: I would prefer if this was being tracked in the `KeyManager` rather than globally here, but also maybe YAGNI?

File: src/misc/KeyManager.js [hunk 2]
```diff
@@ -99,114 +119,106 @@ class KeyManager {
...
-			       }).addShortcut({
-				       key: Keys.ESC,
-				       exec: () => neverNull(this._helpDialog).close(),
-				       help: "close_alt"
-			       }).show()
-		       })
+		// first, decide if we're showing the modal shortcuts or the standard shortcuts
+		// the help dialog will register its own shortcuts which would override the
+		// standard shortcuts if we did this lazily
+		this._showModalShortcuts = this._modalShortcuts.length > 1
```
Comment (johnbotris) [inline src/misc/KeyManager.js:158]: Why do we do this here? In `_handleBatch` we check the value of `_showModalShortcuts`, then we set `_dialogAttrs` accordingly. Can we not just check `_modalShortcuts.length` in `_handleBatch` and handle it there?

File: src/misc/KeyManager.js [hunk 3]
```diff
@@ -83,12 +81,34 @@ export function focusNext(dom: HTMLElement): boolean {
...
 }
 
+type ShortcutOperation
+	= "register"
+	| "unregister"
+	| "registerModal"
+	| "unregisterModal"
+	| "registerDesktop"
+
+type ShortcutBatch = {
```
Comment (johnbotris) [inline src/misc/KeyManager.js:91]: Is this worth keeping if the original bug has been fixed? Will it help us avoid similar issues in the future, or should we just revert it?

**Review by johnbotris — CHANGES_REQUESTED** [review]
It would be better if we tracked `isOpen` inside of the keymanager, rather than globally in `ShortcutDialog`

File: src/misc/KeyManager.js (hunk 2 above)
Comment (ganthern) [reply src/misc/KeyManager.js]: added a better explanation

File: flow/libs.js [hunk 4]
```diff
@@ -38,10 +38,10 @@ type Attrs = $ReadOnly<{[?string]: any}>
 
 declare interface Mithril {
 	// We would like to write a definition which allows omitting Attrs if all keys are optional
-	(component: string | Component | MComponent<void> | Class<MComponent<void>>, children?: Children): Vnode<any>;
+	(component: string | MComponent<any> | Class<MComponent<any>>, children?: Children): Vnode<any>;
```
Comment (charlag) [inline flow/libs.js:41]: You replaced `void` with any `here`. The idea was that you cannot render a component without attrs, if it needs any
