### PR TITLE
Fix email replaced signup 4630

### LINKED ISSUE #4630: loginView doesn't respect newAccountData (login form doesn't get prepopulated after signup)
**Bug in web app**

**Describe the bug**
After signing up, the new mail address doesn't get prepopulated in the login form, instead an empty form is shown.

**To Reproduce**
1. Sign up via the link on the login page
2. see that, after signup completion, the client shows the login form
3. the mail address field is empty

**Expected behavior**
since the signup view explicitly passes the new account data to the login view with `m.route.set`, we should use it.

## Test Notes
* [ ] test in Firefox, Chrome, iOS app
* [ ] create a new account and make sure that the mail address field is prefilled with the just created mail address
* [ ] make sure that the password field is preselected
* [ ] reloading the tab should result in the same outcome
* [ ] when the email address field already contains some input, this content is replaced after new signup

### Regressions
* [ ] credentials that are stored in the browser or operating system can still be used for autofill on all platforms (especially iOS - app and browser)
* [ ] Switching between stored credentials menu and login form works (also functional wise)
* [ ] external login works in e.g. chrome

### LINKED ISSUE #5086: input in the login field is not replaced with the new mail address after signup
small problem with the fix for #4630

1. enter something in the login form email address field
2. open the signup form and close it again -> the inputs content was removed and noAutoLogin=true is set in the URL
3. enter something in the field again
4. start sign up again without reloading the page -> this time, content is retained behind the dialog
5. complete sign up for any mail address
6. the input in the form is not replaced with the new accounts address and the password field is selected

any input in the field should be replaced by the new accounts mail address after signup

## Regression Tests
* [ ] check that autofill still works on ios, android, chrome and firefox
* [ ] check that the behaviour for tapping a notification when the app is closed is still the same as for 3.108.12 in android & ios

### PR DESCRIPTION
**Pull request by nokhub**
fix #5086

### CODE REVIEW

File: src/login/LoginView.ts [hunk 1]
```diff
@@ -366,13 +366,13 @@ export class LoginView extends BaseTopLevelView implements TopLevelView<LoginVie
...
 		}
 
-		this.viewModel.mailAddress(args.loginWith ?? "")
-
-		this.viewModel.password("")
-
 		// We want to focus password field if login field is already filled in
 		if (args.loginWith) {
 			this.loginForm.promise.then((loginForm: LoginForm) => {
+				loginForm.mailAddressTextField.value = ""
```
Comment (ganthern) [inline src/login/LoginView.ts:372]: we need to think/test if there's a way for this to interfere with any autofill

**Review by ganthern — APPROVED** [review]
