### PR TITLE
Fix entity rest cache loadRange

### LINKED ISSUE #3928: Not all users load when first navigating to user management
* Login
* Switch to the user management section
* Not all of the users are loaded
* Go to a different view and then back to user management
* All the users are now loaded

I was able to reproduce on one of my  test system accounts. The global admin user shows initially, but all other only show after the second load

### PR DESCRIPTION
**Pull request by johnbotris**
fix #3928

### CODE REVIEW

File: src/api/worker/rest/EntityRestCache.ts [hunk 1]
```diff
@@ -255,110 +243,186 @@ export class EntityRestCache implements IEntityRestCache {
...
+		while (true) {
+			const range = assertNotNull(await this.storage.getRangeForList(typeRef, listId))
+
+			// Which end of the range to start loading from
+			const loadStartId = reverse
+				? range.lower
+				: range.upper
+
+			// Load some entities
+			const entities = await this.entityRestClient.loadRange(typeRef, listId, loadStartId, count, reverse)
```
Comment (charlag) [inline src/api/worker/rest/EntityRestCache.ts:344]: We can actually be smarter here and load more than count if it makes sense. Otherwise this might lead to a situation where you want to load 1 element far outside of range and we will keep loading in small chunks.

I don't think it's absolutely necessary now but it can absolutely happen.

Maybe easy solution would be to do something like `Math.max(count, DEFAULT_CHUNK_SIZE)`

File: src/api/worker/rest/EntityRestCache.ts [hunk 2]
```diff
@@ -255,110 +243,186 @@ export class EntityRestCache implements IEntityRestCache {
...
 
-					const loadStartId = reverse
-						? range.upper
-						: range.lower
+			const loadStartId = reverse
+				? range.upper
+				: range.lower
 
-					const entities = await this.entityRestClient.loadRange(typeRef, listId, loadStartId, count, !reverse)
+			const entities = await this.entityRestClient.loadRange(typeRef, listId, loadStartId, count, !reverse)
```
Comment (charlag) [inline src/api/worker/rest/EntityRestCache.ts:381]: Same situation with `count` applies here

File: src/api/worker/rest/EntityRestCache.ts [hunk 3]
```diff
@@ -255,110 +243,186 @@ export class EntityRestCache implements IEntityRestCache {
...
 
-				const isLoadingAwayFromRange = (reverse && firstBiggerThanSecond(range.lower, start)) || (!reverse && firstBiggerThanSecond(start, range.upper))
+	/**
+	 * Creates a new list range, reading everything from the server that it can
+	 * range:         (none)
+	 * request:       *------>
+	 * range becomes: |------|
+	 * @private
+	 */
+	private async createNewRange<T extends ListElementEntity>(
```
Comment (charlag) [inline src/api/worker/rest/EntityRestCache.ts:285]: The name is a bit confusing to me. How about `loadWithNewRange()` or something along those lines? Maybe `populateNewRange()`.

File: src/api/worker/rest/EntityRestCache.ts [hunk 4]
```diff
@@ -255,110 +243,186 @@ export class EntityRestCache implements IEntityRestCache {
...
-			await this.storage.setNewRangeForList(typeRef, listId, start, start)
-
-			// The range bounds will be updated in here
-			return this.handleElementRangeResult(typeRef, listId, start, count, reverse, entities, count)
+		if (
+			range == null
+		) {
+			await this.createNewRange(typeRef, listId, start, count, reverse)
+		} else if (
+			!firstBiggerThanSecond(start, range.upper) && !firstBiggerThanSecond(range.lower, start)
```
Comment (charlag) [inline src/api/worker/rest/EntityRestCache.ts:263]: Took me a minute to understand, maybe some comment might make it easier (like "start is inside range")

File: src/api/worker/rest/EntityRestCache.ts [hunk 5]
```diff
@@ -255,110 +243,186 @@ export class EntityRestCache implements IEntityRestCache {
...
+		listId: Id,
+		start: Id,
+		count: number,
+		reverse: boolean
+	) {
+		// Create a new range and load everything
+		const entities = await this.entityRestClient.loadRange(typeRef, listId, start, count, reverse)
+
+		// Initialize a new range for this list
+		await this.storage.setNewRangeForList(typeRef, listId, start, start)
```
Comment (charlag) [inline src/api/worker/rest/EntityRestCache.ts:296]: I am a bit uneasy about creating a new range without elements and then populating it but it if it's empty it should be okay

File: src/api/worker/rest/EntityRestCache.ts [hunk 6]
```diff
@@ -255,110 +243,186 @@ export class EntityRestCache implements IEntityRestCache {
...
-					await this.handleElementRangeResult(typeRef, listId, loadStartId, count, !reverse, entities, count)
+			await this.updateRangeInStorage(typeRef, listId, count, !reverse, entities)
 
-					if (!await this.storage.isElementIdInCacheRange(typeRef, listId, start)) {
-						return this.loadRange(typeRef, listId, start, count, reverse)
-					} else {
-						return this.storage.provideFromRange(typeRef, listId, start, count, reverse)
-					}
-				}
+			if (await this.storage.isElementIdInCacheRange(typeRef, listId, start)) {
```
Comment (charlag) [inline src/api/worker/rest/EntityRestCache.ts:385]: Is this enough? Can we get stuck here? Should we check that we get less than we asked?

File: src/settings/UserListView.ts [hunk 7]
```diff
@@ -24,70 +23,69 @@ import {isUpdateForTypeRef} from "../api/main/EventController"
 import {ButtonN, ButtonType} from "../gui/base/ButtonN"
 import {compareGroupInfos} from "../api/common/utils/GroupUtils"
 import {GENERATED_MAX_ID} from "../api/common/utils/EntityUtils"
-import {showNotAvailableForFreeDialog} from "../misc/SubscriptionDialogs"
 import {ListColumnWrapper} from "../gui/ListColumnWrapper"
 import {assertMainOrNode} from "../api/common/Env"
 import {locator} from "../api/main/MainLocator"
 import Stream from "mithril/stream";
+import {showNotAvailableForFreeDialog} from "../misc/SubscriptionDialogs"
```
Comment (charlag) [inline src/settings/UserListView.ts:30]: Since you are redoing the file, could you also do imports with `.js` please? Webstorm still ignores the preference.

File: src/settings/UserListView.ts [hunk 8]
```diff
@@ -24,70 +23,69 @@ import {isUpdateForTypeRef} from "../api/main/EventController"
...
 
-	constructor(settingsView: SettingsView) {
-		this._adminUserGroupInfoIds = []
-		this._settingsView = settingsView
-		this._listId = new LazyLoaded(() => {
-			return locator.entityClient.load(CustomerTypeRef, neverNull(logins.getUserController().user.customer)).then(customer => {
-				return customer.userGroups
-			})
+	readonly list: List<GroupInfo, UserRow>
+	readonly view: (...args: Array<any>) => any
```
Comment (charlag) [inline src/settings/UserListView.ts:39]:
```suggestion
	readonly view: UpdatableSettingsViewer["view"]
```

File: src/settings/UserListView.ts [hunk 9]
```diff
@@ -24,70 +23,69 @@ import {isUpdateForTypeRef} from "../api/main/EventController"
...
+	readonly onremove: (...args: Array<any>) => any
```
Comment (charlag) [inline src/settings/UserListView.ts:40]:
```suggestion
	readonly onremove: UpdatableSettingsViewer["onremove"]
```

File: src/settings/UserListView.ts (hunk 8 above)
Comment (charlag) [reply src/settings/UserListView.ts:39]: Or just write it like a normal method and rebind to self (both methods)

File: src/settings/UserListView.ts [hunk 10]
```diff
@@ -24,70 +23,69 @@ import {isUpdateForTypeRef} from "../api/main/EventController"
...
+				// we return all users because we have already loaded all users and the scroll bar shall have the complete size.
+				if (logins.getUserController().isGlobalAdmin()) {
+					return allUserGroupInfos
 				} else {
-					throw new Error("fetch user group infos called for specific start id")
+					let localAdminGroupIds = logins
+						.getUserController()
+						.getLocalAdminGroupMemberships()
+						.map(gm => gm.group)
+					return allUserGroupInfos.filter((gi: GroupInfo) => gi.localAdmin && localAdminGroupIds.indexOf(gi.localAdmin) !== -1)
```
Comment (charlag) [inline src/settings/UserListView.ts:74]: `indexOf` -> `contains`

Should be a `Set` theoretically but might be less efficient for such a small number so we can keep it an array

File: src/settings/UserListView.ts [hunk 11]
```diff
@@ -24,70 +23,69 @@ import {isUpdateForTypeRef} from "../api/main/EventController"
...
-									  ofClass(NotFoundError, e => {
-										  // we return null if the entity does not exist
-										  return null
-									  }),
-								  )
-				})
+			loadSingle: async elementId => {
+				const listId = await this.listId.getAsync()
+				try {
+					return await locator.entityClient.load<GroupInfo>(GroupInfoTypeRef, [listId, elementId])
```
Comment (charlag) [inline src/settings/UserListView.ts:80]: I still think that `.catch(ofClass(...))` might look much better here but it's your call

File: src/settings/UserListView.ts [hunk 12]
```diff
@@ -128,56 +126,56 @@ export class UserListView implements UpdatableSettingsViewer {
...
+	private async loadAdmins(): Promise<void> {
 		let adminGroupMembership = logins.getUserController().user.memberships.find(gm => gm.groupType === GroupType.Admin)
 		if (adminGroupMembership == null) return Promise.resolve()
 		const members = await locator.entityClient.loadAll(GroupMemberTypeRef, adminGroupMembership.groupMember[0])
-		this._adminUserGroupInfoIds = members.map(adminGroupMember => adminGroupMember.userGroupInfo[1])
+		this.adminUserGroupInfoIds = members.map(adminGroupMember => adminGroupMember.userGroupInfo[1])
 	}
 
-	_setLoadedCompletely() {
+	private setLoadedCompletely() {
```
Comment (charlag) [inline src/settings/UserListView.ts:153]: This is called once, just inline it

File: src/settings/UserListView.ts [hunk 13]
```diff
@@ -128,56 +126,56 @@ export class UserListView implements UpdatableSettingsViewer {
...
-			if (this._searchResultStreamDependency) {
-				this._searchResultStreamDependency.end(true)
+			if (this.searchResultStreamDependency) {
+				this.searchResultStreamDependency.end(true)
 			}
 		}
 	}
 
-	async _loadAdmins(): Promise<void> {
+	private async loadAdmins(): Promise<void> {
```
Comment (charlag) [inline src/settings/UserListView.ts:146]: If it's not async, let's make it sync?

**Review by charlag — COMMENTED** [review]
Small suggestions, looks very good!

File: src/api/worker/rest/EntityRestCache.ts (hunk 6 above)
Comment (johnbotris) [reply src/api/worker/rest/EntityRestCache.ts:385]: `updateRangeInStorage` checks that and will set the range to `GENERATED_MIN_ID`/`GENERATED_MAX_ID` in this case, so it is implied

Comment (charlag) [reply src/api/worker/rest/EntityRestCache.ts:385]: ah, so it will set it to min/max and then this check will succeed? Let's leave a comment then

File: src/settings/UserListView.ts (hunk 13 above)
Comment (johnbotris) [reply src/settings/UserListView.ts:146]: it does async stuff, we just don't await it. I personally prefer leaving it transparent

File: packages/tutanota-utils/lib/ArrayUtils.ts [hunk 14]
```diff
@@ -512,4 +515,13 @@ export async function partitionAsync<T>(array: Array<T>, predicate: (arg0: T) =>
 	const mask: Array<boolean> = await Promise.all(array.map(predicate))
 	const [left, right] = partition(zip(mask, array), item => item[0])
 	return [left.map(i => i[1]), right.map(i => i[1])]
+}
+
+/**
+ * Create an array with n elements by calling the provided thunk
```
Comment (charlag) [inline packages/tutanota-utils/lib/ArrayUtils.ts:521]: Thunk is generally something that doesn't accept anything but whatever

File: src/api/worker/rest/EntityRestCache.ts [hunk 15]
```diff
@@ -25,6 +25,12 @@ import {QueuedBatch} from "../search/EventQueue"
 
 assertWorkerOrNode()
 
+// The minimum size of a range request when extending an existing range
+// Because we extend by making (potentially) many range requests until we reach the startId
+// We want to avoid that the requests are too small
+// For example, if we
```
Comment (charlag) [inline src/api/worker/rest/EntityRestCache.ts:31]: Unfinished comment, also can be jsdoc

**Review by charlag — APPROVED** [review]
Thanks, looks great, check that comment though

File: packages/tutanota-utils/lib/ArrayUtils.ts (hunk 14 above)
Comment (johnbotris) [reply packages/tutanota-utils/lib/ArrayUtils.ts:521]: Screenshot from 2022-02-28 16-26-42

File: src/api/worker/rest/EntityRestCache.ts (hunk 15 above)
Comment (johnbotris) [reply src/api/worker/rest/EntityRestCache.ts:31]: wow where is my brain
