### PR TITLE
remove extra div from FolderColumnView when there's no button

### LINKED ISSUE #4147: Unexpected clipping/margin for folder column in mobile view
Screenshot from 2022-05-17 13-31-31

Broken by 9bebbd4441540fcdcb699de0acdd78e7213b6c80

### PR DESCRIPTION
**Pull request by ganthern**
fix #4147

### CODE REVIEW

File: src/gui/FolderColumnView.ts [hunk 1]
```diff
@@ -62,9 +62,9 @@ export class FolderColumnView implements Component<Attrs> {
 	}
 
 	private renderMainButton(attrs: Attrs): Children {
-		return attrs.button ? m(FolderColumnHeaderButton, {
+		return attrs.button ? m(".mlr-l.mt.mb", m(FolderColumnHeaderButton, {
```
Comment (charlag) [inline src/gui/FolderColumnView.ts:65]: can you also reformat the condition please to be
```ts
  condition
    ? option1
    : option2

**Review by charlag — APPROVED** [review]
