### PR TITLE
make attendee check after reply button click on event case-insensitive

### LINKED ISSUE #5125: Trying to reply to calendar invite with different email case doesn't work
Same as in #5079 but pressing one of the buttons on the invite banner leads to "You are not attending this event." message.

### PR DESCRIPTION
**Pull request by ganthern**
fix #5125

### CODE REVIEW

File: src/mail/view/EventBanner.ts [hunk 1]
```diff
@@ -137,3 +136,12 @@ function sendResponse(event: CalendarEvent, recipient: string, status: CalendarA
 		}),
 	)
 }
+
+/**
+ * get the attendee from the event that corresponds to the given recipient address, if there is one.
+ */
+function getOwnAttendee(event: CalendarEvent, recipient: string): CalendarEventAttendee | null {
```
Comment (charlag) [inline src/mail/view/EventBanner.ts:143]: I'd name it `findAttendee`, also we should probably put it somewhere common because `CalendarEventViewModel` also has `findOwnAttendee` which is broken in the same exact way I think?

File: src/mail/view/EventBanner.ts [hunk 2]
```diff
@@ -137,3 +136,12 @@ function sendResponse(event: CalendarEvent, recipient: string, status: CalendarA
...
+	const lowerCaseRecipient = recipient.toLowerCase()
+	const ownAttendee = event.attendees.find((a) => a.address.address.toLowerCase() === lowerCaseRecipient)
```
Comment (charlag) [inline src/mail/view/EventBanner.ts:145]: you can also inline this

**Review by charlag — APPROVED** [review]
We could name it `findAttenddeeWithOneOfAddresses`
or we could just merge it
