### PR TITLE
replace multiple occurences of template in translation key text

### LINKED ISSUE #3236: Repeated translation parameter not shown correctly
When a translation has a given parameter `{foo}` more than once, only the first instance is replaced.

**To Reproduce**

1. Create gift card valid in Country1
2. Redeem gift card from different country (make sure browser locale is anything but Country1)
3. See error (**{valid}** should be Deutschland)
Screenshot from 2021-07-01 15-14-46

---

# testing notes
- [ ] Translation keys that have multiple occurrences of a placeholder will be correctly handled (Follow reproduction steps)
- [ ] Placeholders that could be interpreted as regex are handled correctly (check `businessBooking_label`)

### PR DESCRIPTION
**Pull request by johnbotris**
fix #3236

### CODE REVIEW

File: src/api/common/utils/StringUtils.js [hunk 1]
```diff
@@ -106,4 +106,20 @@ export function byteLength(str: ?string): number {
 		if (code >= 0xDC00 && code <= 0xDFFF) i--; //trail surrogate
 	}
 	return s;
+}
+
+/**
+ * replace all instances of substr in str with replacement
+ */
+export function replaceAll(str: string, substr: string, replacement: string): string {
```
Comment (charlag) [inline src/api/common/utils/StringUtils.js:114]: Should we just take replaceAll polyfill from core-js? We wouldn't need tests and we wouldn't need to migrate to builtin later

**Review by charlag — APPROVED** [review]

File: src/api/common/utils/StringUtils.js (hunk 1 above)
Comment (charlag) [reply src/api/common/utils/StringUtils.js:114]: Seems like we don't use core-js anymore so eh

**Review by charlag — APPROVED** [review]
