### PR TITLE
fix inconsistent settings links

### LINKED ISSUE #5515: Email link to any settings view navigates to the login settings
When clicking on an internal link in an email that points to some settings view, the login view is shown instead. This affects e.g. the link to the invoices in the invoice emails and to the link to the plans in the newsletter.

How to reproduce:
1. Send or receive an email with an internal link, e.g. to /settings/subscription
2. Click on the link
-> The login settings are shown
Expected: The subscription settings are shown.

## Test notes
* [ ] the user is redirected to the correct settings
* [ ] when doesn't have access, the login settings is displayed
* [ ] when the setting doesn't exists, the login settings is displayed

### PR DESCRIPTION
**Pull request by murilopereirame**
When the user opens a link that forward to the setting pages the displayed folder is the Login one no matters the folder that is present in the path. This happens due the handle of the path be made before the load of all available folders of the user.

This commit call the path handler after loading all the folders, so it can successfully handle the requested path.

fix #5515

### CODE REVIEW

**Review by charlag — CHANGES_REQUESTED** [review]

File: src/settings/SettingsView.ts [hunk 1]
```diff
@@ -448,7 +448,14 @@ export class SettingsView extends BaseTopLevelView implements TopLevelView<Setti
 	oncreate(vnode: Vnode<SettingsViewAttrs>) {
 		locator.eventController.addEntityListener(this.entityListener)
 
-		this.populateAdminFolders()
+		const currentRoute = m.route.get()
+		this.populateAdminFolders().then(() => {
+			// We have to wait for the folders to be initialized before setting the URL,
+			// otherwise we won't find the requested folder and will just pick the default folder
+			if (currentRoute !== this._userFolders[0].url) {
```
Comment (charlag) [inline src/settings/SettingsView.ts:455]: okay, sorry but I still don't get why we only do it if the URL is *not* the first one. I thought we only want to switch if it *is* the first (default) one? Otherwise we might be elsewhere already?

File: src/settings/SettingsView.ts [hunk 2]
```diff
@@ -588,6 +597,7 @@ export class SettingsView extends BaseTopLevelView implements TopLevelView<Setti
 				m.redraw()
 			} else {
 				// folder path has changed
+				this._setUrl(folder.url)
```
[the remark this answers is not in the document]
Comment (charlag) [reply src/settings/SettingsView.ts:598]: thanks! this should go to the comment :)

File: src/settings/SettingsView.ts (hunk 1 above)
Comment (murilopereirame) [reply src/settings/SettingsView.ts:455]: When users navigate to settings from an internal link coming from an email for example, the onNewUrl is triggered moving they to the default route because not all the folders are available yet, **but** the currentRoute remains the internal link that they want to access, to avoid an unnecessary navigation, like moving again to the default one, the check is realized

Comment (charlag) [reply src/settings/SettingsView.ts:455]: I think I finally get it! I was confused because I forgot that `currentRoute` already has the folder param. I don't think it's harmful to change URL to the same one that we already have, it's probably a noop?

So what I think we actually should do it is

```ts
const stillAtDefaultUrl = m.route.get() === this._userFolders[0].url
if (stillAtDefaultUrl) {
  // the user did not navigate away yet, it is safe to switch to the folder from the parameter
  // ...
}
```

another thing that I've noticed is that we are doing `m.route.param("folder")` but *after* the async loading. Shouldn't we save the folder parameter to a variable before loading (before it's possibly switched)?

File: src/settings/SettingsView.ts [hunk 3]
```diff
@@ -103,6 +103,8 @@ export class SettingsView extends BaseTopLevelView implements TopLevelView<Setti
 	private _selectedFolder: SettingsFolder<unknown>
 	private _currentViewer: UpdatableSettingsViewer | null = null
 	private showBusinessSettings: stream<boolean> = stream(false)
+	private readonly _targetFolder: string
```
Comment (charlag) [inline src/settings/SettingsView.ts:106]: just FYI we don't need underscores in field names, that's pre-typescript convention

**Review by charlag — APPROVED** [review]
