### PR TITLE
Fix checkbox not indicating if disabled

### LINKED ISSUE #3133: Visually indicate when a checkbox is disabled
When a checkbox is disabled (e.g. Save Password when device storage is unavailable), there is no visual indication that it doesn't do anything: The cursor still changes on hover, and when it is clicked it will still flash (even though it's state doesn't change).

## Test Notes
- [x] when disabled both the checkbox and it's label are greyed out on dark mode
- [x] when disabled both the checkbox and it's label are greyed out on light mode
- [x] when enabled both the checkbox and it's label use the standard colour
- [x] when hovering over a disabled checkbox the cursor is displayed as default
- [x] when hovering over an enabled checkbox the cursor is displayed as pointer
- [x] when tabbing across the view, disabled checkboxes are skipped over
- [x] when tabbing across the view, enabled checkboxes are not skipped over
- [x] when clicking on a disabled checkbox the checkbox does not change state
- [x] when clicking on an enabled checkbox the checkbox changes state
- [x] when tabbing over to then pressing space on a disabled checkbox the checkbox does not change state
- [x] when tabbing over to then pressing space on an enabled checkbox the checkbox changes state

### PR DESCRIPTION
**Pull request by rezbyte**
Greys out the checkbox by reducing its opacity & setting the cursor to default. Also included is a small typo fix.

Closes #3133.

### CODE REVIEW

File: src/gui/base/Checkbox.ts [hunk 1]
```diff
@@ -37,10 +37,14 @@ export class Checkbox implements Component<CheckboxAttrs> {
 			},
 			[
 				m(
-					".wrapper.flex.items-center",
+					`.wrapper.flex.items-center${a.disabled ? ".disabled" : undefined}`,
```
Comment (murilopereirame) [inline src/gui/base/Checkbox.ts:40]: Replace undefined by an empty string, otherwise it will append ```undefined``` when **a.disabled** is false

Comment (rezbyte) [reply src/gui/base/Checkbox.ts]: Nice catch, pushed a commit now.

**Review by murilopereirame — APPROVED** [review]
