### PR TITLE
fix wrong this binding in MultiSearchViewer action bar

### LINKED ISSUE #5126: Uncaught TypeError: this is undefined when using any multisearchviewer actions
this probably broke during the rebase:

* open search view
* select multiple mails
* try any of the actions in the action bar
* get error:

```
Feedback v3.109.2 - TypeError - PREMIUM - Browser
Client: Browser
Type: PREMIUM
Tutanota version: 3.109.2
Timestamp (UTC): Mon, 13 Feb 2023 13:15:26 GMT
User agent:
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/109.0
TypeError
Error message: this is undefined
Stacktrace:
selectNone@https://test.tutanota.com/gui-base-59a00497.js:1:148846
execute/Ml/childAttrs/i/i<@https://test.tutanota.com/mail-view-0c0a1747.js:1:47080
execute/wrapClick/<@https://test.tutanota.com/gui-base-59a00497.js:1:104194
onclick@https://test.tutanota.com/gui-base-59a00497.js:1:107029
execute/R</D.prototype.handleEvent@https://test.tutanota.com/app.js:1:25731
```

### PR DESCRIPTION
**Pull request by ganthern**
fix #5126

### CODE REVIEW

File: src/mail/view/MailView.ts [hunk 1]
```diff
@@ -764,7 +764,7 @@ export class MailView extends BaseTopLevelView implements TopLevelView<MailViewA
 	 */
 	private renderHeaderView(): Children {
 		const selectedEntities = this.cache.mailList?.list.getSelectedEntities() ?? []
-		const selectNone = () => this.cache.mailList?.list.selectNone ?? noOp
+		const selectNone = (() => this.cache.mailList?.list.selectNone()) ?? noOp
```
Comment (charlag) [inline src/mail/view/MailView.ts:767]: what the hell is going on here 😅

either the whole function would be nullable (why?) or the result would be (why do we pass no-op then?). Right now this `??` does nothing because it's left side is an arrow function

File: src/search/view/MultiSearchViewer.ts [hunk 2]
```diff
@@ -42,7 +42,7 @@ export class MultiSearchViewer implements Component {
 			}
 
 			const selectedEntities = (this.searchListView.list && this.searchListView.list.getSelectedEntities()) ?? []
-			const selectNone = this.searchListView.list?.selectNone ?? noOp
+			const selectNone = (() => this.searchListView.list?.selectNone()) ?? noOp
```
Comment (charlag) [inline src/search/view/MultiSearchViewer.ts:45]: same here

**Review by charlag — CHANGES_REQUESTED** [review]

**Review by charlag — APPROVED** [review]
