### PR TITLE
Fix broken links for invites from Outlook

### LINKED ISSUE #2741: Some links from calendar invite disappears
>When receiving calendar invites with Zoom links for instance, the link disappears on the accepted and saved invite.

Also update of event is not automatically applied, we should try that out.

### PR DESCRIPTION
**Pull request by charlag**
fix #2741

Outlook has special format for links and it is removed by our
sanitizer. We try to find such places and replace them with proper
HTML.

### CODE REVIEW

File: src/calendar/CalendarUtils.js [hunk 1]
```diff
@@ -762,4 +762,25 @@ export function findPrivateCalendar(calendarInfo: Map<Id, CalendarInfo>): ?Calen
...
+ * ```
+ * text<https://example.com>
+ * ```
+ */
+export function prepareCalendarDescription(description: string): string {
+	return description.replace(/<(http|https):\/\/[A-z0-9$-_.+!*‘(),\/?]+>/gi, (possiblyLink) => {
+		try {
+			const withoutBrackets = possiblyLink.slice(1, -1)
+			const url = new URL(withoutBrackets)
+			return `<a href="${url.toString()}">${withoutBrackets}</a>`
```
Comment (johnbotris) [inline src/calendar/CalendarUtils.js:779]: Should we be setting `target` and `rel` attributes here? or just allow the sanitizer to do it?

**Review by johnbotris — APPROVED** [review]

**Comment by olof-nord** [comment]
Just came here to say that I you are doing a truly great job. That is some edge-edge-edge scenario.
Happy customer since a few years now. Keep up the good work!
