### PR TITLE
Wrap key retrieval errors other than CancelledError in DeviceStorageUnavailableError

### LINKED ISSUE #3900: Unexpected error message: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown
**Describe the bug**
Unexpected error message when starting tutanota desktop client (see detailed error message below) and the user can't login using stored credentials. 

**To Reproduce**
1. uninstall gnome-keyring
2. start tutanota and log in using stored credentials / try adding stored credentials.

**Expected behavior**
An error message should be shown that some dependency is missing and the gnome-keyring needs to be installed. Option to save credentials should not be available.

**Desktop (please complete the following information):**
 - Linux desktop client 3.91.10

**Additional context**
We had this problem before when storing alarms to the keychain (see #2929) and the reason was that we are using `keytar` for accessing the keychain and keytar depends on `libsecret` and that requires `gnome-keyring` to be installed on the system. As soon as  `gnome-keyring` is installed the error should not occur anymore. We are now storing the key for encrypting credentials to the keychain and that is why this error occurs more often #3733.

One option might be to replace `keytar` with electrons `safeStorage` api but there are some problems because the api requires a window to be present #3676 and we cannot use this aproach for securing the alarms.

As we cannot remove the dependency in the short term we should catch the error and show an appropriate error message that a dependency is missing. If possible we can also disable the "save credentials" checkbox.

#3676
#3733
#2929
#1257

> Client: linux
> Type: FREE
> Tutanota version: 3.91.10
> Timestamp (UTC): Mon, 14 Feb 2022 20:43:21 GMT
> User agent:
> Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.91.10 Chrome/96.0.4664.110 Electron/16.0.8 Safari/537.36
> Error
> Error message: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
> Stacktrace:
> Error: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service file

### PR DESCRIPTION
**Pull request by ganthern**
close #3900

### CODE REVIEW

**Review by charlag — CHANGES_REQUESTED** [review]
Looks good but a few things:

 - tests for `KeyStorreFacadeImpl` and `LoginViewModel`
 - commit "wrap fetchOrGenerateKey error in..." doesn't have any desktop-specific parts and can be reworded
 - we silently drop any error when retrieving the key. This might be acceptable on desktop but might be problematic on mobile. I don't want to put a platform switch in LanguageViewModel at all so maybe we should think if we should communicate something
 - `console.warn` doesn't include the message so we lose the context.

File: src/login/LoginViewModel.ts [hunk 1]
```diff
@@ -345,14 +347,19 @@ export class LoginViewModel implements ILoginViewModel {
 					await this._credentialsProvider.store(newCredentials)
 				} catch (e) {
 					if (e instanceof KeyPermanentlyInvalidatedError) {
-						await this._credentialsProvider.clearCredentials()
+						await this._credentialsProvider.clearCredentials(e)
 						await this._updateCachedCredentials()
+					} else if (e instanceof DeviceStorageUnavailableError) {
```
Comment (charlag) [inline src/login/LoginViewModel.ts:352]: Why do we need a catch here and a catch outside? If one of them fails with this error, all others will probably fail as well

File: test/client/desktop/KeyStoreFacadeTest.ts [hunk 2]
```diff
@@ -17,174 +18,160 @@ o.spec("KeyStoreFacade test", function () {
 	let cryptoFacadeSpy: DesktopCryptoFacade
 
 	o.beforeEach(function () {
-		cryptoFacadeSpy = spyify(downcast({}))
+		cryptoFacadeSpy = spyify(downcast({generateDeviceKey: () => new Uint8Array([0, 0])}))
```
Comment (charlag) [inline test/client/desktop/KeyStoreFacadeTest.ts:21]: try to us `as CryptoFacade` as it will at least check that the shape is correct

File: src/login/LoginViewModel.ts (hunk 1 above)
Comment (ganthern) [reply src/login/LoginViewModel.ts:352]: this preserves the behaviour we had previously: 
* when deleting duplicate credentials fails, immediately bail out of the login process
* when saving credentials fails with a known error, still log in, just skip the saving step

both cases should probably log something, but the second one must be caught in the inner `try` so the login can proceed.

Comment (charlag) [reply src/login/LoginViewModel.ts:352]: Right, it's about deletion, not storing. I would suggest to then `break` there

Comment (charlag) [reply src/login/LoginViewModel.ts:352]: wait, sorry, github is confusing, it's fine

File: test/client/desktop/KeyStoreFacadeTest.ts (hunk 2 above)
Comment (ganthern) [reply test/client/desktop/KeyStoreFacadeTest.ts:21]: It would be `DesktopCryptoFacade`, but the downcast saves a bunch of boilerplate because we only need one function and there is a bunch more in that interface

Comment (charlag) [reply test/client/desktop/KeyStoreFacadeTest.ts:21]: It will let you cast it even if things are missing, just will check there's nothing incompatible

**Review by charlag — APPROVED** [review]

**Comment by ganthern** [comment]
commit `remove downcast from KeyStoreFacadeTest.ts` still had a downcast further down...
