### PR TITLE
fix # + <tab> not bringing up the template popup

### LINKED ISSUE #5332: Bringing up the template popup with # + <tab> does not work anymore
broke with the squire update in 3.112.5. You can still open it with ctrl + space.

## Test Notes
* [ ] when typing # + `<tab>` in the mail editor, the template popup is brought up
* [ ] when typing #xxx + `<tab>`, the template editor shows matching templates (xxx being a part of a or being a complete template shortcut)
* [ ] it's still possible to tab out of the editor when # is not typed 
* [ ] it's still possible to insert the template

### PR DESCRIPTION
**Pull request by ganthern**
the new squire changed the way cursor change events are reported to the editor, so we need to update the TemplateShortcutListener.

fix #5332

### CODE REVIEW

File: src/templates/view/TemplateShortcutListener.ts [hunk 1]
```diff
@@ -31,7 +29,8 @@ class TemplateShortcutListener {
 	}
 
 	// add this event listener to handle quick selection of templates inside the editor
-	handleKeyDown(event: Event) {
+	handleKeyDown(event: KeyboardEvent) {
+		console.log("handling keydown!", event)
```
Comment (wrdhub) [inline src/templates/view/TemplateShortcutListener.ts:33]: Do we want this log? Genuinely don't know.

Comment (ganthern) [reply src/templates/view/TemplateShortcutListener.ts:33]: oh no, I forgot about that one.

**Review by wrdhub — APPROVED** [review]
