### PR TITLE
fix ios attachment uploads

### LINKED ISSUE #4361: Cannot send logs files from an account that has blob store enabled
**Describe the bug**
When sending log files from an iOS device with an account that has blob store enabled the offline error message appears. ("Could not reach server, looks like you are offline. Please try again later.")

**To Reproduce**
1. Log in on an iOS device with an account that has blob store enabled.
2. Go to Settings->About and try to send the log files to yourself
3. See offline error message 

**Expected behavior**
Sending the email is possible.

**Smartphone (please complete the following information):**
 - Device: iOS
 - Tutanota Version 3.86.4

### Test Notes
* [ ] attaching and sending logs from the about dialog works
* [ ] they can be opened from another mailbox

### LINKED ISSUE #4476: Can't send attachments on iOS
**Bug in mobile app**
iOS and iPadOS, Tutanota version 3.98.17 and 3.98.20

**Describe the bug**
Sending an Email with any attachment on iOS/iPadOS (file or images from either the gallery or camera) fails with the message "Could not reach server, looks like you are offline. Please try again later"

**Smartphone (please complete the following information):**
 - Device: iPhone 11 Pro Max
 - OS: 15.6

### Test Notes:
* [ ] ios attachment uploads work
* [ ] sending/receiving of mail works
* [ ] the attachments can be downloaded on another mailbox

### PR DESCRIPTION
**Pull request by ganthern**
see  commit messages for details

fix #4476
fix #4361

### CODE REVIEW

File: src/api/worker/facades/MailFacade.ts [hunk 1]
```diff
@@ -348,57 +353,58 @@ export class MailFacade {
...
-				// check if this is a new attachment or an existing one
-				if (providedFile._type === "DataFile") {
-					// user added attachment
-					const fileSessionKey = aes128RandomKey()
-					const dataFile = downcast<DataFile>(providedFile)
-					if (useBlobs) {
-						// return
-						const referenceTokens = await this.blobFacade.encryptAndUpload(ArchiveDataType.Attachments, dataFile.data, senderMailGroupId, fileSessionKey)
-						return this.createAndEncryptDraftAttachment(referenceTokens, fileSessionKey, dataFile, mailGroupKey)
+		if (providedFiles == null || providedFiles.length === 0) return Promise.resolve([])
```
Comment (johnbotris) [inline src/api/worker/facades/MailFacade.ts:356]: could just be `return []`

**Review by johnbotris — APPROVED** [review]
one note but feel free to ignore it

File: src/api/worker/facades/MailFacade.ts (hunk 1 above)
Comment (ganthern) [reply src/api/worker/facades/MailFacade.ts]: good point
