### PR TITLE
Fix client-side captcha verification; fix SignupFormTest

### LINKED ISSUE #6316: Misleading error message in captcha
When trying to solve a captcha and entering minutes outside of a 5 minute interval (11 instead of 10) I get an error message saying "Please enter the time in hours and minutes." which is misleading.

How to reproduce:
1. Start a signup where a captcha is required
2. Fill in the time as "12:37"
3. The error message mentioned is shown

Expected: a message saying that the result is wrong.

Notes:
The error is created after failing a regex check in the client, instead we might want to send the result to the server.

### PR DESCRIPTION
**Pull request by paw-hub**
Fix Captcha matching hours 25-29 and allows it to match times that will never be correct (but can be checked locally).

Add missing SignupFormTest to the test suite.

Fixes #6316

### CODE REVIEW

File: src/subscription/Captcha.ts [hunk 1]
```diff
@@ -17,12 +17,18 @@ import { uint8ArrayToBase64 } from "@tutao/tutanota-utils"
  * @returns {string} HH:MM if parsed, null otherwise
  */
 export function parseCaptchaInput(captchaInput: string): string | null {
-	if (captchaInput.match(/^[0-2]?[0-9]:[0-5]?[05]$/)) {
+	if (captchaInput.match(/^[0-2]?[0-9]:[0-5]?[0-9]$/)) {
```
Comment (charlag) [inline src/subscription/Captcha.ts:20]: I think before it explicitly only matched minutes in 5 min intervals. Did you change this intentionally?

File: src/subscription/Captcha.ts [hunk 2]
```diff
@@ -91,20 +97,28 @@ function showCaptchaDialog(challenge: Uint8Array, token: string): Promise<string
...
+
+			// The user entered a correctly formatted time, but not one that our captcha will ever give out (i.e. not *0 or *5)
+			const minuteOnesPlace = parsedInput[parsedInput.length - 1]
+			if (minuteOnesPlace !== "0" && minuteOnesPlace !== "5") {
+				Dialog.message("createAccountInvalidCaptcha_msg")
+				return
+			}
+
+			dialog.close()
+			locator.serviceExecutor
```
Comment (charlag) [inline src/subscription/Captcha.ts:114]: comment for posterity: (eventually) there should be some class that runs captcha and not just a function and we should inject what we need in it

File: src/subscription/Captcha.ts (hunk 1 above)
Comment (charlag) [reply src/subscription/Captcha.ts:20]: I see that tests actually expected 1 min intervals. I would still check with @armhub if this was intended.

Comment (paw-hub) [reply src/subscription/Captcha.ts:20]: Hey, I did not change it to make the tests pass. This is just because of what the issue was complaining about:

> When trying to solve a captcha and entering minutes outside of a 5 minute interval (11 instead of 10) I get an error message saying "Please enter the time in hours and minutes." which is misleading.

The old regex rejects times that are not 5 minute intervals, thus you get an error stating that the time is malformatted, not that it is wrong.

The solution I found, without changing the error to something complex such as "Please enter the time in hours and minutes, and only in 5 minute intervals." is to allow all correctly formatted times, not just 0/5 minute times, but check them locally.

Comment (paw-hub) [reply src/subscription/Captcha.ts:20]: I suppose another alternative is to not return null, but to return a constant in some enum that we can check against, or throw an error of some kind that we can catch.

I really don't care about the tests checking against *1 to *4 and *6 to *9 minutes. As far as I know, we will never support these.

Comment (charlag) [reply src/subscription/Captcha.ts:20]: I see, I understand now, thank you for explaining!

**Review by charlag — APPROVED** [review]
