### PR TITLE
Use invisible address as displayed sender when sender name is empty

### LINKED ISSUE #8266: VoiceOver does not focus mail expand button if sender name is empty
**To Reproduce**
1. Enable VoiceOver
2. Open email that was sent without a sender name
3. Try to focus mail collapse button (the header)
4. See that the focus goes straight to "more" button.

**Expected behavior**
Mail header expander is always focusable, independent on the sender name.

**Estimated: 1h**
**Time spent: 2h**

## Test notes
- [ ] Enable VoiceOver.
- [ ] Open email that was sent without a sender name.
- [ ] The mail collapse button can be focused (when mail has no sender name, the sender address is read instead).
- [ ] The mail "more" button can be focused.
- [ ] Activating the collapse button folds the mail.

### PR DESCRIPTION
**Pull request by hrb-hub**
Because the sender's name is used as a fold mail button. An empty sender name results in an element with a height of zero, making it impossible to click to fold mails.

VoiceOver also does not focus the fold mail button when the sender name is empty.

Close https://github.com/tutao/tutanota/issues/8266
Close https://github.com/tutao/tutanota/issues/8309

Co-authored-by: paw <paw-hub@users.noreply.github.com>
Co-authored-by: ivk <ivk@tutao.de>

### CODE REVIEW

File: src/mail-app/mail/view/MailViewerHeader.ts [hunk 1]
```diff
@@ -230,7 +232,10 @@ export class MailViewerHeader implements Component<MailViewerHeaderAttrs> {
 						  )
 						: null,
 					this.tutaoBadge(viewModel),
-					m("span.text-break" + (viewModel.isUnread() ? ".font-weight-600" : ""), viewModel.getDisplayedSender()?.name ?? ""),
+					m(
+						"span.text-break" + (viewModel.isUnread() ? ".font-weight-600" : "") + (displayAddressForSender ? ".invisible" : ""),
+						displayAddressForSender ? viewModel.getDisplayedSender()?.address : senderName,
```
Comment (charlag) [inline src/mail-app/mail/view/MailViewerHeader.ts:237]: there is a case where `getDisplayedSender()` is `null` which is for system notifications (when we don't have any sender but we do have a badge). It's probably not a big deal if we can't collapse those "emails" though.

File: src/mail-app/mail/view/MailViewerHeader.ts [hunk 2]
```diff
@@ -230,7 +232,10 @@ export class MailViewerHeader implements Component<MailViewerHeaderAttrs> {
 						  )
 						: null,
 					this.tutaoBadge(viewModel),
-					m("span.text-break" + (viewModel.isUnread() ? ".font-weight-600" : ""), viewModel.getDisplayedSender()?.name ?? ""),
+					m(
+						"span.text-break" + (viewModel.isUnread() ? ".font-weight-600" : "") + (displayAddressForSender ? ".invisible" : ""),
```
Comment (charlag) [inline src/mail-app/mail/view/MailViewerHeader.ts:236]: I wonder if long but invisible mail address will wrap and cause the header to expand. Would be a bit weird probably, we could disable wrapping for this invisible case.

File: src/mail-app/mail/view/MailViewerHeader.ts (hunk 1 above)
Comment (hrb-hub) [reply src/mail-app/mail/view/MailViewerHeader.ts:237]: By badge, do you mean the "Tuta Team" badge? if so, then those can be folded. The listener is on the parent element (subjectActionsLine), this means we can actually fold mails in this current broken state provided the mail is unread, since the unread indicator will give the subjectActionsLine a height greater than zero allowing us to click it :sweat_smile: . So as long as there's something in there, the mail can be folded.

File: src/mail-app/mail/view/MailViewerHeader.ts (hunk 2 above)
Comment (hrb-hub) [reply src/mail-app/mail/view/MailViewerHeader.ts]: I checked and they did :sweat_smile: great catch!

Comment (charlag) [reply src/mail-app/mail/view/MailViewerHeader.ts]: I thought it wasn't overflowing, I thought it was rather wrapping but whatever works!

**Review by charlag — APPROVED** [review]

File: src/mail-app/mail/view/MailViewerHeader.ts (hunk 2 above)
Comment (hrb-hub) [reply src/mail-app/mail/view/MailViewerHeader.ts]: No, you were right it was wrapping. The `overflow-hidden` is so it doesn't push the "more" button out view
