### PR TITLE
Fix contact list invitations not showing on first load

### LINKED ISSUE #9114: Contact list invitations not displayed on first load
**Bug Description**

Contact list Invitations do not show up on first access to Contacts tab.

**To Reproduce**
1. Go to Contacts Tab -> Select one contact list -> 3 dots -> sharing
2. Login as the account that has received the invitation
3. Go to the contacts tab
4. Contact List invitations header is present however the list is not loaded
5. Click on another tab, such as mails
6. Go back to Contacts
7. The Invitation loads

**Expected behavior**
On step 4 the list invitations should have loaded, not requiring changing tabs.

**Screenshots**

Image

**Desktop (please complete the following information):**
 - OS: Debian
 - Version v287.250612.1 

## Test notes
- [ ] Contact list invitations display correctly on first load
  - [ ] Using **account A** create a contact list and share it with **account B**.
  - [ ] Login with **account B** and navigate to contacts.
  - [ ] The new contact list invitation should be visible in the contact list invitations section.
  - [ ] Logout from **account B** and login again to the same account, navigate to contacts, the invitation should again be visible.
- [ ] Contact list invitations update correctly
  - [ ] Using **account B** remain in contact view.
  - [ ] Using a different client, login to **account A** and invite **account B** to another list.
  - [ ] The new invite shows up in **account B**.
  - [ ] Using **account A** revoke **account B**'s access to a contact list, and see that the change is reflected on **account B** (again, without navigating away on **account B**).

### PR DESCRIPTION
**Pull request by hrb-hub**
Introduced in 5fc6c232
This fix also ensures that GroupInvitationFolderRow is imported conditionally which wasn't the case before.

Close #9114

Co-authored-by: bir <bir@tutao.de>

### CODE REVIEW

File: src/mail-app/contacts/view/ContactView.ts [hunk 1]
```diff
@@ -529,28 +532,30 @@ export class ContactView extends BaseTopLevelView implements TopLevelView<Contac
...
+			this.contactListInvitationSection,
 		]
 	}
 
-	private getContactListInvitationRows() {
-		import("../../../common/sharing/view/GroupInvitationFolderRow.js")
-			.then(({ GroupInvitationFolderRow }) => {
-				this.invitationRows = this.contactListViewModel.getContactListInvitations().map((invitation) =>
+	updateContactListInvitationsSection(receivedInvitations: ReceivedGroupInvitation[]) {
+		if (isEmpty(receivedInvitations)) {
```
Comment (charlag) [inline src/mail-app/contacts/view/ContactView.ts:539]: are we missing a redraw now?
