### PR TITLE
8555 update ios sqlcipher

### LINKED ISSUE #8555: Update iOS sqlcipher to 4.6.0
It seems like it's just a matter of 1. clone 2. configure 3. copy files

https://www.zetetic.net/sqlcipher/ios-tutorial/

Please note that we do not need to manually meddle with XCode project files as we generate them.

**Test Notes**
- [ ] Smoke test in iOS to make sure nothing got broken.

### PR DESCRIPTION
**Pull request by BijinDev**
Updated iOS sqlcipher to version 3.46.1

close #8555

### CODE REVIEW

File: src/mail-app/mail/editor/MailEditorViewModel.ts [hunk 1]
```diff
@@ -77,8 +77,8 @@ export function showFileChooserForAttachments(boundingRect: ClientRect, fileType
 export function createAttachmentBubbleAttrs(model: SendMailModel, inlineImageElements: Array<HTMLElement>): Array<AttachmentBubbleAttrs> {
 	return model.getAttachments().map((attachment) => ({
 		attachment,
-		open: null,
```
Comment (wrdhub) [inline src/mail-app/mail/editor/MailEditorViewModel.ts:80]: why are these changes here? It looks like they are for a different issue. But looks good other than that.

Comment (BijinDev) [reply src/mail-app/mail/editor/MailEditorViewModel.ts:80]: yes, this is another commit. I'll rebase the branch

**Review by charlag — APPROVED** [review]
