### PR TITLE
Pinch to zoom for emails

### LINKED ISSUE #1997: Pinch-to-zoom in mail viewer
In addition to being more intuitive than double tapping (some users don't even realize this is possible), this gives the user control of the zoom level.

We will not support dragging while zooming.

- [x] Implement algorithm for initial pinch to zoom
- [x] Adapt algorithm to set correct transform origin and translation for consecutive pinch to zooms
- [x] Consider scrolled or otherwise moved mail body (e.g. opened header)
- [x] Implement dragging
- [x] Respect initially scaled mail body
- [x] Make sure that the double tap zoom still works and zooms to the double tap position (and not top left like currently)
- [x] Respect the viewport borders, so that the mail body border can not be inside the visible area
- [x] make sure that iOS works as well
- [x] Document how the calculations work

## Test notes:
* [ ] should work both on android and ios and for HTML and non-HTML emails:
* [x] large HTML emails (e.g. newsletters) are initially scaled to the available width (i.e. zoomed out initially)
  * double tap:
    * [x] double tapping an unzoomed email zooms in
    * [x] double tapping a zoomed email (zoom factor is not important) should zoom out
    * [x] double tapping a link does not trigger any link action, but will show the desired zooming behavior
    * [x] single tapping a link triggers the link action
    * [x] zoom center of the double tap is the tapped position when zooming in
    * [x] email has the right scroll position after double tap when zooming out
  * pinch zoom and dragging:
    * [x] it is not possible to zoom further out than the initial state
    * [x] a zoom limit exists (infinite zooming is not possible)
    * [x] email can't be dragged in fully zoomed out state
    * [x] no edges are cut-off in fully zoomed out state
    * [x] the zoom center is the middle between the two fingers
    * [x] scrolling the conversation and then zooming works
    * [x] expanding the mail header and then zooming works
    * [x] when zooming out and a border is reached, the zoom center is not longer between the fingers but adjusted in a way to allow further zooming out without violating the borders
    * [x] while dragging and zooming it is not possible to move the borders of the email to the visible area (ask us if this in unclear 😆 )
    * [x] when zoomed in: dragging in vertical direction until it is not longer possible (border reached) -> the conversation starts scrolling
    * [x] zooming in an HTML email before loading images and then loading the images resets the email back to the initial zoom factor
    * [x] when images are loading with a slow internet connection the email is reset to the initial zoom factor whenever the email size changes
  * combination of double tap and pinch zoom
    * [x] it is possible to double tap and then further zoom in via pinching
    * [x] it is possible to zoom out an email completely by double tapping which was zoomed in via pinching
    * [x] ...
* [x] try out different kind of things, also unusual behavior (exploratory testing)

### Regressions:
* [x] non and mobile devices:
  * [x] conversations are scrollable
  * [x] mail header can be expanded without having any bad side effects on the mail (cut-off at the bottom)
  * [x] links can be clicked and are handled correctly (e.g. mailto: opens mailviewer in tutanota, url in browser)
  * [x] non-HTML emails are rendered correctly
  * [x] HTML emails are rendered correctly but without images by default
    * [x] images can be loaded via clicking the respective button

### LINKED ISSUE #5871: pinchzoom on inline images does not suppress opening the download/open dropdown
* open a mail with an inline image
* pinch-zoom on top of the image
* wait about 1 second
* the download/open dropdown opens

the dropdown should probably only open on a single tap on the image, similar to how links are ignored for pinchzoom

https://github.com/tutao/tutanota/issues/1997

Note: double-tap zoom does not have this problem

### LINKED ISSUE #5913: pinchzoom on inline images without maxwidth causes rendering problems
Large inline images (>3000px width ?) without maxwidth are causing rendering problems when zooming out with pinchzoom

#1997 

## Test Notes:
- [ ] send a new mail
- [ ] add an inline image that has a width larger than 4000px
- [ ] pinchzoom is working for this email and inline image
- [ ] send a second mail
- [ ] add an inline image that has a width larger than 4000px
- [ ] remove maxwidth=100% property with the devtools before sending
- [ ] pinchzoom is working for this email and inline image
- [ ] combine both in mail and check that pinchzoom is still working

### PR DESCRIPTION
**Pull request by nokhub**
close #1997
fix #5913 
fix #5871

### CODE REVIEW

File: src/misc/HtmlSanitizer.ts [hunk 1]
```diff
@@ -286,6 +286,12 @@ export class HtmlSanitizer {
 			if (htmlNode.style.position) {
 				htmlNode.style.removeProperty("position")
 			}
+
+			// Don't allow inline images to have a bigger width than the email itself
+			// Otherwise this would lead to weird rendering with very large images and pinch zoom
+			if (htmlNode.tagName === "IMG") {
+				htmlNode.style.maxWidth = "100%"
```
Comment (charlag) [inline src/misc/HtmlSanitizer.ts:293]: does this work in all cases?
Wouldn't it break emails sometimes?

Comment (charlag) [reply src/misc/HtmlSanitizer.ts:293]: Probably fine, just the tests need to be fixed

Comment (nokhub) [reply src/misc/HtmlSanitizer.ts]: it actually turned out to be a bit problematic with placeholders, that's why we changed the replacement order a bit #e4fafa55ed1edeb262095f53bd2333c4507fbac8
