### PR TITLE
Fix issues with temporary login

### LINKED ISSUE #4559: ProgrammingError at signup for paid subscription in desktop client
Reproduced in Linux desktop and Android clients:

1. Sign up in desktop client for a paid account with paypal as payment method
2. Click on the "Buy" button as last step
-> Feedback v3.100.0 - ProgrammingError - UNKNOWN - linux (error might be only shortly visible before switching to login view or stay)

The error is also reproducible in the previous version. The error does neither occur in the web client nor when signing up for a Free account. It looks like we try to access the local storage although it is not initialized yet. It could be related to the background login for saving the payment data or receiving a websocket event while the local storage is not initialized (any more). This is the call stack:

Client: linux
Type: UNKNOWN
Tutanota version: 3.100.0
Timestamp (UTC): Tue, 06 Sep 2022 09:33:55 GMT
User agent:
Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop-test/3.100.0 Chrome/102.0.5005.167 Electron/19.0.14 Safari/537.36
ProgrammingError
Error message: Cache storage is not initialized
Stacktrace:
ProgrammingError: Cache storage is not initialized
at get inner [as inner] (asset://app/worker.js:12:136392)
at Sl.getLastUpdateTime (asset://app/worker.js:12:137260)
at asset://app/common-d62b1623.js:1:12805
at Object.handleMessage (asset://app/common-d62b1623.js:1:16295)
at asset://app/common-d62b1623.js:1:15548
at _worker.onmessage (asset://app/common-d62b1623.js:1:15117)

### PR DESCRIPTION
**Pull request by charlag**
The first issue is attempting to get last update time in OfflineIndicatorViewModel. It was trying to wait for partial login but unfortunately temporary login is also partial login.

We didn't want to just return null in this case as it might get interpreted incorrectly and instead we returned a sum type with the exact case and ignore uninitialized storage in this case.

The other issue was with LoginController and LoginListener not properly resetting themselves on logout (e.g. after temporary login) and giving incorrect results.

The third issue was with PostLoginActions initializing MailModel for temporary login. If a real login into another account is attempted afterwards it would lead to more errors.

To fully solve the problem we should rethink how temporary login affects the rest of the app and perhaps skip most of the things that happen during normal login.

fix #4559

### CODE REVIEW

File: src/api/main/LoginController.ts [hunk 1]
```diff
@@ -256,6 +256,10 @@ export class LoginControllerImpl implements LoginController {
 			await this.userController.deleteSession(sync)
 			this.userController = null
 			this.partialLogin = defer()
+			this.fullyLoggedIn = false
+			const locator = await this.getMainLocator()
+			locator.loginListener.reset()
```
Comment (vitoreiji) [inline src/api/main/LoginController.ts:261]: Should also call `reset()` in the constructor instead of initializing on the class level.

**Review by vitoreiji — APPROVED** [review]
