### PR TITLE
Fix getting into invalid login state

### LINKED ISSUE #5094: Invalid DB state after unsuccessful login
For 3.108.12 we have a number of reports like

```
ProgrammingError
Error message: Already opened database for user [USERID] when trying to open db for [USERID]
```

In the attached logs we always see either of

```
 Error message: Trying to do a network request with encrypted entity but is not fully logged in yet, type: GroupInfo,"LoginIncompleteError: Trying to do a network request with encrypted entity but is not fully logged in yet, type: GroupInfo\n    at Ka._validateAndPrepareRestRequest (asset://app/worker.js:1:29814)\n    at async Ka.load (asset://app/worker.js:1:25084)\n    at async Na.load (asset://app/worker.js:1:17451)"
```

```
 Error message: Trying to do a network request with encrypted entity but is not fully logged in yet, type: MailFolder,"LoginIncompleteError: Trying to do a network request with encrypted entity but is not fully logged in yet, type: MailFolder\n    at Ka._validateAndPrepareRestRequest (asset://app/worker.js:1:29814)\n    at async Ka.loadRange (asset://app/worker.js:1:25702)\n    at async Na.populateNewListWithRange (asset://app/worker.js:1:19941)\n    at async Na.loadRange (asset://app/worker.js:1:19504)"
```

It seems like database is in the odd state where we have enough information to think we can do an offline login but it fails at a certain point, probably `PostLoginActions` (seems like it might be `MailModel#init()` in some cases). If `PostLoginActions` fail we won't move past the login screen but we won't reset the login state on the worker side. Next time we try to log in we will get an error that offline db is already opened and probably will proceed with ephemeral database.

At the very least we should treat an error during `PostLoginActions#onPartialLoginSuccess()` as a login failure and reset the login state. Ideally we would also find out why the database is only partially populated and how to reproduce it.

A workaround for now is to tell users to delete their credentials but this issue can happen again and we should prevent it.

## Test notes
 - [ ] Check login in browser
 - [ ] Check login with new credentials in desktop client
 - [ ] Check login with existing credentials with free account in desktop client
 - [ ] Check login with existing credentials with free account in desktop client failing due to offline and then succeeding when the network is there
 - [ ] Check login with existing credentials with premium account
 - [ ] Check login with existing credentials with premium account being offline and then coming online
 - [ ] Check going offline in browser after login but before mail model is initialized (slow down network) and that the mail model is re-initilized correctly with network if we switch to calendar and back to mail

### PR DESCRIPTION
**Pull request by charlag**
Login state is tracked differently for worker and page sides of the app. When `LoginFacade` (worker) thinks that the partial login is done `LoginController` (page) can still fail, mostly due to `MailModel#init()` being part of the login process.

We suspect that the issue happened due to page login failing. On the next try we would try to log in again even though the login is already done from the worker's perspective.

We had two main options: either aborting worker login when page login (including `PostLoginActions`) fails or taking `MailModel#init()` out of the login process. We went with the latter because most of the code was already written with the assumption that `MailModel` is initialized asynchronously. This has an added benefit of letting user into the app faster. Later we can add some placeholders for the MailView to improve the experience even further.

Since `MailModel#init()` is not part of the login anymore we had to find a way to retry the loading if it fails. We've adapted `MailModel` to make the retry work (which we would need to do in either case) and added another `init()` call on full login as well on using the mailModel. We've changed `MailModel` to not propagate the init errors to the rest of the app but to make them wait. This works better for most places because we don't need additional error handling.

fix #5094

### CODE REVIEW

File: src/mail/view/MailView.ts [hunk 1]
```diff
@@ -556,6 +565,9 @@ export class MailView extends BaseTopLevelView implements TopLevelView<MailViewA
 	}
 
 	private setUrl(url: string) {
+		if (typeof url === "undefined") {
+			throw new Error("undefined mail url!")
```
Comment (ganthern) [inline src/mail/view/MailView.ts:569]: is this a shouldn't-happen programming error?

File: src/mail/view/MailView.ts [hunk 2]
```diff
@@ -248,12 +248,19 @@ export class MailView extends BaseTopLevelView implements TopLevelView<MailViewA
 				if (isSelectedPrefix(MAIL_PREFIX)) {
 					this.setUrl(url)
 				} else {
+					if (typeof url === "undefined") {
+						throw new Error("undefined mail url!")
```
Comment (ganthern) [inline src/mail/view/MailView.ts:252]: Programming error?

File: src/mail/view/MailView.ts (hunk 1 above)
Comment (charlag) [reply src/mail/view/MailView.ts]: I swapped it for `assertNotNull` which cannot use `ProgrammingError` unfortunately but maybe it even should have it's own `AssertionError` or NPE of sorts.

Comment (ganthern) [reply src/mail/view/MailView.ts]: even better!

**Review by ganthern — APPROVED** [review]
