### PR TITLE
Fix window is not defined when starting the desktop app

### LINKED ISSUE #6795: Desktop app doesn't start because of window is not defined
After #6736 the desktop app isn't starting anymore because of an early use of deviceConfig. The message thrown is: ```window is not defined```

Steps to reproduce:
1. Checkout the master branch
2. Run npm ci
3. Try to run the desktop app
4. See the error in terminal

### PR DESCRIPTION
**Pull request by murilopereirame**
After #6736 the theme was being called too early because of a chain of calls from CalendarModel -> CalendarUtils -> CalendarGuiUtils -> ... -> theme -> DeviceConfig throwing an error inside deviceConfig.

This commit moves the function canFullyEditEvent to CalendarViewModel making sure that all the GUI stuff have been already loaded.

fix #6795

### CODE REVIEW

**Review by wrdhub — APPROVED** [review]

File: src/misc/DeviceConfig.ts [hunk 1]
```diff
@@ -108,7 +108,7 @@ export class DeviceConfig implements CredentialsStorage, UsageTestStorage, NewsI
 			hasParticipatedInCredentialsMigration: loadedConfig.hasParticipatedInCredentialsMigration ?? false,
 			syncContactsWithPhonePreference: loadedConfig.syncContactsWithPhonePreference ?? {},
 			isCalendarDaySelectorExpanded: loadedConfig.isCalendarDaySelectorExpanded ?? false,
-			mailAutoSelectBehavior: loadedConfig.behaviorAfterMoveEmailAction ?? (isApp() ? ListAutoSelectBehavior.NONE : ListAutoSelectBehavior.OLDER),
```
Comment (murilopereirame) [inline src/misc/DeviceConfig.ts:111]: fix #6781
