### PR TITLE
Fix cannot see mails older than offline range with free account

### LINKED ISSUE #10694: Cannot see mails older than offline storage range
**Steps to reproduce:**
- Login as a free user
- Have some mails newer than 31 days in Inbox, the rest should be older.
- Logout and login to run offline cleaner
- See that only mails newer than 31 days are shown (you might have to switch folders)

## Test notes
- [ ] Issue no longer reproducible
- [ ] When list is entirely within offline range, no mailSetEntry range request is made
  - [ ] Have dev tools open to the network tab
  - [ ] Login and make sure all mails in inbox are within offline range
  - [ ] Logout and login again so offline cleaner in run
  - [ ] Logout and login again and stay in Inbox folder
  - [ ] In the network tab, check that no mailSetEntry range requests are made (look for `rest/tutanota/mailsetentry`)
  - [ ] Repeat the last two steps a few times and check that no mailSetEntry range requests are made
- [ ] When list is not entirely within offline range, mailSetEntry range requests are made and list is loaded
  - [ ] Have dev tools open to the network tab
  - [ ] Login and make sure all but one mail in inbox are within offline range
  - [ ] Logout and login again so offline cleaner in run
  - [ ] Logout and login again and stay in Inbox folder
  - [ ] In the network tab, check that a mailSetEntry range request is made (look for `rest/tutanota/mailsetentry`) and that the list is loaded correctly
  - [ ] Repeat the last two steps a few times

### PR DESCRIPTION
**Pull request by hrb-hub**
Offline cleaner was not updating range for the entries list correctly, caused by wrongly comparing the oldest entry's id against the cutoff id as if they were GeneratedId instead of CustomId.

When an element's list is fully loaded, we set the list's lower range to MIN_ID (this is different for GeneratedId and CustomId).
When MailOfflineCleaner runs, it deletes mails and entries older than the offline range cutoff, and sets the list's lower range to the cutoffId.
However, if a list is fully loaded and the oldest entry in the list is within the offline range, then the list's lower range is not set to the cutoffId but rather kept as is (MIN_ID).

Because of the incorrect comparison, MailOfflineCleaner was deleting entities older than offline range cutoff, but keeping the list's lower range set to MIN_ID, resulting in a broken state where the list is incomplete but fully loaded.

Close #10694

Co-authored-by: wrd <wrd@tutao.de>
Co-authored-by: abp <abp@tutao.de>
Co-authored-by: das <das@tutao.de>
Co-authored-by: ivk <ivk@tutao.de>
Co-authored-by: paw <paw-hub@users.noreply.github.com>

### CODE REVIEW

**Review by charlag — COMMENTED** [review]
looks good, great find! I would keep refactoring in the second commit separate from the bugfix though

File: src/common/api/common/utils/IndexUtils.ts [hunk 1]
```diff
@@ -58,6 +57,22 @@ export function typeRefToTypeInfo(typeRef: TypeRef<any>): TypeInfo {
 	return typeInfo
 }
 
+export function typeInfoToTypeRef(typeInfo: TypeInfo, appName?: AppName): TypeRef<any> {
```
Comment (charlag) [inline src/common/api/common/utils/IndexUtils.ts]: I would probably use `TypeRef<unknown>`, it is safer

File: src/common/api/common/utils/IndexUtils.ts [hunk 2]
```diff
@@ -58,6 +57,22 @@ export function typeRefToTypeInfo(typeRef: TypeRef<any>): TypeInfo {
...
+	if (appName) {
+		if (typeInfos.get(appName)?.has(typeInfo.typeId)) {
+			return parseTypeString(`${appName}/${typeInfo.typeId}`)
```
Comment (charlag) [inline src/common/api/common/utils/IndexUtils.ts]: I don't understand why we serialize the type and then parse, can't we just construct `TypeRef` right away?

File: src/common/api/common/utils/IndexUtils.ts [hunk 3]
```diff
@@ -58,6 +57,22 @@ export function typeRefToTypeInfo(typeRef: TypeRef<any>): TypeInfo {
...
+		}
+	} else {
+		for (const [app, typeInfosByTypeId] of typeInfos.entries()) {
+			if (typeInfosByTypeId.get(typeInfo.typeId)?.appId === typeInfo.appId) {
+				return parseTypeString(`${app}/${typeInfo.typeId}`)
+			}
+		}
+	}
+
+	throw new Error(`No TypeRef for TypeInfo ${typeInfo.appId}/${typeInfo.typeId}`)
```
Comment (charlag) [inline src/common/api/common/utils/IndexUtils.ts]: putting a pin in that, is it better to return `null`?

File: src/common/api/common/utils/IndexUtils.ts (hunk 1 above)
Comment (charlag) [inline src/common/api/common/utils/IndexUtils.ts]: should we make people explicitly pass the second argument? other it is too easy to forget and make it fall back to the slow path.

File: src/mail-app/workerUtils/index/IndexedDbSearchFacade.ts [hunk 4]
```diff
@@ -569,12 +575,12 @@ export class IndexedDbSearchFacade implements SearchFacade {
 		if (maxExcludedId) {
 			// timestampToGeneratedId provides the lowest id with the given timestamp (server id and counter set to 0),
 			// so we add one millisecond to make sure all ids of the timestamp are covered
-			if (!firstBiggerThanSecond(maxExcludedId, entry.id)) {
+			if (!firstBiggerThanSecondBase64Ext(maxExcludedId, entry.id)) {
```
Comment (charlag) [inline src/mail-app/workerUtils/index/IndexedDbSearchFacade.ts]: I am confused why we do it generically above but only ext in this part

File: src/typerefs/EntityUtils.ts [hunk 5]
```diff
@@ -104,30 +106,44 @@ export type StrippedEntity<T extends Entity> =
 	  >
 	| OptionalEntity<T>
 
+export const enum EntityIdEncoding {
```
Comment (charlag) [inline src/typerefs/EntityUtils.ts:110]: is there a reason we went with string-backed enum and not a number-backed one?

I'm also a bit on the fence about naming. I find it really hard to both write and read, because I need to remember which encoding is used for custom ids and which is for generated ids. At the same time, we only care about encoding and we even re-encode sometimes (like in cache).

File: src/typerefs/EntityUtils.ts [hunk 6]
```diff
@@ -505,7 +517,29 @@ export function isCustomIdType(typeModel: TypeModel): boolean {
...
+	} else {
+		throw new ProgrammingError(`unknown _id type for entity: ${typeModel.app}/${typeModel.id}`)
+	}
+}
+
+/**
+ * customIds are stored as base64url on the server and that's how we get them, but we store them locally as base64ext to make them sortable.
+ * generatedIds are stored as base64ext both on the server and locally.
+ *
+ * BEWARE: Calling this with a customId typeModel and a base64ext encoded customId will lead to unfun consequences.
```
Comment (charlag) [inline src/typerefs/EntityUtils.ts]: "unfun consequences." 😅

**Comment by charlag** [comment]
Great job on that bugfix commit message!

File: src/mail-app/workerUtils/index/IndexedDbSearchFacade.ts (hunk 4 above)
Comment (hrb-hub) [reply src/mail-app/workerUtils/index/IndexedDbSearchFacade.ts]: Because I saw that `maxExcludedId` and `minIncludedId` were `base64ext` encoded and just assumed that `entry.id` was also `base64ext` :sweat_smile: 
Good catch :heart:

File: src/typerefs/EntityUtils.ts (hunk 5 above)
Comment (hrb-hub) [reply src/typerefs/EntityUtils.ts:110]: > is there a reason we went with string-backed enum and not a number-backed one?

It was in case someone used the value directly, but I guess it's not a good enough reason :sweat_smile: 

We're also on the fence about it and are open to suggestions‥ we went with it because apart from branding the ids (which would be big change), we couldn't think of anything better :(
