### PR TITLE
Fix Web Mail Export Viewer appears on first render on desktop

### LINKED ISSUE #8427: Web Mail Export Viewer appears on first render of Mail Export Viewer on desktop
Switching to Email Export View on desktop briefly shows "Export only available on desktop"

### PR DESCRIPTION
**Pull request by hrb-hub**
Close #8427

### CODE REVIEW

**Review by BijinDev — APPROVED** [review]

File: src/mail-app/settings/MailExportViewer.ts [hunk 1]
```diff
@@ -29,12 +29,13 @@ export class MailExportViewer implements UpdatableSettingsViewer {
...
 				".fill-absolute.scroll.plr-l.pb-xl",
 				m(".h4.mt-l", lang.get("mailExportSettings_label")),
-				this.mailExportController
-					? m(MailExportSettings, {
-							mailboxDetails: mailLocator.mailboxModel.mailboxDetails(),
-							logins: mailLocator.logins,
-							mailExportController: this.mailExportController,
-					  })
+				isDesktop()
+					? this.mailExportController &&
```
Comment (charlag) [inline src/mail-app/settings/MailExportViewer.ts:33]: I would rewrite this `&&` as a ternary, mithril doesn't like `undefined`, we are just lucky that `this.mailExportController` is `null`
