### PR TITLE
Fix decryption failed on empty contact fields with Cardinality.ZeroOrOne

### LINKED ISSUE #10204: Crypto error when decrypting contact fields with a cardinality of ZeroOrOne and an empty value
Somehow some contacts ended up with their `nameSuffix` field set to an empty byte array, which is the default value for encrypted fields. This is strange because the `nameSuffix` cardinality has always been `ZeroOrOne` for which the default value is `null` (an empty byte array as a default value for an attribute of cardinality ZeroOrOne is invalid).

**Steps to reproduce:**
This is more noticeable on web
- Create a contact
- Set a breakpoint at https://github.com/tutao/tutanota/blob/7f2f70d3c9d5fb771a8a7ef5507c052288ea9e4d/src/common/api/worker/rest/EntityRestClient.ts#L621
- Edit the contact's `nameSuffix` and save
- When at the breakpoint, mutate the `patchPayload` to set the attribute's value to an empty string
- Continue execution
- Reload the page and see that the contact is no longer visible in the list and see that there's a CryptoError in the logs
  ```
  error when decrypting value on type: [tutanota,Contact] valueName: nameSuffix 
  Object { name: "CryptoError", message: "mac expected but not present" }
  ```

## Test notes
- [x] Contacts having fields with a cardinality of `ZeroOrOne` and an empty value are decrypted without errors and are shown in the list.
- [x] A warning is logged to the console when a field with a cardinality of `ZeroOrOne` and an empty value is decrypted.

### PR DESCRIPTION
**Pull request by hrb-hub**
Close #10204

### CODE REVIEW

File: src/common/api/worker/crypto/CryptoMapper.ts [hunk 1]
```diff
@@ -46,6 +46,10 @@ export function decryptValue(
 ): Nullable<ParsedValue> {
 	if (value == null) {
 		return null
+	} else if (valueType.cardinality === Cardinality.ZeroOrOne && value === "") {
+		// Might happen if cardinality was changed from ZeroOrOne -> One -> ZeroOrOne
```
Comment (charlag) [inline src/common/api/worker/crypto/CryptoMapper.ts:50]: oh dang that's a good one but is it always safe to do? are there cases where we meant to put an empty string in there?

Comment (hrb-hub) [reply src/common/api/worker/crypto/CryptoMapper.ts:50]: As far as I can tell, we only do it for existing attributes of cardinality One
