### PR TITLE
fix firefox pdf attachments bug

### LINKED ISSUE #3983: Attachments are opened in the same tab as the web client in firefox
* in firefox, click on an attached PDF
* It automatically opens in the same tab

If you are using the client without saved credentials, this also results in you being logged out.

This doesn't happen for all filetypes, e.g. images and text files are just downloaded

We should either make sure that the PDF opens in a separate tab _or_ just download it and not try to open it automatically. This seems to be some firefox specific behaviour, as in chromium PDFs are just downloaded.

Some users have noted that firefox no longer offers to open images in a preview after downloading. We might want to do this manually, if it's what users expect.

### PR DESCRIPTION
**Pull request by johnbotris**
Contains a bugfix (more of a workaround) + a cleanup, see commit messages

fix #3983

### CODE REVIEW

**Review by sarashub — APPROVED** [review]

File: src/global.d.ts [hunk 1]
```diff
@@ -49,6 +49,11 @@ declare global {
 		 * It's existence can be used to determine whether or not we are inside a web dialog
 		 * */
 		nativeAppWebDialog: NativeApp | undefined,
+
+		// Type polyfills for FileController
+		// Unsure if they are even still needed at all
```
Comment (charlag) [inline src/global.d.ts:54]: they are not needed
