### PR TITLE
[desktop] use 'wheel' event instead of window.onmousewheel

### LINKED ISSUE #2165: Scaling does not work
v3.75.3

ctrl + mousewheel does not scale app anymore so it's impossible to change the font size.

### PR DESCRIPTION
**Pull request by ganthern**
There seems to be an issue that prevents the wheel listener that's set in the initial execution of the preload script from receiving WheelEvents that were not dispatched manually.

If the listener is attached after the web app has initialized, the problem doesn't occur.

 fix #2165

### CODE REVIEW

**Comment by charlag** [comment]
Please put issue reference into issue body, not the title, otherwise github doesn't link it

**Comment by ganthern** [comment]
> Please put issue reference into issue body, not the title, otherwise github doesn't link it

that's a weird choice

File: src/desktop/ApplicationWindow.js [hunk 1]
```diff
@@ -122,6 +122,7 @@ export class ApplicationWindow {
 				// the preload script changes to the web app
 				contextIsolation: false,
 				webSecurity: true,
+				enableRemoteModule: false,
```
Comment (charlag) [inline src/desktop/ApplicationWindow.js:125]: Is this related to the zooming? I'm okay with including it but maybe in a separate commit or at least commit should say why it's here.

Comment (ganthern) [reply src/desktop/ApplicationWindow.js:125]: it's not related. It is split into its own commit now.

Comment (charlag) [reply src/desktop/ApplicationWindow.js:125]: Thanks! Shouldn't affect us, right? I think we don't use it anymore.

Comment (ganthern) [reply src/desktop/ApplicationWindow.js:125]: we removed remote usages a while ago and as of electron 9 there's even a deprecation warning if the module is used without explicitly enabling it in the webPreferences, which we didn't do. this change shouldn't affect us but removes the possibility of any rogue code messing with the module.
