### PR TITLE
Fix unwanted autologin when cancelling dialogs on login screen

### LINKED ISSUE #2549: closing a dialog on login page will trigger login
You have to tick "Store password" when logging in for this to work
1. Go to the login view (where you can enter Email, password, etc.)
2. Click on **More > Different account > Sign up** , then once the Dialog opens, close it
3. a login will automatically be triggered

alternative step 2: Click on **More > Lost account access** , then close again

https://user-images.githubusercontent.com/70587561/103290192-3d532980-49e9-11eb-8a0d-40c16cbcedfc.mp4

### PR DESCRIPTION
**Pull request by yopfox**
When credentials are stored and the user cancels:

- the dialog for signing up a new account
- the dialog for taking over an account due to inactivity
- the dialog for having lost access to an account

the desired behavior should be that the user is not logged back into the
previously saved account.

To ensure this the parameters for redirecting to the login page have been
changed to not log the user in automatically after cancelling the mentioned
dialogs.

fixes #2549
Co-authored-by: @nif-tutao

### CODE REVIEW

File: src/subscription/UpgradeSubscriptionWizard.ts [hunk 1]
```diff
@@ -188,15 +188,9 @@ export async function loadSignupWizard(subscriptionParameters: SubscriptionParam
...
-			m.route.set("/login", {
-				loginWith: signupData.newAccountData.mailAddress,
-			})
-		} else {
-			m.route.set("/login", {
-				noAutoLogin: true,
-			})
-		}
+		m.route.set("/login", {
+			noAutoLogin: true,
```
Comment (ganthern) [inline src/subscription/UpgradeSubscriptionWizard.ts:192]: I think in this case it would be better to add `noAutoLogin: true` to the case with `newAccountData` so we get to the login form if the account was created (so we keep the branch and pass both `loginWith` and `noAutoLogin` to the `m.route` call)

For example, select a free account in signup, select mail address, wait for it to be created and the recovery code is shown and then cancel out of the wizard until you are back to the login screen -> it should show the form with the new address pre-filled to indicate that the account was created.

make sure to review the test notes after this is changed

**Review by ganthern — CHANGES_REQUESTED** [review]

**Review by ganthern — APPROVED** [review]
