### PR TITLE
Fix perpetual redraw caused by EstimatingProgressMonitor.ts

### LINKED ISSUE #9786: Uncleared progressEstimation interval in EstimatingProgressMonitor.ts causes perpetual redraws
This can be easier to spot by adding logs locally. Alternatively breakpoints can be used. Logs/breakpoints can be added to:
- https://github.com/tutao/tutanota/blob/dc7a95166f52caf83bccf836bb820de64e839194/src/common/api/common/utils/EstimatingProgressMonitor.ts#L40
- https://github.com/tutao/tutanota/blob/dc7a95166f52caf83bccf836bb820de64e839194/src/mail-app/mail/view/MailListView.ts#L320

**Steps to reproduce:**
- Make sure the client is fully synced.
- Add logs/breakpoints.
- Logout and log back in.
- See that the logs/breakpoint are perpetually hit.

**Test notes:**
- [x] Issue no longer reproduces.
- [x] Client syncing works as expected.

### PR DESCRIPTION
**Pull request by hrb-hub**
Perpetual redraw caused by an uncleared progressEstimation interval can occur if `completed` isn't called on EstimatingProgressMonitor.

Close #9786

### CODE REVIEW

File: src/common/api/common/utils/EstimatingProgressMonitor.ts [hunk 1]
```diff
@@ -37,6 +38,7 @@ export class EstimatingProgressMonitor implements IProgressMonitor {
 	public continueEstimation() {
 		clearInterval(this.progressEstimation)
 		this.progressEstimation = setInterval(() => {
+			console.log(`${this.monitorTag}: ${this.percentage().toFixed(2)}% of work completed`)
```
Comment (charlag) [inline src/common/api/common/utils/EstimatingProgressMonitor.ts]: do we want to keep it? Is it not a bit spammy?

Comment (hrb-hub) [reply src/common/api/common/utils/EstimatingProgressMonitor.ts]: I also wasn't super sure about it, which is why I kept it in a separate commit :sweat_smile: .
It can be a bit spammy, but it would make uncleared intervals easier to spot, not sure if it's worth it though. What do you think?

Comment (hrb-hub) [reply src/common/api/common/utils/EstimatingProgressMonitor.ts]: I thought about a bit more and decided to just drop logging.
