### PR TITLE
Prevent requesting Customer instance when external user (fixes NotAuthorizedError when secure external)

### LINKED ISSUE #9574: NotAuthorizedError when replying to secure external email
**Describe the bug**
Replying to secure external email from secure mailbox > NotAuthorizedError

**To Reproduce**
1. Send secure external email 
2. Access secure external mailbox with the received URL and password
3. Reply from the secure mailbox

**Additional context**
The email is sent and received but in the conversation list of the secure external mailbox not immediately visible, only in sent folder.

```Feedback v304.250825.0 - NotAuthorizedError - EXTERNAL - Browser
Client: Browser
Type: EXTERNAL
Tutanota version: 304.250825.0
Timestamp (UTC): Mon, 01 Sep 2025 11:49:25 GMT
Time zone: Europe/Berlin
User agent: Mozilla/5.0 (X11; Linux x86_64; rv:142.0) Gecko/20100101 Firefox/142.0
NotAuthorizedError
Error message: 403: OZ463nn--3-9 | GET /rest/sys/customer/NZagiJr--3-9
Stacktrace:
ja@https://app.tuta.com/common-min-xa4-R8VT.js:1:39380
request/</y.onload@https://app.tuta.com/mail-worker.js:18:87364
```

[worker_tutanota.log](https://github.com/user-attachments/files/22077575/worker_tutanota.log)
[main_tutanota.log](https://github.com/user-attachments/files/22077574/main_tutanota.log)

### PR DESCRIPTION
**Pull request by paw-hub**
For UserSatisfactionUtils, we disallow showing ratings, as it requires checking a customer creation date, and since we aren't a customer, this is not applicable.

In the case of getTemplateLanguages, we were silently ignoring the NotAuthorized error, but we still should avoid requesting things that will fail.

Closes #9574

### CODE REVIEW

**Comment by charlag** [comment]
Nice, `UserSatisfactionDialog` is failing though

**Comment by paw-hub** [comment]
:(

File: test/tests/misc/UserSatisfactionDialogTests.ts [hunk 1]
```diff
@@ -2,7 +2,7 @@ import o from "@tutao/otest"
 import { evaluateRatingEligibility, isEventHappyMoment, RatingDisallowReason } from "../../../src/common/ratings/UserSatisfactionUtils.js"
 import { DeviceConfig } from "../../../src/common/misc/DeviceConfig.js"
 import { object, verify, when } from "testdouble"
-import { CommonLocator, initCommonLocator } from "../../../src/common/api/main/CommonLocator.js"
+import { CommonLocator, initCommonLocator, locator } from "../../../src/common/api/main/CommonLocator.js"
```
Comment (charlag) [inline test/tests/misc/UserSatisfactionDialogTests.ts]: `locator` is not used but is still imported

Comment (paw-hub) [reply test/tests/misc/UserSatisfactionDialogTests.ts]: :(
