### PR TITLE
let context menu click noop if webContents is unavailable, fix #2112

### LINKED ISSUE #2112: Cannot read property 'webContents' of undefined
```
Client: darwin
Tutanota version: 3.74.2
User agent:
Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) tutanota-desktop/3.74.2 Chrome/80.0.3987.163 Electron/8.2.3 Safari/537.36
TypeError
Error message: Cannot read property 'webContents' of undefined
Stacktrace:
TypeError: Cannot read property 'webContents' of undefined
at click (src/desktop/DesktopContextMenu.js:20:165)
at MenuItem.click (../../../../../electron/js2c/browser_init.js:1501:9)
at Function.executeCommand (../../../../../electron/js2c/browser_init.js:1762:13)
```

### PR DESCRIPTION
**Pull request by ganthern**
BrowserWindow arg to the handler will be undefined if no window is open.
Since context menu actions make no sense without context, the click
handlers should noop in this case.

### CODE REVIEW

File: test/client/desktop/DesktopContextMenuTest.js [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+		lang: {get: key => key}
+	}
+
+	const electron = {
+		clipboard: {
+			writeText: () => {}
+		},
+		Menu: n.classify({
+			prototype: {
+				append: function () {},
```
Comment (charlag) [inline test/client/desktop/DesktopContextMenuTest.js:21]: can write it like
```js
append() {}
```

even in objects
Just wanted to point out.
