### PR TITLE
fix mailbody issues

### LINKED ISSUE #4309: MailBody is flashing when mail is updated
First Case:
1. Have unread email in mailbox
2. Open it with 2 or 3 column layout
3. See that email is marked as read
4. See that mail body flashes when update arrives

Second Case (arguably the worse one):
1. open a mail in the two- or three-column layout
2. click on another one
3. see that the old mailbody overstays its welcome and gets removed too late

### PR DESCRIPTION
**Pull request by johnbotris**
fix the flicker when the unread state is changed:
Instead of recreating the view model we just update the mail in the existing one. This introduced the issue that the existing mail body would not be updated so we have to manually call `loadAll`, and also re-call `replaceInlineImages` hence the funky business with streams

fix the flickering when `contrastFixNeeded` is true: this is also fixed by not recreating the viewModel

fix the rendering of a new mailbody:
Mithril was reusing the dom element when switching from rendering a mail body to rendering the progress spinner. Because of the shadow dom, the old content was remaining. I opted to add keys to the different elements to force mithril to re-render it completely.

fix #4309

### CODE REVIEW

File: src/mail/view/MailViewerViewModel.ts [hunk 1]
```diff
@@ -478,8 +497,12 @@ export class MailViewerViewModel {
 
 	/** @return list of inline referenced cid */
 	private async loadMailBody(mail: Mail): Promise<string[]> {
-		// Short-circuit if we already loaded everything. Will avoid resetting contentBlockingStatus or mail body.
-		if (this.sanitizeResult) {
+		if (
+			this.renderedMail != null && haveSameId(mail, this.renderedMail)
+			&& mail.state !== MailState.DRAFT
```
Comment (ganthern) [inline src/mail/view/MailViewerViewModel.ts:502]: what is the purpose of singling out drafts here?

Comment (johnbotris) [reply src/mail/view/MailViewerViewModel.ts:502]: we don't want to exit early for drafts here because they may actually have been edited, whereas non-drafts can't be edited so we don't need to reload them if we have already loaded them. I'll improve the comment

**Review by ganthern — APPROVED** [review]

**Comment by charlag** [comment]
Do we need additional test notes? I think we should test mail viewer very closely
