### PR TITLE
Fallback to blue if an invalid color is passed

### LINKED ISSUE #6515: calendar freeze on invalid color gba
```
Logger.ts:99 Error: Assertion failed: Invalid color code: #gba(0, 0, 0, 0)
    at b (Utils.js:83:15)
    at re (Color.ts:21:2)
    at oe (Color.ts:9:22)
    at Na (CalendarGuiUtils.ts:522:9)
    at Dn.view (CalendarEventBubble.ts:46:13)
    at Function.s (mithril.js:186:16)
    at mithril.js:301:46
    at mithril.js:306:3
    at u (mithril.js:221:8)
    at c (mithril.js:205:5)
```

## Test notes
- [ ] Calendar colors still work correctly

### PR DESCRIPTION
**Pull request by paw-hub**
It doesn't make sense to error here and make the entire app unusable, so we just fallback to a blue color.

Fixes #6515

### CODE REVIEW

File: src/calendar/gui/CalendarGuiUtils.ts [hunk 1]
```diff
@@ -726,8 +727,11 @@ export const iconForAttendeeStatus: Record<CalendarAttendeeStatus, AllIcons> = O
 	[CalendarAttendeeStatus.ADDED]: Icons.CircleEmpty,
 })
 export const getGroupColors = memoized((userSettingsGroupRoot: UserSettingsGroupRoot) => {
-	return userSettingsGroupRoot.groupSettings.reduce((acc, gc) => {
-		acc.set(gc.group, gc.color)
+	return userSettingsGroupRoot.groupSettings.reduce((acc, { group, color }) => {
+		if (!isValidColorCode(color)) {
+			color = blue
```
Comment (charlag) [inline src/calendar/gui/CalendarGuiUtils.ts:732]: `defaultCalendarColor`

**Review by charlag — APPROVED** [review]
