### PR TITLE
Fix show contact not displaying the contact

### LINKED ISSUE #7256: Clicking "show contact" on a mail does not redirect to the selected contact.
**Bug in app**

**Describe the bug**
Clicking on "show contact" on a mail (clicking on the mail address) does not redirect to the selected contact, but instead just opens the contact view in the last selected state.

**To Reproduce**
1. Go to a mail that has a contact connected to it
2. Click on the sender mail address
3. Click on "Show Contact"
4. See that you are redirect to the contact view, but the contact is not selected 
    (it might be selected by chance, if the contact is indeed the first one in the list)

**Expected behavior**
Clicking on "show contact" on a mail directly redirects to the selected contact in the contact view.

 - Version v235.240718.0

## Test notes
- [ ] In single column view
  - [ ] Opening the contacts view via the tab shows the list and not the details view
  - [ ] Pressing 'show contacts' in the dropdown on a mail address displays the contact in the details view
 - [ ] In the two and three column views
   - [ ] Opening the contacts view via the tab shows the list and the details view with the last contact to be selected
   - [ ] Pressing 'show contacts' in the dropdown on a mail address displays the contact selected in the contact view

### PR DESCRIPTION
**Pull request by rezbyte**
This PR makes the show contact option open the contacts view with the relevant contact selected. It opens the details view on single column view. There is also a commit which removes `targetContactId` because we never set it to anything other than `null`.

Closes #7256.

### CODE REVIEW

File: src/contacts/view/ContactViewModel.ts [hunk 1]
```diff
@@ -46,17 +45,18 @@ export class ContactViewModel {
 	async init(contactListId?: Id, contactId?: Id) {
 		// update url if the view was just opened
 		if (contactListId == null && contactId == null) this.updateUrl()
-		if (this.contactListId) return
+
+		// If we have already initialized the view model with the user's contact list, then select the contact within it
+		if (this.contactListId && typeof contactId === "string") {
```
Comment (charlag) [inline src/contacts/view/ContactViewModel.ts:50]: similarly I am trying to understand why `loadAndSelect()` below is not sufficient

File: src/contacts/view/ContactViewModel.ts [hunk 2]
```diff
@@ -72,12 +72,10 @@ export class ContactViewModel {
...
 	private updateUrl() {
 		const contactId =
-			this.targetContactId != null
-				? this.targetContactId
-				: !this.listModel.state.inMultiselect && this.listModel.getSelectedAsArray().length === 1
+			!this.listModel.state.inMultiselect && this.listModel.getSelectedAsArray().length === 1
 				? getElementId(this.listModel.getSelectedAsArray()[0])
 				: null
-		if (contactId) {
+		if (contactId && !styles.isSingleColumnLayout()) {
```
Comment (charlag) [inline src/contacts/view/ContactViewModel.ts:78]: viewModel should not be aware of styles

**Comment by charlag** [comment]
It works great but I am not sure why it didn't work before…

File: src/contacts/view/ContactView.ts [hunk 3]
```diff
@@ -816,6 +816,10 @@ export class ContactView extends BaseTopLevelView implements TopLevelView<Contac
 		} else {
 			this.contactViewModel.init(args.listId, args.contactId)
 		}
+
+		// Show the details of the contact on mobile instead of just all contacts
+		const isWithContact = !(args.Id == null && args.contactId == null)
```
[the remark this answers is not in the document]
Comment (rezbyte) [reply src/contacts/view/ContactView.ts:821]: `onSingleSelection()` is not called when the contacts view is opened from another view due to the lack of user interaction.  The show contacts button just sets the route to the contacts page.

File: src/contacts/view/ContactViewModel.ts (hunk 1 above)
Comment (rezbyte) [reply src/contacts/view/ContactViewModel.ts:50]: Good point, I could merge this into the assignment on line 55.
```js 
this.contactListId = this.contactListId
			? this.contactListId
			: assertNotNull(await this.contactModel.getContactListId(), "not available for external users")
```

File: src/contacts/view/ContactViewModel.ts (hunk 2 above)
Comment (rezbyte) [reply src/contacts/view/ContactViewModel.ts:78]: This is a good point. The proper alternative would be to have an additional parameter in `init()` to handle whether the contact should be remembered  or another function altogether. It is a refactor however so I choose this instead to avoid stepping on toes. I will push a commit with a refactor and it can be dropped if it is not preferable.

Comment (rezbyte) [reply src/contacts/view/ContactViewModel.ts]: I have pushed a refactored approach. It can be changed/dropped if needed.

**Review by wec43 — APPROVED** [review]
No obviously problem I can see.
