### PR TITLE
Fix back swipe doesn't return to mail tab after multi-selecting contacts

### LINKED ISSUE #6181: Back swipe/press does not return to email tab after multi-selecting contacts
**Bug in mobile app**

**Describe the bug**
After a back event (back swiping or pressing the back button) from performing a multi-select in the contacts view, further back events will not return to the emails tab. The back events continue to be broken even after switching out of and back to the contacts view. Only opening a contact, then causing another back event makes the next back event return the emails tab.

**To Reproduce**
1. Go to the contacts view
2. Do a multi-select on some contacts
3. Back swipe or press back to close the multi-select
4. Back swipe or press back again
5. The view is not returned to the mail view

**Expected behavior**
The final back swipe returns the view to the emails tab.

**Smartphone (please complete the following information):**
 - Device: Pixel 4a
 - OS: Android
 - Version 13

**Additional context**
It seems that after canceling the multi-select, `this.getSelectedContacts().length` has a value of `1` instead of the expected `0`.

## Test Notes
* [ ] Selecting one contact and pressing/swiping back returns to contact list
* [ ] Pressing back again returns to mail list view
---
* [ ] Selecting all contacts trough toolbar works
* [ ] Pressing/Swiping back unselect all contacts
* [ ] Pressing back again returns to mail list view
---
* [ ] Multi selecting contacts trough long press works
* [ ] Pressing/Swiping back unselect all selected contacts
* [ ] Pressing back again returns to mail list view

### PR DESCRIPTION
**Pull request by murilopereirame**
When the user multi-select any quantity of contacts at the ContactView and after swiping/pressing back two times it doesn't return to MailList view.

This commit makes sure to just handle the back actions and clear the selection if there's any contact selected, otherwise do the default app handling for back swipe/press.

fix #6181

### CODE REVIEW

File: src/misc/ListModel.ts [hunk 1]
```diff
@@ -542,6 +542,10 @@ export class ListModel<ElementType extends ListElement> {
 		return this.state.items.length === 0 && this.state.loadingStatus === ListLoadingState.Done
 	}
 
+	isSelectionEmpty(): boolean {
+		return this.state.selectedItems.size === 0
```
Comment (charlag) [inline src/misc/ListModel.ts:546]: is this the right thing to check? Shouldn't we check multiselect mode instead?

Comment (charlag) [reply src/misc/ListModel.ts:546]: if we open something and then go back to the list isn't it still selected?

Comment (murilopereirame) [reply src/misc/ListModel.ts:546]: I think we can´t leave the page when the ```multiSelect``` is on before exiting the multi selection. Also, I just realized that we can start a multi selection with 0 items and checking for ```selectedItems === 0``` will make the app go back instead of disabling the multi selection

**Review by charlag — APPROVED** [review]
