### PR TITLE
Have Rich Text Toolbar actions for signature editor match mail editor

### LINKED ISSUE #9666: Loading an image into signature not possible
**Bug when on android Tuta apps**

Describe the bug/To Reproduce
Settings > Email > Email signature
Change the signature from "Default" to "Custom"
Press on the small image icon in the upper right-hand corner
nothing happens. No window opens

Expected Behaviour
The options between mail editor and signature editor are consistent. Remove the option from the app.

Devices:
Pixel 4a Android 13
Tuta Mail App 308.250911.0

Additional Context
Doing the same thing on iPhone 16 worked without any issues

**Estimated : 2h**

## Test notes
- [ ] On desktop or web, the insert image option shows up for the signature editor and is usable
- [ ] On mobile app, the insert image option does not show up

### PR DESCRIPTION
**Pull request by wrdhub**
Close #9666

### CODE REVIEW

File: src/mail-app/settings/EditSignatureDialog.ts [hunk 1]
```diff
@@ -32,7 +32,7 @@ export function show(props: TutanotaProperties) {
 			.setValue(getSignature(selectedType, defaultSignature, currentCustomSignature))
 			.enableToolbar()
 			.setToolbarOptions({
-				imageButtonClickHandler: insertInlineImageB64ClickHandler,
+				imageButtonClickHandler: isApp() ? null : insertInlineImageB64ClickHandler,
```
Comment (charlag) [inline src/mail-app/settings/EditSignatureDialog.ts:36]: I would put a reason either here or in the commit message or both.

Inline images require transporting them over IPC boundary and we don't have a suitable way to do that yet.

**Review by hrb-hub — APPROVED** [review]
