### PR TITLE
Fix password change credentials 

### LINKED ISSUE #5166: Stored credentials are not updated after changing password
When you change the password on one client, stored credentials on all other clients are not updated after the first login. The user is prompted for a password each time. 

This affects all platforms.

## Test Notes:
* [ ] Premium Account
  * [ ] login on two devices, both with stored credentials
    * [ ] change credentials on one of the two devices
    * [ ] you should get logged out of the second device
    * [ ] click on the stored credentials on the device where you just got logged out
    * [ ] you are prompted to type in the new password and can use the mailbox afterwards
    * [ ] log out
    * [ ] when you log in again you are not asked for credentials again and everything works fine
  * [ ] have stored credentials on two devices but only be logged in on one device
    * [ ] change password on the device where you're logged in
    * [ ] shows same behavior like above
  * [ ] use an account that has a second factor registered and store credentials on two devices
    * [ ] you can change the password without being prompted to use the second factor
    * [ ] on the other you are prompted to use the second factor FIXME
  * [ ] login on two devices, both with stored credentials
    * [ ] change credentials on one of the two devices
    * [ ] you should get logged out of the second device
    * [ ] deactivate internet connection
    * [ ] click on the stored credentials on the device where you just got logged out
    * [ ] offline login works fine
    * [ ] activate internet again
    * [ ] try to reconnect and you are prompted for the password again FIXME
* [ ] Free Account
  * [ ] login on two devices, both with stored credentials
    * [ ] change credentials on one of the two devices
    * [ ] you should get logged out of the second device
    * [ ] click on the stored credentials on the device where you just got logged out
    * [ ] the credentials are deleted completely
    * [ ] the mailbox works after you have logged in again
  * [ ] have stored credentials on two devices but only be logged in on one device
    * [ ] change password on the device where you're logged in
    * [ ] shows same behavior like above
  * [ ] use an account that has a second factor registered and store credentials on two devices
    * [ ] you can change the password without being prompted to use the second factor
    * [ ] click on the stored credentials on the device where you just got logged out
    * [ ] the credentials are deleted completely
    * [ ] the mailbox works after you have logged in again and were prompted for the second factor
 * [ ] External Login
   * [ ] when the tutanota sender changes the shared password and sends a new mail, the old external login link does not work anymore (no login attempt possible)
   * [ ] if the password is changed (and new mail is sent) while logged in, the external user can keep using the mailbox until they log out, then the outdated link message is shown

## Regressions
* [ ] the phishing/spam banner still works
* [ ] the phishing/spam banner does not show tutanota.com links for non-admin whitelabel users
* [ ] creating more calendars works for premium only
* [ ] sending calendar invite still works
* [ ] calendar event popup still shows the bell icon for alarms
* [ ] creating users works
* [ ] creating aliases works
* [ ] creating contacts works
* [ ] in single-column mode, the bottom nav only shows the calendar/contact/search buttons for internal users
* [ ] the progress bar in the header works as expected when syncing
* [ ] header shortcuts (contact/calendar etc) work, but only while logged in
* [ ] contact form requests and login work
* [ ] recovering a login works with recovery dialog and for resetting the 2nd factor
* [ ] editing the custom external notification mail for whitelabel still works
* [ ] inbox rules are still applied and can be edited
* [ ] password strength indicator still works (try using the user's name, mail address, ....)
* [ ] out of office notifications work as expected
* [ ] trying to use a business feature (like adding a template group) shows the business upgrade dialog on plain premium
* [ ] we can open the mailbox from a mailto link or a notification in desktop
* [ ] calendar opens from an alarm notification
* [ ] search for longer than the 30 days (?) still requires premium
* [ ] the search overlay only shows the "change time period" text to premium
* [ ] adding groups works
* [ ] displaying the recover code works
* [ ] appearance settings are applied from the users account info
* [ ] signature can be edited and is applied
* [ ] global settings view loads fine
* [ ] sending/accepting calendar share works
* [ ] purchasing / redeeming gift cards works
* [ ] premium/free/business signup works
* [ ] deleting an account works, with takeover
* [ ] templates can be edited and applied

### PR DESCRIPTION
**Pull request by nokhub**
close #5166

### CODE REVIEW

**Comment by ganthern** [comment]
> You got rid of `logins` singleton??? woah

by stuffing it on locator, so kiiindaaa?

File: src/api/worker/rest/DefaultEntityRestCache.ts [hunk 1]
```diff
@@ -111,6 +114,11 @@ export interface ExposedCacheStorage {
 	getLastUpdateTime(): Promise<LastUpdateTime>
 
 	clearExcludedData(): Promise<void>
+
+	/**
+	 * remove an entity from the cache by typeRef and Id
+	 * */
+	deleteIfExists<T extends SomeEntity>(typeRef: TypeRef<T>, listId: Id | null, id: Id): Promise<void>
```
Comment (charlag) [inline src/api/worker/rest/DefaultEntityRestCache.ts:121]: Ideally we shouldn't allow deleting `ListElement`s willy-nilly but maybe if we mention it in the jsdoc it is enough?

File: src/api/worker/rest/DefaultEntityRestCache.ts [hunk 2]
```diff
@@ -704,6 +710,9 @@ export class DefaultEntityRestCache implements EntityRestCache {
 		// No need to try to download something that's not there anymore
 		if (cached != null) {
 			try {
+				// if the password changed we'll be logged out at this point.
+				// not catching the NotAuthorized or NotAuthenticated Error that results of this to delete the user
```
Comment (charlag) [inline src/api/worker/rest/DefaultEntityRestCache.ts:714]: >not catching the NotAuthorized or NotAuthenticated Error that results of this to delete the user

I am confused by the meaning and the sentence itself

File: src/misc/ErrorHandlerImpl.ts [hunk 3]
```diff
@@ -174,62 +175,65 @@ function logoutIfNoPasswordPrompt() {
...
+		return
+	}
+	const { logins, loginFacade, secondFactorHandler, credentialsProvider, sqlCipherFacade, cacheStorage } = locator
+	// Make sure that partial login part is complete before we will try to make a new session.
+	// Otherwise we run into a race condition where login failure arrives before we initialize userController.
+	await logins.waitForPartialLogin()
+	console.log("RELOGIN", logins.isUserLoggedIn())
+	const oldSessionType = logins.getUserController().sessionType
+	const userId = logins.getUserController().user._id
+	const mailAddress = assertNotNull(logins.getUserController().userGroupInfo.mailAddress, "could not get mailAddress from userGroupInfo")
```
Comment (charlag) [inline src/misc/ErrorHandlerImpl.ts:188]: This show function is getting so complicated already that I wonder if we should shove it into `LoginFacade` somehow, maybe in two parts but probably later

File: src/api/worker/rest/DefaultEntityRestCache.ts (hunk 1 above)
Comment (ganthern) [reply src/api/worker/rest/DefaultEntityRestCache.ts:121]: I think it would be good to mention that, yes

we can change the signature to always take null as listId and make T extends ElementEntity as well, the implementation/internal interface should be allowed to take wider types while the exposed interface is more restricted?

File: src/api/worker/rest/DefaultEntityRestCache.ts (hunk 2 above)
Comment (ganthern) [reply src/api/worker/rest/DefaultEntityRestCache.ts:714]: wording needs to be improved

we forgot to mention that this is true for user updates. it was supposed to mean that we will drop into the session recovery flow if we don't catch that (expected) error here

File: src/settings/whitelabel/WhitelabelThemeSettings.ts [hunk 4]
```diff
@@ -70,7 +69,7 @@ export class WhitelabelThemeSettings implements Component<WhitelabelThemeSetting
 			})
 			this.saveCustomTheme(customTheme, whitelabelConfig, whitelabelDomainInfo)
 
-			if (logins.isWhitelabel()) {
+			if (locator.logins.isWhitelabel()) {
```
[the remark this answers is not in the document]
Comment (ganthern) [reply src/settings/whitelabel/WhitelabelThemeSettings.ts:72]: yes, whitelabel is at the end of the list when the errors happen and was therefore one of the first we tried to fix properly

File: src/misc/ErrorHandlerImpl.ts (hunk 3 above)
Comment (charlag) [reply src/misc/ErrorHandlerImpl.ts:188]: I don't think this part will be redone together with the login screen tbh

File: src/settings/whitelabel/WhitelabelThemeSettings.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (ganthern) [reply src/settings/whitelabel/WhitelabelThemeSettings.ts:72]: and I just noticed that we didn't end up injecting anything in logincontroller after all

File: src/misc/ErrorHandlerImpl.ts (hunk 3 above)
Comment (ganthern) [reply src/misc/ErrorHandlerImpl.ts:188]: I thought we're talking about a redo of the login flow not only UI

File: src/api/worker/rest/DefaultEntityRestCache.ts [hunk 5]
```diff
@@ -710,9 +715,11 @@ export class DefaultEntityRestCache implements EntityRestCache {
 		// No need to try to download something that's not there anymore
 		if (cached != null) {
 			try {
-				// if the password changed we'll be logged out at this point.
-				// not catching the NotAuthorized or NotAuthenticated Error that results of this to delete the user
-				// allows us to still use the offline login with the old user
+				// in case this is an update for the user: if the password changed we'll be logged out at this point
```
Comment (charlag) [inline src/api/worker/rest/DefaultEntityRestCache.ts:718]: I am sorry but I am still confused. "doing this", doing what? Where do we catch those errors? What do we do when they are caught? Wouldn't `_handleProcessingError` throw the entity update out if we are not authorized?

**Review by charlag — APPROVED** [review]
There are still 2 places with loading customer but it's not important
