### PR TITLE
Calendar fixes

### LINKED ISSUE #4846: Scrolling bugs in calendar
In desktop:

 - in month view the whole screen sometimes scrolls
 - in day/week view it doesn't scroll

## Test notes
Check on Desktop, Chrome, Firefox, Safari:
 - [ ] Month view never scrolls vertically.
   - [ ] Month view does not scroll and fully fits without gaps when events on a day a folded and the indicator is shown
 - [ ] Month view never shows the vertical scrollbar, not even while resizing vertically
 - [ ] Day, Week, Agenda views can be scrolled vertically normally
 
In mobile apps(check both):
 - [ ] Can still scroll between pages and the page preview is shown while panning horizontally
 - [ ] There isn't any vertical scroll for the month view
 - [ ] Day, Agenda can be scrolled vertically normally

### LINKED ISSUE #4847: Some calendar items are not visible in month view
With Tutanota version 3.105.9 some calendar items are not visible in the month view anymore.

Steps to reproduce:

- Create two calendars
- Create Appointments on two consecutive days (e.g. 5 each day) while each day only has calendar entries of one calendar
- The second day is missing some calendar entries in the month view, even though there is still space to display them

See the following screenshots

Calendar event is missing even there is space:
Image
Calendar event is showing in week view:
Image

## Test notes
 - [ ] Make sure two events in the month view are on the consecutive days and would be on the same row (e.g. at the same time). They should be displayed on the same row.
 - [ ] Check that all the expected events are displayed in the month view. Single-day events fill up the day at any empty spots:
not like this:
image
should look like this:
image
 - [ ] Regression:  Create following events of different lengths (e.g. 10 minutes, 15 minutes, 30 minutes...) and check that they do not overlap. Check in day view and week view.
 - [ ] Check that in day/week view events that would overlap are correctly split into multiple columns, including multi-day events
 - [ ] Check that all-day events are still correctly displayed at the top of day/week views

### PR DESCRIPTION
**Pull request by nokhub**
fix #4846 
fix #4847

### CODE REVIEW

File: src/misc/ClientDetector.ts [hunk 1]
```diff
@@ -24,7 +24,7 @@ export class ClientDetector {
 
 		this._setDeviceInfo()
 
-		this.overflowAuto = this.cssPropertyValueSupported("overflow", "overlay") ? "overlay" : "auto"
+		this.overflowAuto = "auto"// this.cssPropertyValueSupported("overflow", "overlay") ? "overlay" : "auto"
```
Comment (ganthern) [inline src/misc/ClientDetector.ts:27]: straggling comment

**Review by wrdhub — APPROVED** [review]
The more in-depth comments are good, fixes wonky spacing in month view.

File: src/calendar/date/CalendarUtils.ts [hunk 2]
```diff
@@ -399,17 +410,43 @@ function getCalculationEvent(event: CalendarEvent, zone: string, handleAsAllDay:
...
+ * |           |   |          |
+ * |           |   +----------+
+ * +-----------+
+ *
+ * There could be a case where they are flipped vertically, but we don't have them because earlier events will be always first. so the "left" top edge will
+ * always be "above" the "right" top edge.
+ */
 function collidesWith(a: CalendarEvent, b: CalendarEvent): boolean {
-	return (a.endTime.getTime() > b.startTime.getTime() && a.startTime.getTime() < b.endTime.getTime()) || overlapsWith(a.startTime, a.endTime, b.startTime)
+	return (a.endTime.getTime() > b.startTime.getTime() && a.startTime.getTime() < b.endTime.getTime())
```
Comment (ganthern) [inline src/calendar/date/CalendarUtils.ts:435]: i feel this could use test cases

File: src/calendar/date/CalendarUtils.ts [hunk 3]
```diff
@@ -399,17 +410,43 @@ function getCalculationEvent(event: CalendarEvent, zone: string, handleAsAllDay:
...
-//therefore, we check whether the event height is less than the minimum height
-function overlapsWith(firstEventStart: Date, firstEventEnd: Date, secondEventStart: Date): boolean {
-	//we are only interested in the height on the last day of the event
+/**
+ * Due to the minimum height for events they overlap if a short event is directly followed by another event,
+ * therefore, we check whether the event height is less than the minimum height.
+ *
+ * This does not cover all the cases but handles the case when the second event starts right after the first one.
+ */
+function visuallyOverlaps(firstEventStart: Date, firstEventEnd: Date, secondEventStart: Date): boolean {
```
Comment (ganthern) [inline src/calendar/date/CalendarUtils.ts:444]: same here

File: src/calendar/date/CalendarUtils.ts [hunk 4]
```diff
@@ -309,11 +309,18 @@ export function colorForBg(color: string): string {
...
+ * Columns are abstract and can be actually the rows. A single column progresses in time while multiple columns can happen in parallel.
+ * @param eventsTakeUpWholeColumn {Function} when false, we can put multiple events one after another in a single column, otherwise only one event can be
+ * in one column on a single day (it will "stretch" events from the day start until the next day).
+ */
 export function layOutEvents(
 	events: Array<CalendarEvent>,
 	zone: string,
 	renderer: (columns: Array<Array<CalendarEvent>>) => ChildArray,
-	handleAsAllDay: boolean,
+	eventsTakeUpWholeColumn: boolean,
```
Comment (ganthern) [inline src/calendar/date/CalendarUtils.ts:323]: should probably be an enum, call sites are unclear. Maybe CollisionLayout.Stack and CollisionLayout.Squash or w/e

File: src/misc/ClientDetector.ts (hunk 1 above)
Comment (charlag) [reply src/misc/ClientDetector.ts:27]: oh we shouldn't actually change it at all, oops

File: src/calendar/date/CalendarUtils.ts (hunk 3 above)
Comment (nokhub) [reply src/calendar/date/CalendarUtils.ts:444]: We tried writing tests for it but decided against it since the layout computation is very unclear and probably buggy.
It adds vertical padding to all events with no obvious reason.
We plan to do more investigation in the future, but other issues have priority now.

**Review by ganthern — APPROVED** [review]

**Review by wrdhub — APPROVED** [review]
