### PR TITLE
Show gift card print button only when not on app

### LINKED ISSUE #2511: Gift card mobile
the unreleased sharing of gift cards on mobile is currently broken as the logo icon isn't being retained in our assets

### PR DESCRIPTION
**Pull request by jowlo**
fix #2511

### CODE REVIEW

File: src/subscription/giftcards/GiftCardUtils.js [hunk 1]
```diff
@@ -187,25 +187,23 @@ export function showGiftCardToShare(giftCard: GiftCard) {
...
+											: m(ButtonN, {
+												click: () => {
+													copyToClipboard(link)
+														.then(() => {infoMessage = "giftCardCopied_msg"})
+														.catch(() => {infoMessage = "copyLinkError_msg"})
+												},
+												label: "copyToClipboard_action",
+												icon: () => Icons.Clipboard
+											}),
+										!isApp() ? m(ButtonN, {
```
Comment (charlag) [inline src/subscription/giftcards/GiftCardUtils.js:199]: pls reformat as
```js
condition
  ? option1
  : option2
```

**Review by charlag — CHANGES_REQUESTED** [review]

File: src/subscription/giftcards/GiftCardUtils.js (hunk 1 above)
Comment (jowlo) [reply src/subscription/giftcards/GiftCardUtils.js]: Oopsie, sorry, done!
