### PR TITLE
Try to select sticky mail if in list

### LINKED ISSUE #7585: Opening a mail from the notification does not highlight mail in list
**Describe the bug**
When clicking on a notification, it opens the relevant mail. This mail is not highlighted in the mail list, so if I click on that mail (the mail that is open and should be highlighted) it reopens the mail I had previously opened. 

**To Reproduce**
1. Have desktop client open and have a mail selected (mail 1).
2. Get a notification for a new mail (mail 2) and click on it.
3. It goes to the desktop client and opens mail 2.
4. Mail 2 is not highlighted in the mail list. <- First Issue
5. Click on mail 2 in the mail list, mail 1 is opened. <- Second issue
6. If a mail other than mail 2 is clicked, that mail is opened as normal.

**Expected behavior**
When the mail is opened, it should be highlighted in the mail list. 

## Test notes

- [ ] Log in on desktop and make sure notifications are enabled
  - [ ] Receive an email while viewing the Inbox and click on the notification. The email should now be visibly selected in the inbox.
  - [ ] Receive an email while viewing the Archive folder and click on the notification. The email should be visible, but you are still in the Archive folder and nothing is selected.
- [ ] On mobile, if not logged in and a notification is selected, the following behavior is true:
  - [ ] Your inbox is loaded (no missing list) with no items selected
  - [ ] The mail preview still shows the mail

### PR DESCRIPTION
**Pull request by paw-hub**
Fix the sticky mail selection behavior so that if we are on the list, it will visually show that mail being selected. If not, don't try to go to that list.

Fixes #7585

### CODE REVIEW

**Review by hrb-hub — APPROVED** [review]

**Review by wrdhub — APPROVED** [review]

File: src/mail-app/mail/view/MailViewModel.ts [hunk 1]
```diff
@@ -340,7 +354,7 @@ export class MailViewModel {
 		this._folder = folder
 		this.listStreamSubscription?.end(true)
 		this.listStreamSubscription = this.listModel!.stateStream.map((state) => this.onListStateChange(state))
-		this.listModel!.loadInitial()
+		this.listModel!.loadInitial().then(noOp)
```
Comment (charlag) [inline src/mail-app/mail/view/MailViewModel.ts:357]: why is `then(noOp)` needed?

File: src/mail-app/mail/view/MailViewModel.ts [hunk 2]
```diff
@@ -230,12 +235,21 @@ export class MailViewModel {
 	}
 
 	private async loadExplicitMailTarget(listId: Id, mailId: Id, onMissingTargetEmail: () => unknown) {
+		// shouldStop returning true guarantees we won't load anything if the mail is not in the list already, so
+		// this will be synchronous
+		const listMail = await this.listModel?.loadAndSelect(mailId, () => true)
```
Comment (charlag) [inline src/mail-app/mail/view/MailViewModel.ts:240]: it should stop if we get called with another id

File: src/mail-app/mail/view/MailViewModel.ts (hunk 1 above)
Comment (charlag) [reply src/mail-app/mail/view/MailViewModel.ts:357]: there's a magical comment that you can ask IDE to insert that suppresses it

File: src/mail-app/mail/view/MailViewModel.ts (hunk 2 above)
Comment (charlag) [reply src/mail-app/mail/view/MailViewModel.ts:247]: I misread it, you are trying to select it without loading anything. So this will only select the mail if it's already in the list.

File: src/mail-app/mail/view/MailViewModel.ts [hunk 3]
```diff
@@ -230,16 +240,26 @@ export class MailViewModel {
...
+		if (listMail) {
+			console.log(TAG, "opening mail from list", mailId)
+			return
+		}
+
 		const cached = await this.cacheStorage.get(MailTypeRef, listId, mailId)
 		if (cached) {
 			console.log(TAG, "opening cached mail", mailId)
+			await this.resetOrInitializeList([listId, mailId])
```
Comment (charlag) [inline src/mail-app/mail/view/MailViewModel.ts:256]: I am confused, above we call `loadAndSelect()` and this function is supposed to deselect?

Comment (charlag) [reply src/mail-app/mail/view/MailViewModel.ts:256]: Let's say we already have a correct folder loaded and then we click on notification. Let's say the email is already in the list. Wouldn't we `loadAndSelect()` to select it and then `resetOrInitializeList()` which will deselect it?

Comment (charlag) [reply src/mail-app/mail/view/MailViewModel.ts:256]: Ahhhh yes sorry!
