### PR TITLE
Fix url/email input types not being used for some fields

### LINKED ISSUE #6097: Virtual keyboard does not switch to URL type when entering hyperlinks on iOS
**Bug in mobile app**

**Describe the bug**
When using the hyperlink dialog to enter a hyperlink on iOS, the standard 'Alphabet' virtual keyboard is used instead of the 'URL' virtual keyboard.

**To Reproduce**
1. Create an email
2. Open the hyperlink dialog in the formatting bar
3. See that the default keyboard is used

**Expected behavior**
Upon opening the hyperlink dialog, the 'URL' virtual keyboard is utilized.

**Additional context**
I was testing on the 3.118.24 build.

## Test notes

- [ ] On iOS and Android, check the following text fields, and make sure they bring up the correct keyboard types:
  - [ ] Contact email text field should bring up email keyboard
  - [ ] Email recipient text fields should bring up email keyboard
  - [ ] Make link dialog should bring up URL keyboard
  - [ ] Takeover email text field in delete account AND takeover account dialog should bring up email keyboard
  - [ ] Notification email address dialog should bring up email keyboard
  - [ ] Imprint and privacy policy text fields in Whitelabel should bring up URL keyboard

### PR DESCRIPTION
**Pull request by paw-hub**
This hints devices such as phones what keyboard type to use.

Fixes #6097

### CODE REVIEW

File: src/gui/base/Dialog.ts [hunk 1]
```diff
@@ -753,6 +753,7 @@ export class Dialog implements ModalComponent {
 	 * @param infoMsgId help label of the text field
 	 * @param value initial value
 	 * @param inputValidator Called when "Ok" is clicked receiving the entered text. Must return null if the text is valid or an error messageId if the text is invalid, so an error message is shown.
+	 * @param textFieldType Text field type to display (determines what keyboard to display on mobile devices)
 	 * @returns A promise resolving to the entered text. The returned promise is only resolved if "ok" is clicked.
 	 */
 	static showTextInputDialog(
```
Comment (charlag) [inline src/gui/base/Dialog.ts:759]: we should make this an argument object, it's hard to read otherwise

File: src/gui/base/Dialog.ts [hunk 2]
```diff
@@ -58,6 +58,26 @@ export type ActionDialogProps = {
 	type?: DialogType
 }
 
+export type TextInputDialogProps = {
```
Comment (charlag) [inline src/gui/base/Dialog.ts:61]: don't change it now but generally we use `interface` over `type`

File: src/gui/base/Dialog.ts [hunk 3]
```diff
@@ -748,84 +768,45 @@ export class Dialog implements ModalComponent {
...
-	static showProcessTextInputDialog(
-		titleId: TranslationKey | lazy<string>,
-		labelIdOrLabelFunction: TranslationKey | lazy<string>,
-		infoMsgId: (TranslationKey | null) | (lazy<string> | null),
-		value: string,
-		okAction: (arg0: string) => Promise<unknown>,
-		inputValidator?: stringValidator,
-	) {
-		let result = value
+	static showProcessTextInputDialog(props: TextInputDialogProps, okAction: (action: string) => Promise<unknown>) {
```
Comment (charlag) [inline src/gui/base/Dialog.ts]: we should probably just get rid of it at some point

**Review by charlag — APPROVED** [review]
