### PR TITLE
Fix overlays flickering upon appearance

### LINKED ISSUE #3079: overlay elements flicker upon creation
We use `displayOverlay()` to show different overlays (e.g. search(Ctrl+F) in the desktop client: or the notification overlay).
When the actual element is attached to the dom it flickers. This is because it is displayed in its final state briefly before the `createAnimation` is called (which might for example move it in from outside the screen).

We should fix how animations work in such cases. It might be that we have similar problems in other places.

## Test notes
On desktop:
- [ ] Search bar can be opened with `Ctrl+F`
- [ ] Search bar can be closed

On iOS:
- [ ] Snackbar appears fine

### PR DESCRIPTION
**Pull request by rezbyte**
This PR replaces the old JavaScript based animations for the overlays with CSS Animations. It also deprecates the old JavaScript based animations in favor of CSS animations. I did not replace the JavaScript animations everywhere to avoid this PR getting too big, but aim for a gradual replacement every time we work on something that uses them.

Closes #3079.

### CODE REVIEW

File: src/gui/base/Overlay.ts [hunk 1]
```diff
@@ -95,20 +104,32 @@ export const overlay: Component = {
...
+							}
 						},
 					},
 					m(attrs.component),
 				)
 			}),
 		),
 }
+
+function mapToArray<T, K>(map: Map<T, K>): Array<[T, K]> {
```
Comment (rezbyte) [inline src/gui/base/Overlay.ts:129]: Just wanted to note here that I wanted to put this into the map utils package but was not sure how.

Comment (charlag) [reply src/gui/base/Overlay.ts:129]: so is it like `Array.from(map.entries())`?

File: src/gui/base/Overlay.ts [hunk 2]
```diff
@@ -95,20 +104,32 @@ export const overlay: Component = {
...
+								overlays.delete(key)
 							}
 						},
-						onremove: () => {
-							overlayAttrs[1] = null
+						onupdate(vnode: VnodeDOM<any>): any {
+							if (attrs.isClosing && attrs.closeAnimation != null) {
+								const dom = vnode.dom as HTMLElement
+
+								// Force the environment to restart the animations via a reflow
```
Comment (charlag) [inline src/gui/base/Overlay.ts:116]: not only this is hacky but also causes a relayout?

**Review by charlag — COMMENTED** [review]
I would suggest using [Web Animations API](https://developer.mozilla.org/en-US/docs/Web/API/Web_Animations_API) instead of juggling CSS classes. Maybe reimplement our Animations class based on them.

File: src/gui/base/Overlay.ts (hunk 1 above)
Comment (rezbyte) [reply src/gui/base/Overlay.ts:129]: TypeScript gave me warnings about it not being compatible with ECMAScript 2015 when I tried that.

File: src/gui/base/Overlay.ts (hunk 2 above)
Comment (rezbyte) [reply src/gui/base/Overlay.ts:116]: It is hacky but it seems to be the standard technique afaik. The 'relayout' (the term MDN & Google use is 'reflow') is deliberate as animations are only played on reflow.

**Comment by charlag** [comment]
Could you please undeprecate our animations class (we can reimplement how it's done internally but if we want to use  CSS animations everywhere we should discuss it) and try to reimplement overlay thing with Web Animation API?

I think there are great use cases for CSS animations and transitions but in many of  our cases they'll be very cumbersome.

**Comment by rezbyte** [comment]
> Could you please undeprecate our animations class (we can reimplement how it's done internally but if we want to use CSS animations everywhere we should discuss it) and try to reimplement overlay thing with Web Animation API?
> 
> I think there are great use cases for CSS animations and transitions but in many of our cases they'll be very cumbersome.

Ah, sorry I did not address this point in my replies. Thanks for bringing the Animation API to my attention, I will undeprecate the Animation class for now. As you mentioned, we should discuss a transition to CSS animations as I suspect  doing so would reduce (if done properly) the size of the codebase significantly & avoid bugs such as the flickering.

File: src/gui/base/Overlay.ts (hunk 1 above)
Comment (rezbyte) [reply src/gui/base/Overlay.ts:129]: Ah, my mistake I tried `overlay.entries().map()` which is not supported yet on `IterableIterator`s. I just peeked at the `tsconfigs`s & it seems we are targeting ECMAScript 2020. So I have no idea why it showed an error about ECMAScript 2015 specifically.

I will remove this function now.

**Comment by rezbyte** [comment]
As discussed this morning, using WAAPI reintroduces the issue & requires more hacky workarounds. We should stick to CSS Animations at least for the opening animations. 

I have a couple of WAAPI implementations stashed if we want to look at them at a later time.

**Comment by rezbyte** [comment]
Using CSS Animations for create animations [is the officially recommended technique by the Mithril team](https://mithril.js.org/animation.html#animation-on-element-creation).

File: src/gui/base/Overlay.ts (hunk 2 above)
Comment (rezbyte) [reply src/gui/base/Overlay.ts:103]: Unfortunately their workaround is not applicable & the reflow is still needed but it did help simplify the code.

File: src/gui/base/Overlay.ts [hunk 3]
```diff
@@ -104,19 +96,21 @@ export const overlay: Component = {
...
 								// Force the environment to restart the animations via a reflow
 								dom.className = baseClasses
 								void dom.offsetWidth
-								dom.className = classes
+
+								// Play the closing animation
+								dom.className = baseClasses + " " + attrs.closeAnimation
+
+								// Wait for the close animation to complete
+								return new Promise(function (resolve) {
```
Comment (charlag) [inline src/gui/base/Overlay.ts:111]: small nicpick but this could be an arrow function

Comment (rezbyte) [reply src/gui/base/Overlay.ts]: Good catch! Looks nicer that way.

**Review by charlag — APPROVED** [review]

**Comment by charlag** [comment]
We probably don't need much of test notes? maybe a regression test?

**Comment by rezbyte** [comment]
> We probably don't need much of test notes? maybe a regression test?

I have added a few things, just regressions tests.
