### PR TITLE
fix search list duplication

### LINKED ISSUE #1972: Search results are duplicated
Our user submitted a way to reproduce this issue (thanks!):

 1. be in search view
 2. type something for new search and immediately press Return
 3. See duplicated results

I tried it out and I could reproduce it. Seems like we do two search queries at once.

### PR DESCRIPTION
**Pull request by johnbotris**
if we try to search again for the exact same query, then we will just return the promise from the previous search query.

Will need to be confirmed that this is the right way to go by someone who groks the search implementation

 fix #1972

### CODE REVIEW

File: src/search/model/SearchModel.js [hunk 1]
```diff
@@ -85,14 +106,32 @@ export class SearchModel {
...
 }
 
+function areSearchQueriesEqual(a: SearchQuery, b: SearchQuery) {
+	return a.query === b.query
+		&& compareSearchRestriction(a.restriction, b.restriction)
+		&& a.minSuggestionCount === b.minSuggestionCount
+		&& a.maxResults === b.maxResults
+}
+
+function compareSearchRestriction(a: SearchRestriction, b: SearchRestriction): boolean {
```
Comment (charlag) [inline src/search/model/SearchModel.js:121]: `areSearchQueriesEqual`, `compareSearchRestriction`, `arrayEquals` do the same thing for different types but named differently?

File: src/search/view/SearchListView.js [hunk 2]
```diff
@@ -127,14 +124,38 @@ export class SearchListView {
...
+				}
+
+				// save to a local var because flow complains at about it being nullable when returning
+				const deferredResult = defer()
+				this._lastSearchResults = deferredResult
+
+				this._loadSearchResults(lastResult, startId !== GENERATED_MAX_ID, startId, count)
+		                    .then(results => results.map(instance => new SearchResultListEntry(instance)))
+				    .then(results => {
+					    if (this._lastSearchResults) {
```
Comment (charlag) [inline src/search/view/SearchListView.js:152]: What if this is not our deferred but already a new one? I think check should be `this._lastSearchResults === deferredResult` and only then we should resolve it?

**Review by charlag — CHANGES_REQUESTED** [review]

File: src/search/model/SearchModel.js (hunk 1 above)
Comment (johnbotris) [reply src/search/model/SearchModel.js:121]: fair point, i forget to rename `compareSearchRestriction` anyway. I'll make them all be named `*Equals`

**Review by charlag — APPROVED** [review]
