### PR TITLE
only invoke indexMailboxes once when extending or creating search index

### LINKED ISSUE #6278: Creating or extending search index is slow
**Describe the bug**
Search index creation is very slow even if there are just a few hundred emails in the inbox. I noticed that when trying to find an email in my personal mailbox that is from 8 years ago but it is also slow if i just create the initial mail index for the first 30 days.  

**To Reproduce**
1. Login in to desktop or web app. 
2. Ensure that no credentials or search index is stored for the account you want to test with (check using dev tools)
4. Enable search and observe log
5. Check search index performance output from IndexerCore.ts

**Expected behavior**
Search index is created in a few seconds.

**Additional context**
Here is an example of the initial indexin

30 days,  74 mails, **50670ms**

```
IndexerCore.ts:941 {"indexingTime":57.59999999962747,"storageTime":1480,"preparingTime":49190.19999999739,"mailcount":74,"storedBytes":760928,"encryptionTime":369.199999996461,"writeRequests":5148,"largestColumn":295,"words":5012,"indexedBytes":682158,"downloadingTime":48763.400000001304} total time:  50670.19999999739
```

Similar results for extending the index for  30 more days.
next 30 days, 61 mails, **58618ms**

```
IndexerCore.ts:941 {"indexingTime":57.599999997764826,"storageTime":1886,"preparingTime":56732.50000000186,"mailcount":61,"storedBytes":649648,"encryptionTime":353.40000000037253,"writeRequests":4285,"largestColumn":413,"words":1989,"indexedBytes":663768,"downloadingTime":56321.500000003725} total time:  58618.50000000186. 
```

### PR DESCRIPTION
**Pull request by bedhub**
fixes #6278

This fix only removes the duplicate invocation of indexMailboxes which already improves the performance for my case by factor 10.

Timings for initial indexing:
30 days, 74 mails, **7224 ms**
```
IndexerCore.ts:941 {"indexingTime":65.10000000335276,"storageTime":2390.100000000559,"preparingTime":4834.699999997392,"mailcount":74,"storedBytes":760928,"encryptionTime":449.8999999957159,"writeRequests":5148,"largestColumn":295,"words":5012,"indexedBytes":682158,"downloadingTime":4319.699999998324} total time:  7224.799999997951
```

Next 30 days:
30 days, 61 mails, **6554 ms**
```
IndexerCore.ts:941 {"indexingTime":58.20000000298023,"storageTime":1879.2999999998137,"preparingTime":4674.89999999851,"mailcount":61,"storedBytes":649648,"encryptionTime":391.39999999664724,"writeRequests":4285,"largestColumn":413,"words":1989,"indexedBytes":663768,"downloadingTime":4225.299999998882} total time:  6554.199999998324
```

### CODE REVIEW

**Comment by ganthern** [comment]
that's cool. I'm not quite sure how this causes a factor 10 speedup though. 

We'll also need some test notes

File: src/api/worker/search/MailIndexer.ts [hunk 1]
```diff
@@ -285,10 +285,7 @@ export class MailIndexer {
 	async extendIndexIfNeeded(user: User, newOldestTimestamp: number): Promise<void> {
 		if (this.currentIndexTimestamp > FULL_INDEXED_TIMESTAMP && this.currentIndexTimestamp > newOldestTimestamp) {
 			this.mailboxIndexingPromise = this.mailboxIndexingPromise
-				.then(
-					async () => await this.indexMailboxes(user, newOldestTimestamp),
-					async () => await this.indexMailboxes(user, newOldestTimestamp),
-				)
+				.then(async () => await this.indexMailboxes(user, newOldestTimestamp))
```
Comment (charlag) [inline src/api/worker/search/MailIndexer.ts:288]: `(async () => await {})` makes no sense
