### PR TITLE
Better info dialogs around adding email addresses

### LINKED ISSUE #6667: Legacy account gets error when adding email addresses
Legacy accounts are getting errors when trying to add another email address

**To Reproduce**
1. Have a legacy account
2. add another email address under Settings > mail > Email addresses
3. The "Add email address" dialog appears
4. Type in address and press "okay"
5. error appears: BadRequestError 400 for mailaddressaliasservice

**Expected behavior**
This happens both when the account has more than the allowed amount of email addresses and unused email addresses available.
In the first case, an upgrade dialog should appear.
In the latter, the address should be added.

## Test Notes
- [ ] Legacy Paid Account
     - [ ]  When adding another email address, @tutamail.com is the default domain
     - [ ]  trying to select the tuta.com domain shows a popup explaining that tuta is only for new subscriptions
     - [ ] when trying to add another email address with no slots left, an upgrade dialog is shown
- [ ] New Paid Account
     - [ ]  when adding another email address @tuta.com is the default domain
          - [ ] Unless the account has a custom domain, then that domain is shown
     - [ ] Adding another email address with any domain works
     - [ ] when trying to add another email address with no slots left:
        - [ ] On the Revolutionary or Essential plan: an upgrade dialog is shown
        - [ ] on advanced, unlimited, or legend: a "max # of aliases" message is shown
- [ ] Custom email domain
  - [ ] can add another email address with custom email domain even when number of address slots is full
  - [ ] cannot add another email address with non-custom email domain when number of address slots is full

### PR DESCRIPTION
**Pull request by wrdhub**
fix #6667

### CODE REVIEW

File: src/settings/mailaddress/MailAddressTableModel.ts [hunk 1]
```diff
@@ -182,7 +183,7 @@ export class MailAddressTableModel {
 			(config) => Number(config.nbrOfAliases) > this.userGroupInfo.mailAddressAliases.length,
 		)
 		if (plansWithMoreAliases.length > 0) {
-			throw new UpgradeRequiredError("moreAliasesRequired_msg", plansWithMoreAliases)
+			showPlanUpgradeRequiredDialog(plansWithMoreAliases, "moreAliasesRequired_msg")
```
Comment (charlag) [inline src/settings/mailaddress/MailAddressTableModel.ts:186]: I think we didn't want to show dialogs directly from the model, thus an error. We could return something.

**Review by charlag — APPROVED** [review]
