### PR TITLE
fix short events not being displayed sometimes in the 6th week row

### LINKED ISSUE #5839: Incorrect display of multiple day event
When creating a calendar event between years that is 14 days or less, the days in the new year are not displayed as part of the event.

1. Go to Calendar.
2. Create an event between years. The event should be 14 days or less.
3. Days in the new year are not displayed as part of the event.

Screenshot from 2023-09-01 17-05-00
Screenshot from 2023-09-01 17-04-40

Reproduced on web, Desktop, and Android app.

### LINKED ISSUE #5896: event sometimes not displaying properly at month end
Events between February and March 2024 are not displayed properly

**To Reproduce**
1. Go to Calendar
2. Create Event between February and March (for example 26th February - 06th March 2024)
4. The event will only display until 03rd of March 

**Screenshots**
image

**Additional context**
I could not identify the clear edges as if the event is longer or adjusting the start/end date sometimes does not reproduce.
The issue was reproduce-able on Desktop & Mobile

## Test Notes
* [ ] re-test this bug
* [ ] retest #5839 
* [ ] test https://github.com/tutao/tutanota/issues/5920
* [ ] try other configurations with short events (non-repeating, shorter than 15 days)
* [ ] the events are also still displayed correctly after reloading the page
* [ ] this also works in situation with multiple clients working on the same calendar (shared calendar, just multiple tabs on the same calendar)
* [ ] the events are also displayed correctly when switching betweeen months

### PR DESCRIPTION
**Pull request by ganthern**
we changed addDaysForEventInstance to only worry about the month it was called for and ignore the rest of the event that may extend to the next month, but did not adapt CalendarViewModel._addOrUpdateEvent to also add short events to the month where they end.

in cases where we
* receive an entity event update for a short event that starts in the current month but ends in the next
* the month view displays a complete week that is part of the next month at the bottom (to fill the 6x7 grid)

we would therefore not display that events end.

fix #5896
fix #5839
fix 3a68f207dd02637603419b2d661d68c46ba6645e

### CODE REVIEW

File: src/calendar/view/CalendarViewModel.ts [hunk 1]
```diff
@@ -381,11 +382,13 @@ export class CalendarViewModel implements EventDragHandlerCallbacks {
 			return
 		}
 		const eventListId = getListId(event)
-		const eventMonth = getMonthRange(getEventStart(event, this.timeZone), this.timeZone)
-		if (isSameId(calendarInfo.groupRoot.shortEvents, eventListId) && this._loadedMonths.has(eventMonth.start)) {
-			// If the month is not loaded, we don't want to put it into events.
-			// We will put it there when we load the month
-			this._addDaysForEvent(event, eventMonth)
+		if (isSameId(calendarInfo.groupRoot.shortEvents, eventListId)) {
```
Comment (charlag) [inline src/calendar/view/CalendarViewModel.ts:385]: this is only called from `entityEventsReceived()` but the issues are about just opening the calendar? Am I wrong?

Comment (ganthern) [reply src/calendar/view/CalendarViewModel.ts:385]: as far as I know and could reproduce, this is purely an issue when we receive the event through an entity update, they appear correctly once you reload the page

**Review by charlag — APPROVED** [review]
