### PR TITLE
Remove check that resulted in reloading with empty search results

### LINKED ISSUE #6082: Using Field/Email Folder filter in Search to return nothing results in odd behaviour
Repro steps:
1. Search in mail for something that will return results.
2. Change the Field or Email Folder to something that will return no results.
3. Change the Field or Email Folder back to what was returning results before (or something else you know should return results), nothing will be displayed.
4. Try to click on Email, Contacts, or Calendar in the top bar; it will stay on Search (but results will be shown).

Additional note:
If you switch between Field/Email Folder filters that return results, it will work fine.

### PR DESCRIPTION
**Pull request by wrdhub**
fix #6082

### CODE REVIEW

File: src/search/view/SearchViewModel.ts [hunk 1]
```diff
@@ -465,11 +465,10 @@ export class SearchViewModel {
 
 	private async loadSearchResults<T extends SearchableTypes>(
 		currentResult: SearchResult,
-		getMoreFromSearch: boolean,
 		startId: Id,
 		count: number,
 	): Promise<{ items: T[]; newSearchResult: SearchResult }> {
-		const result = getMoreFromSearch && hasMoreResults(currentResult) ? await this.searchFacade.getMoreSearchResults(currentResult, count) : currentResult
+		const result = hasMoreResults(currentResult) ? await this.searchFacade.getMoreSearchResults(currentResult, count) : currentResult
```
Comment (ganthern) [inline src/search/view/SearchViewModel.ts:471]: so in this place, we're asking the result (in effect, the index) if there's more results and only then call getMoreSearchResults. getMoreSearchResults has its own check for moreResults.length === 0 and may extend the index if it's true. what's the intended behavior here, is the check to prevent us from accidentally extending the index?

**Review by ganthern — COMMENTED** [review]
I would like an explanation what exactly went wrong in the commit message and what the solution entails. was it that the information "we're done because our startId is MAX_ID" was held onto too long? and now we just trust the index to tell us when we're done?

**Comment by ganthern** [comment]
also, are there any test files that could be updated to add a check for this situation?

File: src/search/view/SearchViewModel.ts (hunk 1 above)
Comment (wrdhub) [reply src/search/view/SearchViewModel.ts:471]: I guess that was the original intent? the searchFacade checks moreResults too, and only extends if needed so we may not even need this check here anymore at all, just go ahead and call getMoreSearchResults (which is what is essentially happening right now anyway)

**Review by ganthern — APPROVED** [review]
